### PR TITLE
bug: Fixed passing of existing destroy plan files

### LINKED ISSUE #5319: Destroy from --filter-allow-destroy fails when --out-dir is used on apply
## Describe the bug

When I plan with `--filter-allow-destroy` and `--out-dir`, and afterwards apply with again `--filter-allow-destroy` and `--out-dir`, then the destroy fails because Terragrunt passes both `-destroy` and the `.tfplan` file to `tofu apply`, which isn't valid:

```
...
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: ╷
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: │ Error: Too many command line arguments
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: │ 
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: │ Expected at most one positional argument.
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: ╵
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: For more help on using this command, run:
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu:   tofu apply -help
20:26:59.141 ERROR  Run failed: error occurred:

* Failed to execute "tofu apply -destroy -input=false /tmp/tfplans/stacks/test/.terragrunt-stack/unit2/tfplan.tfplan -auto-approve /tmp/tfplans/stacks/test/.terragrunt-stack/unit2/tfplan.tfplan" in /tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2/.terragrunt-cache/8l0AbeQqn1Q1-hbovfehud5K0Co/pqq9QYaHhItAGESypz4dlOkxMkc
...
```

Also interesting that the `.tfplan` file seems to be passed twice to `tofu apply`.

## Steps To Reproduce

```
# modules/module/main.tf
resource "null_resource" "echo" {
  provisioner "local-exec" {
    command = "echo 'hello there'"
  }
}

# units/unit/terragrunt.hcl
include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "${find_in_parent_folders("modules")}/module"
}

# stacks/root.hcl
remote_state {
  backend = "local"

  config = {
    path = "/tmp/tfstate/${path_relative_to_include()}/terraform.tfstate"
  }

  generate = {
    path = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# stacks/test/terragrunt.stack.hcl
unit "unit1" {
  source = "${find_in_parent_folders("units")}/unit"
  path = "unit1"
}

unit "unit2" {
  source = "${find_in_parent_folders("units")}/unit"
  path = "unit2"
}
```

```
$ git init
$ git add .
$ git commit -m "initial commit"
$ git commit --allow-empty -m "dummy"

$ cd stacks

$ terragrunt run --all -- apply

# Comment out unit2 in stack

$ git add .
$ git commit -m 'remove unit 2'

$ rm -rf /tmp/tfplans

$ terragrunt run --all --filter "[HEAD~1...HEAD]" --filter-allow-destroy --out-dir "/tmp/tfplans" -- plan
20:25:38.743 INFO   Generating unit unit1 from ./test/terragrunt.stack.hcl
20:25:38.743 INFO   Generating unit unit1 from /tmp/terragrunt-worktree-HEAD-3557043763/stacks/test/terragrunt.stack.hcl
20:25:38.743 INFO   Generating unit unit2 from /tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/terragrunt.stack.hcl
20:25:38.743 INFO   Generating unit unit1 from /tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/terragrunt.stack.hcl
20:25:38.748 WARN   One or more units discovered using Git-based filter expressions (e.g. [HEAD~1...HEAD]) do not have a remote_state configuration. This may result in unexpected outcomes, such as outputs for dependencies returning empty. It is strongly recommended to use remote state when working with Git-based filter expressions.
20:25:38.748 INFO   Unit queue will be processed for plan in this order:
- Unit stacks/test/.terragrunt-stack/unit2

20:25:38.808 INFO   [stacks/test/.terragrunt-stack/unit2] Downloading Terraform configurations from /tmp/terragrunt-worktree-HEAD_1-1645053435/modules/module into /tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2/.terragrunt-cache/R_dSXBMC16fNQmzxAXwyHV91XNU/egbI6mn1PjqkttuzTXpKDJXWulQ
20:25:38.858 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: Initializing the backend...
20:25:38.863 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: 
20:25:38.863 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: Successfully configured the backend "local"! OpenTofu will automatically
20:25:38.863 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: use this backend unless the backend configuration changes.
20:25:38.866 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: Initializing provider plugins...
20:25:38.866 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: - Finding latest version of hashicorp/null...
20:25:39.917 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: - Installing hashicorp/null v3.2.4 to the shared cache directory...
20:25:40.414 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: - Installed hashicorp/null v3.2.4 (signed, key ID 0C0AF313E5FD9F80)
20:25:40.414 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: - Using hashicorp/null v3.2.4 from the shared cache directory
20:25:40.414 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: Providers are signed by their developers.
20:25:40.414 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: If you'd like to know more about provider signing, you can read about it here:
20:25:40.414 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: https://opentofu.org/docs/cli/plugins/signing/
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: OpenTofu has created a lock file .terraform.lock.hcl to record the provider
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: selections it made above. Include this file in your version control repository
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: so that OpenTofu can guarantee to make the same selections by default when
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: you run "tofu init" in the future.
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: OpenTofu has been successfully initialized!
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: 
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: You may now begin working with OpenTofu. Try running "tofu plan" to see
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: any changes that are required for your infrastructure. All OpenTofu commands
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: should now work.
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: If you ever set or change modules or backend configuration for OpenTofu,
20:25:40.415 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: rerun this command to reinitialize your working directory. If you forget, other
20:25:40.416 INFO   [/tmp/terragrunt-worktree-HEAD_1-1645053435/stacks/test/.terragrunt-stack/unit2] tofu: commands will detect it and remind you to do so if necessary.
20:25:40.749 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu: null_resource.echo: Refreshing state... [id=2621967827208791117]
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu: OpenTofu used the selected providers to generate the following execution
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu: plan. Resource actions are indicated with the following symbols:
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu:   - destroy
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu: OpenTofu will perform the following actions:
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu:   # null_resource.echo will be destroyed
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu:   - resource "null_resource" "echo" {
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu:       - id = "2621967827208791117" -> null
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu:     }
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu: Plan: 0 to add, 0 to change, 1 to destroy.
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu: 
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu: ─────────────────────────────────────────────────────────────────────────────
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu: Saved the plan to:
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu: /tmp/tfplans/stacks/test/.terragrunt-stack/unit2/tfplan.tfplan
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu: To perform exactly these actions, run the following command to apply:
20:25:40.848 STDOUT [stacks/test/.terragrunt-stack/unit2] tofu:     tofu apply "/tmp/tfplans/stacks/test/.terragrunt-stack/unit2/tfplan.tfplan"

❯❯ Run Summary  1 units  2s
   ────────────────────────────
   Succeeded    1

$ terragrunt run --all --filter "[HEAD~1...HEAD]" --filter-allow-destroy --out-dir "/tmp/tfplans" -- apply
20:26:53.419 INFO   Generating unit unit1 from ./test/terragrunt.stack.hcl
20:26:53.419 INFO   Generating unit unit1 from /tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/terragrunt.stack.hcl
20:26:53.419 INFO   Generating unit unit2 from /tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/terragrunt.stack.hcl
20:26:53.419 INFO   Generating unit unit1 from /tmp/terragrunt-worktree-HEAD-1906115360/stacks/test/terragrunt.stack.hcl
20:26:53.424 WARN   One or more units discovered using Git-based filter expressions (e.g. [HEAD~1...HEAD]) do not have a remote_state configuration. This may result in unexpected outcomes, such as outputs for dependencies returning empty. It is strongly recommended to use remote state when working with Git-based filter expressions.
20:26:53.424 INFO   Unit queue will be processed for apply in this order:
- Unit stacks/test/.terragrunt-stack/unit2

Are you sure you want to run 'terragrunt apply' in each unit of the run queue displayed above? (y/n) y
20:26:55.400 INFO   [stacks/test/.terragrunt-stack/unit2] Downloading Terraform configurations from /tmp/terragrunt-worktree-HEAD_1-3360260208/modules/module into /tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2/.terragrunt-cache/8l0AbeQqn1Q1-hbovfehud5K0Co/pqq9QYaHhItAGESypz4dlOkxMkc
20:26:55.452 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: Initializing the backend...
20:26:55.456 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: 
20:26:55.456 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: Successfully configured the backend "local"! OpenTofu will automatically
20:26:55.456 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: use this backend unless the backend configuration changes.
20:26:55.458 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: Initializing provider plugins...
20:26:55.458 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: - Finding latest version of hashicorp/null...
20:26:58.754 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: - Installing hashicorp/null v3.2.4 to the shared cache directory...
20:26:59.077 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: - Installed hashicorp/null v3.2.4 (signed, key ID 0C0AF313E5FD9F80)
20:26:59.077 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: - Using hashicorp/null v3.2.4 from the shared cache directory
20:26:59.077 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: Providers are signed by their developers.
20:26:59.077 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: If you'd like to know more about provider signing, you can read about it here:
20:26:59.077 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: https://opentofu.org/docs/cli/plugins/signing/
20:26:59.077 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: OpenTofu has created a lock file .terraform.lock.hcl to record the provider
20:26:59.077 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: selections it made above. Include this file in your version control repository
20:26:59.077 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: so that OpenTofu can guarantee to make the same selections by default when
20:26:59.077 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: you run "tofu init" in the future.
20:26:59.077 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: OpenTofu has been successfully initialized!
20:26:59.078 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: 
20:26:59.078 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: You may now begin working with OpenTofu. Try running "tofu plan" to see
20:26:59.078 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: any changes that are required for your infrastructure. All OpenTofu commands
20:26:59.078 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: should now work.
20:26:59.078 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: If you ever set or change modules or backend configuration for OpenTofu,
20:26:59.078 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: rerun this command to reinitialize your working directory. If you forget, other
20:26:59.078 INFO   [/tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2] tofu: commands will detect it and remind you to do so if necessary.
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: ╷
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: │ Error: Too many command line arguments
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: │ 
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: │ Expected at most one positional argument.
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: ╵
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu: For more help on using this command, run:
20:26:59.136 STDERR [stacks/test/.terragrunt-stack/unit2] tofu:   tofu apply -help
20:26:59.141 ERROR  Run failed: error occurred:

* Failed to execute "tofu apply -destroy -input=false /tmp/tfplans/stacks/test/.terragrunt-stack/unit2/tfplan.tfplan -auto-approve /tmp/tfplans/stacks/test/.terragrunt-stack/unit2/tfplan.tfplan" in /tmp/terragrunt-worktree-HEAD_1-3360260208/stacks/test/.terragrunt-stack/unit2/.terragrunt-cache/8l0AbeQqn1Q1-hbovfehud5K0Co/pqq9QYaHhItAGESypz4dlOkxMkc
  ╷
  │ Error: Too many command line arguments
  │ 
  │ Expected at most one positional argument.
  ╵
  
  For more help on using this command, run:
    tofu apply -help
  
  exit status 1


❯❯ Run Summary  1 units  3s
   ────────────────────────────
   Failed       1

```

## Expected behavior

It should be possible to plan destroy's from --filter-allow-destroy by using --out-dir and then apply those plans afterwards.
If a `.tfplan` file is found then the `-destroy` flag of the apply should probably be omitted?

## Must haves

- [x] Steps for reproduction provided.

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: [v0.97.1](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.97.1)
- OpenTofu/Terraform version: OpenTofu v1.10.7
- Environment details (Ubuntu 20.04, Windows 10, etc.): Ubuntu 24.04.3 LTS

### PR DESCRIPTION
**Pull request by denis256**
## Description

Found that cli arguments for `apply -destroy` and plan:

```
0 = "apply"
1 = "-no-color"
2 = "-destroy"
3 = "-input=false"
4 = "/tmp/TestDestroyWithOutDirGitFilter3718382455/002/unit-to-destroy/tfplan.tfplan"
5 = "-auto-approve"
```
Plan file should be in the end

* added a basic test to track that the issue exists
* implemented re-order of arguments for unit to set plan file in the end

Fixes #5319.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved Terraform plan-argument handling to avoid duplicate plan outputs, ensure plan-related arguments are ordered at the end, and prevent accidental re-addition of existing plan files or mis-ordered flag/value groups.

* **Tests**
  * Added an integration test covering destroy with Git-based filtering and a custom output directory to ensure plan files are written only to the specified outDir and not to unexpected worktree paths.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: internal/runner/runnerpool/runner.go [hunk 1]
```diff
@@ -774,15 +773,35 @@ func (r *Runner) syncTerraformCliArgs(l log.Logger, opts *options.TerragruntOpti
...
 
-			unit.Execution.TerragruntOptions.TerraformCliArgs = mergedArgs
+			// reorder arguments to have plan file args at the end
+			var (
+				regularArgs []string
+				planArgs    []string
+			)
+
+			for _, arg := range mergedArgs {
+				if isPlanArg(arg) {
```
Comment (yhakbar) [inline internal/runner/runnerpool/runner.go]: Won't this be a problem if a user supplies something like:

```bash
tg run -- plan -out plan.plan -no-color
```

Where it will shuffle away the plan from the out? Maybe instead we should only inject flags like `-auto-approve` before any other flags?

File: internal/runner/runnerpool/runner.go [hunk 2]
```diff
@@ -774,15 +773,35 @@ func (r *Runner) syncTerraformCliArgs(l log.Logger, opts *options.TerragruntOpti
...
 		}
 
 		planFile := unit.PlanFile(opts)
+
 		if planFile != "" {
 			l.Debugf("Using output file %s for unit %s", planFile, unit.Execution.TerragruntOptions.TerragruntConfigPath)
 
+			if slices.Contains(unit.Execution.TerragruntOptions.TerraformCliArgs, planFile) {
+				return
+			}
```
Comment (yhakbar) [inline internal/runner/runnerpool/runner.go]: This seems valid
