### PR TITLE
fix: Using cty.DynamicVal to avoid 'Unsupported Attribute' errors

### LINKED ISSUE #5811: `terragrunt hcl validate` fails with "Unsupported attribute" when dependency.outputs is referenced
## Describe the bug

`terragrunt hcl validate` fails with an _Unsupported attribute_ error when a `terragrunt.hcl` file references `dependency.<name>.outputs.*`.

During HCL validation, the `dependency` block appears to be resolved as an object with only a single `inputs` attribute, rather than the expected `outputs` attribute. This makes the command unusable for validating any module that uses dependency outputs.

When `mock_outputs` are defined for a `dependency` block, the validation succeeds but still warns on missing dependency `outputs`.

Noteworthy, the `dependency` block is surfacing as object with 1 attribute "inputs", while the Terragrunt docs explicitly state that `dependency.<name>.inputs` has been deprecated and removed, and that `dependency.<name>.outputs` is the only valid option.

## Steps To Reproduce

Create a `terragrunt.hcl` that defines at least one `dependency` block and references the output of another existing `terragrunt.hcl` with `dependency.<name>.outputs.<key>` in its inputs block:

```hcl
dependency "vpc" {
  config_path = "../vpc"
}

inputs = {
  vpc_id = dependency.vpc.outputs.vpc_id
}
```

Run `terragrunt hcl validate` or `terragrunt hcl validate --inputs`:

```
│ Error: Unsupported attribute
│
│   on /path/to/terragrunt.hcl line 68:
│   68:   vpc_id   = dependency.vpc.outputs.vpc_id
│     ├────────────────
│     │ dependency.vpc is object with 1 attribute "inputs"
│
│ This object does not have an attribute named "outputs".
```

Adding mocked values:

```hcl
dependency "vpc" {
  config_path = "../vpc"
  
  mock_outputs = {
    vpc_id = "mock-vpc-id"
  }
}

inputs = {
  vpc_id = dependency.vpc.outputs.vpc_id
}
```

Run `terragrunt hcl validate` or `terragrunt hcl validate --inputs`:

```
Config ../vpc/terragrunt.hcl is a dependency of ./terragrunt.hcl that has no outputs, but mock outputs provided and returning those in dependency output.
```

## Expected behavior

`terragrunt hcl validate` and `terragrunt hcl validate --inputs` should correctly resolve `dependency` blocks by treating the outputs attribute as available during static validation or by using the configured `mock_outputs`.

The command should behave analogously to how `terragrunt plan` handles dependency outputs when `mock_outputs` are defined.

## Versions

`terragrunt hcl validate` fails at least since 0.84.0
`terragrunt hcl validate --inputs` works for 0.97.2 and fails since 0.98.0
 
- Terragrunt version: 1.0.0, 0.98.0, 0.97.2, 0.84.0
- Terraform version: 1.14.7
- OS: macOS 26.4 (M2), Ubuntu 24.04 LTS, Amazon Linux 2023

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #5811.

`terragrunt hcl validate` previously failed with "Unsupported attribute" when a configuration referenced `dependency.<name>.outputs.<key>` without `mock_outputs`. 

During validation, output resolution is skipped, but the `outputs` attribute was never added to the dependency evaluation context, causing any output reference to error. The fix provides a dynamic placeholder for dependency outputs (and inputs) during validation so that attribute access evaluates to unknown rather than failing. Additionally, the dependency resolution pipeline is now more resilient during validation. Dependencies with unresolvable `config_path` values or nonexistent targets no longer cause the entire `dependency` namespace to disappear from the evaluation context.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Validation no longer errors for references to dependency outputs when mock outputs are absent; dependency attributes evaluate as unknown instead of failing.
  * Validation is more resilient: unresolved dependency config paths or missing targets no longer remove the dependency namespace.

* **Documentation**
  * Added v1.0.1 changelog entry documenting dependency validation improvements.

* **Tests**
  * Added fixtures covering dependency output and unresolvable-path validation scenarios.

### CODE REVIEW

File: pkg/config/dependency.go [hunk 1]
```diff
@@ -515,10 +536,17 @@ func dependencyBlocksToCtyValue(traceCtx context.Context, pctx *ParsingContext,
 					lock.Unlock()
 
 					dependencyEncodingMap["outputs"] = *dependencyConfig.RenderedOutputs
+				} else if pctx.SkipOutput {
+					// During hcl validate, output resolution is skipped. Use cty.DynamicVal so that
+					// attribute access on dependency outputs (e.g. dependency.x.outputs.y) evaluates
+					// to unknown rather than producing an "Unsupported attribute" error.
+					dependencyEncodingMap["outputs"] = cty.DynamicVal
```
Comment (denis256) [inline pkg/config/dependency.go:545]: Silent dynamic val setting, I was thinking that it may be helpful to do a debug log to know that this happened

**Review by denis256 — DISMISSED** [review]

File: pkg/config/dependency.go (hunk 1 above)
Comment (yhakbar) [reply pkg/config/dependency.go:545]: Added

**Review by denis256 — APPROVED** [review]
