### PR TITLE
#2467 Parallel TFLint execution errors

### LINKED ISSUE #2467: TFLint execution fail on reading generated files
Found that in case of multiple dependent modules, execution of tflint hook may fail on reading random files from `.terragrunt-cache` directory

```
Failed to load configurations; :0,0-0: Failed to read file; The file "../../../../../../../../../_regional/ecr-repos/.terragrunt-cache/7I4-il5IuWxHyoYlk8UCZ4i7ALo/fCw8UgbtyEKZwmAHcT_oAWkqDzs/modules/data-stores/ecr-repos/outputs.tf" does not exist., and 3 other diagnostic(s):

  on  line 0:
  (source code not available)

The file "../../../../../../../../../_regional/ecr-repos/.terragrunt-cache/7I4-il5IuWxHyoYlk8UCZ4i7ALo/fCw8UgbtyEKZwmAHcT_oAWkqDzs/modules/data-stores/ecr-repos/outputs.tf" does not exist.

Error: Failed to read file

  on  line 0:
  (source code not available)

The file "../../../../../../../../../_regional/ecr-repos/.terragrunt-cache/7I4-il5IuWxHyoYlk8UCZ4i7ALo/fCw8UgbtyEKZwmAHcT_oAWkqDzs/modules/data-stores/ecr-repos/provider.tf" does not exist.

```

### PR DESCRIPTION
**Pull request by denis256**
## Description

Included changes:
* defined map of locks used when source code changes are applied - downloading of source code, code generation
* added test which generates 50 modules that use one module to verify if tflint is executed without errors
* since tflint execution change working directory - extracted tflint tests in a separated file with sequential execution and separated CICD job

Fixes #2467.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Updated execution of tflint hook not be executed in the same time with downloading of dependencies and generation of terraform files.

### CODE REVIEW

File: cli/cli_app.go [hunk 1]
```diff
@@ -539,6 +530,31 @@ func RunTerragrunt(terragruntOptions *options.TerragruntOptions) error {
 	return runTerragruntWithConfig(terragruntOptions, updatedTerragruntOptions, terragruntConfig, false)
 }
 
+func generateConfig(terragruntConfig *config.TerragruntConfig, updatedTerragruntOptions *options.TerragruntOptions) error {
+	rawActualLock, _ := sourceChangeLocks.LoadOrStore(updatedTerragruntOptions.DownloadDir, &sync.Mutex{})
+	actualLock := rawActualLock.(*sync.Mutex)
```
Comment (marinalimeira) [inline cli/cli_app.go:535]: That's a good solution for the concurrency issue

**Review by marinalimeira — APPROVED** [review]
Thanks a lot for the fix! I tested it locally and it's working perfectly.

File: cli/cli_app.go [hunk 2]
```diff
@@ -539,6 +530,31 @@ func RunTerragrunt(terragruntOptions *options.TerragruntOptions) error {
 	return runTerragruntWithConfig(terragruntOptions, updatedTerragruntOptions, terragruntConfig, false)
 }
 
+func generateConfig(terragruntConfig *config.TerragruntConfig, updatedTerragruntOptions *options.TerragruntOptions) error {
+	rawActualLock, _ := sourceChangeLocks.LoadOrStore(updatedTerragruntOptions.DownloadDir, &sync.Mutex{})
```
Comment (brikis98) [inline cli/cli_app.go:534]: Is the second return arg an error? If so, shouldn't we handle it?

File: cli/cli_app.go [hunk 3]
```diff
@@ -715,6 +731,10 @@ func processHooks(hooks []config.Hook, terragruntOptions *options.TerragruntOpti
 				workingDir = *curHook.WorkingDir
 			}
 
+			rawActualLock, _ := sourceChangeLocks.LoadOrStore(workingDir, &sync.Mutex{})
+			actualLock := rawActualLock.(*sync.Mutex)
+			actualLock.Lock()
```
Comment (brikis98) [inline cli/cli_app.go:736]: Where's the unlock for this one?

Comment (brikis98) [reply cli/cli_app.go:736]: Oh, I see it way further down. Shouldn't it be in a `defer` right here to ensure it actually happens?

**Review by brikis98 — COMMENTED** [review]
I'm missing some context... Why is the code generation causing problems for `tflint`? And why does locking fix it?

**Comment by marinalimeira** [comment]
> I'm missing some context... Why is the code generation causing problems for `tflint`? And why does locking fix it?

When running `terragrunt plan/apply`, it generates some files, that `tflint` also verifies. When running `terragrunt` in a folder (like our generated `dev` environment), where some modules are dependent on others, `tflint`'s execution fails with the following error:

```
Failed to load configurations; us-west-2/_regional/service-quotas/.terragrunt-cache/Se3unvAhqLvfgdPeStzta0o1kXc/Y8HvXELUP-w73eRl14qBcHB6tuY/modules/request-quota-increase/main.tf:20,1-22: `iam_policies` module is not found. Did you run `terraform init`?; :

Failed to load configurations; :0,0-0: Failed to read file; The file "_global/ops-admin-role/.terragrunt-cache/5YhfosnJfHtL4YQUCe2Y-ihaiIU/ys8jy-n1SJGgEsoriEY2K6klFwc/modules/custom-iam-entity/provider_version_override.tf" does not exist.:

Failed to load configurations; :0,0-0: Failed to read file; The file "_global/ops-admin-role/.terragrunt-cache/5YhfosnJfHtL4YQUCe2Y-ihaiIU/ys8jy-n1SJGgEsoriEY2K6klFwc/modules/custom-iam-entity/provider_version_override.tf" does not exist.:

Failed to load configurations; :0,0-0: Failed to read file; The file "_global/account-baseline/.terragrunt-cache/2hLHzz2YVLupoiooPpuoEXnPdbk/bCEKY1MAKiwFzhWcmV6kScGevos/modules/landingzone/account-baseline-app/provider_version_override.tf" does not exist.:
```

When running `terragrunt` in subfolders, like `dev/_global/` or `dev/us-west-2/`, this problem doesn't happen. Also running with `--terragrunt-parallelism=1` in the `dev/` folder, the issue doesn't happen.

I paired with Denis and he figured out that it's a concurrency problem caused by the "code generation" step. This PR is adding the locks to make sure that `tflint` won't access an folder while other module is re-generating it.

**Comment by brikis98** [comment]
> I paired with Denis and he figured out that it's a concurrency problem caused by the "code generation" step. This PR is adding the locks to make sure that `tflint` won't access an folder while other module is re-generating it.

But what is the problem, specifically? What is happening concurrently that causes this issue? I know we generate code, but doesn't `tflint` run _after_ the code generation step? Where is the concurrent overlap?

**Comment by marinalimeira** [comment]
> > I paired with Denis and he figured out that it's a concurrency problem caused by the "code generation" step. This PR is adding the locks to make sure that `tflint` won't access an folder while other module is re-generating it.
> 
> But what is the problem, specifically? What is happening concurrently that causes this issue? I know we generate code, but doesn't `tflint` run _after_ the code generation step? Where is the concurrent overlap?

The concurrent step is when running `terragrunt run-all apply`. [You can see the full logs without the error fix in this gist](https://gist.github.com/marinalimeira/e1b464b29a72414ba09abdd9390fc84a).

It's the concurrency between all modules within the same environment. Logs with the error fix:
```
INFO[0001] The stack at /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev will be processed in the following order for command apply:
Group 1
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc

Group 2
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/sns-topic
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/alb
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/alb-internal
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/route53-private
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/ecs-deploy-runner

Group 3
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/openvpn-server

Group 4
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/data-stores/rds
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/ecs-cluster

Group 5
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/sample-app-backend
- Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/sample-app-frontend

Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n) y
INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc]
Plugin `aws-cis` is already installed
INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas]
INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc]
INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public]
INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role]
INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc]
Plugin `aws-cis` is already installed
INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas]
Plugin `aws-cis` is already installed
INFO[0009] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline]
INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc]
Plugin `aws-cis` is already installed
INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public]
Plugin `aws-cis` is already installed
INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role]
Plugin `aws-cis` is already installed
INFO[0010] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline]
Acquiring state lock. This may take a few moments...
Acquiring state lock. This may take a few moments...
Acquiring state lock. This may take a few moments...
Acquiring state lock. This may take a few moments...
Acquiring state lock. This may take a few moments...
Acquiring state lock. This may take a few moments...
```

File: cli/cli_app.go (hunk 2 above)
Comment (marinalimeira) [reply cli/cli_app.go:534]: No, it's a boolean that represents if the value for the lock key was loaded (true) of stored (false).

From the docs:
```
// LoadOrStore returns the existing value for the key if present.
// Otherwise, it stores and returns the given value.
// The loaded result is true if the value was loaded, false if stored.
```

File: cli/cli_app.go (hunk 3 above)
Comment (denis256) [reply cli/cli_app.go:736]: hi, I will try to update this soon - most probably it should be extracted as separated function, or moved at beginning of hooks function

**Comment by marinalimeira** [comment]
I will merge this PR so we can unblock the release, if there are fixes we can do it in a follow-up PR.

**Comment by brikis98** [comment]
> > > I paired with Denis and he figured out that it's a concurrency problem caused by the "code generation" step. This PR is adding the locks to make sure that `tflint` won't access an folder while other module is re-generating it.
> > 
> > 
> > But what is the problem, specifically? What is happening concurrently that causes this issue? I know we generate code, but doesn't `tflint` run _after_ the code generation step? Where is the concurrent overlap?
> 
> The concurrent step is when running `terragrunt run-all apply`. [You can see the full logs without the error fix in this gist](https://gist.github.com/marinalimeira/e1b464b29a72414ba09abdd9390fc84a).
> 
> It's the concurrency between all modules within the same environment. Logs with the error fix:
> 
> ```
> INFO[0001] The stack at /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev will be processed in the following order for command apply:
> Group 1
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc
> 
> Group 2
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/sns-topic
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/alb
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/alb-internal
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/route53-private
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/ecs-deploy-runner
> 
> Group 3
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/openvpn-server
> 
> Group 4
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/data-stores/rds
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/ecs-cluster
> 
> Group 5
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/sample-app-backend
> - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/sample-app-frontend
> 
> Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n) y
> INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc]
> Plugin `aws-cis` is already installed
> INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas]
> INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc]
> INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public]
> INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role]
> INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc]
> Plugin `aws-cis` is already installed
> INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas]
> Plugin `aws-cis` is already installed
> INFO[0009] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline]
> INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc]
> Plugin `aws-cis` is already installed
> INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public]
> Plugin `aws-cis` is already installed
> INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role]
> Plugin `aws-cis` is already installed
> INFO[0010] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline]
> Acquiring state lock. This may take a few moments...
> Acquiring state lock. This may take a few moments...
> Acquiring state lock. This may take a few moments...
> Acquiring state lock. This may take a few moments...
> Acquiring state lock. This may take a few moments...
> Acquiring state lock. This may take a few moments...
> ```

I'm not trying to be a pain, but I still don't have a good mental model of what's happening here:

1. You run `run-all apply`. 
2. Let's say there are 5 folders, and `apply` is happening concurrently in all of them.
3. In each of the 5 folders, some code generation may happen.
4. I'm seeing some errors from `tflint` about not being able to read files.

Which files are affected in (4)? Is it specifically generated files? If so, doesn't `tflint` run _after_ code generation? If so, why are we seeing an error? Is something concurrently deleting the files?

**Comment by marinalimeira** [comment]
> > > > I paired with Denis and he figured out that it's a concurrency problem caused by the "code generation" step. This PR is adding the locks to make sure that `tflint` won't access an folder while other module is re-generating it.
> > > 
> > > 
> > > But what is the problem, specifically? What is happening concurrently that causes this issue? I know we generate code, but doesn't `tflint` run _after_ the code generation step? Where is the concurrent overlap?
> > 
> > 
> > The concurrent step is when running `terragrunt run-all apply`. [You can see the full logs without the error fix in this gist](https://gist.github.com/marinalimeira/e1b464b29a72414ba09abdd9390fc84a).
> > It's the concurrency between all modules within the same environment. Logs with the error fix:
> > ```
> > INFO[0001] The stack at /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev will be processed in the following order for command apply:
> > Group 1
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc
> > 
> > Group 2
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/sns-topic
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/alb
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/alb-internal
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/route53-private
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/ecs-deploy-runner
> > 
> > Group 3
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/openvpn-server
> > 
> > Group 4
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/data-stores/rds
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/ecs-cluster
> > 
> > Group 5
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/sample-app-backend
> > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/sample-app-frontend
> > 
> > Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n) y
> > INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc]
> > Plugin `aws-cis` is already installed
> > INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas]
> > INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc]
> > INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public]
> > INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role]
> > INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc]
> > Plugin `aws-cis` is already installed
> > INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas]
> > Plugin `aws-cis` is already installed
> > INFO[0009] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline]
> > INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc]
> > Plugin `aws-cis` is already installed
> > INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public]
> > Plugin `aws-cis` is already installed
> > INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role]
> > Plugin `aws-cis` is already installed
> > INFO[0010] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline]
> > Acquiring state lock. This may take a few moments...
> > Acquiring state lock. This may take a few moments...
> > Acquiring state lock. This may take a few moments...
> > Acquiring state lock. This may take a few moments...
> > Acquiring state lock. This may take a few moments...
> > Acquiring state lock. This may take a few moments...
> > ```
> 
> I'm not trying to be a pain, but I still don't have a good mental model of what's happening here:
> 
>     1. You run `run-all apply`.
> 
>     2. Let's say there are 5 folders, and `apply` is happening concurrently in all of them.
> 
>     3. In each of the 5 folders, some code generation may happen.
> 
>     4. I'm seeing some errors from `tflint` about not being able to read files.
> 
> 
> Which files are affected in (4)? Is it specifically generated files? If so, doesn't `tflint` run _after_ code generation? If so, why are we seeing an error? Is something concurrently deleting the files?

Yes, `tflint` does run after code generation, but some modules depend on the others. See the graph below. When `rds`, `openvpn-server`, `route53-private`, `alb-internal`, `alb` etc run, they all re-generate the `vpc` one. When a subset of them try to do it at the same time, `tflint` raises an error because the file can't be read.

image

**Comment by marinalimeira** [comment]
> > > > > > I paired with Denis and he figured out that it's a concurrency problem caused by the "code generation" step. This PR is adding the locks to make sure that `tflint` won't access an folder while other module is re-generating it.
> > > > > 
> > > > > 
> > > > > But what is the problem, specifically? What is happening concurrently that causes this issue? I know we generate code, but doesn't `tflint` run _after_ the code generation step? Where is the concurrent overlap?
> > > > 
> > > > 
> > > > The concurrent step is when running `terragrunt run-all apply`. [You can see the full logs without the error fix in this gist](https://gist.github.com/marinalimeira/e1b464b29a72414ba09abdd9390fc84a).
> > > > It's the concurrency between all modules within the same environment. Logs with the error fix:
> > > > ```
> > > > INFO[0001] The stack at /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev will be processed in the following order for command apply:
> > > > Group 1
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc
> > > > 
> > > > Group 2
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/sns-topic
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/alb
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/alb-internal
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/route53-private
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/ecs-deploy-runner
> > > > 
> > > > Group 3
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/openvpn-server
> > > > 
> > > > Group 4
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/data-stores/rds
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/ecs-cluster
> > > > 
> > > > Group 5
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/sample-app-backend
> > > > - Module /Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/services/sample-app-frontend
> > > > 
> > > > Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n) y
> > > > INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc]
> > > > Plugin `aws-cis` is already installed
> > > > INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas]
> > > > INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc]
> > > > INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public]
> > > > INFO[0008] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role]
> > > > INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/mgmt/networking/vpc]
> > > > Plugin `aws-cis` is already installed
> > > > INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/_regional/service-quotas]
> > > > Plugin `aws-cis` is already installed
> > > > INFO[0009] Executing hook: tflint                        prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline]
> > > > INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/us-west-2/dev/networking/vpc]
> > > > Plugin `aws-cis` is already installed
> > > > INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/route53-public]
> > > > Plugin `aws-cis` is already installed
> > > > INFO[0009] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/ops-admin-role]
> > > > Plugin `aws-cis` is already installed
> > > > INFO[0010] Tflint has run successfully. No issues found.  prefix=[/Users/marina/go/src/github.com/gruntwork-io/infrastructure-live-marina-34nd9/dev/_global/account-baseline]
> > > > Acquiring state lock. This may take a few moments...
> > > > Acquiring state lock. This may take a few moments...
> > > > Acquiring state lock. This may take a few moments...
> > > > Acquiring state lock. This may take a few moments...
> > > > Acquiring state lock. This may take a few moments...
> > > > Acquiring state lock. This may take a few moments...
> > > > ```
> > > 
> > > 
> > > I'm not trying to be a pain, but I still don't have a good mental model of what's happening here:
> > > ```
> > > 1. You run `run-all apply`.
> > > 
> > > 2. Let's say there are 5 folders, and `apply` is happening concurrently in all of them.
> > > 
> > > 3. In each of the 5 folders, some code generation may happen.
> > > 
> > > 4. I'm seeing some errors from `tflint` about not being able to read files.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Which files are affected in (4)? Is it specifically generated files? If so, doesn't `tflint` run _after_ code generation? If so, why are we seeing an error? Is something concurrently deleting the files?
> > 
> > 
> > Yes, `tflint` does run after code generation, but some modules depend on the others. See the graph below. When `rds`, `openvpn-server`, `route53-private`, `alb-internal`, `alb` etc run, they all re-generate the `vpc` one. When a subset of them try to do it at the same time, `tflint` raises an error because the file can't be read.
> > image
> 
> Ah, OK, so it sounds like the issue is:
> 
>     1. We run `run-all apply`.
> 
>     2. One of the modules, say, `vpc`, generates some file `foo.tf`, and starts running `tflint`.
> 
>     3. Another module that depends on `vpc` (via `dependency` block) is running concurrently, and it ends up re-generating `foo.tf`, just as `tflint` is trying to process it.
> 
> 
> Is that right?

Yes, that's exactly what's happening!

> And it looks like the fix is:
> 
>     1. Add a lock to generate code into folder XXX.
> 
>     2. Add a lock to run hooks in folder XXX.
> 
>     3. So in theory, this ensures that if a hook (e.g., `tflint`) is running, we aren't concurrently overriding code in that same folder with code generation.
> 
> 
> Is that right?

Yep, it's what this PR is doing.

> If so, then a few questions/comments:
> 
>     1. We need to add comments above that lock / `sync.Map` to explain this and link back to this PR discussion. Otherwise, future maintainers will have to reverse engineer what's going on. This can be in a follow-up PR.

Opened a PR with the new comment: https://github.com/gruntwork-io/terragrunt/pull/2476

>     2. We should ensure we're unlocking in a `defer` as mentioned in the comment above. Again, this can be in a follow-up PR.

Got it. I  will create a new task, [Denis already commented above that he will follow-up on this](https://github.com/gruntwork-io/terragrunt/pull/2469/files#r1120111692).

>     3. How confident are we that we lock on _all_ file changes in a given folder `xxx` inside of `.terragrunt-cache`? Here's a few I can think of:
>        
>        1. Generating code into `xxx` via a `generate` block. I think we have a lock here.
>        2. Generating code into `xxx` via the `backend` block. Do we lock on this?
>        3. Copying code into `xxx` from the working directory: we copy over any files that are sitting adjacent to the `terragrunt.hcl`, such as any `.tf` files, `.tfvars` files, etc. Do we lock on this?
>        4. Running `terraform init` in folder `xxx`. This will result in `.xxx/.terraform` being regenerated. Do we lock on this?
>        5. What else?

I will take a look on the code on Monday!
 
>     4. Thought experiment: is locking on code generation and hooks in folder `xxx` the right solution? Or should we be locking on _all_ TG execution in folder `xxx`? For example, when you do `run-all apply`, we start executing, say, 3 modules concurrently: `A`, `B`, `C`. Now imagine that `A` and `B` both depends on `C` via a `dependency` blocks. Before this PR, we could run code generation and hooks in `C` twice, concurrently, once from each of `A` and `B`'s `dependency` blocks. With this PR, we now have locking on code generation and hooks... But perhaps what we really want is a _global_ lock, so that only one thing can execute `C` at a time: if we're processing a `dependency` block on `C` from `A`, then processing the `dependency` block from `B` has to wait. That will include the code generation and hooks, but also code copying, `init`, and anything else we add in the future.

I will raise this in an issue! We can continue the discussion from there.
 
>     5. Thought experiment: should code generation be idempotent? If code generation creates a file `foo.tf`, and its contents are the same as the `foo.tf` on disk, perhaps we don't overwrite it?

I will add this on the same issue as (4).

**Comment by brikis98** [comment]
Thanks @marinalimeira!
