### PR TITLE
Fixing converting absolute paths to relative in logs

### LINKED ISSUE #3428: Issue with module path logging
## Describe the bug

Since #3400 module path logged in Group 1 has and incorrect path listed, also initial INFO entries related to "Retrieved output from" are missing.

## Steps To Reproduce

Using source (but also happens with compiled version)

`go run main.go run-all init --terragrunt-non-interactive --terragrunt-working-dir /workspace/redacted/environment-definitions/nonprod/na/projects/redacted/dev-na/us-east-2/databricks`

Log:

```
Group 1
- Module ./primary../../../../../../../../..

Group 2
- Module ./primary/catalogs
- Module ./primary/compute_pools
- Module ./primary/external_locations
- Module ./primary/sql_warehouses


17:48:45.727 STDOUT [primary../../../../../../../../..] terraform: Initializing the backend...
17:48:49.996 STDOUT [primary../../../../../../../../..] terraform: Initializing modules...
17:48:50.031 STDOUT [primary../../../../../../../../..] terraform: Initializing provider plugins...
17:48:50.031 STDOUT [primary../../../../../../../../..] terraform: - Reusing previous version of hashicorp/time from the dependency lock file
17:48:50.158 STDOUT [primary../../../../../../../../..] terraform: - Reusing previous version of databricks/databricks from the dependency lock file
17:48:51.252 STDOUT [primary../../../../../../../../..] terraform: - Reusing previous version of hashicorp/random from the dependency lock file
17:48:51.328 STDOUT [primary../../../../../../../../..] terraform: - Reusing previous version of hashicorp/aws from the dependency lock file
17:48:51.416 STDOUT [primary../../../../../../../../..] terraform: - Using previously-installed hashicorp/random v3.6.2
17:48:51.756 STDOUT [primary../../../../../../../../..] terraform: - Using previously-installed hashicorp/aws v5.65.0
17:48:51.768 STDOUT [primary../../../../../../../../..] terraform: - Using previously-installed hashicorp/time v0.12.0
17:48:51.799 STDOUT [primary../../../../../../../../..] terraform: - Using previously-installed databricks/databricks v1.51.0
17:48:51.799 STDOUT [primary../../../../../../../../..] terraform: Terraform has been successfully initialized!
17:48:51.799 STDOUT [primary../../../../../../../../..] terraform: You may now begin working with Terraform. Try running "terraform plan" to see
17:48:51.799 STDOUT [primary../../../../../../../../..] terraform: any changes that are required for your infrastructure. All Terraform commands
17:48:51.799 STDOUT [primary../../../../../../../../..] terraform: should now work.
17:48:51.800 STDOUT [primary../../../../../../../../..] terraform: If you ever set or change modules or backend configuration for Terraform,
17:48:51.800 STDOUT [primary../../../../../../../../..] terraform: rerun this command to reinitialize your working directory. If you forget, other
17:48:51.800 STDOUT [primary../../../../../../../../..] terraform: commands will detect it and remind you to do so if necessary.
17:48:57.111 STDOUT [primary/sql_warehouses] terraform: Initializing the backend...
```

## Expected behavior

Log:

```
Group 1
- Module primary/workspace

Group 2
- Module primary/catalogs
- Module primary/compute_pools
- Module primary/external_locations
- Module primary/sql_warehouses


17:51:36.409 INFO   [../../../databricks/rbac/groups] Retrieved output from ../../../databricks/rbac/groups/terragrunt.hcl
17:52:22.475 INFO   [../../../../platform/dev-na/us-east-2/kms_keys] Retrieved output from ../../../../platform/dev-na/us-east-2/kms_keys/terragrunt.hcl
17:52:33.557 INFO   [../../../databricks/rbac/svc_principals/dev_na_tableau] Retrieved output from ../../../databricks/rbac/svc_principals/dev_na_tableau/terragrunt.hcl
17:52:37.358 INFO   [../../../databricks/metastores] Retrieved output from ../../../databricks/metastores/terragrunt.hcl
17:52:40.240 STDOUT [primary/workspace] terraform: Initializing the backend...
17:52:43.879 STDOUT [primary/workspace] terraform: Initializing modules...
17:52:43.903 STDOUT [primary/workspace] terraform: Initializing provider plugins...
17:52:43.903 STDOUT [primary/workspace] terraform: - Reusing previous version of hashicorp/aws from the dependency lock file
17:52:44.040 STDOUT [primary/workspace] terraform: - Reusing previous version of hashicorp/time from the dependency lock file
17:52:45.169 STDOUT [primary/workspace] terraform: - Reusing previous version of databricks/databricks from the dependency lock file
17:52:45.250 STDOUT [primary/workspace] terraform: - Reusing previous version of hashicorp/random from the dependency lock file
17:52:45.631 STDOUT [primary/workspace] terraform: - Using previously-installed hashicorp/aws v5.65.0
17:52:45.639 STDOUT [primary/workspace] terraform: - Using previously-installed hashicorp/time v0.12.0
17:52:45.668 STDOUT [primary/workspace] terraform: - Using previously-installed databricks/databricks v1.51.0
17:52:45.677 STDOUT [primary/workspace] terraform: - Using previously-installed hashicorp/random v3.6.2
17:52:45.677 STDOUT [primary/workspace] terraform: Terraform has been successfully initialized!
17:52:45.677 STDOUT [primary/workspace] terraform: You may now begin working with Terraform. Try running "terraform plan" to see
17:52:45.677 STDOUT [primary/workspace] terraform: any changes that are required for your infrastructure. All Terraform commands
17:52:45.677 STDOUT [primary/workspace] terraform: should now work.
17:52:45.677 STDOUT [primary/workspace] terraform: If you ever set or change modules or backend configuration for Terraform,
17:52:45.677 STDOUT [primary/workspace] terraform: rerun this command to reinitialize your working directory. If you forget, other
17:52:45.677 STDOUT [primary/workspace] terraform: commands will detect it and remind you to do so if necessary.
17:52:49.200 INFO   [primary/workspace] Retrieved output from primary/workspace/terragrunt.hcl
17:52:51.101 STDOUT [primary/catalogs] terraform: Initializing the backend...
```

## Versions

- Terragrunt version: 0.67.5
- OpenTofu/Terraform version: Terraform v1.9.2
- Environment details (Ubuntu 20.04, Windows 10, etc.): Debian Bookworm

## Additional context

Commits before #3400 and version 0.67.4 work as expected.

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Fixes #3428.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### CODE REVIEW

File: test/integration_test.go [hunk 1]
```diff
@@ -149,6 +150,47 @@ func TestLogWithAbsPath(t *testing.T) {
...
+				assert.Contains(t, stderr, "Module ./bbb/ccc/module-b")
+				assert.Contains(t, stderr, "Downloading Terraform configurations from .. into ./bbb/ccc/workspace/.terragrunt-cache")
+				assert.Contains(t, stderr, "[bbb/ccc/workspace]")
+				assert.Contains(t, stderr, "[bbb/ccc/module-b]")
+			},
+		},
+	}
+
+	for i, testCase := range testCases {
+		testCase := testCase
```
Comment (yhakbar) [inline test/integration_test.go:179]: @levkohimins you don't need to do this anymore, as of go 1.22:
https://tip.golang.org/doc/go1.22

Comment (levkohimins) [reply test/integration_test.go]: Understood. Fixed. Thanks.

**Review by yhakbar — APPROVED** [review]
