### PR TITLE
fix: Fixing cache server absolute URLs in self-discovery

### LINKED ISSUE #5156: Terragrunt (Cache server) fails when absolute URLs used in registry's self-discovery (`modules.v1`)
## Describe the bug

When using Cache Server and trying to pull a sub-module from a Terraform registry that uses absolute URLs in it's self discovery the module will fail to retrieve with a message:

```bash
  │ Error: Error accessing remote module registry
  │ 
  │   on my-module.tf line 1:
  │    1: module "my-module" {
  │ 
  │ Failed to retrieve available versions for module "my-module"
  │ (my-module.tf:1) from private.registry.url: the request failed after
  │ 2 attempts, please try again later: Get
  │ "https://<hostname><absolute-url>/registry/my-module/aws/versions":
  │ dial tcp: lookup <hostname>https on <IP>:<PORT>: no such
  │ host.
```

## Steps To Reproduce

1. Use a registry that uses absolute paths in it's self-discovery, e.g.:
```bash
$ curl https://packages.syncron.team/.well-known/terraform.json
{
  "modules.v1" : "https://<hostname>/somepath/modules/",
}
```
2. Pull the module within a `.tf` file:
```hcl
module "my-module" {
  source = "<hostname>/registry/my-module/aws"
  version = "= 1.0.0"
}
```
3. Try to run `terragrunt plan`
4. Observe the error

## Expected behavior

Terragrunt pulls the module

## Versions

- Terragrunt version: `0.93.11`
- OpenTofu/Terraform version: `1.8.5`
- Environment details (Ubuntu 20.04, Windows 10, etc.): Ubuntu 24.04

## Additional information

I've traced the root of the problem to https://github.com/gruntwork-io/terragrunt/blob/main/internal/providercache/provider_cache.go#L322 

It seems that the Cache Server is naively assuming relative URLs without double checking (and `DiscoveryURL` is also just a container for the contents present in the file).

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #5156.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Bug Fixes
- Fixed module URL resolution to correctly handle Terraform registries that return absolute URLs in discovery responses, preventing malformed URL construction with double hostnames.

### CODE REVIEW

File: test/integration_serial_test.go [hunk 1]
```diff
@@ -240,6 +240,116 @@ func TestTerragruntProviderCacheWithNetworkMirror(t *testing.T) {
...
+	err = os.WriteFile(terragruntHclPath, []byte("# Test fixture for absolute module URL\n"), 0644)
+	require.NoError(t, err)
+
+	cliConfigFilename, err := os.CreateTemp(helpers.TmpDirWOSymlinks(t), "*")
+	require.NoError(t, err)
+
+	defer cliConfigFilename.Close()
+
+	t.Setenv(tf.EnvNameTFCLIConfigFile, cliConfigFilename.Name())
+	defer os.Unsetenv(tf.EnvNameTFCLIConfigFile)
```
Comment (denis256) [inline test/integration_serial_test.go:302]: t.Setenv() already registers a t.Cleanup to restore the env var.

File: internal/providercache/provider_cache.go [hunk 2]
```diff
@@ -565,3 +565,14 @@ func filterRegistriesByImplementation(registryNames []string, implementation opt
...
+
+// ResolveModulesURL resolves the modules.v1 URL from registry discovery.
+// If the URL is already absolute (contains "://"), it is returned as-is.
+// Otherwise, it is treated as a relative path and combined with the registry name.
+func ResolveModulesURL(registryName, modulesV1 string) string {
+	if strings.Contains(modulesV1, "://") {
+		return modulesV1
+	}
+
+	return fmt.Sprintf("https://%s%s", registryName, modulesV1)
```
Comment (denis256) [inline internal/providercache/provider_cache.go:577]: Most probably will not happen, but if modulesV1 is a relative path and lacks a leading /, the output URL has no path separator

**Review by denis256 — APPROVED** [review]
