### PR TITLE
fix: Fixing remote state init skip

### LINKED ISSUE #2082: terragrunt does not pass -backend=false to terraform
Looks like terragrunt swallows the `-backend=false` flag during init ops. We need this to run linting against the codebase on an execution env that has no credentials.

```
~ terragrunt init -backend=false
╷
│ Error: Backend initialization required, please run "terraform init"
│ 
│ Reason: Initial configuration of the requested backend "s3"
[...]
~ terragrunt init -backend=false --terragrunt-no-auto-init
╷
│ Error: Backend initialization required, please run "terraform init"
│ 
│ Reason: Initial configuration of the requested backend "s3"
[...]
```
However, with terraform directly:

```
~  terraform init -backend=false 
Initializing modules...
- bastion in ../../modules/bastion

Initializing provider plugins...
- Finding latest version of hashicorp/template...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v4.11.0...
- Installed hashicorp/aws v4.11.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)

[...]

Terraform has been successfully initialized!
[...]
```

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #2082.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Updated package `remote`.

### CODE REVIEW

File: remote/remote_state.go [hunk 1]
```diff
@@ -94,10 +94,16 @@ func (remoteState *RemoteState) Initialize(ctx context.Context, terragruntOption
...
-// 1. Remote state has not already been configured
-// 2. Remote state has been configured, but with a different configuration
-// 3. The remote state initializer for this backend type, if there is one, says initialization is necessary
+// 1. Remote state auto-initialization has been disabled
+// 2. Remote state has not already been configured
+// 3. Remote state has been configured, but with a different configuration
+// 4. The remote state initializer for this backend type, if there is one, says initialization is necessary
 func (remoteState *RemoteState) NeedsInit(terragruntOptions *options.TerragruntOptions) (bool, error) {
+	if terragruntOptions.DisableBucketUpdate {
+		terragruntOptions.Logger.Debugf("Skipping remote state initialization due to --terragrunt-disable-bucket-update flag")
```
Comment (levkohimins) [inline remote/remote_state.go:103]:
```suggestion
		terragruntOptions.Logger.Debugf("Skipping remote state initialization due to --%s flag", commands.TerragruntDisableBucketUpdateFlagName)
```

If the flag is renamed, we are unlikely to remember to update the log message. It is more reliable to use the flag name from the constant.

**Review by levkohimins — CHANGES_REQUESTED** [review]

File: remote/remote_state.go (hunk 1 above)
Comment (yhakbar) [reply remote/remote_state.go]: Resolved.

**Review by levkohimins — APPROVED** [review]
Thanks!
