### PR TITLE
Scaffold command, fix unable to handle https URL

### LINKED ISSUE #2987: Scaffold command doesn't handle "https" in a URL correctly, and also doesn't handle errors correctly
**Describe the bug**

1. The `scaffold` command can handle `github.com` URLs, but not `https://github.com` URLs. 
2. When the `scaffold` command fails to handle a URL, it logs a warning, but then proceeds with code generation anyway, so you end up with a largely empty `terragrunt.hcl`.

**To Reproduce**

```hcl
terragrunt scaffold https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example//modules/s3-bucket
```

In the logs, you'll briefly see:

```
WARN[0000] Failed to parse url https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/tree/master/modules/s3-bucket
WARN[0000] Failed to parse module url https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/tree/master/modules/s3-bucket
fatal: remote error:
 gruntwork-io/terragrunt-infrastructure-modules-example/tree/master/modules/s3-bucket is not a valid repository name
Visit https://support.github.com/ for help
WARN[0001] Failed to find last release tag for https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/tree/master/modules/s3-bucket
```

Then the screen is cleared and you get:

```
INFO[0001] Scaffolding a new Terragrunt module https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/tree/master/modules/s3-bucket to /tmp/test-scaffolding
INFO[0001] Running boilerplate generation to /tmp/test-scaffolding
```

And you then end up with a `terragrunt.hcl` where none of the required or optional input variables have been filled in.

**Expected behavior**

1. If `scaffold` can't process a URL, it should show an error and exit.
2. That said, since users are likely to copy/paste URLs from their browser, we should probably make URLs with the `https://` prefix work. FWIW, I believe the `catalog` command _does_ handle the "https://" prefix OK, so perhaps we can reuse the code from there?

**Versions**
- Terragrunt version: v0.55.13

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Fixes the issue where the `scaffold` command is unable to parse a URL with the http(s) scheme.

Fixes #2987.

### CODE REVIEW

**Review by autero1 — DISMISSED** [review]
LGTM!

File: terraform/source_test.go [hunk 1]
```diff
@@ -54,12 +54,41 @@ func TestSplitSourceUrl(t *testing.T) {
...
 		})
 	}
 }
 
+func TestToSourceUrl(t *testing.T) {
+	t.Parallel()
+
+	testCases := []struct {
+		sourceURL         string
+		workingDir        string
```
Comment (denis256) [inline terraform/source_test.go:68]: looks like `workingDir` is empty in each test case, do we need it in the struct?

Comment (levkohimins) [reply terraform/source_test.go:68]: Thanks. Added a few test cases with the workingDir values.

**Review by denis256 — DISMISSED** [review]

File: terraform/source.go [hunk 2]
```diff
@@ -195,7 +195,16 @@ func ToSourceUrl(source string, workingDir string) (*url.URL, error) {
...
+	sourceUrl, err := parseSourceUrl(rawSourceUrlWithGetter)
+	if err != nil {
+		return nil, err
+	}
+
+	// explicitly add prefix git:: for the http scheme to avoid further errors
+	if strings.HasPrefix(sourceUrl.Scheme, "http") {
+		sourceUrl.Scheme = "git::" + sourceUrl.Scheme
+	}
+	return sourceUrl, nil
```
Comment (brikis98) [inline terraform/source.go:207]: How do we know that an http URL is always Git? Terraform supports a variety of [source URLs](https://developer.hashicorp.com/terraform/language/modules/sources), including some http URLs that are _not_ Git.

Comment (levkohimins) [reply terraform/source.go:207]: Here we add the default _git_ protocol if the user has not specified anything. Otherwise, we will then get an error when we ask go-getter to clone a repository.
I just thought, that we should add `git` it not only to `https://`, but also to `ssh://`

Comment (levkohimins) [reply terraform/source.go]: without default protocol `getter.Get` returns 
```
 *errors.errorString error downloading 'https://github.com/gruntwork-io/terraform-aws-lambda': bad response code: 404
```

Comment (brikis98) [reply terraform/source.go]: Hm, I'm not sure that's right. I think we need to be more picky and do checks based on the supported [module source URLs](https://developer.hashicorp.com/terraform/language/modules/sources):

- If it starts with `http` and the domain is `github.com`, `gitlab.com`, or `bitbucket.org`, or the URL contains `.git`, then I think we can safely prepend `git::`.
- If it starts with `http` and the domain includes `amazonaws.com`, we prepend `s3::`.
- If it starts with `http` and the domain includes `googleapis.com`, we prepend `gcs::`.

Comment (levkohimins) [reply terraform/source.go]: Ah, understood. It's redone, thank you.

File: terraform/source.go [hunk 3]
```diff
@@ -195,7 +199,57 @@ func ToSourceUrl(source string, workingDir string) (*url.URL, error) {
 		return nil, errors.WithStackTrace(err)
 	}
 
-	return parseSourceUrl(rawSourceUrlWithGetter)
+	sourceUrl, err := parseSourceUrl(rawSourceUrlWithGetter)
```
Comment (brikis98) [inline terraform/source.go:202]: Sorry I didn't notice this before, but I'm noticing you're passing in `rawSourceUrlWithGetter` to this method. The `WithGetter` part suggests to me this is a "getter" as parsed by the `go-getter` library. is it possible that the getter is _already_ set to the value we need, and we just need to prepend it at the end? In other words, we don't need to write our own custom logic to figure out the getter?

File: terraform/source.go [hunk 4]
```diff
@@ -195,7 +199,57 @@ func ToSourceUrl(source string, workingDir string) (*url.URL, error) {
...
+	if err != nil {
+		return nil, err
+	}
+
+	return PrependSourceType(sourceUrl), nil
+}
+
+// PrependSourceType prepends one of the "s3, gcs3, hg, git" source type to the http(s)/ssh scheme, if the user has omittied it.
```
Comment (brikis98) [inline terraform/source.go:210]: NIT: link to module source URL docs or maybe go-getter docs as context on what these are.

File: terraform/source.go (hunk 3 above)
Comment (levkohimins) [reply terraform/source.go:202]: Understand your thought, because I was thinking the same, since this is the same Golang package, it would be logical that the result from `getter.Detect` could be immediately used for `getter.Get`, but unfortunately this is not the case. I tested, `getter.Detect` does prepend a source type if we only pass URL without scheme:

 `github.com/gruntwork-io/terraform-aws-lambda` -> `git::https://github.com/gruntwork-io/terraform-aws-lambda.git`

and doesn't if there's the scheme:

`https://github.com/gruntwork-io/terraform-aws-lambda` -> `https://github.com/gruntwork-io/terraform-aws-lambda.git`

I also tested to pass `https://github.com/gruntwork-io/terraform-aws-lambda` to `getter.Get`, and got the error

```
'https://github.com/gruntwork-io/terraform-aws-lambda': bad response code: 404
```

File: terraform/source.go (hunk 4 above)
Comment (levkohimins) [reply terraform/source.go:210]: Updated the comment. Thanks.

File: terraform/source_test.go [hunk 5]
```diff
@@ -54,12 +54,50 @@ func TestSplitSourceUrl(t *testing.T) {
...
 			require.NoError(t, err)
 
-			assert.Equal(t, testCase.expectedRootRepo, actualRootRepo.String())
+			assert.Equal(t, testCase.expectedSo, actualRootRepo.String())
 			assert.Equal(t, testCase.expectedModulePath, actualModulePath)
 		})
 	}
 }
 
+func TestPrependSourceType(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply terraform/source_test.go:63]: Thanks.

File: terraform/source.go (hunk 3 above)
Comment (levkohimins) [reply terraform/source.go:202]: The only way is if we remove the schema before passing it to `Detect`.

Comment (levkohimins) [reply terraform/source.go]: There is a new version 2.2.1 of `go-getter`, but it is very different from the 1.7.1 version we are using now.
We'll have to rewrite the code to use it. I don’t yet know how it behaves with the http scheme. Should I check this?

Comment (brikis98) [reply terraform/source.go]: Thanks for looking into it. Prob not worth a big upgrade now. Let's go with what you have here.

**Review by brikis98 — APPROVED** [review]
LGTM

**Comment by levkohimins** [comment]
> LGTM

Thanks for the review!
