### PR TITLE
fix: checking dependent modules in `destroy` command

### LINKED ISSUE #2508: Destroy command failing to find file when using dependency
I have the following setup:

```text
├── terraform
│   ├── envs
│   │   └── dev
│   │       ├── base
│   │       │   └── main.tf
│   │       └── cluster
│   │           └── main.tf
│   └── states
│       ├── dev-base.state
│       └── dev-cluster.state
└── terragrunt
    ├── envs
    │   └── dev
    │       ├── base
    │       │   ├── terragrunt.hcl
    │       │   └── tier.hcl
    │       ├── cluster
    │       │   ├── terragrunt.hcl
    │       │   └── tier.hcl
    │       └── env.hcl
    ├── org.hcl
    └── terragrunt.hcl
```

Where the files content is as follows:

```hcl
# terraform/envs/dev/base/main.tf      
output "some_output" {
  value = "something"
}
```
```hcl
# terraform/envs/dev/cluster/main.tf 
variable "some_input" {}

output "some_output" {
  value = "${var.some_input} else"
}
```
```hcl
# terragrunt/envs/dev/base/terragrunt.hcl    
terraform {
  source = "../../../../terraform//envs/dev/base"
}

include {
  path = find_in_parent_folders()
}
```
```hcl
# terragrunt/envs/dev/cluster/terragrunt.hcl 
terraform {
  source = "../../../../terraform//envs/dev/cluster"
}

include {
  path = find_in_parent_folders()
}

dependency "base" {
  config_path = "../base"
}

inputs = {
  some_input = dependency.base.outputs.some_output
}
```
```hcl
# terragrunt/terragrunt.hcl                  
locals {
  org_vars = read_terragrunt_config(find_in_parent_folders("org.hcl"))
  env_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  tier_vars = read_terragrunt_config("tier.hcl")

  organization_unit = local.org_vars.locals.organization_unit
  environment       = local.env_vars.locals.environment
  tier              = local.tier_vars.locals.tier
}

generate "provider" {
  path      = "terraform.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    terraform {
      backend "local" {
        path = "../../../../../../../../../../terraform/states/${local.environment}-${local.tier}.state"
      }
    }
    EOF
}

inputs = merge(
  local.org_vars.locals,
  local.env_vars.locals,
  local.tier_vars.locals,
)
```
```hcl
# terragrunt/envs/dev/base/tier.hcl    
locals {
  tier = "base"
}
```
```hcl
# terragrunt/envs/dev/cluster/tier.hcl       
locals {
  tier = "cluster"
}
```
```hcl
# terragrunt/envs/dev/env.hcl       
locals {
  environment = "dev"
}
```
```hcl
# terragrunt/org.hcl          
locals {
  organization_unit = "test"
}
```

When I run `terragrunt apply` from the `terragrunt/envs/dev/base` directory and then from the `terragrunt/envs/dev/cluster` directory, all works just fine. But once I run `terragrunt destroy` from the `terragrunt/envs/dev/cluster` directory, I get an error the it cannot find files used in the included `terragrunt.hcl` but the destruction works just fine:

```text
ERRO[0000] Error: Error in function call
       prefix=[/tmp/test/terragrunt] 
ERRO[0000]   on /tmp/test/terragrunt/terragrunt.hcl line 2, in locals:  prefix=[/tmp/test/terragrunt] 
ERRO[0000]    2:   org_vars = read_terragrunt_config(find_in_parent_folders("org.hcl"))  prefix=[/tmp/test/terragrunt] 
ERRO[0000]                                               prefix=[/tmp/test/terragrunt] 
ERRO[0000] Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a org.hcl in any of the parent folders of /tmp/test/terragrunt/terragrunt.hcl. Cause: Traversed all the
way to the root..
  prefix=[/tmp/test/terragrunt] 
ERRO[0000] Encountered error while evaluating locals in file /tmp/test/terragrunt/terragrunt.hcl  prefix=[/tmp/test/terragrunt] 

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Changes to Outputs:
  - some_output = "something else" -> null

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value:
```

But if I comment out the `dependency` related blocks from the `terragrunt/envs/dev/cluster/terragrunt.hcl` file:

```hcl
terraform {
  source = "../../../../terraform//envs/dev/cluster"
}

include {
  path = find_in_parent_folders()
}

#dependency "base" {
#  config_path = "../base"
#}

inputs = {
  #some_input = dependency.base.outputs.some_output
  some_input = "something"
}
```

the `terragrunt destroy` command is showing no error:

```text

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Changes to Outputs:
  - some_output = "something else" -> null

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: 
```

It looks like when the `dependency` is used, it somehow evaluates the `destroy` command from the perspective of the included `terragrunt.hcl` file instead of from the perspective of the root `terragrunt.hcl` file.

I tried to use the Terragrunt built-in functions (e.g. `get_terragrunt_dir`, `get_parent_terragrunt_dir`, `get_original_terragrunt_dir`,  `path_relative_to_include`,  `path_relative_from_include`) in the paths specified in the `terraform` and `dependency` blocks but nothing really helped.

This issue is similar to #2330 and #1891 with the difference that I don't specify the `--terragrunt-working-dir` at all as I run the commands directly from the root module.

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

This PR fixes: The `destroy` process checks dependent modules, 
https://github.com/gruntwork-io/terragrunt/blob/e5b394060e8eb5009b99d15195e64688614a768f/cli/cli_app.go#L533
which does not take into account that the configuration can be a parent and contain built-in functions for determining the paths to the child configuration.

Fixes #2508.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)
fix: checking dependent modules in `destroy` command

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -80,7 +80,7 @@ type TerragruntConfig struct {
 	IsPartial bool
 
 	// Map of processed includes
-	ProcessedIncludes map[string]IncludeConfig
+	ProcessedIncludes IncludeConfigs
```
Comment (denis256) [inline config/config.go:83]: I was wondering if should be used a pointer to `IncludeConfigs`

**Review by denis256 — APPROVED** [review]

File: config/config.go (hunk 1 above)
Comment (levkohimins) [reply config/config.go:83]: If you meant:
* `ProcessedIncludes *IncludeConfigs` - _maps_ are reference types, so they are always passed by reference. We don't need a pointer. 
* `type IncludeConfigs map[string]*IncludeConfig` - yes, it will be more correct, but I suggest changing it next time

**Comment by levkohimins** [comment]
Thank you for the review @denis256!
