### PR TITLE
Fix color output on Windows

### LINKED ISSUE #614: No colour output since release 0.17.0 on Windows x64
It seems 0.17.x breaks colour output, and prints the escape sequences instead, at least on Windows x64. This worked as intended on 0.16.x.

**0.16.x:**
terragrunt_0 16 x png

**0.17.x:**
terragrunt_0 17 x

**System:**
- Windows 10 Enterprise build 17134
- Terraform 0.11.7 and 0.11.10
- Terragrunt 0.16.10, 0.16.14, 0.17.0, 0.17.1, 0.17.2

### PR DESCRIPTION
**Pull request by jereksel**
Sources:

https://stackoverflow.com/questions/56460651/golang-fmt-print-033c-and-fmt-print-x1bc-are-not-clearing-screenansi-es
https://github.com/containerd/console/blob/f652dc3/console_windows.go#L46

Fixes #614

### CODE REVIEW

**Comment by brikis98** [comment]
Thanks for the PR! I'm super booked this week, but will try to take a look in the next few days.

File: shell/ptty_windows.go [hunk 1]
```diff
@@ -11,6 +13,25 @@ import (
 	"github.com/gruntwork-io/terragrunt/options"
 )
 
+func PrepareConsole() {
+	enableVirtualTerminalProcessing(os.Stderr)
+	enableVirtualTerminalProcessing(os.Stdout)
+}
+
+func enableVirtualTerminalProcessing(file *os.File) {
+
```
Comment (brikis98) [inline shell/ptty_windows.go:22]: NIT: extra whitespace?

File: shell/ptty_windows.go [hunk 2]
```diff
@@ -11,6 +13,25 @@ import (
...
+	var mode uint32
+	handle := windows.Handle(file.Fd())
+	if err := windows.GetConsoleMode(handle, &mode); err != nil {
+		fmt.Printf("failed to get console mode: %v\n", err)
```
Comment (brikis98) [inline shell/ptty_windows.go:26]: 1. Should we really ignore these errors? Or return them and cause the Terragrunt command to fail? I can't tell if this is something optional or not.
1. If we are going to ignore these errors, we should log them, probably with debug logging (`util.Debugf`), using the logger in `terragrunt.Options`, which can be passed in here as an arg.

File: shell/ptty_windows.go [hunk 3]
```diff
@@ -11,6 +13,25 @@ import (
...
+	}
+
+	if err := windows.SetConsoleMode(handle, mode|windows.ENABLE_VIRTUAL_TERMINAL_PROCESSING); err != nil {
+		fmt.Printf("failed to set console mode: %v\n", err)
```
Comment (brikis98) [inline shell/ptty_windows.go:30]: Same here with error handling

File: shell/ptty_windows.go [hunk 4]
```diff
@@ -11,6 +13,25 @@ import (
 	"github.com/gruntwork-io/terragrunt/options"
 )
 
+func PrepareConsole() {
+	enableVirtualTerminalProcessing(os.Stderr)
+	enableVirtualTerminalProcessing(os.Stdout)
+}
+
+func enableVirtualTerminalProcessing(file *os.File) {
```
Comment (brikis98) [inline shell/ptty_windows.go:21]: Please add a comment explaining what this method does, including those links to StackOverflow / GitHub

File: shell/ptty_windows.go [hunk 5]
```diff
@@ -11,6 +13,25 @@ import (
 	"github.com/gruntwork-io/terragrunt/options"
 )
 
+func PrepareConsole() {
```
Comment (brikis98) [inline shell/ptty_windows.go:16]: Please add a comment explaining what this method does

File: shell/ptty_windows.go (hunk 3 above)
Comment (brikis98) [reply shell/ptty_windows.go:30]: Do we need [this fallback](https://github.com/containerd/console/blob/f652dc3/console_windows.go#L49-L51)?

File: shell/ptty_windows.go [hunk 6]
```diff
@@ -11,6 +13,25 @@ import (
...
+	enableVirtualTerminalProcessing(os.Stderr)
+	enableVirtualTerminalProcessing(os.Stdout)
```
Comment (brikis98) [inline shell/ptty_windows.go:18]: Do we need to do it [for stdin too](https://github.com/containerd/console/blob/f652dc3/console_windows.go#L33-L44)?

**Comment by yorinasub17** [comment]
> so I'm not sure on how to test this.

FYI I had plans to test this on my windows desktop tomorrow or Wednesday.

File: shell/ptty_windows.go (hunk 6 above)
Comment (jereksel) [reply shell/ptty_windows.go:18]: I was thinking about it to be honest and I don't know, because we don't input any escaped characters. But I guess I'll add it for completeness sake.

File: shell/ptty_windows.go (hunk 2 above)
Comment (jereksel) [reply shell/ptty_windows.go:26]: Yeah, we can't just ignore them, because `mode` would not be set - I've added `return` there - I can only test it on my Windows 10 and I'm not sure how it will behave on other Windows versions

File: shell/ptty_windows.go (hunk 1 above)
Comment (jereksel) [reply shell/ptty_windows.go:22]: Removed

File: shell/ptty_windows.go (hunk 3 above)
Comment (jereksel) [reply shell/ptty_windows.go:30]: That's good question - Windows docs does not say what happens to the state when error is returned. Just in case I've added setting console mode to previous value

File: shell/ptty_windows.go (hunk 5 above)
Comment (jereksel) [reply shell/ptty_windows.go:16]: Added

File: shell/ptty_windows.go (hunk 4 above)
Comment (jereksel) [reply shell/ptty_windows.go:21]: Added to `PrepareConsole`

File: shell/ptty_windows.go (hunk 2 above)
Comment (brikis98) [reply shell/ptty_windows.go]: The `return` helps to prevent the code from continuing to run... But should the actual error be returned all the way up the stack, causing Terragrunt to exit? Or are these errors safe to ignore and just mean less pretty terminal output?

File: shell/ptty_windows.go [hunk 7]
```diff
@@ -11,8 +12,31 @@ import (
...
+	var mode uint32
+	handle := windows.Handle(file.Fd())
+	if err := windows.GetConsoleMode(handle, &mode); err != nil {
+		options.Logger.Printf("failed to get console mode: %v\n", err)
+		return
+	}
+
+	if err := windows.SetConsoleMode(handle, mode|windows.ENABLE_VIRTUAL_TERMINAL_PROCESSING); err != nil {
+		options.Logger.Printf("failed to set console mode: %v\n", err)
+		_ = windows.SetConsoleMode(handle, mode)
```
Comment (brikis98) [inline shell/ptty_windows.go:34]: NIT: If we're going to ignore the error, you don't need the `_ = ` portion.

**Comment by brikis98** [comment]
@yorinasub17 Let me know if you've had a chance to try this out.

**Comment by yorinasub17** [comment]
Apologies for the delay here. I have verified that this works on my windows box!

**Comment by brikis98** [comment]
Thanks Yori! @jereksel Could you resolve the last remaining (very minor) comment? After that, I can kick off tests.

File: shell/ptty_windows.go (hunk 7 above)
Comment (jereksel) [reply shell/ptty_windows.go:34]: Sorry about that - GoLand without it was warning me that error is ignored

Comment (brikis98) [reply shell/ptty_windows.go:34]: But you're still ignoring the error, so how is this better? Either don't use it at all or at least log it...

**Comment by jereksel** [comment]
Sorry that it took so long

**Comment by brikis98** [comment]
Thanks! Kicking off tests now.

**Comment by brikis98** [comment]
Hm, looks like a compile error?

```
# github.com/gruntwork-io/terragrunt/shell
shell/run_shell_cmd.go:98:31: not enough arguments in call to runCommandWithPTTY
	have (*exec.Cmd, io.Writer, io.Writer)
	want (*options.TerragruntOptions, *exec.Cmd, io.Writer, io.Writer)
# github.com/gruntwork-io/terragrunt/shell [github.com/gruntwork-io/terragrunt/shell.test]
shell/run_shell_cmd.go:98:31: not enough arguments in call to runCommandWithPTTY
	have (*exec.Cmd, io.Writer, io.Writer)
	want (*options.TerragruntOptions, *exec.Cmd, io.Writer, io.Writer)
FAIL	github.com/gruntwork-io/terragrunt/cli [build failed]
FAIL	github.com/gruntwork-io/terragrunt/config [build failed]
FAIL	github.com/gruntwork-io/terragrunt/configstack [build failed]
```

**Comment by jereksel** [comment]
Should be fine now

**Comment by brikis98** [comment]
Re-running...

**Comment by brikis98** [comment]
Tests passed! Merging now, thanks!

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.27
