### PR TITLE
fix config remote state s3 and update if needs

### LINKED ISSUE #1106: Versioning is not enabled
Here's my remote config.
`remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
    bucket         = "naimishshah-dev-terraform-c13f60a4-e2a6-4c1b-9647-db3a47932b60"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-west-2"
    encrypt        = true
    dynamodb_table = "my-lock-table-c13f60a4-e2a6-4c1b-9647-db3a47932b60"
    profile        = "personal-services-dev"
  }
}`

Here is the output from Terragrunt/Terraform.

[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 Waiting for bucket naimishshah-dev-terraform-c13f60a4-e2a6-4c1b-9647-db3a47932b60 to be created
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 S3 bucket naimishshah-dev-terraform-c13f60a4-e2a6-4c1b-9647-db3a47932b60 created.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 WARNING: Versioning is not enabled for the remote state S3 bucket naimishshah-dev-terraform-c13f60a4-e2a6-4c1b-9647-db3a47932b60. We recommend enabling versioning so that you can roll back to previous versions of your Terraform state in case of error.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 Lock table my-lock-table-c13f60a4-e2a6-4c1b-9647-db3a47932b60 does not exist in DynamoDB. Will need to create it just this first time.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 Creating table my-lock-table-c13f60a4-e2a6-4c1b-9647-db3a47932b60 in DynamoDB
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 Table my-lock-table-c13f60a4-e2a6-4c1b-9647-db3a47932b60 is not yet in active state. Will check again after 10s.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:40 Success! Table my-lock-table-c13f60a4-e2a6-4c1b-9647-db3a47932b60 is now in active state.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:40 No tags for lock table given.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:40 Running command: terraform init

### LINKED ISSUE #1143: Terragrunt creates an s3 bucket with invalid KMS settings
When running `terragrunt plan` for the first time and accepting the the prompt to create an S3 bucket for the backend. The bucket is configured with a custom KMS key even though a `kms_key_id` is not specified.

```
$ terragrunt -v
terragrunt version v0.23.10
```

When you `terragrunt apply`, Terraform will create the resource but is not able to save the state file on s3

```
Failed to save state: failed to upload state: KMS.NotFoundException: Invalid keyId aws/s3
```

To fix this you have to manually edit the KMS properties for the bucket and either:

1.  Enter a valid custom KMS ARN, or
2. Change the dropdown from "Custom KMS ARN" to "aws/s3"

My main terragrunt.hcl has the following:

```
remote_state {
  backend = "s3"

  generate = {
    path = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    region = "us-east-1"
    bucket = "some.bucket.somewhere"
    key    = "bob.tfstate"
  }
}
```

This screenshot shows what the bucket properties look like immediately after Terragrunt has created the bucket 
image

### LINKED ISSUE #1770: Unable to set terragrunt remote bucket encryption, access logging, etc.
Hello
A little background.
I have several AWS accounts under TG and TF control, some work started in the middle of 2019. Last account created in July 2021. 

terragrunt version v0.31.4

Here is my remote state conf:
```terraform
remote_state {
  backend = "s3"

  config = {
    bucket = "fn-terragrunt-state-${get_env("TF_VAR_region", "")}-${get_aws_account_id()}"
    accesslogging_bucket_name = "fn-terragrunt-state-${get_env("TF_VAR_region", "")}-${get_aws_account_id()}"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "${get_env("TF_VAR_region", "")}"
    encrypt        = true
    dynamodb_table = "terragrunt-locks"
    enable_lock_table_ssencryption = true
  }
}

```
Now, on the most recent bucket missing is:
- access logging

On a bucket from 2019 missing is
- default encryption
- public access blocking
- bucket policy (enforce SSL only)

If I try to create new bucket for the state (change location in config) the bucket is created as expected, with all of the settings in place. 
When I run apply, init, etc, nothing changes on existing buckets. The only thing I was able to enforce was lock table encryption.

Expected behavior:
When running apply or init existing remote state bucket settings should be updated with the defined configuration that is:
- access logging
- default encryption
- public access blocking
- bucket policy (enforce SSL only)

My question is: is this a bug or expected behavior? If expected behavior, how can I enforce updating old buckets with new, proper settings?

Thank you!

### PR DESCRIPTION
**Pull request by leonardobiffi**
Hi, this PR is a suggestion to resolve the KMS config when the bucket is created, as the default key KMS ID is not being informed, the bucket has encryption enabled but without the KMS:

image

I am also suggesting an important change so that buckets that do not comply with the default encryption settings, public access blocking, bucket policy (enforce SSL only), access logging, versioning enabled are updated according to what is defined in the block of config. The `disable_bucket_update` attribute disable this behavior for anyone managing the bucket outside of terragrunt. This change causes the buckets to be updated when running terragrunt to conform to the config that are already made when the bucket is created.

Another fix is for the bucket policy, where currently only EnforcedTLS is being defined, the first policy configured for RootAccess is overwritten.
What I changed is to check the policy already configured and be attached to the existing one, as shown in the image below

image

Closes #1770 
Closes #1143 
Closes #1106

### CODE REVIEW

File: remote/remote_state_s3.go [hunk 1]
```diff
@@ -381,20 +390,205 @@ func createS3BucketIfNecessary(s3Client *s3.S3, config *ExtendedRemoteStateConfi
...
+		return nil
+	}
+
+	prompt := fmt.Sprintf("Remote state S3 bucket %s is out of date. Would you like Terragrunt to update it?", config.remoteStateConfigS3.Bucket)
+	shouldUpdateBucket, err := shell.PromptUserForYesNo(prompt, terragruntOptions)
+	if err != nil {
+		return err
+	}
+
+	if shouldUpdateBucket {
```
Comment (denis256) [inline remote/remote_state_s3.go:414]: Make sense to return if `shouldUpdateBucket` is false? it will reduce number of nested blocks

```
if !shouldUpdateBucket {
  return nil
}
```

File: remote/remote_state_s3_test.go [hunk 2]
```diff
@@ -276,6 +276,7 @@ func TestGetTerraformInitArgs(t *testing.T) {
 				"skip_bucket_ssencryption":       false,
 				"skip_bucket_root_access":        false,
 				"skip_bucket_enforced_tls":       false,
+				"disable_bucket_update":          false,
```
Comment (denis256) [inline remote/remote_state_s3_test.go:279]: I think will be good to have a test for case `disable_bucket_update=true`

File: remote/remote_state_s3.go [hunk 3]
```diff
@@ -663,6 +944,39 @@ func EnableEnforcedTLSAccesstoS3Bucket(s3Client *s3.S3, config *ExtendedRemoteSt
...
+// Helper function to check if the enforced TLS policy is enabled for the bucket
+func checkIfBucketEnforcedTLS(s3Client *s3.S3, config *RemoteStateConfigS3, terragruntOptions *options.TerragruntOptions) (bool, error) {
+	terragruntOptions.Logger.Debugf("Checking if bucket %s is enforced with TLS", config.Bucket)
+
+	policyOutput, err := s3Client.GetBucketPolicy(&s3.GetBucketPolicyInput{
+		Bucket: aws.String(config.Bucket),
+	})
+	if err != nil {
+		terragruntOptions.Logger.Debugf("Could not get policy for bucket %s", config.Bucket)
+		return false, nil
```
Comment (denis256) [inline remote/remote_state_s3.go:956]: `err` is not returned, it is by intention?

File: remote/remote_state_s3_test.go (hunk 2 above)
Comment (leonardobiffi) [reply remote/remote_state_s3_test.go]: changed

File: remote/remote_state_s3.go (hunk 3 above)
Comment (leonardobiffi) [reply remote/remote_state_s3.go]: Yes, but I improved this error check to return no err when bucket dont have policy

File: remote/remote_state_s3.go (hunk 1 above)
Comment (leonardobiffi) [reply remote/remote_state_s3.go]: changed

**Comment by denis256** [comment]
Noticed that integration tests failed, each run different tests, I was wondering merge from master(to include https://github.com/gruntwork-io/terragrunt/pull/2073) will help tests to pass

https://app.circleci.com/pipelines/github/gruntwork-io/terragrunt?branch=pull-request-2063&filter=all

**Comment by denis256** [comment]
Noticed that integration tests failed, each run different tests, I was wondering merge from master(to include https://github.com/gruntwork-io/terragrunt/pull/2073) will help tests to pass

https://app.circleci.com/pipelines/github/gruntwork-io/terragrunt?branch=pull-request-2063&filter=all

**Comment by leonardobiffi** [comment]
@denis256 Hi, 
Did this change in the integration test work?
Do I need to change something in PR?

**Comment by denis256** [comment]
@leonardobiffi try to merge the last changes from master and we will see if it will help to pass more integration tests

**Comment by denis256** [comment]
Build passed :+1:

**Review by denis256 — APPROVED** [review]

**Comment by leonardobiffi** [comment]
@denis256 when this PR will be release?

**Comment by denis256** [comment]
Hi, I think this week, I was doing more tests to see if will appear any issue when switching from older versions

**Comment by leonardobiffi** [comment]
@denis256 awesome, let me known if anything is wrong

File: remote/remote_state_s3.go [hunk 4]
```diff
@@ -381,20 +390,207 @@ func createS3BucketIfNecessary(s3Client *s3.S3, config *ExtendedRemoteStateConfi
...
+}
+
+type S3BucketConfig struct {
+	Versioning    string
+	SSEEncryption string
+	RootAccess    string
+	EnforcedTLS   string
+	AccessLogging string
+	PublicAccess  string
+}
```
Comment (yorinasub17) [inline remote/remote_state_s3.go:491]: It looks like value of the string is immaterial in `configBucket`, and is only used to track if these attributes need updating. Is that true?

If so, these should be `bool` instead of `string` and the struct should be renamed to something like `S3BucketUpdatesRequired`.

**Review by yorinasub17 — COMMENTED** [review]
This LGTM as well! Thanks for the contribution! I had one small request, but once that's addressed, we can move forward with this.

cc @denis256

File: remote/remote_state_s3.go (hunk 4 above)
Comment (leonardobiffi) [reply remote/remote_state_s3.go]: @yorinasub17 Hi, it does make sense. I made the suggested adjustment and the necessary corrections. Let me know if I'm missing something

**Review by yorinasub17 — APPROVED** [review]
Updates LGTM! I'll kick off a regression build and if it passes, we can merge this in!

**Comment by denis256** [comment]
Noticed that still fail test `TestTerragruntStackCommands`, 3 runs - 3 failures:

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

text = "[I am a mgmt vpc template. I have no dependencies.]"
=== CONT  TestTerragruntStackCommands
    integration_test.go:3716: Failed to run Terragrunt command 'terragrunt apply-all --terragrunt-non-interactive --terragrunt-working-dir /tmp/terragrunt-test076015731/fixture-stack/mgmt' due to error: 2 errors occurred:
        	* Cannot process module Module /tmp/terragrunt-test076015731/fixture-stack/mgmt/bastion-host (excluded: false, assume applied: false, dependencies: [/tmp/terragrunt-test076015731/fixture-stack/mgmt/vpc, /tmp/terragrunt-test076015731/fixture-stack/mgmt/kms-master-key]) because one of its dependencies, Module /tmp/terragrunt-test076015731/fixture-stack/mgmt/kms-master-key (excluded: false, assume applied: false, dependencies: []), finished with an error: NoSuchPublicAccessBlockConfiguration: The public access block configuration was not found
        	status code: 404, request id: 0QH1FH92JDDZNA0B, host id: +mMt9VWzhriq9ozRqh2/W0ko1XcwmIZy97r3j1tpTgDN/yjcU32ru4Tsm9W+vrhjYKsLaNgwFHA=
        	* NoSuchPublicAccessBlockConfiguration: The public access block configuration was not found
        	status code: 404, request id: 0QH1FH92JDDZNA0B, host id: +mMt9VWzhriq9ozRqh2/W0ko1XcwmIZy97r3j1tpTgDN/yjcU32ru4Tsm9W+vrhjYKsLaNgwFHA=
        
        
        
        Stdout: (see log output above)
        
        Stderr: (see log output above)

```

**Comment by leonardobiffi** [comment]
@denis256 awesome, let me known if anything is wrong

> Noticed that still fail test `TestTerragruntStackCommands`, 3 runs - 3 failures:
> 
> ```
> Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
> 
> Outputs:
> 
> text = "[I am a mgmt vpc template. I have no dependencies.]"
> === CONT  TestTerragruntStackCommands
>     integration_test.go:3716: Failed to run Terragrunt command 'terragrunt apply-all --terragrunt-non-interactive --terragrunt-working-dir /tmp/terragrunt-test076015731/fixture-stack/mgmt' due to error: 2 errors occurred:
>         	* Cannot process module Module /tmp/terragrunt-test076015731/fixture-stack/mgmt/bastion-host (excluded: false, assume applied: false, dependencies: [/tmp/terragrunt-test076015731/fixture-stack/mgmt/vpc, /tmp/terragrunt-test076015731/fixture-stack/mgmt/kms-master-key]) because one of its dependencies, Module /tmp/terragrunt-test076015731/fixture-stack/mgmt/kms-master-key (excluded: false, assume applied: false, dependencies: []), finished with an error: NoSuchPublicAccessBlockConfiguration: The public access block configuration was not found
>         	status code: 404, request id: 0QH1FH92JDDZNA0B, host id: +mMt9VWzhriq9ozRqh2/W0ko1XcwmIZy97r3j1tpTgDN/yjcU32ru4Tsm9W+vrhjYKsLaNgwFHA=
>         	* NoSuchPublicAccessBlockConfiguration: The public access block configuration was not found
>         	status code: 404, request id: 0QH1FH92JDDZNA0B, host id: +mMt9VWzhriq9ozRqh2/W0ko1XcwmIZy97r3j1tpTgDN/yjcU32ru4Tsm9W+vrhjYKsLaNgwFHA=
>         
>         
>         
>         Stdout: (see log output above)
>         
>         Stderr: (see log output above)
> ```
> 
> Can be a concurrency issue? when multiple tests try to change S3 configuration?

@denis256 Hi, i fixed this error and the test passed. Can you validate?

See here this error message: https://github.com/aws/aws-sdk-go/blob/main/service/s3control/errors.go#L50

**Comment by denis256** [comment]
I see the build started to pass, I'm still somehow suspect since the last change is to shallow NoSuchPublicAccessBlockConfiguration error, and before last change individual run of `TestTerragruntStackCommands` passed but it failed when the entire `integration_test.go` was executed

**Comment by leonardobiffi** [comment]
@denis256 Hi,
The `integration_test.go` still failing because of update in s3?
I couldn`t see circleCI pipeline

**Comment by leonardobiffi** [comment]
@denis256 
Looking at this aws doc, I understood that this error happens for accounts that don't have the option to configure S3 PublicAccess at the account level

https://docs.aws.amazon.com/sdk-for-go/api/service/s3control/#S3Control.GetPublicAccessBlock
https://docs.aws.amazon.com/AmazonS3/latest/userguide/configuring-block-public-access-account.html

What do you think?

**Comment by denis256** [comment]
Hello,
error make sense to handle for buckets without PublicAccess configured, 
but it doesn't explain why individual execution of `TestTerragruntStackCommands` pass successfully, but run of entire integration tests fails on `TestTerragruntStackCommands` (all this before commit with handling of error)

**Review by denis256 — APPROVED** [review]

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.37.0
