### PR TITLE
Fixed searching for configs with non-default names #2704.

### LINKED ISSUE #2031: Terragrunt "run-all plan" do not respects TERRAGRUNT_CONFIG env variable
Hi, I've set `TERRAGRUNT_CONFIG=.terragrunt.hcl`. 
So my root and leaf folders have this .terragrunt.hcl file.
Everything works well when I'm trying to run terragrunt from child folder, but I get "Could not find any subfolders with Terragrunt configuration files" error when trying to run from `terragrunt run-all plan` from root. Renaming .terragrunt.hcl -> terragrunt.hcl fixes the issue, but I would prefer to use "dot" prefix if possible.

It seems like [this line](https://github.com/gruntwork-io/terragrunt/blob/f6b5661906b71dfe2f261a029ae3809f233d06a7/config/config.go#L582) is using default config name and not the parsed argument.

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

* Fixed searching for config with explicitly specified `--terragrunt-config` and `run-all` command.
* Added the ability to explicitly specify the name of dependency configuration files, which may differ from the default name `terragrunt.conf`.

Fixes #2031 .

### CODE REVIEW

File: config/dependency.go [hunk 1]
```diff
@@ -177,20 +177,27 @@ func decodeAndRetrieveOutputs(
...
 	paths := []string{}
 	for _, decodedDependencyBlock := range decodedDependencyBlocks {
 		configPath := decodedDependencyBlock.ConfigPath
-		if util.IsFile(configPath) && filepath.Base(configPath) == DefaultTerragruntConfigPath {
-			// dependencies system expects the directory containing the terragrunt.hcl file
-			configPath = filepath.Dir(configPath)
-		}
+
+		// absolutePath := configPath
+		// if !filepath.IsAbs(absolutePath) {
```
Comment (denis256) [inline config/dependency.go:190]: This part is required?

Comment (levkohimins) [reply config/dependency.go]: Oh, forgot to delete this code. Thanks. Fixed.

**Review by denis256 — APPROVED** [review]

**Comment by levkohimins** [comment]
@denis256, thanks for the review!

**Comment by levkohimins** [comment]
Resolved in [v0.50.15](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.15) release.
