### PR TITLE
#2450 Improved loading of TFLint configuration

### LINKED ISSUE #2450: Built-in tflint hook doesn't find .tflint.hcl if it's in the current directory
Minimal example:

```bash
mkdir -p demo
cd demo
touch main.tf
cat > .tflint.hcl <<-END
  config { format = "compact" }
END
cat > terragrunt.hcl <<-END
  terraform {
    before_hook "lint" {
      commands = ["validate"]
      execute  = ["tflint"]
    }
  }
END
terragrunt validate
```

This script fails on the last line with the error "Could not find .tflint.hcl config file in the parent folders: Traversed all the day to the root". Running `tflint` directly works as expected (it reads the config file in the current directory and prints a warning in compact format).

terragrunt version v0.43.2

### PR DESCRIPTION
**Pull request by denis256**
## Description

Found that `findTflintConfigInProject()` function is not checking current directory for `tflint` configurations.
Tssue wasn't detected before since in tests were used `terraform` blocks with `source` field which during execution leads to copying of working directory to a temporary location from which `tflint` configuration lookup works by finding parent config file.

Included changes:
* added test case for failing case, with `terraform` block without `source` field
* updated `findTflintConfigInProject` to check current directory for tflint configuration and then lookup parent directories
* added tflint test for Windows CI

Fixes #2450.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Fixed bug in tflint configuration loading.

### Migration Guide

N/A

### CODE REVIEW

File: test/integration_windows_test.go [hunk 1]
```diff
@@ -64,3 +68,17 @@ func TestWindowsTerragruntSourceMapDebug(t *testing.T) {
 		})
 	}
 }
+
+func TestWindowsTflintIsInvoked(t *testing.T) {
```
Comment (marinalimeira) [inline test/integration_windows_test.go:72]: Very nice

**Review by marinalimeira — APPROVED** [review]
LGTM! That's a nice improvement!! 🎉
