### PR TITLE
fix: Fixing null input passing

### LINKED ISSUE #5452: Input variable set to null fails to pass to Terraform as of v0.99.0
## Describe the bug

Passing a `null` value via Terragrunt `inputs` results in "Error: No value for required variable".
This behavior is a regression introduced in version 0.99.0. Version 0.98.0 handles `null` inputs correctly.

## Steps To Reproduce

1. Define a Terraform variable without a default:
```tf
variable "test" {
  type = string
}
```
2. Pass null in `terragrunt.hcl`:
```hcl
inputs = {
  test = null
}
```
3. Run `terragrunt plan` with terragrunt 0.99.0. -> Error
4. Run `terragrunt plan` with terragrunt 0.98.0. -> No error

## Expected behavior

Terragrunt should pass the null value to Terraform, satisfying the variable requirement without triggering a "not set" error.

## Must haves

- [x] Steps for reproduction provided.

## Versions

- Terragrunt version: 0.99
- OpenTofu/Terraform version: 1.14.4
- Environment details: RHEL 8.10

Image

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #5452.

The PR #5396 accidentally removed too much code as it was inter-mingled with null handling that we actually do need.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **New Features**
  * Terragrunt now supports passing null values to Terraform variables. When null-valued inputs are configured, they are correctly handled and forwarded to Terraform during execution.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: internal/runner/run/run.go [hunk 1]
```diff
@@ -256,6 +258,20 @@ func runTerragruntWithConfig(
...
 
+	// Write null-valued inputs to a tfvars.json file that OpenTofu/Terraform will auto-load.
+	nullVarsFile, err := setTerragruntNullValuesRunCfg(opts, cfg)
+	if err != nil {
+		return err
+	}
+
+	defer func() {
+		if nullVarsFile != "" {
+			if err := os.Remove(nullVarsFile); err != nil && !errors.Is(err, os.ErrNotExist) {
```
Comment (denis256) [inline internal/runner/run/run.go:269]: `err` declaration shadows global declaration

```
if removeErr := os.Remove(nullVarsFile); removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) {
```

File: test/integration_test.go [hunk 2]
```diff
@@ -4718,3 +4718,31 @@ func TestNoColorDependency(t *testing.T) {
...
+	t.Parallel()
+
+	tmpEnvPath := helpers.CopyEnvironment(t, testFixtureNullValue)
+	testPath := filepath.Join(tmpEnvPath, testFixtureNullValue)
+
+	_, _, err := helpers.RunTerragruntCommandWithOutput(
+		t,
+		"terragrunt apply -auto-approve --non-interactive --working-dir "+testPath,
+	)
+	require.NoError(t, err)
```
Comment (denis256) [inline test/integration_test.go:4735]: I think we may need to verify if `.terragrunt-null-vars.auto.tfvars.json` is removed
