### PR TITLE
fix: Ensure queue entries are still marked as ready if they have dependencies/dependents that are excluded

### LINKED ISSUE #5192: --queue-strict-include and --filter don't run units when dependencies are excluded from queue (regression since v0.89.0)
## Describe the bug

Since Terragrunt v0.89.0 (which introduced Runner Pool), using `--queue-strict-include` with `--queue-include-dir` or the experimental `--filter` flag no longer runs the filtered units when their dependencies are not included in the queue.

The Runner Pool shows `found 0 readyEntries tasks` and exits without running anything, even though the filtered units are correctly identified and marked as `excluded: false`.

This worked correctly in v0.88.x with the group-based execution model, where dependencies only needed to be *already applied* (have existing state), not *in the queue*.

## Steps To Reproduce

Given a stack structure:
```
live/prod/region/app/
├── identity/
│   └── terragrunt.hcl
├── network/
│   └── terragrunt.hcl  (depends on identity)
└── instance/
    └── terragrunt.hcl  (depends on network)
```

Where `network` depends on `identity` and `instance` depends on `network`, and all units have been previously applied (state exists):

**With --queue-strict-include:**
```bash
cd live/prod/region/app
terragrunt plan --all --queue-include-dir '**/network' --queue-strict-include
```

**With experimental --filter:**
```bash
TG_EXPERIMENT_MODE='true' terragrunt plan --all --filter 'source=**/network'
```

**Debug output shows:**
```
Stack at live/prod/region/app:
  => Unit ./network (excluded: false, assume applied: false, dependencies: [./identity])
Runner Pool Controller: starting with 1 tasks, concurrency 2147483647
Runner Pool Controller: found 0 readyEntries tasks
```

The unit is queued but never runs because its dependency (`identity`) is not in the queue.

## Expected behavior

When using `--queue-strict-include` or `--filter`, filtered units should run if their dependencies:
1. Have existing Terraform state (already applied), OR
2. Are explicitly included in the queue

The v0.88.x behavior allowed running a subset of units as long as their dependencies had valid state. This is essential for:
- Targeted deployments during migrations
- Running plans on specific module types across environments
- Iterative development without processing the entire DAG

## Workaround

Using `--queue-ignore-dag-order` allows the filtered units to run:
```bash
TG_EXPERIMENT_MODE='true' terragrunt plan --all --filter 'source=**/network' --queue-ignore-dag-order
```

However, this disables **all** DAG ordering, which is undesirable when filtering multiple units that have dependencies on each other.

## Versions

- Terragrunt version: 0.94.0 (broken since 0.89.0)
- Terragrunt version that worked: 0.88.x
- OpenTofu version: 1.10.8
- Environment: Ubuntu Linux

## Additional context

The v0.89.0 release notes state:
> "Runner Pool executes each unit as soon as its dependencies are resolved"

This appears to be the root cause - the Runner Pool requires dependencies to be *resolved in the current run*, rather than checking if they have existing state.

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #5192.

Ensures that queue entries are still marked as ready if they have dependencies/dependents that are not in the queue as a consequence of being excluded.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### Migration Guide

---

> [!NOTE]
> Make queue treat dependencies not present in the queue (e.g., due to `--queue-strict-include`/`--filter`) as ready by assuming existing state or `AssumeAlreadyApplied`, wiring a `unitsMap` from the runner and adding integration tests/fixtures.
> 
> - **Queue**
>   - Add `unitsMap` field and `SetUnitsMap` to reference all discovered `*component.Unit` by path.
>   - Update `areDependenciesReadyUnsafe`: if a dependency isn’t in the queue, consider it ready when `AssumeAlreadyApplied` or assume existing state; no longer blocks on absent deps. Honors `IgnoreDependencyErrors` as before.
> - **Runner**
>   - Build a `unitsMap` from resolved units and set it on the queue to enable dependency readiness checks for excluded/not-queued units (e.g., `--queue-strict-include`, `--filter`).
> - **Tests & Fixtures**
>   - Add `test/fixtures/queue-strict-include/*` with a transitive dep chain.
>   - Add `TestQueueStrictIncludeWithDependencyNotInQueue` covering plan/destroy with `--queue-strict-include`/`--queue-include-dir` and experimental `--filter`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit c8d1ccd7fb94cf6393d79e83c411e277ff51db13. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

## Summary by CodeRabbit

* **New Features**
  * Enhanced dependency resolution to properly handle filtered queue configurations, enabling strict include/filter options to work correctly with dependent modules.

* **Tests**
  * Added integration tests validating dependency handling behavior with strict include filtering and transitive dependency chains.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: internal/queue/queue.go [hunk 1]
```diff
@@ -332,12 +338,24 @@ func (q *Queue) GetReadyWithDependencies() []*Entry {
...
 func (q *Queue) areDependenciesReadyUnsafe(e *Entry) bool {
 	for _, dep := range e.Component.Dependencies() {
 		depEntry := q.entryByPathUnsafe(dep.Path())
 		if depEntry == nil {
-			return false
+			// Dependency not in queue - check if assumed already applied
+			if q.unitsMap != nil {
+				if unit, ok := q.unitsMap[dep.Path()]; ok {
+					if unit.Execution != nil && unit.Execution.AssumeAlreadyApplied {
+						// Dependency is assumed already applied, consider it ready
```
Comment (denis256) [inline internal/queue/queue.go:351]: Should we add a debug log that the dependency was assumed to be already applied? it may be helpful during debug
