### PR TITLE
fix: Fixing provider cache lock file corruption

### LINKED ISSUE #5616: `--provider-cache` usage corrupts pre-existing `.terraform.lock.hcl`
## Describe the bug

I just stumbled upon the [provider cache server](https://terragrunt.gruntwork.io/docs/features/provider-cache-server) feature which sounded like a solution to the problem I'm trying to solve. Unfortunately, initial assessment revealed a serious issue - its implementation assumes that a **Terraform-generated** `.terraform.lock.hcl` file can be modified by Terragrunt.

Terragrunt not only updates its content, but also corrupts it (see below for details).

In my case, `.terraform.lock.hcl` files are versioned in Git and updated when there's a good reason to do so (e.g. new module was added to the codebase). The vast majority of day-to-day operations must NOT modify its content (unless it's someone's clear intention), so the file stays unchanged in order to guarantee reproducible builds.

## Steps To Reproduce

Here's a back-of-a-napkin script to reproduce the problem in a clean/isolated environment: 

```bash
#!/usr/bin/env bash

set -euo pipefail

# Init a Git repo
cd "$(mktemp -d -t terragrunt-provider-cache-server-XXXXXX)"
git init

# Exclude Terragrunt's auto-generated files from version control
cat >.gitignore <<'GITIGNORE'
.terraform
.terraformrc
GITIGNORE

# Generate a minimal Terraform module
cat >main.tf <<'MAINTF'
terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.0, < 7.0"
    }
  }
}

module "bucket" {
  source  = "cloudposse/s3-bucket/aws"
  version = "4.10.0"
}
MAINTF

# Add terragrunt.hcl (required for Terragrunt to recognise this directory)
touch terragrunt.hcl

# Generate the lock file with Terraform
terraform init -backend=false

# Remove the local provider installation to simulate a clean CI checkout
rm -rf .terraform

# Commit the clean lock file so we can diff it after the Terragrunt run
git add -A
git -c user.email="user@example.com" -c user.name="User" -c commit.gpgsign=false commit -m "Initial commit"

# Run Terragrunt with the provider cache server enabled (the failure is expected here)
TG_PROVIDER_CACHE=1 TG_LOG_LEVEL=debug terragrunt run -- init -backend=false || true

# Show what Terragrunt wrote to the lock file
echo "--- lock file diff ---"
git diff .terraform.lock.hcl

# Prove the corruption: a plain `terraform init` now fails
terraform init -backend=false
```

## Expected behavior

Terragrunt must not modify pre-existing `.terraform.lock.hcl` files - it's harmful and there's no reason to do so.

If the `.terraform.lock.hcl` file already exists - leave it as-is, do **NOT** attempt to patch it (that's Terraform's responsibility). If the file is missing - just run `terraform init` to get it generated (and again - do **NOT** attempt to update it).

## Must haves

- [x] Steps for reproduction provided.

## Nice to haves

The script attached above yields the following:

```console
Initialized empty Git repository in /private/var/folders/12/_7vry_l93t1d051k3_171n_00000gn/T/terragrunt-provider-cache-server-THJJiS/.git/
Initializing modules...
Downloading registry.terraform.io/cloudposse/s3-bucket/aws 4.10.0 for bucket...
- bucket in .terraform/modules/bucket
Downloading registry.terraform.io/cloudposse/iam-s3-user/aws 1.2.0 for bucket.s3_user...
...
Terraform has been successfully initialized!
...
[main (root-commit) 85a08f3] Initial commit
 4 files changed, 62 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 .terraform.lock.hcl
 create mode 100644 main.tf
 create mode 100644 terragrunt.hcl
17:16:37.073 DEBUG  Terragrunt Version: 0.99.4
17:16:37.073 DEBUG  using cache key for version files: r01AJjVD7VSXCQk1ORuh_no_NRY
17:16:37.073 DEBUG  Running command: terraform -version
17:16:37.073 DEBUG  Engine is not enabled, running command directly in .
17:16:37.095 DEBUG  terraform version: 1.14.5
...
17:16:43.848 DEBUG  Total provider caches: 2
17:16:43.848 DEBUG  Cache 0: registry.terraform.io/hashicorp/aws v6.33.0, requestIDs: [36e29d70-fc5e-4a6a-9cf8-c16a497cf432], ready: true, err: <nil>
17:16:43.848 DEBUG  Cache 1: registry.terraform.io/hashicorp/time v0.13.1, requestIDs: [36e29d70-fc5e-4a6a-9cf8-c16a497cf432], ready: true, err: <nil>
17:16:43.848 DEBUG  Provider registry.terraform.io/hashicorp/aws v6.33.0 is ready
17:16:43.848 DEBUG  Provider registry.terraform.io/hashicorp/time v0.13.1 is ready
17:16:43.848 DEBUG  Returning 2 ready providers for requestID: 36e29d70-fc5e-4a6a-9cf8-c16a497cf432
17:16:43.849 DEBUG  Applied constraint >= 3.0, < 7.0 to provider registry.terraform.io/hashicorp/aws
17:16:43.849 DEBUG  No constraint found for provider registry.terraform.io/hashicorp/time
17:16:44.334 DEBUG  Running command: terraform init -backend=false
17:16:44.334 DEBUG  Engine is not enabled, running command directly in .
17:16:44.358 STDOUT terraform: Initializing modules...
17:16:44.379 STDERR terraform: ╷
17:16:44.379 STDERR terraform: │ Error: Invalid provider version constraints
17:16:44.379 STDERR terraform: │
17:16:44.379 STDERR terraform: │   on .terraform.lock.hcl line 6:
17:16:44.379 STDERR terraform: │   (source code not available)
17:16:44.379 STDERR terraform: │
17:16:44.379 STDERR terraform: │ The recorded version constraints for provider
17:16:44.379 STDERR terraform: │ registry.terraform.io/hashicorp/aws must be written in normalized form: ">=
17:16:44.379 STDERR terraform: │ 3.0.0, < 7.0.0".
17:16:44.379 STDERR terraform: ╵
17:16:44.381 DEBUG  Copying lock file from ./.terraform.lock.hcl to .
17:16:44.381 DEBUG  Attempting error recovery for error: error occurred: Failed to execute "terraform init backend false" in ../../../ 7vry l93t1d051k3 171n 00000gn/T/terragrunt provider cache server THJJiS Error: Invalid provider version constraints on .terraform.lock.hcl line 6: (source code not available) The recorded version constraints for provider registry.terraform.io/hashicorp/aws must be written in normalized form: " 3.0.0 7.0.0". exit status 1
17:16:44.381 DEBUG  Provider cache service shutting down...
17:16:44.381 DEBUG  Provider cache service shutdown complete
17:16:44.381 INFO   Shutting down Terragrunt Cache server...
17:16:44.381 INFO   Terragrunt Cache server stopped
17:16:44.381 ERROR  error occurred:

* Failed to execute "terraform init -backend=false" in .
  ╷
  │ Error: Invalid provider version constraints
  │
  │   on .terraform.lock.hcl line 6:
  │   (source code not available)
  │
  │ The recorded version constraints for provider
  │ registry.terraform.io/hashicorp/aws must be written in normalized form: ">=
  │ 3.0.0, < 7.0.0".
  ╵

  exit status 1

--- lock file diff ---
diff --git a/.terraform.lock.hcl b/.terraform.lock.hcl
index 6d013fc..bc34238 100644
--- a/.terraform.lock.hcl
+++ b/.terraform.lock.hcl
@@ -3,7 +3,7 @@

 provider "registry.terraform.io/hashicorp/aws" {
   version     = "6.33.0"
-  constraints = ">= 2.0.0, >= 3.0.0, >= 4.9.0, < 7.0.0"
+  constraints = ">= 3.0, < 7.0"
   hashes = [
     "h1:wNrviem6bg9fq1bYvtGqH9QWO6iWbM1bBRLSqFJWqWM=",
     "zh:207f3f9db05c11429a241b84deeecfbd4caa941792c2c49b09c8c85cd59474dd",
Initializing modules...
╷
│ Error: Invalid provider version constraints
│
│   on .terraform.lock.hcl line 6:
│   (source code not available)
│
│ The recorded version constraints for provider registry.terraform.io/hashicorp/aws must be written in normalized form: ">= 3.0.0, < 7.0.0".
```

## Versions

- Terragrunt version: v0.99.4
- OpenTofu/Terraform version: v1.14.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): macOS Tahoe 26.3

## Additional context

The current provider cache implementation contains at least two compounding bugs:

- [`normalizeVersionConstraint`](https://github.com/gruntwork-io/terragrunt/blob/0241ffb3b803f2a861e47904d466f2968c35ec06/internal/tf/getproviders/constraints.go#L223) (introduced in #4563) only handles single-operator constraints (2 tokens). A multi-part constraint like `>= 3.0, < 7.0` splits into 4 tokens, falls through all branches, and is returned **unchanged** - missing the patch-version suffix that Terraform's lock file parser requires (`>= 3.0.0, < 7.0.0`)
- [`updateProviderBlock`](https://github.com/gruntwork-io/terragrunt/blob/0241ffb3b803f2a861e47904d466f2968c35ec06/internal/tf/getproviders/lock.go#L114) performs a **raw string comparison** between the constraint in the existing lock file and the constraint extracted from `required_providers`. These two values cannot be directly compared: the lock file records Terraform's aggregated constraint across the entire module dependency tree (e.g. `>= 2.0.0, >= 3.0.0, >= 4.9.0, < 7.0.0`), whereas [`ParseProviderConstraints`](https://github.com/gruntwork-io/terragrunt/blob/0241ffb3b803f2a861e47904d466f2968c35ec06/internal/tf/getproviders/constraints.go#L23) (called from [`warmUpCache`](https://github.com/gruntwork-io/terragrunt/blob/0241ffb3b803f2a861e47904d466f2968c35ec06/internal/providercache/provider_cache.go#L181)) only scans `.tf` files in the working directory and is unaware of sub-module constraints. The two strings will almost always differ, causing `shouldUpdateConstraints = true` to fire unconditionally and overwrite a pre-existing, correctly generated lock file

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #5616.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Better detection and handling of Terraform lock files to avoid unnecessary lock updates during provider cache operations
  * Improved normalization of multi-part version constraints (e.g., ">= 3.0, < 7.0")
  * More robust lockfile constraint updates that preserve aggregated constraints instead of overwriting them

* **Tests**
  * Added tests covering multi-part constraint normalization and lockfile constraint preservation

### CODE REVIEW

File: internal/tf/getproviders/lock.go [hunk 1]
```diff
@@ -190,6 +164,29 @@ func getExistingHashes(providerBlock *hclwrite.Block, provider Provider) ([]Hash
...
+		`"`,
+		"",
+	)
+
+	currentConstraints, err := version.NewConstraint(currentConstraintsValue)
+	if err != nil {
+		return true
+	}
+
+	newVersion, _ := version.NewVersion(providerVersion)
```
Comment (denis256) [inline internal/tf/getproviders/lock.go]: Ignored error

File: internal/tf/getproviders/lock.go [hunk 2]
```diff
@@ -190,6 +164,29 @@ func getExistingHashes(providerBlock *hclwrite.Block, provider Provider) ([]Hash
...
+
+	return !currentConstraints.Check(newVersion)
```
Comment (denis256) [inline internal/tf/getproviders/lock.go:190]: newVersion can be nil?

File: internal/tf/getproviders/lock.go (hunk 1 above)
Comment (yhakbar) [reply internal/tf/getproviders/lock.go]: Good catch. Added a check for this.

File: internal/tf/getproviders/lock.go (hunk 2 above)
Comment (yhakbar) [reply internal/tf/getproviders/lock.go:190]: Added an error check, and I don't believe it can be nil if no error is thrown.
