### PR TITLE
Check hash and signature of cached providers

### LINKED ISSUE #3047: Checking the hash/signature of cached providers using the Terragrunt Provider Cache server
**Describe the bug**

When implementing the Terragrunt Provider Cache server, to speed up `terraform init`, it was decided to use [TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE](https://developer.hashicorp.com/terraform/cli/config/config-file#allowing-the-provider-plugin-cache-to-break-the-dependency-lock-file), which allows you to create a lock file super quickly, but this has its drawback, it completely trusts the files from the cache and does not check their cache and signature.

The discussion started from #3001

**To Reproduce**
`terragrunt run-all apply --terragrunt-provider-cache`

**Expected behavior**
Every time Terraform requests a provider, Terragrunt Provider Cache should download the hash and signature from the remote registry to check and ensure that the cached provider is not corrupted.

**Versions**
- Terragrunt version: [v0.56.4](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.56.4)

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

1. Replaced `terraform providers lock -platform=xxx_xxxx` with `terraform init`.
2. Added hash and signature authentication.

Fixes #3047.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added[X] / Removed / Updated.

Check hash and signature of cached providers

### CODE REVIEW

File: cli/provider_cache.go [hunk 1]
```diff
@@ -69,7 +69,7 @@ func InitProviderCacheServer(opts *options.TerragruntOptions) (*ProviderCacheSer
 	if opts.ProviderCacheToken == "" {
 		opts.ProviderCacheToken = uuid.New().String()
 	}
-	// Currently, the cache server only supports the `x-api-key` token.
+	// Currently, the cache cache only supports the `x-api-key` token.
```
Comment (brikis98) [inline cli/provider_cache.go:72]: NIT: Search & replace issue? Says "cache cache."

File: cli/provider_cache.go [hunk 2]
```diff
@@ -79,118 +79,80 @@ func InitProviderCacheServer(opts *options.TerragruntOptions) (*ProviderCacheSer
...
-	return envs
+	return shell.RunTerraformCommandWithOutput(ctx, cloneOpts, args...)
 }
 
-// createLocalCLIConfig creates a local CLI configuration that merges the default/user configuration with our Private Registry configuration.
-// We don't want to use Terraform's `plugin_cache_dir` feature because the cache is populated by our Terragrunt Provider Cache server, and to make sure that no Terraform process ever overwrites the global cache, we clear this value.
-// In order to force Terraform to queries our registry instead of the original one, we use the section below.
+// createLocalCLIConfig creates a local CLI config that merges the default/user configuration with our Provider Cache configuration.
+// We don't want to use Terraform's `plugin_cache_dir` feature because the cache is populated by our Terragrunt Provider Cache cache, and to make sure that no Terraform process ever overwrites the global cache, we clear this value.
+// In order to force Terraform to queries our cache cache instead of the original one, we use the section below.
```
Comment (brikis98) [inline cli/provider_cache.go:155]: More search/replace issues resulting in "cache cache," it seems. I won't highlight others; do a scan through, as there are prob more!

File: cli/provider_cache.go [hunk 3]
```diff
@@ -212,36 +174,100 @@ func providerCacheEnvironment(opts *options.TerragruntOptions, cliConfigFile str
 //		}
 //	}
 //
-// This func doesn't change the default CLI config file, only creates a new one at the given path `cliConfigFile`. Ultimately, we can assign this path to `TF_CLI_CONFIG_FILE`.
-func createLocalCLIConfig(opts *options.TerragruntOptions, cliConfigFile string, registryProviderURL *url.URL) error {
+// This func doesn't change the default CLI config file, only creates a new one at the given path `filename`. Ultimately, we can assign this path to `TF_CLI_CONFIG_FILE`.
+//
+// It creates two types of configuration depending on the `cacheRequestID` variable set.
+// 1. If `cacheRequestID` is set, `terraform init` does _not_ use the provider cache directory, the cache server creates a cache for requested providers and returns HTTP status 423. Since for each module we create the CLI config, using `cacheRequestID` we have opprotuenty later retrieve from the cache server exactly those cached providers that were requested by `terraform init` using this configuration.
```
Comment (brikis98) [inline cli/provider_cache.go:180]:
```suggestion
// 1. If `cacheRequestID` is set, `terraform init` does _not_ use the provider cache directory, the cache server creates a cache for requested providers and returns HTTP status 423. Since for each module we create the CLI config, using `cacheRequestID` we have the opportunity later retrieve from the cache server exactly those cached providers that were requested by `terraform init` using this configuration.
```

File: docs/_docs/02_features/provider-cache.md [hunk 4]
```diff
@@ -79,18 +79,18 @@ terragrunt apply
...
-    * The Terragrunt Provider Cache server returns the HTTP status _429 Locked_ to Terraform. This is because we do _not_ want Terraform to actually download any providers as a result of calling `terraform providers lock` (as that command does _not_ use any caching); we only use that command to get the list of required providers.
-    * At this point, all providers are downloaded and cached, so finally, we run `terragrunt init`, which will find all the providers it needs in the cache, and it'll create symlinks to them nearly instantly, with no additional downloading.
+    * The Terragrunt Provider Cache server returns the HTTP status _429 Locked_ to Terraform. This is because we do _not_ want Terraform to actually download any providers as a result of calling `terraform init` (as that command does _not_ use any caching); we only use that command to get the list of required providers.
```
Comment (brikis98) [inline docs/_docs/02_features/provider-cache.md:92]: NIT: "as that command does _not_ use any caching" isn't accurate for `init`...

File: docs/_docs/02_features/provider-cache.md [hunk 5]
```diff
@@ -79,18 +79,18 @@ terragrunt apply
...
   * Set environment variables:
      * [TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE](https://developer.hashicorp.com/terraform/cli/config/config-file#allowing-the-provider-plugin-cache-to-break-the-dependency-lock-file) allows to generate `.terraform.lock.hcl` files based only on provider hashes from the cache directory.
      * [TF_CLI_CONFIG_FILE](https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_plugin_cache_dir) sets to use just created local CLI config `.terragrunt-cache/.terraformrc`
      * [TF_TOKEN_*](https://developer.hashicorp.com/terraform/cli/config/config-file#environment-variable-credentials) sets per-remote-registry tokens for authentication to Terragrunt Provider Cache server.
 * Any time Terragrunt is going to run `init`:
-    * Call `terraform providers lock -platform=cache_provider`. This gets Terraform to request all the providers it needs from the Terragrunt Provider Cache server.
+    * Call `terraform init`. This gets Terraform to request all the providers it needs from the Terragrunt Provider Cache server.
```
Comment (brikis98) [inline docs/_docs/02_features/provider-cache.md:90]: The docs need to be updated to call out where we do hash/signature checking.

File: terraform/provider/hash.go [hunk 6]
```diff
@@ -0,0 +1,58 @@
+package provider
```
Comment (brikis98) [inline terraform/provider/hash.go:1]: Is this all novel code you wrote yourself? Or is it based on the hash/signature checks in Terraform? Or OpenTofu? Due to TF's switch to BSL, we have to be careful about what code we use or copy here!

This question applies to `hash.go`, `package_authentication.go`, etc.

**Review by brikis98 — COMMENTED** [review]
Do we have e2e tests for this?

That is, tests that (a) download valid providers and validate their checksums & signatures and (b) download intentionally invalid providers and ensure we show an error when the checksums or signatures don't match?

File: cli/provider_cache.go (hunk 1 above)
Comment (levkohimins) [reply cli/provider_cache.go]: Thanks.

File: cli/provider_cache.go (hunk 2 above)
Comment (levkohimins) [reply cli/provider_cache.go]: Fixed everywhere, thanks.

File: cli/provider_cache.go (hunk 3 above)
Comment (levkohimins) [reply cli/provider_cache.go]: Thanks.

File: docs/_docs/02_features/provider-cache.md (hunk 5 above)
Comment (levkohimins) [reply docs/_docs/02_features/provider-cache.md:90]: Understood. I mentioned this in the docs.

File: terraform/provider/hash.go (hunk 6 above)
Comment (levkohimins) [reply terraform/provider/hash.go:1]: I took the needed code from Terraform 1.5 and changed it by about 10%. Since we are already importing some terraform code as a package, I'm not sure if I need to additionally specify this in these files.

Comment (brikis98) [reply terraform/provider/hash.go:1]: As long as it is MPL TF, that is fine.

**Review by brikis98 — APPROVED** [review]
LGTM!

**Comment by levkohimins** [comment]
> > > Do we have e2e tests for this?
> > > That is, tests that (a) download valid providers and validate their checksums & signatures and (b) download intentionally invalid providers and ensure we show an error when the checksums or signatures don't match?
> > 
> > 
> > We have unit tests that cover 100% of this functionality. For e2e/integration tests we need to implement a test private registry server to simulate the invalid providers. It's quite time-consuming, but if necessary, I'll do it. Or maybe you can recommend a better approach?
> > Thank for the review!
> 
> I don't want to spend a ton of time on this, but I do want to build confidence the hashes and signatures are really checked. We can prob merge this PR as-is. That said, is there some compromise solution that you could add in a follow up PR in a few hours? Could you re-use your own code to run a mock registry on localhost? So you execute `run-all`, this runs TG, which in turn runs real TF processes that try to download providers, which triggers the TG provider cache, and instead of trying to download those providers from registry.terraform.io, it tries to download them from localhost:12345, which is a server where we can return either valid mock providers or mock providers with invalid signatures.

Very interesting idea! I'll think about it, I'm sure I'll come up with something. Thank you!
