### PR TITLE
fix: duplicate error reporting in worker pool

### LINKED ISSUE #5525: Duplicate errors in commands that use the worker pool
## Description

The worker pool in `internal/worker/worker.go` appends every error to `allErrors` twice, causing all error output to be duplicated. Any command that uses the worker pool (e.g. `terragrunt stack generate`) reports 2N errors instead of N, with each error message appearing identically twice. I've sent a PR #5526 to fix this. The PR contains more implementation details.

## Steps To Reproduce

1. Create a `terragrunt.stack.hcl` with a unit pointing to a nonexistent path:

```hcl
unit "broken" {
  source = "/nonexistent/path"
  path   = "broken"
}
```

2. Run:

```bash
terragrunt stack generate
```

3. Observe the output:

```
ERROR  2 errors occurred:

* Failed to fetch unit broken
  Original error: stat /nonexistent/path: no such file or directory

* Failed to fetch unit broken
  Original error: stat /nonexistent/path: no such file or directory
```

The same error is listed twice. With multiple failing units, every error is doubled.

## Expected behavior

A single failing unit should produce a single error:

```
ERROR  error occurred:

* Failed to fetch unit broken
  Original error: stat /nonexistent/path: no such file or directory
```

## Must haves

- [x] Steps for reproduction provided.

## Nice to haves

- [x] Terminal output

## Versions

- Terragrunt version: v0.97.2 (bug introduced in PR #4078, commit `9f9929a1`)
- OpenTofu/Terraform version: N/A (bug is in terragrunt internals, not provider-dependent)
- Environment details: macOS 15.7.3, arm64, Go 1.25.5 (reproducible on all platforms)

## Additional context

The bug was introduced in PR #4078 ("stack validation improvements"). `Submit()` appends errors to `allErrors` via a direct `appendError()` call, and then also sends the error through `resultChan` to `collectResults()`, which appends it to `allErrors` a second time. In the normal case both paths fire, doubling every error.

### PR DESCRIPTION
**Pull request by anuragrao04**
Fixes #5525 

## Problem

Every error from the worker pool (e.g. during `terragrunt stack generate`) is reported twice. N errors become 2N in the output.

## Root cause

`Submit()` in `internal/worker/worker.go` appends each error to `allErrors` via two paths that both fire in the normal case:

1. Direct `wp.appendError(err)` call
2. Send to `resultChan` -> `collectResults()` -> `wp.allErrors.Append(err)`

The likely intent (added in PR #4078) was for `appendError()` to return an error, so the second `if err != nil` block would only fire as a fallback when the direct append failed:

```go
		// If there's an error, always record it directly first
		if err != nil {
			err = wp.appendError(err) 
			// expected to return an error and the second err != nil check was
			// supposed to check this error. But appendError() doesn't return an error
			// and the second err != nil ended up checking the original err = task() error
		}

		// Only try to send result to channel if there's an error and pool isn't stopping
		if err != nil {
			select {
			case <-wp.doneChan:
				// Pool is stopping, error already recorded directly via appendError
			case wp.resultChan <- err:
				// Successfully sent the error
			default: // Channel might be closed or full, but we already recorded the error via appendError, so we can safely continue without panic
			}
		}
	}()

```

But `appendError()` has no return value, so `err` remains the original task error and the second block always runs — both paths fire on every error.

## Fix

Removed the `resultChan` send from `Submit()`, keeping only the direct `appendError()` call. The direct call runs inside the task goroutine before `wg.Done()`, so it guarantees the error is recorded before `Wait()` returns.

## How To Reproduce

```hcl
# terragrunt.stack.hcl
unit "broken" {
  source = "/nonexistent/path"
  path   = "broken"
}
```

```
$ terragrunt stack generate
# Before fix: "2 errors occurred" with the same error listed twice
# After fix: "1 error occurred"
# If it doesn't happen the first time, run multiple times. It
# is a race condition
```

## Testing

- Added error count assertion to `TestSomeTasksReturnErrors` — previously it only checked `require.Error(t, errs)` without verifying the count, which is why the bug wasn't caught by CI
- All worker pool tests pass with `-race`
- Downstream stack config tests pass
- `go vet` clean
- Manual verification against reproduction case

## Summary by CodeRabbit

* **Refactor**
  * Simplified internal error handling to centralize error accumulation and remove the previous mixed propagation paths, reducing complexity and improving reliability.

* **Tests**
  * Strengthened tests to assert the aggregated error type and exact wrapped error count, improving detection of multi-error scenarios and regression protection.

---

> [!NOTE]
> **Low Risk**
> Small, localized concurrency simplification in `internal/worker` that removes unused channels and makes error aggregation deterministic; minimal behavioral change beyond eliminating duplicate errors.
> 
> **Overview**
> Fixes worker pool error reporting so each task failure is aggregated **once** by removing the `resultChan`/`doneChan` plumbing and `collectResults()` goroutine; `Submit()` now only records errors via the thread-safe `appendError()` path.
> 
> Simplifies shutdown (`Start`/`Stop`/`GracefulStop`) by no longer recreating/closing the removed channels, and tightens tests to assert `Wait()` returns an `*errors.MultiError` with the expected wrapped error count (preventing regressions of the 2x error bug).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 49a98596e676ff1a0eb97856d51dcbbc536ddf88. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: internal/worker/worker.go [hunk 1]
```diff
@@ -157,21 +157,9 @@ func (wp *Pool) Submit(task Task) {
...
 		if err != nil {
 			wp.appendError(err)
 		}
-
-		// Only try to send result to channel if there's an error and pool isn't stopping
-		if err != nil {
-			select {
-			case <-wp.doneChan:
-				// Pool is stopping, error already recorded directly via appendError
-			case wp.resultChan <- err:
```
Comment (denis256) [inline internal/worker/worker.go:170]: `resultChan` now is unused

Comment (denis256) [reply internal/worker/worker.go:170]: Looks like if we remove resultChan path, the entire collectResults/channel architecture becomes unnecessary

**Review by denis256 — COMMENTED** [review]
PR introduces a lot of dead code

**Comment by denis256** [comment]
```
level=info msg="File cache stats: 2 entries of total size 9.4KiB"
internal/worker/worker_test.go:86:18: type assertion on error will fail on wrapped errors. Use errors.As to check for specific errors (errorlint)
	multiErr, ok := errs.(*errors.MultiError)
	                ^
internal/worker/worker.go:159:1: unnecessary whitespace (err) (wsl_v5)

^
2 issues:
* errorlint: 1
```
