### PR TITLE
bug: reference of dependency outputs in generate

### LINKED ISSUE #4962: Dependency output in generate block regression in v0.89.0+
## Describe the bug

Since Terragrunt v0.89.0, using a `dependency` output reference within a `generate` block results in the following error when using `run --all -- plan`:
```hcl
20:47:30.537 ERROR  Error: Unsuitable value type
20:47:30.537 ERROR    on ./testing/terragrunt.hcl line 50, in generate "provider_test":
20:47:30.537 ERROR    52:   contents  = <<EOF
20:47:30.537 ERROR    53: provider "test" {
20:47:30.537 ERROR    54:   api_token = "${dependency.other.outputs.secrets.test_provider_token}"
20:47:30.537 ERROR    55: }
20:47:30.537 ERROR    56: EOF
20:47:30.537 ERROR  Unsuitable value: value must be known
```

The same code works:
* in versions `v0.88.1` and before
* if run as `terragrunt run -- plan` directly within the given module (without `--all`)
* if the same dependency output is used in `inputs` instead of a `generate` block

## Steps To Reproduce

```hcl
dependencies {
  paths = ["../other"]
}
dependency "other" {
  config_path = "../other"
}
generate "provider_test" {
  path      = "provider_test.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "test" {
  api_token = "${dependency.other.outputs.secrets.test_provider_token}"
}
EOF
}
```

## Versions

- Terragrunt version: `v0.90.0`
- OpenTofu/Terraform version: `Terraform v1.13.3 on darwin_arm64`
- Environment details (Ubuntu 20.04, Windows 10, etc.): `macOS 15.6.1`

### PR DESCRIPTION
**Pull request by denis256**
## Description

* simplified discovery to use partial parsing and get better performance
* fixed parsing of HCL to support dependency output reference in generate
* simplified `hcl validate` to use only discovery and not set global action function
* hcl validate tests update
* added regression tests

Fixes #4962.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed handling of dependency outputs in generate blocks during configuration validation and planning operations.
  * Improved validation command to properly process multi-component configurations and aggregate errors across components.

* **Tests**
  * Added regression tests for dependency outputs in generate blocks and input processing scenarios.

### CODE REVIEW

File: test/integration_regressions_test.go [hunk 1]
```diff
@@ -97,3 +99,97 @@ func TestIncludeError(t *testing.T) {
...
+	tmpEnvPath := helpers.CopyEnvironment(t, testFixtureDependencyGenerate)
+	rootPath := util.JoinPath(tmpEnvPath, testFixtureDependencyGenerate)
+	otherPath := util.JoinPath(rootPath, "other")
+	testingPath := util.JoinPath(rootPath, "testing")
+
+	helpers.CleanupTerraformFolder(t, rootPath)
+
+	helpers.RunTerragrunt(
+		t,
+		"terragrunt apply --auto-approve --non-interactive --working-dir "+otherPath,
```
Comment (yhakbar) [inline test/integration_regressions_test.go]:
```suggestion
		"terragrunt apply --non-interactive --working-dir "+otherPath+ " -- -auto-approve",
```

This is what you want?

File: internal/discovery/discovery.go [hunk 2]
```diff
@@ -479,8 +479,27 @@ func Parse(
 		parsingCtx = parsingCtx.WithParseOption(parseOptions)
 	}
 
+	// Choose between full and partial parsing based on context:
```
Comment (yhakbar) [inline internal/discovery/discovery.go]: I'm not sure about this logic. Why are we failing parsing during discovery to support the behavior of validation? It feels like we're working around the problem in a weird way.
