### PR TITLE
Fix init command used to download remote configurations

### LINKED ISSUE #174: How to remote configurations + remote state + multiple modules, goes wrong
I have to following and I'm not sure what I'm doing wrong, I want to be able to run two commands:

```shell
terragrunt apply # on the network folder to create just the network
```

and/or

```shell
terragrunt apply-all # on the root folder `terraform` to create network, database and compute resources
```

My project structure looks like:

screen shot 2017-04-22 at 13 18 46

My `terraform.tfvars` files looks like:

**terraform/network/terraform.tfvars**
```hcl
terragrunt = {
    terraform {
        source = "../../modules//network"
    },
    include {
        path = "${find_in_parent_folders()}"
    }
}
```

**terraform/terraform.tfvars**
```hcl
terragrunt = {
    terraform {
        extra_arguments "custom_vars" {
            commands = [
                "plan",
                "apply",
                "destroy"
            ]
            arguments = [
                "-var-file=${get_tfvars_dir()}/../variables.tfvars"
            ]
        }
    },
    remote_state {
        backend = "s3"
        config {
            bucket  = "my-bucket"
            key     = "aws/myapp/${path_relative_to_include()}/terraform.tfstat"
            region  = "eu-west-1"
        }
    }
}
```
I'm looking forward to move those `modules` into their own repo and then be able to do a proper `source=git::git@...` and pull the source code from git however I can't manage to make it work, it looks like the tmp folder got created properly and the code from my modules it's there however when it comes to run the terraform command it can not find the variables and terraform ask me to introduce them, on the tmp folder there are not `variables.tfvars` file so I guess that's why it's asking me for them.

I reckon I have misunderstood something and mixing concepts in here hope someone can point me out in the right direction, ta

### PR DESCRIPTION
**Pull request by brikis98**
This PR fixes #174 and #176. We’ve been using the `terraform init` command to download remote Terraform configurations for a while now. As of Terraform 0.9, this same command also tries to configure backends, download modules, etc. When updating Terragrunt to support Terraform 0.9, we forgot to update this original `init` call to pass `backend` parameters.

### CODE REVIEW

File: cli/cli_app.go [hunk 1]
```diff
@@ -42,6 +42,24 @@ var DEPRECATED_COMMANDS = map[string]string{
...
+	"plan",
+	"push",
+	"refresh",
+	"show",
+	"taint",
+	"untaint",
+	"validate",
+	"force-unlock",
+	"state",
+}
```
Comment (brikis98) [inline cli/cli_app.go]: This change is not directly related to this PR, but also something I missed when updating Terragrunt to work with Terraform 0.9.

File: test/integration_test.go [hunk 2]
```diff
@@ -282,6 +284,48 @@ func TestLocalWithRelativeExtraArgs(t *testing.T) {
 	runTerragrunt(t, fmt.Sprintf("terragrunt apply --terragrunt-non-interactive --terragrunt-working-dir %s", TEST_FIXTURE_LOCAL_RELATIVE_ARGS_DOWNLOAD_PATH))
 }
 
+func TestLocalWithBackend(t *testing.T) {
```
Comment (brikis98) [inline test/integration_test.go]: This test case would fail before this PR

**Comment by brikis98** [comment]
@josh-padnick I'm going to merge this in so I can submit a couple more fixes. Feedback welcome!
