### PR TITLE
fix: Removing path manipulation in log messages

### LINKED ISSUE #5043: terragrunt modifies paths in `before_hook` output
## Describe the bug

terragrunt modifies paths in `before_hook` output

## Reproducing bugs

We have written a `before_hook` in bash to ensure that terragrunt runs with sensible environment settings. If the environment is not properly set, it will suggest how to integrate in the environment, and exit with an error.

When the hook runs, the output from the script itself has the correct format. However, when the output is then captured and printed by terragrunt's log, the paths in the output are made relative, which in this specific case is a mess:

```
terragrunt init
13:36:39.189 INFO   Executing hook: env_check
Terragrunt environment check failed:
Required environment variables:
  export TG_BACKEND_BOOTSTRAP="true"
  export TG_PROVIDER_CACHE="true"
  export TG_PROVIDER_CACHE_DIR="/home/bronto/.terraform.d/plugin-cache"
13:36:39.194 ERROR  Error running hook env_check with message: Failed to execute "../../../../.terragrunt_hooks/check_terragrunt_env.sh " in .
Terragrunt environment check failed:
Required environment variables:
  export TG_BACKEND_BOOTSTRAP="true"
  export TG_PROVIDER_CACHE="true"
  export TG_PROVIDER_CACHE_DIR="../../../../../../../.terraform.d/plugin-cache"

exit status 1
13:36:39.194 ERROR  Errors encountered running before_hooks. Not running 'terraform'.
13:36:39.194 ERROR  error occurred:

* Failed to execute "../../../../.terragrunt_hooks/check_terragrunt_env.sh " in .
  Terragrunt environment check failed:
  Required environment variables:
    export TG_BACKEND_BOOTSTRAP="true"
    export TG_PROVIDER_CACHE="true"
    export TG_PROVIDER_CACHE_DIR="../../../../../../../.terraform.d/plugin-cache"
  
  exit status 1
```

I maintain that when an external programs emits an error, the error message from the program should be leaved untouched by terragrunt. In cases like this, it will just make it harder to understand what one should do to fix the error.

## Steps To Reproduce

Have this hook somewhere in the filesystem, where terragrunt can access it (we have it in a directory in our IaC repo):

```shell
#!/usr/bin/env bash

set -euo pipefail

REQUIRED_EXPORTS=()
REQUIRED_DIRS=()
ERRORS=()

# Helper: suggest mkdir if directory doesn't exist
suggest_mkdir_if_missing() {
    local dir="$1"
    if [[ -n "$dir" && ! -d "$dir" ]]; then
        REQUIRED_DIRS+=("$dir")
    fi
}

# Check required boolean variables
[[ "${TG_BACKEND_BOOTSTRAP:-}" != "true" ]] && REQUIRED_EXPORTS+=('export TG_BACKEND_BOOTSTRAP="true"')
[[ "${TG_PROVIDER_CACHE:-}" != "true" ]] && REQUIRED_EXPORTS+=('export TG_PROVIDER_CACHE="true"')

# Ensure TF_PLUGIN_CACHE_DIR and TG_PROVIDER_CACHE_DIR are set and consistent
tf_dir="${TF_PLUGIN_CACHE_DIR:-}"
tg_dir="${TG_PROVIDER_CACHE_DIR:-}"

# Check for mismatch (both set but different)
if [[ -n "$tf_dir" && -n "$tg_dir" && "$tf_dir" != "$tg_dir" ]]; then
    ERRORS+=("TF_PLUGIN_CACHE_DIR and TG_PROVIDER_CACHE_DIR are set to different paths:")
    ERRORS+=("  TF_PLUGIN_CACHE_DIR=$tf_dir")
    ERRORS+=("  TG_PROVIDER_CACHE_DIR=$tg_dir")
    ERRORS+=("  They must be set to the same path.")
# Suggest setting any unset cache directories
elif [[ -z "$tf_dir" || -z "$tg_dir" ]]; then
    target_dir="${tf_dir:-${tg_dir:-$HOME/.terraform.d/plugin-cache}}"
    [[ -z "$tf_dir" ]] && REQUIRED_EXPORTS+=("export TF_PLUGIN_CACHE_DIR=\"$target_dir\"")
    [[ -z "$tg_dir" ]] && REQUIRED_EXPORTS+=("export TG_PROVIDER_CACHE_DIR=\"$target_dir\"")
fi

# Check if the cache directory exists (whether both were set or we just suggested them)
if [[ -n "$tf_dir" || -n "$tg_dir" ]]; then
    cache_dir="${tf_dir:-$tg_dir}"
    suggest_mkdir_if_missing "$cache_dir"
fi

# Report all errors and required exports
if [[ ${#ERRORS[@]} -ne 0 || ${#REQUIRED_EXPORTS[@]} -ne 0 || ${#REQUIRED_DIRS[@]} -ne 0 ]]; then
    echo "Terragrunt environment check failed:" >&2
    [[ ${#ERRORS[@]} -ne 0 ]] && printf 'ERROR: %s\n' "${ERRORS[@]}" >&2

    if [[ ${#REQUIRED_EXPORTS[@]} -ne 0 ]]; then
        [[ ${#ERRORS[@]} -ne 0 ]] && echo >&2 # Add blank line if we had errors
        echo "Required environment variables:" >&2
        printf '  %s\n' "${REQUIRED_EXPORTS[@]}" >&2
    fi

    if [[ ${#REQUIRED_DIRS[@]} -ne 0 ]]; then
        [[ ${#ERRORS[@]} -ne 0 || ${#REQUIRED_EXPORTS[@]} -ne 0 ]] && echo >&2 # Add blank line
        echo "Ensure the following directories exist:" >&2
        for dir in "${REQUIRED_DIRS[@]}"; do
            printf '  mkdir -p "%s"\n' "$dir" >&2
        done
    fi
    exit 1
fi
```

Have a `before_hook` like this in your configuration (in our case, it's in `root.hcl`), where `local.hooks_dir` is set to the directory where you put the hook above:

```hcl
  before_hook "env_check" {
    commands = [local.current_terraform_command]
    execute  = ["${local.hooks_dir}/check_terragrunt_env.sh"]
  }
```

Ensure that you are using terragrunt's standard logging (you should have no environment variables or command-line options that modify the logging format)

Ensure that you have `TF_PLUGIN_CACHE_DIR` or `TG_PROVIDER_CACHE_DIR` unset.

Then run, for example, `terragrunt init`.

## Expected behavior

The output of the hook will be correct (with an absolute path), the ERROR output will have the absolute path converted to relative.

## Must haves

- [X] Steps for reproduction provided.

## Nice to haves

- [X] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v0.89.3
- OpenTofu/Terraform version: v1.13.4
- Environment details (Ubuntu 20.04, Windows 10, etc.): Debian Linux 13, MacOS

## Additional context

N/A

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #5043.

Removes the logic to manipulate log messages to make discovered paths relative.

Log messages should be emitted exactly as-is, and it's the responsiblity of the caller to decide whether or not to make paths in log messages relative.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

- New Features
  - Richer error messages now include working directory context.
  - Logs can show relative or absolute paths based on settings for clearer output.
  - TFLint commands execute from the project root for consistent path handling.

- Style
  - Standardized path formatting across logs; removed a redundant debug message.
  - Simplified log message fields to reduce noise.

- Tests
  - Added and updated integration tests and fixtures to verify path formatting, hook path preservation, repo_root/terragrunt_dir outputs, TFLint config detection, and dependency script paths.

### CODE REVIEW

File: internal/tflint/tflint.go [hunk 1]
```diff
@@ -53,15 +53,21 @@ func RunTflintWithOpts(ctx context.Context, l log.Logger, opts *options.Terragru
...
 
-	l.Debugf("Initializing tflint in directory %s", opts.WorkingDir)
+	l.Debugf(
+		"Initializing tflint in directory %s",
+		util.RelPathForLog(opts.RootWorkingDir, opts.WorkingDir, opts.LogShowAbsPaths),
+	)
 
 	tflintArgs := hookExecute[1:]
 
+	configFileRel := util.RelPathForLog(opts.WorkingDir, configFile, opts.LogShowAbsPaths)
```
Comment (denis256) [inline internal/tflint/tflint.go:63]: RelPathForLog returns a relative path suitable for logging - not sure why it is used to construct path for tflint

File: internal/runner/run/download_source.go [hunk 2]
```diff
@@ -61,7 +61,11 @@ func DownloadTerraformSource(
 		return nil, err
 	}
 
-	l.Debugf("Copying files from %s into %s", opts.WorkingDir, terraformSource.WorkingDir)
+	l.Debugf(
+		"Copying files from %s into %s",
+		util.RelPathForLog(opts.WorkingDir, opts.WorkingDir, opts.LogShowAbsPaths),
```
Comment (denis256) [inline internal/runner/run/download_source.go:66]: RelPathForLog - basePath and targetPath are the same paths, it will be resolved to "."

File: internal/util/file.go [hunk 3]
```diff
@@ -1153,6 +1153,31 @@ func SanitizePath(baseDir string, file string) (string, error) {
 	return fullPath, nil
 }
 
+// RelPathForLog returns a relative path suitable for logging.
+// If the path cannot be made relative, it returns the original path.
+// Paths that don't start with ".." get a "./" prefix for clarity.
+// If showAbsPath is true, the original targetPath is returned unchanged.
+func RelPathForLog(basePath, targetPath string, showAbsPath bool) string {
```
Comment (denis256) [inline internal/util/file.go:1160]: No unit tests for this function, will be good to track that it is working as expected

File: internal/runner/run/download_source.go (hunk 2 above)
Comment (yhakbar) [reply internal/runner/run/download_source.go:66]: Unless the user uses `--log-show-abs-path`.

File: internal/tflint/tflint.go (hunk 1 above)
Comment (yhakbar) [reply internal/tflint/tflint.go:63]: I don't want to log different values in logging than is used for the CLI invocation of tflint (which we do now, btw), and I don't want to have the CLI invocation of tflint always use abs paths. This makes it so that we tell tflint to use paths that are convenient to log, and work just the same.

File: internal/util/file.go (hunk 3 above)
Comment (yhakbar) [reply internal/util/file.go:1160]: I can add those.

**Review by denis256 — APPROVED** [review]
