### PR TITLE
#2595 Fix for fetching reference value with slashes

### LINKED ISSUE #2595: ref in terraform source (git) gets truncated if containing slash
**Describe the bug**
Using a git branch name containing a forward slash as ref in the terraform source results in the branch name being truncated at the slash.

ERRO[0000] 1 error occurred:
	* error downloading 'ssh://git@gitlab.com/repo.git?ref=feat': /usr/local/bin/git exited with 1: error: pathspec 'feat' did not match any file(s) known to git

**To Reproduce**
```hcl
terraform {
  source = "git::git@gitlab.com:repo.git//.?ref=feat/example"
}
```

**Expected behavior**
Terragrunt using the correct and complete ref.

**Versions**
- Terragrunt version: v0.46.2 (it works with v0.45.18)
- Terraform version: v1.4.6
- Environment details: macOS Ventura 13.4 (darwin_amd64) (but also on an M1 and a Ubuntu)

### PR DESCRIPTION
**Pull request by denis256**
## Description

Included changes:
 * add test for handling repository sources with ref
 * source map handling by setting in url module path

Fixes #2595.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Updated fetching of `?ref=` value with slashes.

### Migration Guide

N/A

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -531,6 +533,20 @@ func adjustSourceWithMap(sourceMap map[string]string, source string, modulePath
 		}
 		moduleSubdir = moduleSubdirFromUrl
 	}
+	// if source path contains "?ref=", reconstruct module dir using "//"
+	if strings.Contains(sourcePath, "?ref=") && moduleSubdir != "" {
```
Comment (jaymecd) [inline config/config.go:537]: wouldn't it be easier to split by `//`? convention over configuration approach.

Comment (levkohimins) [reply config/config.go:537]: Wouldn't it be better to move this logic to `util.JoinTerraformModulePath` ?

**Review by levkohimins — APPROVED** [review]
LGTM!
