### PR TITLE
fix: Fixing issue with ending runs from `--queue-exclude-external`

### LINKED ISSUE #4448: bug: Run Summary fails with `run --all --queue-exclude-external` in a unit with dependencies.
> If I run `terragrunt plan --all --queue-exclude-external` with the Report experiment enabled, and some dependencies are external to the current folder (but the resources exist and are created already), I get errors for those resources:
> 
> ```
> 12:03:47.147 ERROR  [../configuration/s3-bucket-configurations] Error ending run for module ../configuration/s3-bucket-configurations: run not found in report: ../configuration/s3-bucket-configurations
> 12:03:47.147 ERROR  [../networking/vpc] Error ending run for module ../networking/vpc: run not found in report: ../networking/vpc
> 12:03:51.762 STDOUT [runner-registration-api-large] tofu: gitlab_user_runner.main[0]: Refreshing state... [id=47873586]
> 12:03:51.805 STDOUT [runner-registration-api-medium] tofu: gitlab_user_runner.main[0]: Refreshing state... [id=47873587]
> ```
> 
> I do not believe that should be marked as an error per se. Running Terragrunt this way is a legitimate use of this tool. The resources exist already. Their outputs are correct. I only care about resources under the current folder.
> 
> Perhaps Report should ignore the external resources in this case. Or, at least, do not flag them as errors.
> 
> ```
> % terragrunt -version
> terragrunt version v0.81.8
> ``` 

 _Originally posted by @FlorinAndrei in [#3628](https://github.com/gruntwork-io/terragrunt/issues/3628#issuecomment-2988950029)_

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #4448.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Fixed bug with `--queue-exclude-external` in `report` experiment.

## Summary by CodeRabbit

- **New Features**
  - Added support for marking external dependencies as excluded in reports when using the `--queue-exclude-external` flag.
  - Introduced a new reason label for exclusions in report summaries.

- **Bug Fixes**
  - Improved error handling for external dependencies excluded from the run queue, ensuring accurate reporting.

- **Refactor**
  - Centralized logic for deriving display names from run paths for more consistent reporting.

- **Tests**
  - Added an integration test to verify correct reporting of excluded external dependencies.
  - Updated existing tests to use dynamic temporary directories and feature flags for improved reliability.

- **Chores**
  - Updated test fixtures to use configurable feature values for dependency paths.

### CODE REVIEW

File: configstack/running_module.go [hunk 1]
```diff
@@ -221,7 +221,34 @@ func (module *RunningModule) moduleFinished(moduleErr error, r *report.Report, r
 
 		if reportExperiment {
 			if err := r.EndRun(module.Module.Path); err != nil {
-				module.Logger.Errorf("Error ending run for module %s: %v", module.Module.Path, err)
+				// If the run is not found in the report, it likely means this module was an external dependency
+				// that was excluded from the queue (e.g., with --queue-exclude-external).
+				if !errors.Is(err, report.ErrRunNotFound) {
```
Comment (denis256) [inline configstack/running_module.go:226]: I was thinking that it may be helpful to extract this logic as a separate function

**Review by denis256 — APPROVED** [review]

File: configstack/running_module.go (hunk 1 above)
Comment (yhakbar) [reply configstack/running_module.go:226]: Ya, you're right.
