### PR TITLE
Fixing output STDOUT logs to `stdout`

### LINKED ISSUE #3367: 0.67.0 makes STDOUT output in log format
## Describe the bug

terragrunt started printing its normal output in log format

## Steps To Reproduce

Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```hcl
terragrunt version v0.67.0
❯ \terragrunt plan         
13:13:16.454 STDOUT terraform: data.terraform_remote_state.infrastructure_network: Reading...
13:13:17.808 STDOUT terraform: data.terraform_remote_state.infrastructure_network: Read complete after 2s
13:13:17.870 STDOUT terraform: Terraform used the selected providers to generate the following execution
13:13:17.870 STDOUT terraform: plan. Resource actions are indicated with the following symbols:
13:13:17.870 STDOUT terraform:   + create
13:13:17.870 STDOUT terraform: Terraform will perform the following actions:
13:13:17.870 STDOUT terraform:   # aws_s3_bucket.bucket will be created
13:13:17.870 STDOUT terraform:   + resource "aws_s3_bucket" "bucket" {
13:13:17.870 STDOUT terraform:       + acceleration_status         = (known after apply)
13:13:17.870 STDOUT terraform:       + acl                         = (known after apply)
13:13:17.870 STDOUT terraform:       + arn                         = (known after apply)
13:13:17.870 STDOUT terraform:       + bucket                      = "my-bucket"
13:13:17.870 STDOUT terraform:       + bucket_domain_name          = (known after apply)
13:13:17.870 STDOUT terraform:       + bucket_prefix               = (known after apply)
13:13:17.870 STDOUT terraform:       + bucket_regional_domain_name = (known after apply)
13:13:17.870 STDOUT terraform:       + force_destroy               = false
13:13:17.870 STDOUT terraform:       + hosted_zone_id              = (known after apply)
13:13:17.870 STDOUT terraform:       + id                          = (known after apply)
13:13:17.870 STDOUT terraform:       + object_lock_enabled         = (known after apply)
13:13:17.870 STDOUT terraform:       + policy                      = (known after apply)
13:13:17.870 STDOUT terraform:       + region                      = (known after apply)
13:13:17.870 STDOUT terraform:       + request_payer               = (known after apply)
13:13:17.870 STDOUT terraform:       + tags_all                    = {
13:13:17.870 STDOUT terraform:           + "email"          = "FILL_THIS_IN"
13:13:17.870 STDOUT terraform:           + "product"        = "terraforms"
13:13:17.870 STDOUT terraform:           + "provisioned_by" = "terraform"
13:13:17.870 STDOUT terraform:           + "service"        = "foo"
13:13:17.870 STDOUT terraform:           + "terraform_path" = "foo"
13:13:17.870 STDOUT terraform:         }
13:13:17.870 STDOUT terraform:       + website_domain              = (known after apply)
13:13:17.870 STDOUT terraform:       + website_endpoint            = (known after apply)
13:13:17.870 STDOUT terraform:       + cors_rule (known after apply)
13:13:17.870 STDOUT terraform:       + grant (known after apply)
13:13:17.870 STDOUT terraform:       + lifecycle_rule (known after apply)
13:13:17.870 STDOUT terraform:       + logging (known after apply)
13:13:17.870 STDOUT terraform:       + object_lock_configuration (known after apply)
13:13:17.870 STDOUT terraform:       + replication_configuration (known after apply)
13:13:17.870 STDOUT terraform:       + server_side_encryption_configuration (known after apply)
13:13:17.870 STDOUT terraform:       + versioning (known after apply)
13:13:17.870 STDOUT terraform:       + website (known after apply)
13:13:17.870 STDOUT terraform:     }
13:13:17.870 STDOUT terraform: Plan: 1 to add, 0 to change, 0 to destroy.
13:13:17.870 STDOUT terraform: 
13:13:17.870 STDOUT terraform: 
13:13:17.870 STDOUT terraform: ─────────────────────────────────────────────────────────────────────────────
13:13:17.870 STDOUT terraform: Note: You didn't use the -out option to save this plan, so Terraform can't
13:13:17.870 STDOUT terraform: guarantee to take exactly these actions if you run "terraform apply" now.
```

## Expected behavior

```
terragrunt version v0.66.9
❯ \terragrunt plan
data.terraform_remote_state.infrastructure_network: Reading...
data.terraform_remote_state.infrastructure_network: Read complete after 2s

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_s3_bucket.bucket will be created
  + resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "my-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_prefix               = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = {
          + "email"          = "FILL_THIS_IN"
          + "product"        = "terraforms"
          + "provisioned_by" = "terraform"
          + "service"        = "foo"
          + "terraform_path" = "foo"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + cors_rule (known after apply)

      + grant (known after apply)

      + lifecycle_rule (known after apply)

      + logging (known after apply)

      + object_lock_configuration (known after apply)

      + replication_configuration (known after apply)

      + server_side_encryption_configuration (known after apply)

      + versioning (known after apply)

      + website (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v0.67.0
- OpenTofu/Terraform version: 1.9.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): ubuntu 22.04

## Additional context

In order to get things back to how they were, it seems one is forced to use `--terragrunt-log-level error --terragrunt-forward-tf-stdout `. Is that what we are supposed to do? One should have to opt-in to the new STDOUT format rather than being forced to opt-out to maintain the status quo.

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Without the `--terragrunt-forward-tf-stdout` flag, **STDOUT** level log entries were sent to `stdout`. They mixed with the JSON output, causing parsing issues in the user's workflow.

Modifying [terraform/log.go](https://github.com/gruntwork-io/terragrunt/pull/3409/files#diff-cca62ade57f96ca077da41742f057c9b69a1888d2c627c99bded0f63faf91ac7) file does not relate to this issue, just a small code refactoring.

Fixes #3367.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### CODE REVIEW

File: terraform/log.go [hunk 1]
```diff
@@ -22,41 +25,51 @@ var (
 	tfLogTimeLevelMsgReg = regexp.MustCompile(`(?i)(^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}\S*)\s*\[(trace|debug|warn|info|error)\]\s*(.+\S)$`)
 )
 
-func ParseLogFunc(msgPrefix string) writer.WriterParseFunc {
+// ParseLogFunc wrappes `PraerLog` to add msg prefix and bypasses the the parse erorr if `returnError` is false,
```
Comment (yhakbar) [inline terraform/log.go:28]:
```suggestion
// ParseLogFunc wraps `ParseLog` to add msg prefix and bypasses the the parse erorr if `returnError` is false,
```

Comment (levkohimins) [reply terraform/log.go]: Thanks

**Review by yhakbar — APPROVED** [review]
