### PR TITLE
fix bug where strict validation wasn't always respected

### LINKED ISSUE #1793: terragrunt-strict-validate option is not working as expected
terragrunt version v0.31.6

When running [validate-inputs](https://terragrunt.gruntwork.io/docs/reference/cli-options/#validate-inputs) with the strict validate flag, it does not error on unused inputs like it claims it should. Only warnings. Running in debug mode shows that it is not enabling strict checking.

```shell
$ terragrunt validate-inputs --terragrunt-strict-validate
WARN[0000] The following inputs passed in by terragrunt are unused:  prefix=[/host_home/Projects/infra] 
WARN[0000] 	- foo                                        prefix=[/host_home/Projects/infra] 
WARN[0000]                                               prefix=[/host_home/Projects/infra] 
INFO[0000] All required inputs are passed in by terragrunt  prefix=[/host_home/Projects/infra] 
WARN[0000] Terragrunt configuration has misaligned inputs, but running in relaxed mode so ignoring.  prefix=[/host_home/Projects/infra] 


$ terragrunt validate-inputs --terragrunt-strict-validate --terragrunt-log-level debug
DEBU[0000] Found locals block: evaluating the expressions. 
DEBU[0000] Evaluated 5 locals (remaining 0): aws_region, aws_profile, aws_acct_name, aws_acct_id, env_name 
DEBU[0000] Running command: terraform --version          prefix=[/host_home/Projects/infra] 
DEBU[0000] Terraform version: 1.0.5                     
DEBU[0000] Reading Terragrunt config file at /host_home/Projects/infra/terragrunt.hcl 
DEBU[0000] Found locals block: evaluating the expressions. 
DEBU[0000] Evaluated 5 locals (remaining 0): aws_acct_id, env_name, aws_region, aws_profile, aws_acct_name 
DEBU[0000] Downloading Terraform configurations from file:///host_home/Projects/infra/terraform into /host_home/Projects/infra/.terragrunt-cache/7U3u4b5Qruzi8IXcDWJKVhY1rpU/L76ZjGDuhKIWoP-Ukd4lmxYLxz8 
DEBU[0000] Copying files from /host_home/Projects/infra into /host_home/Projects/infra/.terragrunt-cache/7U3u4b5Qruzi8IXcDWJKVhY1rpU/L76ZjGDuhKIWoP-Ukd4lmxYLxz8 
DEBU[0000] Setting working directory to /host_home/infra/.terragrunt-cache/7U3u4b5Qruzi8IXcDWJKVhY1rpU/L76ZjGDuhKIWoP-Ukd4lmxYLxz8 
WARN[0000] The following inputs passed in by terragrunt are unused:  prefix=[/host_home/Projects/infra] 
WARN[0000] 	- foo                                        prefix=[/host_home/Projects/infra] 
WARN[0000]                                               prefix=[/host_home/Projects/infra] 
INFO[0000] All required inputs are passed in by terragrunt  prefix=[/host_home/Projects/infra] 
DEBU[0000] Strict mode enabled: false                    prefix=[/host_home/Projects/infra] 
WARN[0000] Terragrunt configuration has misaligned inputs, but running in relaxed mode so ignoring.  prefix=[/host_home/Projects/infra] 

$ echo $?
0
```

### PR DESCRIPTION
**Pull request by raidancampbell**
Rough flow of the affected bug
1. [if the configuration has a source directive specified](https://github.com/raidancampbell/terragrunt/blob/aa552aa8eaf3a2d2ae20a2898f92ecd1a1bc0967/cli/cli_app.go#L441-L441)
2. [then a new configuration is created](http://github.com/raidancampbell/terragrunt/blob/aa552aa8eaf3a2d2ae20a2898f92ecd1a1bc0967/cli/cli_app.go#L446-L446)
3. [this new configuration is a clone of the previous](http://github.com/raidancampbell/terragrunt/blob/aa552aa8eaf3a2d2ae20a2898f92ecd1a1bc0967/cli/download_source.go#L51-L51)
4. [which changes a few key fields, while mostly copying over the others](http://github.com/raidancampbell/terragrunt/blob/aa552aa8eaf3a2d2ae20a2898f92ecd1a1bc0967/options/options.go#L324-L324)
5. The affected flag was accidentally omitted from this function when the flag was created.

This resolves #1793

### CODE REVIEW

File: options/options.go [hunk 1]
```diff
@@ -324,6 +324,7 @@ func (terragruntOptions *TerragruntOptions) Clone(terragruntConfigPath string) *
 		WorkingDir:                   workingDir,
 		Logger:                       util.CreateLogEntryWithWriter(terragruntOptions.ErrWriter, workingDir, terragruntOptions.LogLevel, terragruntOptions.Logger.Logger.Hooks),
 		LogLevel:                     terragruntOptions.LogLevel,
+		ValidateStrict:               terragruntOptions.ValidateStrict,
```
Comment (denis256) [inline options/options.go:327]: I think will be helpful to have a unit test to keep track that in future required fields are copied

Comment (raidancampbell) [reply options/options.go:327]: I agree, but now the same problem is moved to a different place: if someone adds a new field to the struct and forgets to add it to the new unit test, then it doesn't help and may still be forgotten in `Clone`.  The only guarantee I can see here is some cleverness with the `reflect` package, which I'm not super keen on.

I'm assuming the unit test would be a simple "make a struct, call clone, modify the original, then assert that the clone has the original's old contents." Did you have something else in mind?

Comment (denis256) [reply options/options.go:327]: I was thinking that may be implemented some kind of integration test, to verify if will fail `validate-inputs` execution 

More examples in:
https://github.com/gruntwork-io/terragrunt/blob/master/test/integration_test.go

**Comment by denis256** [comment]
Fail test `TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs` in sequential runs

```
=== CONT  TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs
    integration_test.go:3243: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] Full contents of stdout:
    integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] 
    integration_test.go:3243: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] Full contents of stderr:
    integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:21Z level=debug msg=Did not find any locals block: skipping evaluation.
    integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:21Z level=debug msg=Running command: terraform --version prefix=[fixture-validate-inputs/fail-unused-inputs] 
    integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:40Z level=debug msg=Terraform version: 1.1.4
    integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:40Z level=debug msg=Reading Terragrunt config file at fixture-validate-inputs/fail-unused-inputs/terragrunt.hcl
    integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:40Z level=debug msg=Did not find any locals block: skipping evaluation.
    integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:40Z level=debug msg=Downloading Terraform configurations from git::https://github.com/gruntwork-io/terragrunt.git?ref=v0.9.9 into /home/circleci/project/test/fixture-validate-inputs/fail-unused-inputs/.terragrunt-cache/-yMkQdn1hTcblL7xI42i8k6U9Ws/p_piCTTWVab2Hmnj1OtnAruj8J4
    integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] 
    integration_debug_test.go:281: 
        	Error Trace:	integration_debug_test.go:281
        	            				integration_debug_test.go:161
        	Error:      	Received unexpected error:
        	            	1 error occurred:
        	            		* error downloading 'https://github.com/gruntwork-io/terragrunt.git?ref=v0.9.9': /usr/bin/git exited with 1: error: pathspec 'master' did not match any file(s) known to git
        	            	
        	            	
        	Test:       	TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs
--- FAIL: TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs (19.58s)

```

**Comment by raidancampbell** [comment]
> Fail test `TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs` in sequential runs
> 
> ```
> === CONT  TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs
>     integration_test.go:3243: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] Full contents of stdout:
>     integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] 
>     integration_test.go:3243: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] Full contents of stderr:
>     integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:21Z level=debug msg=Did not find any locals block: skipping evaluation.
>     integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:21Z level=debug msg=Running command: terraform --version prefix=[fixture-validate-inputs/fail-unused-inputs] 
>     integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:40Z level=debug msg=Terraform version: 1.1.4
>     integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:40Z level=debug msg=Reading Terragrunt config file at fixture-validate-inputs/fail-unused-inputs/terragrunt.hcl
>     integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:40Z level=debug msg=Did not find any locals block: skipping evaluation.
>     integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] time=2022-04-20T17:37:40Z level=debug msg=Downloading Terraform configurations from git::https://github.com/gruntwork-io/terragrunt.git?ref=v0.9.9 into /home/circleci/project/test/fixture-validate-inputs/fail-unused-inputs/.terragrunt-cache/-yMkQdn1hTcblL7xI42i8k6U9Ws/p_piCTTWVab2Hmnj1OtnAruj8J4
>     integration_test.go:3246: [TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs] 
>     integration_debug_test.go:281: 
>         	Error Trace:	integration_debug_test.go:281
>         	            				integration_debug_test.go:161
>         	Error:      	Received unexpected error:
>         	            	1 error occurred:
>         	            		* error downloading 'https://github.com/gruntwork-io/terragrunt.git?ref=v0.9.9': /usr/bin/git exited with 1: error: pathspec 'master' did not match any file(s) known to git
>         	            	
>         	            	
>         	Test:       	TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs
> --- FAIL: TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs (19.58s)
> ```

I'm stumped.

 - I can't replicate this locally
 - I don't have permissions to view the CircleCI output, so I can't try out fixes to and see if they fix the CI build
 - The same `terraform` block directive added in 6d37d8c87154ecd8a36979d7e0c8fd8943500ffc exists in many places throughout the tests

As far as I can tell, it looks like terragrunt is invoking `go-getter` to grab the `source` field.  Internally, `go-getter` is parsing `git::https://github.com/gruntwork-io/terragrunt.git?ref=v0.9.9`, which is then yielding the error.  I'm no git wizard, but it feels like there's some state for pulling that repository which is not fully initialized or otherwise in the wrong state.

Looking around, I _did_ find a difference with some other tests containing references to fixtures with `source` directives.  52598ebed1733f6aa55da5f513b74ef862e75889 brings this test in line with those by cleaning up any potential local state: it continues to work for me locally before and after this change though.  If this doesn't do the trick, I'm afraid I'm going to need a bit of help diagnosing the test

**Comment by rhoboat** [comment]
Hm... `v0.9.9` is fishy. 🐠 *Looking...*

File: test/fixture-validate-inputs/fail-unused-inputs/terragrunt.hcl [hunk 2]
```diff
@@ -2,3 +2,8 @@ inputs = {
   input = "hello world"
   unused_input = "I am unused"
 }
+
+# the existence of a `source` directive manifests the bug in https://github.com/gruntwork-io/terragrunt/issues/1793
+terraform {
+  source = "github.com/gruntwork-io/terragrunt.git//test/fixture-download/hello-world?ref=v0.9.9"
```
Comment (rhoboat) [inline test/fixture-validate-inputs/fail-unused-inputs/terragrunt.hcl:8]: AH, so this is supposed to be an invalid `ref`?

**Comment by denis256** [comment]
Hi,
adding of `terraform { source = ...` to `test/fixture-validate-inputs/fail-unused-inputs` will make terragrunt to clone remote repository during tests execution, and `fail-unused-inputs` is used in 2 tests, which during tests run on clean environment(without `.terragrunt-cache`) may lead to parallel `git clone` in the same directory which ends with error...

Steps to verify:

```
cd test
# clean cached clone if exist
rm -rf fixture-validate-inputs/fail-unused-inputs/.terragrunt-cache/

# Run parallel tests that use same directory
go test  -parallel 2   -run "^TestTerragruntValidateInputsWithStrictModeDisabledAndUnusedInputs|TestTerragruntValidateInputsWithStrictModeEnabledAndUnusedInputs$"


```

To avoid such collisions can be used `copyEnvironment / EvalSymlinks` to copy fixture directory into temporary location and run tests there:
```
t.Parallel()
tmpPath, _ := filepath.EvalSymlinks(copyEnvironment(t, "fixture-validate-inputs"))
moduleDir := filepath.Join(tmpPath, "fixture-validate-inputs", "fail-unused-inputs")

```

**Comment by raidancampbell** [comment]
Nice catch, and thanks for the reproducing instructions!  64679f50ab313a70517ac806c062268712baa860 implements your suggested solution and has been tested locally to confirm it fixes the problem

**Review by denis256 — APPROVED** [review]
:+1:
