### PR TITLE
fix: Addressing panic in `read_terragrunt_config()`

### LINKED ISSUE #5949: read_terragrunt_config in locals block panics with nil pointer dereference in v1.0.1
## Description

After upgrading from terragrunt v0.91.5 to v1.0.1, `read_terragrunt_config()` called inside a `locals` block causes a nil pointer dereference panic during the discovery/relationship phase. This worked correctly in v0.91.5.

### Minimal config pattern

Each stack's `terragrunt.hcl` includes an env-specific config via an environment variable:

```hcl
include "root" {
  path = find_in_parent_folders(get_env("ENVIRONMENT_HCL"))
}

locals {
  env_vars = read_terragrunt_config(find_in_parent_folders(get_env("ENVIRONMENT_HCL")))
}
```

The `ENVIRONMENT_HCL` env var is set before invocation (e.g., `export ENVIRONMENT_HCL=staging-env.hcl`) and points to a valid HCL file in a parent directory.

### Command

```bash
export ENVIRONMENT_HCL=staging-env.hcl
terragrunt run -all plan
```

### Impact

This pattern is used across ~36 stacks. All of them panic immediately — no stacks can be planned.

## Error output

```
ERROR  Error: Error in function call
ERROR    on envs/example-stack/terragrunt.hcl line 15, in locals:
ERROR    15:   env_vars = read_terragrunt_config(find_in_parent_folders(get_env("ENVIRONMENT_HCL")))
ERROR  Call to function "read_terragrunt_config" failed: panic in function implementation:
       runtime error: invalid memory address or nil pointer dereference

goroutine 32 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x64
github.com/zclconf/go-cty/cty/function.errorForPanic(...)
	github.com/zclconf/go-cty@v1.18.0/cty/function/error.go:44
github.com/zclconf/go-cty/cty/function.Function.Call.func2()
	github.com/zclconf/go-cty@v1.18.0/cty/function/function.go:349 +0x84
github.com/gruntwork-io/terragrunt/pkg/config.PartialParseConfig(...)
	github.com/gruntwork-io/terragrunt/pkg/config/config_partial.go:609 +0xacc
github.com/gruntwork-io/terragrunt/pkg/config.TerragruntConfigFromPartialConfig(...)
	github.com/gruntwork-io/terragrunt/pkg/config/config_partial.go:340 +0x31c
github.com/gruntwork-io/terragrunt/pkg/config.setIAMRole(...)
	github.com/gruntwork-io/terragrunt/pkg/config/config.go:1569 +0x200
github.com/gruntwork-io/terragrunt/pkg/config.ParseConfig(...)
	github.com/gruntwork-io/terragrunt/pkg/config/config.go:1309 +0xb8
github.com/gruntwork-io/terragrunt/pkg/config.ParseTerragruntConfig(...)
	github.com/gruntwork-io/terragrunt/pkg/config/config_helpers.go:1072 +0x278
github.com/gruntwork-io/terragrunt/internal/discovery.parseComponent(...)
	github.com/gruntwork-io/terragrunt/internal/discovery/phase_parse.go:266 +0x698
github.com/gruntwork-io/terragrunt/internal/discovery.(*RelationshipPhase).discoverRelationships(...)
	github.com/gruntwork-io/terragrunt/internal/discovery/phase_relationship.go:157 +0xec
```

## Environment

- **Terragrunt version:** v1.0.1
- **Terraform version:** 1.14
- **OS:** macOS (Darwin) and Linux (GitHub Actions runner)
- **Worked on:** v0.91.5

## Notes

- v1.0.2 fixes a related nil pointer panic in `get_repo_root()` but it's unclear if that fix also covers this code path (haven't tested yet)
- The crash originates in the new discovery/relationship phase (`internal/discovery/phase_parse.go` → `PartialParseConfig`) which appears to be new in 1.0
- The `ENVIRONMENT_HCL` env var is confirmed set — the same config works perfectly on v0.91.5

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #5949.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed a crash when `include` and `locals` blocks with `read_terragrunt_config()` were combined during configuration discovery. The parser now properly surfaces underlying configuration errors instead of displaying misleading error messages.

### CODE REVIEW

File: pkg/config/config_partial_test.go [hunk 1]
```diff
@@ -143,6 +143,166 @@ func TestPartialParseDoesNotResolveIgnoredBlockEvenInParent(t *testing.T) {
...
+
+			childPath := filepath.Join(childDir, config.DefaultTerragruntConfigPath)
+			require.NoError(t, os.WriteFile(childPath, []byte(childHCL), 0644))
+
+			l := logger.CreateLogger()
+
+			ctx, pctx := newTestParsingContext(t, childPath)
+			pctx = pctx.WithDecodeList(config.TerragruntFlags)
+
+			require.NotPanics(t, func() {
```
Comment (denis256) [inline pkg/config/config_partial_test.go:299]: Check for  "no panic", but no check that any error is returned or partial populated config.

**Review by denis256 — APPROVED** [review]
