### PR TITLE
fix: Use env vars for `sops_decrypt_file`

### LINKED ISSUE #3438: `sops_decrypt_file` doesn't use dynamic authentication
## Describe the bug

The `sops_decrypt_file` function doesn't utilize the values returned when using [terragrunt-auth-provider-cmd](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-auth-provider-cmd) to authenticate with backends like AWS KMS.

## Steps To Reproduce

Assume a role in AWS that has permission to a KMS key, use that KMS key to encrypt a yml file with sops, like this:

```bash
$ cat secrets.unencrypted
values:
    something: foo

$ SOPS_KMS_ARN='arn for a kms key' sops encrypt secrets.yml.unencrypted > secrets.yml
```

Then attempt to perform a plan on a `terragrunt.hcl` file like this:

```hcl
generate "main" {
  path      = "main.tf"
  if_exists = "overwrite"
  contents  = <<EOF
EOF
}

locals {
  secret_vars = yamldecode(sops_decrypt_file("secrets.yml"))
  test_vars   = run_cmd("echo", local.secret_vars.values.something)
}
```

Using a command like this:

```bash
terragrunt plan --terragrunt-auth-provider-cmd 'cat auth.json'
```

Where `auth.json` is credentials for AWS in [this format](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-auth-provider-cmd).

## Expected behavior

The credentials should be made available by `auth-provider-cmd` so that users can transparently use `sops_decrypt_file` to access secret values.

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: 0.67.13
- OpenTofu version: v1.7.1
- Environment details (Ubuntu 20.04, Windows 10, etc.): MacOS 14.6.1

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #3438.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Updated `sops_decrypt_file` to use environment variables that might have been set by `terragrunt-auth-provider-cmd`.

### CODE REVIEW

File: test/integration_sops_test.go [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+	cleanupTerraformFolder(t, testFixtureSops)
+	tmpEnvPath := copyEnvironment(t, testFixtureSops)
+	rootPath := util.JoinPath(tmpEnvPath, testFixtureSops)
+
+	runTerragrunt(t, "terragrunt apply -auto-approve --terragrunt-non-interactive --terragrunt-working-dir "+rootPath)
+
+	stdout := bytes.Buffer{}
+	stderr := bytes.Buffer{}
+
+	err := runTerragruntCommand(t, "terragrunt output -no-color -json --terragrunt-non-interactive --terragrunt-working-dir "+rootPath, &stdout, &stderr)
```
Comment (denis256) [inline test/integration_sops_test.go:31]: It can be complicated to debug since the output is not printed, can be used `runTerragruntCommandWithOutput()` which will return output and print

**Review by denis256 — APPROVED** [review]
