### PR TITLE
fix: Correct displaying deprecated flag warnings

### LINKED ISSUE #3872: Incorrect suggestion for deprecation warning `--terragrunt-no-auto-init` ==> `--no-auto-init=false` in v0.73.0
## Describe the bug

v0.73.0 is warning about the deprecation of `--terragrunt-no-auto-init`, which is fine, but is suggesting to replace it with `--no-auto-init=false`. That seems inverted... Should probably just be `--no-auto-init`.

```
17:32:39.959 WARN   The `--terragrunt-no-auto-init` flag is deprecated and will be removed in a future version. Use `--no-auto-init=false` instead.
```

### LINKED ISSUE #3878: Incorrect suggestion for deprecation warning --terragrunt-forward-tf-stdout
## Describe the bug

Running `terragrunt --terragrunt-forward-tf-stdout` gives
```
The `--terragrunt-forward-tf-stdout` global flag is moved to `run` command and will be removed from the global flags in a future version. Use `--run --tf-forward-stdout` instead.
The `--terragrunt-forward-tf-stdout` flag is deprecated and will be removed in a future version. Use `--tf-forward-stdout` instead.
```

The suggestion `--run --tf-forward-stdout` is incorrect. It should be `run --tf-forward-stdout`.

## Versions

- Terragrunt version: `0.73.1`

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Fixes #3878.
Fixes #3872.

Got rid of similar warning messages for moved global flags:
```
WARN The `--terragrunt-no-auto-init` global flag is moved to `run` command and will be removed from the global flags in a future version. Use `--run --no-auto-init=false` instead.
WARN The `--terragrunt-no-auto-init` flag is deprecated and will be removed in a future version. Use `--no-auto-init=false` instead.
WARN The `--terragrunt-forward-tf-stdout` global flag is moved to `run` command and will be removed from the global flags in a future version. Use `--run --tf-forward-stdout` instead.
WARN The `--terragrunt-forward-tf-stdout` flag is deprecated and will be removed in a future version. Use `--tf-forward-stdout` instead.
```

Reduced to:
```
WARN The `--terragrunt-no-auto-init` global flag is moved to `run` command and will be removed from the global flags in a future version. Use `--run --no-auto-init=false` instead.
WARN The `--terragrunt-forward-tf-stdout` global flag is moved to `run` command and will be removed from the global flags in a future version. Use `--run --tf-forward-stdout` instead.
```

## Summary by CodeRabbit

- **New Features**
  - Enhanced help and version commands for clearer guidance.
  - Introduced several additional run command flags to improve CLI functionality.

- **Refactor**
  - Streamlined command categorization and flag handling for a more intuitive user experience.
  - Improved handling for negative boolean and deprecated flags.
  - Migrated from experimental libraries to standard solutions for consistency.
  - Simplified logging level configuration by directly parsing environment variables.

- **Tests**
  - Expanded test coverage to ensure robustness of flag evaluations and deprecated flag warnings.

### CODE REVIEW

**Comment by levkohimins** [comment]
I switched to draft because I remembered I still needed to make a few small improvements.

File: cli/flags/flag_opts.go [hunk 1]
```diff
@@ -3,17 +3,27 @@ package flags
...
 
+// WithDeprecatedMovedFlag returns an `Option` that will register the given `deprecatedFlag`
+// as a deprecated flag that is moved to the given `commandName`. For example:
+//
+//	NewFlag(nil, WithDeprecatedMovedFlag(&cli.BoolFlag{
+//	  Name:    "no-auto-init",
+//	}, "run", nil))
+//
+// Log output:
+// WARN The `--no-auto-init` global flag is moved to `run` command and will be removed from the global flags in a future version. Use `run --no-auto-init` instead.
```
Comment (yhakbar) [inline cli/flags/flag_opts.go:24]:
```suggestion
// WARN The global `--no-auto-init` flag has moved to the `run` command and will not be accessible as a global flag in a future version of Terragrunt. Use `run --no-auto-init` instead.
```

Make sure to update the actual warning too.

File: cli/flags/global/flags.go [hunk 2]
```diff
@@ -66,6 +70,41 @@ const (
 	DeprecatedTfLogJSONFlagName            = "tf-logs-to-json"
 )
 
+// NewFlagsWithDeprecatedMovedFlags returns global flags along with flags that have been moved to other commands and hidden from CLI help.
+func NewFlagsWithDeprecatedMovedFlags(opts *options.TerragruntOptions) cli.Flags {
+	globalFlags := NewFlags(opts, nil)
+
+	// Since the flags we take from the command may already have deprecated flags,
+	// and each time we call `commands.New` we define them again (deprecated flags),
```
Comment (yhakbar) [inline cli/flags/global/flags.go:78]:
```suggestion
	// and we redefine them each time we call `commands.New`,
```

File: cli/flags/global/flags.go [hunk 3]
```diff
@@ -66,6 +70,41 @@ const (
...
+	// we need to clear `Strict Controls` to avoid them being displayed and causing duplicate warnings, for example, log output:
+	//
+	// WARN The `--terragrunt-no-auto-init` global flag is moved to `run` command and will be removed from the global flags in a future version. Use `--run --no-auto-init=false` instead.
```
Comment (yhakbar) [inline cli/flags/global/flags.go:81]: See my note above about updating this text.

File: cli/flags/global/flags.go [hunk 4]
```diff
@@ -66,6 +70,41 @@ const (
...
+	// WARN The `--terragrunt-no-auto-init` flag is deprecated and will be removed in a future version. Use `--no-auto-init=false` instead.
```
Comment (yhakbar) [inline cli/flags/global/flags.go:82]:
```suggestion
	// WARN The `--terragrunt-no-auto-init` flag is deprecated and will be removed in a future version of Terragrunt. Use `--no-auto-init` instead.
```

Note the second part of the change: users should set the value to `--no-auto-init`, not `--no-auto-init=false`. Even if it works, it's a double-negative and that's confusing.

File: internal/cli/bool_flag.go [hunk 5]
```diff
@@ -31,7 +31,8 @@ type BoolFlag struct {
 	// Destination ia a pointer to which the value of the flag or env var is assigned.
 	// It also uses as the default value displayed in the help.
 	Destination *bool
-	// If set to true, then the assigned flag value will be inverted
+	// If set to true, then the assigned flag value will be inverted.
+	// Example: With `Negative: true`, --flag=true becomes false, and --flag=false becomes true.
```
Comment (yhakbar) [inline internal/cli/bool_flag.go:35]:
```suggestion
	// Example: With `Negative: true`, `--boolean-flag` sets the value to `false`, and `--boolean-flag=false` sets the value to `true`.
```

I think this explains the behavior more clearly, as it's why we'd use it.

File: internal/strict/controls/deprecated_flag_name.go [hunk 6]
```diff
@@ -40,8 +41,8 @@ func NewDeprecatedMovedFlagName(deprecatedFlag, newFlag cli.Flag, commandName st
 			Name:        deprecatedName,
 			Description: "replaced with: " + newName,
 		},
-		ErrorFmt:       "The `--%s` global flag is no longer supported. Use `--%s` instead.",
-		WarningFmt:     "The `--%s` global flag is moved to `" + commandName + "` command and will be removed from the global flags in a future version. Use `--%s` instead.",
+		ErrorFmt:       "The `--%s` global flag is no longer supported. Use `%s` instead.",
+		WarningFmt:     "The `--%s` global flag is moved to `" + commandName + "` command and will be removed from the global flags in a future version. Use `%s` instead.",
```
Comment (yhakbar) [inline internal/strict/controls/deprecated_flag_name.go:45]:
```suggestion
		WarningFmt:     "The `--%s` global flag has moved to the `" + commandName + "` command and will be removed from global flags in a future version of Terragrunt. Use `%s` instead.",
```

These initially confused me. It would help to add a comment above this that the second placeholder has both the command and the flag, and that's why it doesn't have the dashes.

**Review by yhakbar — APPROVED** [review]
We need to update some of the language for warnings/errors.

Please make sure we update those before releasing if you merge this without updating them.

File: cli/flags/global/flags.go (hunk 4 above)
Comment (levkohimins) [reply cli/flags/global/flags.go:82]: Regarding `=false`, yes I fixed it in this PR. I just took this log when running on the main branch. 

Regarding ` of Terragrunt`, We need to change it [here](https://github.com/gruntwork-io/terragrunt/blob/6bf5e1ce7617a758383d6fb99fc63d3f56864bf1/internal/strict/controls/deprecated_flag_name.go#L43-L44) first.

File: cli/flags/flag.go [hunk 7]
```diff
@@ -34,36 +34,41 @@ func NewMovedFlag(deprecatedFlag cli.Flag, newCommandName string, regControlsFn
 }
 
 // TakesValue implements `cli.Flag` interface.
-func (new *Flag) TakesValue() bool {
-	if new.Flag.Value() == nil {
+// It returns `true` for all flags except boolean ones that are `false` or `true` inverted.
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply cli/flags/flag.go:37]: I specified `TakesValue` at the first line.

[the remark this answers is not in the document]
Comment (levkohimins) [reply cli/flags/flag.go:37]:
```
// TakesValue implements `github.com/urfave/cli.DocGenerationFlag` required to generate help.
// TakesValue returns `true` for all flags except boolean ones that are `false` or `true` inverted.
```

**Review by yhakbar — APPROVED** [review]
