### PR TITLE
fix: Fixing generation in stacks that read files

### LINKED ISSUE #5681: Git-based filter ignores changes in files loaded via read_terragrunt_config()
## Describe the bug
When using Git-based filter expressions with stacks, changes to files read from `terragrunt.stack.hcl` via `read_terragrunt_config() `should mark the stack as affected and result in runnable units being discovered for terragrunt` run --all`.

I have my terraform variables in a seperate file per unit and load them like so:

``` hcl
locals {
  core_infrastructure = read_terragrunt_config("core_infrastructure.hcl")
}

# and reference them in a unit like so
unit "core_infra" {
  source = "***//core_infrastructure"
  path   = "core_infrastructure"
  values = local.core_infrastructure.inputs
}
```
so changes in the core_infrastructure.hcl directly affects the unit.

but running:
```
terragrunt run --all --filter '[origin/main]' -- plan
```

I get:
`WARN   No units discovered. Creating an empty runner.`

when I run:
`git diff --name-status origin/main HEAD`

I do see changes
`core_infrastructure.hcl`

## Steps To Reproduce

The following reproduces the bug from a clean temporary repository.

1. Create a minimal terragrunt stack project but add a seperate .hcl file next to the `terragrunt.stack.hcl` file:
```
tg-stack-read-repro/
├── modules/
│   └── unit_1/
│       ├── main.tf
│       └── terragrunt.hcl
└── stacks/
    └── test_app/
        ├── terragrunt.stack.hcl
        └── unit_1.hcl
```

modules/unit_1/main.tf
``` hcl
output "example" {
  value = "ok"
}
```

modules/unit_1/terragrunt.hcl
``` hcl
# leave empty
```

stacks/test_app/terragrunt.stack.hcl
``` hcl
locals {
  unit_1 = read_terragrunt_config("unit_1.hcl")
}

unit "unit_1" {
  source = "${get_repo_root()}/modules/unit_1"
  path   = "unit_1"
  values = local.unit_1.inputs
}
```

stacks/test_app/unit_1.hcl
``` hcl
inputs = {
  example = "v1"
}
```

2. Commit the initial state:
``` bash
git init -b main
git add .
git commit -m "initial stack"
git update-ref refs/remotes/origin/main HEAD
```

3. Make changes to `unit_1.hcl` but not `terragrunt.stack.hcl` (setting the value to v2):

``` hcl
inputs = {
  example = "v2"
}
```

4. Commit those changes
``` bash
git add stacks/test_app/unit_1.hcl
git commit -m "change stack input sidecar"
```

5. filtering the changes

Here we see the file differs from HEAD
``` bash
git diff --name-status HEAD~1 HEAD
# returns
M	stacks/test_app/unit_1.hcl
```

but running the terragrunt command with a git-filter I get no runners:
``` bash
terragrunt run --all --filter '[HEAD~1...HEAD]' -- plan
# returns
WARN   No units discovered. Creating an empty runner.
```

## Expected behavior
when making changes in  stacks/test_app/unit_1.hcl I expect the git-filter to recognize this as a change, since a change in that file directly affects the unit. But somehow it only considers changes in the `terragrunt.stack.hcl` file.

`terragrunt run --all --filter '[origin/main] -- plan`

## Must haves

- [X] Steps for reproduction provided.

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v0.97.2
- Terraform version: 1.14.5
- Environment details: Ubuntu 24.04

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #5681.

I pushed for the original implementation of the fix to do less work to dodge an unnecessary walk, but we did end up needing to do extra work in the walk anyways. This updates the implementation so that we also generate stacks if they are reading a file and that file changes.

As part of this change, the classification status of `StatusDiscovered` was renamed to `StatusReadyForFilter`, as that better reflects why some things are marked with the status even though it's going to be filtered out during filter evaluation.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [ ] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [ ] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved handling of stack discovery when filters are active, ensuring correct exclusion precedence and proper tracking of affected stacks during parsing operations.
  * Enhanced worktree change processing to include stacks affected by reading filters, preventing incomplete stack discovery scenarios.

* **Tests**
  * Added comprehensive integration tests for stack filtering behavior, including exclusion precedence, filter interactions, and file dependency scenarios.

### CODE REVIEW

File: internal/discovery/phase_worktree.go [hunk 1]
```diff
@@ -227,15 +227,19 @@ func (p *WorktreePhase) discoverChangesInWorktreeStacks(
 
 	stackDiff := w.Stacks()
 
+	allChanged := make([]worktrees.StackDiffChangedPair, 0, len(stackDiff.Changed)+len(stackDiff.ReadingAffected))
+	allChanged = append(allChanged, stackDiff.Changed...)
+	allChanged = append(allChanged, stackDiff.ReadingAffected...)
+
 	g, ctx := errgroup.WithContext(ctx)
-	g.SetLimit(max(1, min(runtime.NumCPU(), len(stackDiff.Added)+len(stackDiff.Removed)+len(stackDiff.Changed)*2)))
+	g.SetLimit(max(1, min(runtime.NumCPU(), len(stackDiff.Added)+len(stackDiff.Removed)+len(allChanged)*2)))
```
Comment (thisguycodes) [inline internal/discovery/phase_worktree.go:235]: nit:
```suggestion
	g.SetLimit(
		max(
			1,
			min(
				runtime.GOMAXPROCS(0),
				len(stackDiff.Added)+len(stackDiff.Removed)+len(allChanged)*2,
			),
		),
	)
```

the re-formatting is subjective (I find this very dense and hard to count the parenthesis), but [GOMAXPROCS](https://pkg.go.dev/runtime#GOMAXPROCS) is going to be more correct, as `NumCPU()` returns the number of underlying CPUs on the system, but if we're in a container we likely have access to less than that.

File: internal/stacks/generate/generate.go [hunk 2]
```diff
@@ -339,75 +340,120 @@ func worktreeStacksToGenerate(
...
 	// we need to generate all the stacks in the given worktree, as units within the generated stack might be affected.
-	//
-	// Based on business logic, the from branch here should never be used, but we'll check it anyways for completeness.
-	// We only require parsing for reading filters, and those only trigger in expanded Git expressions when
-	// the file is modified (which would result in a toFilter being returned).
+	// We also identify which specific stacks are affected by reading filters so that the worktree discovery phase
+	// can walk them for unit-level changes.
+
+	g, ctx := errgroup.WithContext(ctx)
+	g.SetLimit(min(runtime.NumCPU(), max(1, len(w.WorktreePairs)*2))) //nolint:mnd
```
Comment (thisguycodes) [inline internal/stacks/generate/generate.go:361]:
```suggestion
	g.SetLimit(min(runtime.GOMAXPROCS(0), max(1, len(w.WorktreePairs)*2))) //nolint:mnd
```

sames as other comment: `NumCPU()` returns CPU of the underlying system, which may be wrong if we're in a container

File: internal/discovery/phase_worktree.go (hunk 1 above)
Comment (yhakbar) [reply internal/discovery/phase_worktree.go:235]: Good idea! Addressed here:
https://github.com/gruntwork-io/terragrunt/pull/5794
