### PR TITLE
Get rid of third party code

### LINKED ISSUE #3092: Flaky TestJsonHcl test
**Describe the bug**
Noticed that TestJsonHcl test sometimes fail
```
=== RUN   TestJsonHcl
    marshal_test.go:35: 
        	Error Trace:	/home/circleci/project/terraform/cliconfig/marshal_test.go:35
        	Error:      	Not equal: 
        	            	expected: "\n  parties = [\n    \"one\",\n    \"two\",\n    [\n      \"four\"\n    ],\n    {\n      six = 61\n    }\n  ]\n  name = \"peter\"\n"
        	            	actual  : "\n  name = \"peter\"\n  parties = [\n    \"one\",\n    \"two\",\n    [\n      \"four\"\n    ],\n    {\n      six = 61\n    }\n  ]\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,3 @@
        	            	 
        	            	+  name = "peter"
        	            	   parties = [
        	            	@@ -11,3 +12,2 @@
        	            	   ]
        	            	-  name = "peter"
        	            	 
        	Test:       	TestJsonHcl
--- FAIL: TestJsonHcl (0.00s)
```

**To Reproduce**
Run `TestJsonHcl`

**Expected behavior**
Pass each time `TestJsonHcl`

https://circleci.com/api/v1.1/project/github/gruntwork-io/terragrunt/25757/output/104/0?file=true&allocation-id=6627eb1e46dbea09204437c4-0-build%2FABCDEFGH

[unit-tests.txt](https://github.com/gruntwork-io/terragrunt/files/15080807/unit-tests.txt)

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Fixes #3092.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### CODE REVIEW

File: terraform/cliconfig/config.go [hunk 1]
```diff
@@ -68,14 +73,19 @@ func (cfg *Config) Save(configPath string) error {
...
-	newHCL, err := Marshal(cfg)
-	if err != nil {
-		return errors.WithStackTrace(err)
-	}
-	newHCL = append(rawHCL, newHCL...)
+	f := hclwrite.NewEmptyFile()
+
+	gohcl.EncodeIntoBody(cfg, f.Body())
+
+	// newHCL, err := Marshal(cfg)
```
Comment (denis256) [inline terraform/cliconfig/config.go:80]: Not sure if we need commented code here :thinking:

**Review by denis256 — DISMISSED** [review]

**Review by denis256 — APPROVED** [review]
