### PR TITLE
bug: discovery parsing errors handling

### LINKED ISSUE #4983: Unrecoverable parse error for ./terragrunt.hcl: Could not find Terragrunt configuration settings in ./terragrunt.hcl
It will be hard to provide a minimal repro case here. But this is a file that works with 0.90.0 (and many versions before), but fails with 0.91.1. Since the error seems specific to 0.91, and is some kind of low-level error, I hope you won't need an elaborate repro mockup.

Here is the error:

```
18:25:54.487 DEBUG  Evaluated 1 locals (remaining 0): s3_name_prefix
18:25:54.490 DEBUG  Exposing include block 'root'
18:25:54.490 DEBUG  Found locals block: evaluating the expressions.
18:25:54.490 DEBUG  Evaluated 2 locals (remaining 0): base_source_url, tags_stub
18:25:54.490 DEBUG  Exposing include block 'compcommon'
18:25:54.491 DEBUG  Unrecoverable parse error for ./terragrunt.hcl: Could not find Terragrunt configuration settings in ./terragrunt.hcl
18:25:54.491 WARN   Parsing errors where encountered while discovering dependencies. They were suppressed, and can be found in the debug logs.
18:25:54.491 DEBUG  Errors: %!w(*errors.joinError=&{[0x1400040ba40]})
18:25:54.491 DEBUG  Provider cache service shutting down...
18:25:54.491 DEBUG  Provider cache service shutdown complete
18:25:54.491 INFO   Shutting down Terragrunt Cache server...
18:25:54.491 INFO   Terragrunt Cache server stopped
18:25:54.491 ERROR  Could not find Terragrunt configuration settings in ./terragrunt.hcl
18:25:54.639 ERROR  Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

Here is the file:

[terragrunt.hcl.txt](https://github.com/user-attachments/files/22981702/terragrunt.hcl.txt)

In infrastructure-modules, the folder with the source code only has a very trivial "module" that doesn't really create anything, just has inputs and outputs.

[main.tf.txt](https://github.com/user-attachments/files/22981703/main.tf.txt)

root.hcl has the usual boilerplate code.

Let me know if you need anything else.

### PR DESCRIPTION
**Pull request by denis256**
## Description

* improved detection of legacy fields during HCL parsing
* discovery: skip include-only configs; cleaner suppressed-errors logging (no %w/%!w); fixes #4983
* runner pool: correct log formatting by calling Path(), simplified discovery -> runner pool structs conversion logic, removed duplicated functions
* tests: added regression tests for parsing errors

Before this fix:

image

After this fix:

image

Fixes #4983.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Deprecated configuration syntax now yields clear, early errors; unlabeled includes show a deprecation message.
  * Improved dependency discovery messaging and debug logging; include-only/no-settings parsing can be skipped when suppression is enabled.

* **New Features**
  * Run-all flows with generate/expose improved to avoid parsing/formatting artifacts; run-all can auto-approve when configured.
  * External-dependency prompting behavior refined for clearer prompts.

* **Tests**
  * Added fixtures and regression tests covering deprecated syntax, exposed includes, and run-all+generate scenarios.

### CODE REVIEW

File: internal/discovery/discovery.go [hunk 1]
```diff
@@ -514,6 +515,18 @@ func Parse(
 	//nolint: contextcheck
 	cfg, err = config.PartialParseConfigFile(parsingCtx, l, parseOpts.TerragruntConfigPath, nil)
 	if err != nil {
+		// Treat include-only/no-settings configs as non-fatal during discovery when suppression is enabled
+		if suppressParseErrors && containsNoSettingsError(err) {
+			l.Debugf("Skipping include-only config during discovery: %s", parseOpts.TerragruntConfigPath)
+
+			// Store an empty partial config to avoid nil dereferences in subsequent dependency discovery
```
Comment (yhakbar) [inline internal/discovery/discovery.go]: This is odd to me. Why don't we just nil check later?

**Review by yhakbar — APPROVED** [review]

**Comment by FlorinAndrei** [comment]
Awesome, thank you!

Is this going to be included in v0.93.4?
