### PR TITLE
Stacks: nested stack outputs

### LINKED ISSUE #4121: `stack output` doesn't work right on nested stacks
## Describe the bug

When using the `stack output` command on a `terragrunt.stack.hcl` file with nested stacks, the result does not appear in a format that is useful for accessing the values of nested stack outputs.

## Steps To Reproduce

Create a `terragrunt.stack.hcl` file with nested stacks, and attempt to access outputs from the nested stacks.

## Expected behavior

Nested output named after the stacks to the units.

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: latest
- OpenTofu/Terraform version: N/A
- Environment details (Ubuntu 20.04, Windows 10, etc.): macOS

## Additional context

I'll share offline.

### PR DESCRIPTION
**Pull request by denis256**
## Description

* Improved output fetching of outputs in nested stacks
* Added tests to track reading of nested outputs

stack-clean-stack

Fixes #4121.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

- **Refactor / Improvements**
  - Streamlined output handling in the CLI and stack commands for a consistent, hierarchical presentation across raw, formatted, and JSON views.
  - Enhanced processing of nested configuration data for clearer and more reliable display of complex values.
  - Improved error handling and output structure in the `StackOutput` function.

- **New Features**
  - Introduced new configuration templates demonstrating multi-stack and multi-unit setups.
  - Added Terraform module enhancements with dedicated input and output definitions for improved data mapping.
  - New test functions added to improve coverage for output formatting and stack commands.
  - Added a new function for retrieving string representations of output values, enhancing usability.
  - Added a new test for stack output commands using a raw format, improving testing of output behaviors.

### CODE REVIEW

File: config/config_as_cty.go [hunk 1]
```diff
@@ -840,6 +840,23 @@ func convertToCtyWithJSON(val any) (cty.Value, error) {
 // Converts arbitrary go type (struct that has cty tags, slice, map with string keys, string, bool, int
 // uint, float, cty.Value) to a cty Value
 func goTypeToCty(val any) (cty.Value, error) {
+	// Check if the value is a map
+	if m, ok := val.(map[string]interface{}); ok {
```
Comment (yhakbar) [inline config/config_as_cty.go:844]:
```suggestion
	if m, ok := val.(map[string]any); ok {
```

NIT: Prefer `any`

File: config/stack.go [hunk 2]
```diff
@@ -119,44 +119,77 @@ func GenerateStacks(ctx context.Context, opts *options.TerragruntOptions) error
...
-func StackOutput(ctx context.Context, opts *options.TerragruntOptions) (map[string]map[string]cty.Value, error) {
-	opts.Logger.Debugf("Generating output from %s", opts.TerragruntStackConfigPath)
-	opts.TerragruntStackConfigPath = filepath.Join(opts.WorkingDir, defaultStackFile)
-	stackTargetDir := filepath.Join(opts.WorkingDir, stackDir)
-	stackFiles, err := listStackFiles(opts, stackTargetDir)
+// StackOutput collects and returns the Terraform output values for all declared units in a stack hierarchy.
+//
+// This function is a central component of Terragrunt's stack output system, providing a mechanism to
+// aggregate and organize outputs from multiple deployments in a hierarchical structure. It's particularly
+// useful when working with complex infrastructure composed of multiple interconnected Terraform modules.
```
Comment (yhakbar) [inline config/stack.go:126]:
```suggestion
// useful when working with complex infrastructure composed of multiple interconnected Terragrunt units.
```

File: config/stack.go [hunk 3]
```diff
@@ -119,44 +119,77 @@ func GenerateStacks(ctx context.Context, opts *options.TerragruntOptions) error
...
+//
+// The function performs several key operations:
+//
+//  1. Discovers all stack definition files (terragrunt.stack.hcl) in the working directory and its subdirectories.
+//  2. For each stack file, parses the configuration and extracts the declared stacks and units.
+//  3. For each unit, reads its Terraform outputs from the corresponding .terragrunt-stack directory.
+//  4. Constructs a hierarchical map of outputs by organizing units according to their stack hierarchy.
```
Comment (yhakbar) [inline config/stack.go:133]:
```suggestion
//  4. Constructs a hierarchical map of outputs by organizing units according to their position in the stack hierarchy.
```

File: config/stack.go [hunk 4]
```diff
@@ -119,44 +119,77 @@ func GenerateStacks(ctx context.Context, opts *options.TerragruntOptions) error
...
+//
+// Errors can occur during stack file listing, value reading, stack config parsing, output reading,
+// or when converting the final output structure to cty.Value format.
+func StackOutput(ctx context.Context, opts *options.TerragruntOptions) (cty.Value, error) {
+	opts.Logger.Debugf("Generating output from %s", opts.WorkingDir)
 
+	foundFiles, err := listStackFiles(opts, opts.WorkingDir)
 	if err != nil {
-		return nil, errors.Errorf("Failed to list stack files in %s %v", stackTargetDir, err)
+		return cty.NilVal, errors.Errorf("Failed to list stack files in %s: %v", opts.WorkingDir, err)
```
Comment (yhakbar) [inline config/stack.go:160]:
```suggestion
		return cty.NilVal, errors.Errorf("Failed to list stack files in %s: %w", opts.WorkingDir, err)
```

NIT: Prefer `%w`

File: config/stack.go [hunk 5]
```diff
@@ -119,44 +119,77 @@ func GenerateStacks(ctx context.Context, opts *options.TerragruntOptions) error
...
 		if err != nil {
-			return nil, errors.New(err)
+			return cty.NilVal, errors.Errorf("Failed to read values from %s: %v", dir, err)
 		}
 
 		stackFile, err := ReadStackConfigFile(ctx, opts, path, values)
-
 		if err != nil {
-			return nil, errors.New(err)
+			return cty.NilVal, errors.Errorf("Failed to read stack file %s: %v", path, err)
```
Comment (yhakbar) [inline config/stack.go:180]:
```suggestion
			return cty.NilVal, errors.Errorf("Failed to read stack file %s: %w", path, err)
```
NIT: Prefer `%w`

File: config/stack.go [hunk 6]
```diff
@@ -166,20 +199,141 @@ func StackOutput(ctx context.Context, opts *options.TerragruntOptions) (map[stri
...
+//   - flat: A map where keys are dot-separated paths (e.g., "parent.child.unit") and values are
+//     maps of cty.Value representing the Terraform outputs for each unit
+//
+// Returns:
+//   - map[string]interface{}: A nested map structure reflecting the hierarchy implied by the dot notation
+//   - error: An error if conversion fails, particularly when building the nested structure
+//
+// Errors can occur during cty.Value conversion or when attempting to traverse the nested structure
+// if the path contains contradictory type information (e.g., a path segment is both a leaf and a branch).
+func nestUnitOutputs(flat map[string]map[string]cty.Value) (map[string]interface{}, error) {
```
Comment (yhakbar) [inline config/stack.go:305]:
```suggestion
func nestUnitOutputs(flat map[string]map[string]cty.Value) (map[string]any, error) {
```

NIT: Prefer `any`

File: config/stack.go [hunk 7]
```diff
@@ -166,20 +199,141 @@ func StackOutput(ctx context.Context, opts *options.TerragruntOptions) (map[stri
...
+			if i == len(parts)-1 {
+				ctyValue, err := convertValuesMapToCtyVal(value)
+				if err != nil {
+					return nil, errors.Errorf("Failed to convert unit output to cty value: %s %v", flatKey, err)
+				}
+
+				current[part] = ctyValue
+			} else {
+				if _, exists := current[part]; !exists { // Traverse or create next level
+					current[part] = make(map[string]interface{})
```
Comment (yhakbar) [inline config/stack.go:322]:
```suggestion
					current[part] = make(map[string]any)
```
NIT: Prefer `any`

File: config/stack.go [hunk 8]
```diff
@@ -166,20 +199,141 @@ func StackOutput(ctx context.Context, opts *options.TerragruntOptions) (map[stri
...
+				}
+
+				var ok bool
+
+				current, ok = current[part].(map[string]interface{})
```
Comment (yhakbar) [inline config/stack.go:327]:
```suggestion
				current, ok = current[part].(map[string]any)
```
NIT: Prefer `any`

**Review by yhakbar — APPROVED** [review]
