### PR TITLE
fix: handling of exclusions when reading outputs

### LINKED ISSUE #5864: Exclude Block Breaks Stack Output
## Describe the bug

We are using the [exclude](https://docs.terragrunt.com/reference/hcl/blocks/#exclude) block to only conditionally deploy a specific unit in our  stack. When running `terragrunt stack output --dependency-fetch-output-from-state` the command fails with the following error:

```
ERROR  operation error S3: GetObject, https response error StatusCode: 404, RequestID: SOMEID, HostID: SOMEID, NoSuchKey: The specified key does not exist.
```

We did add `output` to the `actions` array of the `exclude` block.
We did add `output` to the `mock_outputs_allowed_terraform_commands` array of any dependent units.

If we disable the `dependency-fetch-output-from-state` experiment, it works fine.

## Steps To Reproduce

1. Create the following project structure:
```
.
├── modules
│   └── conditional
│       └── main.tf
├── root.hcl
├── terragrunt.stack.hcl
└── units
    └── conditional
        └── terragrunt.hcl
```
2. Add file content:

<details>
  <summary>root.hcl</summary>

```hcl
remote_state {
  backend = "s3"

  config = {
    bucket = "<your-bucket-name>"

    encrypt      = true
    key          = "${path_relative_to_include()}/tofu.tfstate"
    region       = "eu-central-1"
    use_lockfile = true
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
```
</details>

<details>
  <summary>terragrunt.stack.hcl</summary>

```hcl
unit "conditional" {
  source = "./units/conditional"
  path   = "conditional"
}
```
</details>

<details>
  <summary>terragrunt.hcl</summary>

```hcl
exclude {
  if                   = true
  actions              = ["plan", "apply", "destroy", "output"]
  exclude_dependencies = true
}

include "root" {
  path           = find_in_parent_folders("root.hcl")
  merge_strategy = "deep"
}

terraform {
  source = "${dirname(find_in_parent_folders("root.hcl"))}//modules/conditional"
}
```
</details>

3. Add valid S3 bucket to `root.hcl`
4. Execute `terragrunt stack run init`
5. Execute `terragrunt stack output --dependency-fetch-output-from-state`
6. Execute `terragrunt stack output --no-dependency-fetch-output-from-state`
7. See difference

## Expected behavior

Both output commands should return
```shell
conditional = {}
```

The `dependency-fetch-output-from-state` experiment should respect the `exclude` block.

## Must haves

- [x] Steps for reproduction provided.

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v1.0.0
- OpenTofu version: v1.11.6
- Environment details (Ubuntu 20.04, Windows 10, etc.): macOS 26.4 (arm64)

## Additional context

Possibly related:
 - #3349

### PR DESCRIPTION
**Pull request by denis256**
## Description

* added handling of exclude block during outputs fetching
* usage of discovery for finding units

Fixes #5864.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **New Features**
  * Stack output now respects exclude rules: excluded units appear with empty output maps.

* **Bug Fixes**
  * Avoid collecting outputs for excluded units and prevent related filesystem side effects.
  * Improved handling and reporting when reading unit outputs fails.

* **Tests**
  * Added unit and integration tests covering exclude scenarios and output assertions.

* **Fixtures**
  * Added stack and unit fixtures to validate excluded vs. non-excluded behavior.

* **Documentation**
  * Changelog entry documenting v1.0.2 behavior and exclude semantics.

### CODE REVIEW

File: internal/stacks/output/output.go [hunk 1]
```diff
@@ -107,6 +109,7 @@ func StackOutput(
 		parsedStackFiles[path] = stackFile
 
 		targetDir := filepath.Join(dir, config.StackDir)
+		excludedPaths := discoverExcludedPaths(ctx, l, opts, targetDir)
```
Comment (yhakbar) [inline internal/stacks/output/output.go]: Why are we walking the tree twice? Can't we work this out during the initial walk to get the outputs?

File: docs/src/data/changelog/v1.0.2.mdx [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+
+### 🐛 Bug Fixes
+
+---
+
+#### `stack output` now respects the `exclude` block
+
+`terragrunt stack output` previously ignored the `exclude` block on units, attempting to fetch outputs (including directly from S3 state when using `--dependency-fetch-output-from-state`) for units that should have been excluded.
+
+The fix uses Terragrunt discovery to identify excluded units before reading outputs. Excluded units now appear in the stack output as empty objects (`{}`), consistent with how they are handled during `stack run`.
```
Comment (yhakbar) [inline docs/src/data/changelog/v1.0.2.mdx]: Wait, I thought you changed this so that they're just omitted?

File: internal/stacks/generate/generate.go [hunk 3]
```diff
@@ -50,7 +50,7 @@ func GenerateStacks(
 	opts *options.TerragruntOptions,
 	wts *worktrees.Worktrees,
 ) error {
-	foundFiles, err := ListStackFiles(ctx, l, opts, opts.WorkingDir, wts)
```
Comment (yhakbar) [inline internal/stacks/generate/generate.go:53]: NIT: I don't love that we're increasing dependency on `opts` here. Ideally we would fully strip out what we need from opts and pass that in instead.

File: internal/stacks/generate/generate.go [hunk 4]
```diff
@@ -261,50 +261,93 @@ func addNewNodesToGraph(
...
 }
 
-// ListStackFiles searches for stack files in the specified directory.
-//
-// We only want to use the discovery package when the filter flag experiment is enabled, as we need to filter discovery
-// results to ensure that we get the right files back for generation.
+// ListStackFiles searches for stack files starting from opts.WorkingDir via
+// the discovery package. Filters from opts.Filters are applied to restrict
+// results to matching stacks when set.
 func ListStackFiles(
```
Comment (yhakbar) [inline internal/stacks/generate/generate.go:267]: Do we need this wrapper at this stage? Why not just inline the logic for `listStackFilesAndExcludes`?

This seems fishy to me.

File: internal/stacks/generate/generate.go [hunk 5]
```diff
@@ -261,50 +261,93 @@ func addNewNodesToGraph(
...
 	ctx context.Context,
 	l log.Logger,
 	opts *options.TerragruntOptions,
-	dir string,
 	worktrees *worktrees.Worktrees,
 ) ([]string, error) {
-	discovery, err := discovery.NewForStackGenerate(l, discovery.StackGenerateOptions{
+	foundFiles, _, err := listStackFilesAndExcludes(ctx, l, opts, worktrees, false)
```
Comment (yhakbar) [inline internal/stacks/generate/generate.go]: NIT: This `false` parameter at the end isn't great. It's unclear what it does from here.

File: internal/stacks/generate/generate.go [hunk 6]
```diff
@@ -261,50 +261,93 @@ func addNewNodesToGraph(
...
+
+	return foundFiles, err
+}
+
+// ListStackFilesWithExcludes searches for stack files and also returns the set
+// of unit paths that should be excluded from the current terraform command.
```
Comment (yhakbar) [inline internal/stacks/generate/generate.go]:
```suggestion
// of unit paths that should be excluded from the current tofu/terraform command.
```

File: internal/stacks/generate/generate.go [hunk 7]
```diff
@@ -261,50 +261,93 @@ func addNewNodesToGraph(
...
+//
+// On discovery failure, returns an error. Callers that want soft-fail behavior
+// should use ListStackFiles instead.
+func ListStackFilesWithExcludes(
+	ctx context.Context,
+	l log.Logger,
+	opts *options.TerragruntOptions,
+	worktrees *worktrees.Worktrees,
+) ([]string, map[string]struct{}, error) {
+	return listStackFilesAndExcludes(ctx, l, opts, worktrees, true)
```
Comment (yhakbar) [inline internal/stacks/generate/generate.go]: NIT: Why aren't we just exporting `listStackFilesAndExcludes`? I don't see the value in this wrapper.

File: internal/stacks/generate/generate.go [hunk 8]
```diff
@@ -261,50 +261,93 @@ func addNewNodesToGraph(
...
+}
+
+func listStackFilesAndExcludes(
```
Comment (yhakbar) [inline internal/stacks/generate/generate.go]: NIT: How much value does this whole function have? Should we just call the discovery directly? Finding stuff is what it's there for.

File: internal/stacks/output/output.go [hunk 9]
```diff
@@ -261,6 +270,34 @@ func nestUnitOutputs(flat map[string]map[string]cty.Value) (map[string]any, erro
 	return nested, nil
 }
 
+// readUnitOutput returns the terraform outputs for a unit.
```
Comment (yhakbar) [inline internal/stacks/output/output.go]:
```suggestion
// readUnitOutput returns the tofu/terraform outputs for a unit.
```

File: pkg/config/exclude_test.go [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+			},
+			action: "output",
+			want:   false,
+		},
+		{
+			name: "all actions prevents output",
+			exclude: config.ExcludeConfig{
+				If:      true,
+				Actions: []string{"all"},
+				NoRun:   &boolTrue,
```
Comment (yhakbar) [inline pkg/config/exclude_test.go]: NIT: I don't think you have to do this anymore.

You can just do:

```go
				NoRun:   new(true)
```

**Review by yhakbar — DISMISSED** [review]

**Review by yhakbar — APPROVED** [review]
