### PR TITLE
Fixed handling of dependency outputs when json log format is enabled

### LINKED ISSUE #3043: Operations with json logging fail when there is a dependency with outputs
**Describe the bug**

When I have two terragrunt modules which have a dependency defined (Module B uses outputs from Module A) using the `dependency` block.

**To Reproduce**

Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```hcl
# File: module-a/terragrunt.hcl



# File: module-a/outputs.tf

output "test" {
  value = "hello-world"
}

# File: module-b/terragrunt.hcl

dependency "a" {
  config_path = "../module-a"
}

inputs = {
  test = dependency.a.outputs.test
}

# File: module-b/variables.tf

variable "test" {
}

```

Run in `module-b`:

```bash
terragrunt plan -json --terragrunt-json-log --terragrunt-tf-logs-to-json &> plan-log.json
```

**Expected behavior**

Plan Operations run through.

**Nice to have**

Log excerpt:

```
<version calls>

{"executedCommandArgs":["output","-json"],"level":"info","msg":"{","time":"2024-04-09T10:33:10+02:00","workingDir":"/workspace/tf-repro/module-a"}
{"executedCommandArgs":["output","-json"],"level":"info","msg":"  \"test\": {","time":"2024-04-09T10:33:10+02:00","workingDir":"/workspace/tf-repro/module-a"}
{"executedCommandArgs":["output","-json"],"level":"info","msg":"    \"sensitive\": false,","time":"2024-04-09T10:33:10+02:00","workingDir":"/workspace/tf-repro/module-a"}
{"executedCommandArgs":["output","-json"],"level":"info","msg":"    \"type\": \"string\",","time":"2024-04-09T10:33:10+02:00","workingDir":"/workspace/tf-repro/module-a"}
{"executedCommandArgs":["output","-json"],"level":"info","msg":"    \"value\": \"hello-world\"","time":"2024-04-09T10:33:10+02:00","workingDir":"/workspace/tf-repro/module-a"}
{"executedCommandArgs":["output","-json"],"level":"info","msg":"  }","time":"2024-04-09T10:33:10+02:00","workingDir":"/workspace/tf-repro/module-a"}
{"executedCommandArgs":["output","-json"],"level":"info","msg":"}","time":"2024-04-09T10:33:10+02:00","workingDir":"/workspace/tf-repro/module-a"}

<version calls>

{"level":"error","msg":"Could not parse output from terragrunt config /workspace/tf-repro/module-a/terragrunt.hcl. Underlying error: unexpected end of JSON input","time":"2024-04-09T10:33:11+02:00"}
{"level":"error","msg":"Unable to determine underlying exit code, so Terragrunt will exit with error code 1","time":"2024-04-09T10:33:11+02:00"}
```

**Versions**

- Terragrunt version: 0.56.3
- Terraform version: 1.5.7
- Environment details: Ubuntu 22.04 LTS

### PR DESCRIPTION
**Pull request by denis256**
## Description

Included changes:
* disabled json wrapping when reading outputs
* added matrix test to track changes
* added usage of `runTerragruntCommandWithOutput` on some failing tests - will raise a separated issue to switch all remaining tests

Fixes #3043.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### CODE REVIEW

File: config/dependency.go [hunk 1]
```diff
@@ -891,6 +891,18 @@ func runTerragruntOutputJson(ctx *ParsingContext, targetConfig string) ([]byte,
...
+	currentIncludeModulePrefix := ctx.TerragruntOptions.IncludeModulePrefix
+
+	// reset the settings after the run
+	defer func() {
+		ctx.TerragruntOptions.TerraformLogsToJson = currentTerraformLogsToJson
+		ctx.TerragruntOptions.IncludeModulePrefix = currentIncludeModulePrefix
+	}()
+	// Disable json wrapping to allow reading of outputs
+	ctx.TerragruntOptions.TerraformLogsToJson = false
+	ctx.TerragruntOptions.IncludeModulePrefix = false
```
Comment (levkohimins) [inline config/dependency.go:904]:
```suggestion
	newOpts := *ctx.TerragruntOptions
	newOpts.TerraformLogsToJson = false
	newOpts.IncludeModulePrefix = false
	newOpts.Writer = stdoutBufferWriter

	ctx = ctx.WithTerragruntOptions(&newOpts)
```

Comment (levkohimins) [reply config/dependency.go:904]: I think it's better to create a new context. it will be more reliable with concurrency.

**Review by levkohimins — CHANGES_REQUESTED** [review]

**Review by levkohimins — APPROVED** [review]
LGTM!
