### PR TITLE
fix: Addressing commas in external IDs

### LINKED ISSUE #4086: External IDs with a comma , fails
## Describe the bug

When using the `remote_state` block in a terragrunt HCL file, trying to assume a role while specifying a `.config.external_id` string with a comma in it causes any Terragrunt action (plan/apply/etc) to fail with the following error:

```
s3_assume_role.hcl:1,38-2,1: Invalid multi-line string; Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \n escape to represent a newline character or use the "heredoc" multi-line template syntax.
```

## Steps To Reproduce

Create a root.hcl with the following block:

```hcl
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket = "tfstate-${local.aws_account_id}-eu-central-1"

    key            = "${local.aws_account_id}/${path_relative_to_include()}/terraform.tfstate"
    region         = "eu-central-1"
    encrypt        = true
    dynamodb_table = "terraform-state-lock"
    role_arn       = "arn:aws:iam::${local.aws_account_id}:role/deploy"
    external_id    = "a,b"
  }
}
```

Note that the external_id field has a comma , in it.

## Expected behavior

A comma is a valid character for an AWS IAM role external ID. Therefore, we use a random password generator that includes this character in its character set. I expect that external IDs with commas in them are parsed as a literal string character, rather than treating it as a newline or new string.

## Nice to haves

```
ERROR  6 errors occurred:

* s3_assume_role.hcl:1,38-2,1: Invalid multi-line string; Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \n escape to represent a newline character or use the "heredoc" multi-line template syntax., and 1 other diagnostic(s)

* Cannot process module Module ./monitoring (excluded: false, assume applied: false, dependencies: [./aurora]) because one of its dependencies, Module ./aurora (excluded: false, assume applied: false, dependencies: [./base]), finished with an error: Cannot process module Module ./aurora (excluded: false, assume applied: false, dependencies: [./base]) because one of its dependencies, Module ./base (excluded: false, assume applied: false, dependencies: []), finished with an error: s3_assume_role.hcl:1,38-2,1: Invalid multi-line string; Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \n escape to represent a newline character or use the "heredoc" multi-line template syntax., and 1 other diagnostic(s)

* Cannot process module Module ./aurora (excluded: false, assume applied: false, dependencies: [./base]) because one of its dependencies, Module ./base (excluded: false, assume applied: false, dependencies: []), finished with an error: s3_assume_role.hcl:1,38-2,1: Invalid multi-line string; Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \n escape to represent a newline character or use the "heredoc" multi-line template syntax., and 1 other diagnostic(s)

* s3_assume_role.hcl:1,38-2,1: Invalid multi-line string; Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \n escape to represent a newline character or use the "heredoc" multi-line template syntax., and 1 other diagnostic(s)

* s3_assume_role.hcl:1,38-2,1: Invalid multi-line string; Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \n escape to represent a newline character or use the "heredoc" multi-line template syntax., and 1 other diagnostic(s)

* s3_assume_role.hcl:1,38-2,1: Invalid multi-line string; Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \n escape to represent a newline character or use the "heredoc" multi-line template syntax., and 1 other diagnostic(s)

14:52:31.704 ERROR  Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

## Versions

- Terragrunt version: v0.76.8
- OpenTofu/Terraform version: Terraform 1.11.3
- Environment details (Ubuntu 20.04, Windows 10, etc.): Fedora CoreOS 41

## Additional context

We've had these external IDs for almost a year, but only just found this error popping up relatively recently, so I can assume that this was a regression in recent versions. At this point I don't have concrete timelines on when this started happening and which versions were in use, but if you need more help pinpointing it let me know and I can dig further.

For now, we have worked around this issue by regenerating our external IDs with the offending character removed.

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #4086 .

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

- **New Features**
  - Enhanced configuration processing now correctly formats comma-separated values outside of quoted text.
  - Introduced a new remote state configuration option to support assume role behavior with multiple external IDs.
  - Added support for AWS OIDC functionality within CircleCI environments.

- **Tests**
  - Added an integration test to validate the handling of multiple external IDs in AWS assume role scenarios.
  - Introduced tests for AWS OIDC assume role functionality, ensuring proper configuration and execution in CircleCI environments.
  - Added a test to validate the new string processing function for handling commas outside of quotes.

### CODE REVIEW

**Review by denis256 — DISMISSED** [review]

File: codegen/generate.go [hunk 1]
```diff
@@ -543,6 +544,41 @@ func convertValue(v any) (ctyjson.SimpleJSONValue, error) {
...
+	// |          # OR
+	// (,)        # Start group 2: Match and capture a comma
+	//
+	re = regexp.MustCompile(`("[^"\\]*(?:\\.[^"\\]*)*")|(,)`)
+)
+
+// replaceAllCommasOutsideQuotesWithNewLines replaces all commas outside quotes with new lines.
+// This is useful for instances where a single line of HCL content might contain a comma, and we don't
+// want to split the line into multiple lines.
+func replaceAllCommasOutsideQuotesWithNewLines(s string) string {
```
Comment (levkohimins) [inline codegen/generate.go:567]: I think it's worth having a unit test for this method.

**Review by levkohimins — DISMISSED** [review]

**Review by levkohimins — APPROVED** [review]
Good job 👍
