### PR TITLE
Fixing registry host discovery (Terragrunt Provider Cache)

### LINKED ISSUE #3421: Terragrunt Provider Cache discovers registry names URLs instead of mirror servers URLs
## Describe the bug

Terragrunt Provider Cache discovers URLs that are specified as `--terragrunt-provider-cache-registry-names` rather than URLs of the mirror servers from which it caches providers.

## Steps To Reproduce

```
terragrunt --terragrunt-provider-cache --terragrunt-provider-cache-registry-names registry.opentofu.org
```

`~/.terraformrc`
```hcl
provider_installation {
  direct {
    exclude = ["*/*/*"]
  }
  network_mirror {
    url = "https://artifactory-host/registry-terraform-io-mirror/providers/"
    include = ["*/*/*"]
  }
}
```

## Expected behavior

Terragrunt discovers endpoints of the host specified in the `network_mirror` section.

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v0.67.9

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Fixes #3421.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### CODE REVIEW

File: cli/provider_cache.go [hunk 1]
```diff
@@ -255,22 +254,15 @@ func (cache *ProviderCache) createLocalCLIConfig(ctx context.Context, opts *opti
...
 		if err != nil {
-			if !liberrors.As(err, &NotFoundWellKnownURL{}) {
-				return err
-			}
-
-			urls = DefaultRegistryURLs
-			opts.Logger.Debugf("Unable to discover %q registry URLs, reason: %q, use default URLs: %s", registryName, err, urls)
-		} else {
-			opts.Logger.Debugf("Discovered %q registry URLs: %s", registryName, urls)
+			return err
```
Comment (denis256) [inline cli/provider_cache.go:259]: Make sense to wrap `errors.WithStackTrace(err)` ?

Comment (levkohimins) [reply cli/provider_cache.go:259]: > Does it make sense to wrap `errors.WithStackTrace(err)`?

No, because `apiURLs, err := cache.Server.DiscoveryURL(ctx, registryName)` already wrapped the error, so we'll have the full stack trace anyway. Wrapping the error only makes sense when we create an error or grab it from a third-party package.

File: pkg/cli/args.go [hunk 2]
```diff
@@ -112,6 +117,17 @@ func (args Args) CommandName() string {
 	return ""
 }
 
+// SubCommandName returns the second value if it starts without a dash `-`, otherwise that means the args do not consist a sub scommand and an empty string is returned.
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply pkg/cli/args.go:120]: Looks like the [codespell](https://app.circleci.com/pipelines/github/gruntwork-io/terragrunt/4821/workflows/8b8a8e7f-dbcf-46b5-81c5-f4789e107b33/jobs/43183) isn't working very well.

**Review by denis256 — DISMISSED** [review]

**Review by yhakbar — APPROVED** [review]
LGTM

**Comment by yhakbar** [comment]
@levkohimins , take note of the strict lint results:

```
cli/provider_cache.go:149: Function 'TerraformCommandHook' is too long (67 > 60) (funlen)
func (cache *ProviderCache) TerraformCommandHook(ctx context.Context, opts *options.TerragruntOptions, args cli.Args) (*util.CmdOutput, error) {
pkg/cli/args.go:39:55: Comment should end in a period (godot)
// Second returns the first argument or a blank string
                                                      ^
terraform/cache/handlers/provider.go:111:56: Comment should end in a period (godot)
// DiscoveryURL implements ProviderHandler.DiscoveryURL
                                                       ^
pkg/cli/args.go:120: line is 166 characters (lll)
// SubCommandName returns the second value if it starts without a dash `-`, otherwise that means the args do not consist a subcommand and an empty string is returned.
terraform/cache/handlers/provider.go:36: line is 180 characters (lll)
// DiscoveryURL looks for the first handler that can handle the given `registryName`, which is determined by the include and exclude settings in the `.terraformrc` CLI config file.
terraform/cache/handlers/provider.go:76: line is 155 characters (lll)
        // We use [xsync.MapOf](https://github.com/puzpuzpuz/xsync?tab=readme-ov-file#map) instead of standard `sync.Map` since it's faster and has generic types.
terraform/cache/handlers/provider.go:80: line is 127 characters (lll)
func NewCommonProviderHandler(providerService *services.ProviderService, includes, excludes *[]string) *CommonProviderHandler {
terraform/cache/handlers/provider.go:124: line is 139 characters (lll)
                handler.providerService.Logger().Debugf("Unable to discover %q registry URLs, reason: %q, use default URLs: %s", registryName, err, urls)
terraform/cache/handlers/provider_direct.go:58: line is 148 characters (lll)
// https://developer.hashicorp.com/terraform/cloud-docs/api-docs/private-registry/provider-versions-platforms#get-all-versions-for-a-single-provider
terraform/cache/handlers/provider_direct.go:84: line is 134 characters (lll)
                Path:   path.Join(apiURLs.ProvidersV1, provider.Namespace, provider.Name, provider.Version, "download", provider.OS, provider.Arch),
terraform/cache/handlers/provider_direct.go:128: line is 126 characters (lll)
                        Path:   filepath.Join(apiURLs.ProvidersV1, provider.RegistryName, provider.Namespace, provider.Name, provider.DownloadURL),
terraform/cache/controllers/provider.go:52: line is 128 characters (lll)
        controller.GET("/:cache_request_id/:registry_name/:namespace/:name/:version/download/:os/:arch", controller.getPlatformsAction)
terraform/cache/server.go:63: line is 180 characters (lll)
// DiscoveryURL looks for the first handler that can handle the given `registryName`, which is determined by the include and exclude settings in the `.terraformrc` CLI config file.
shell/context.go:22: line is 123 characters (lll)
type RunShellCommandFunc func(ctx context.Context, opts *options.TerragruntOptions, args cli.Args) (*util.CmdOutput, error)
terraform/cache/handlers/provider.go:34:6: exported: exported type ProviderHandlers should have comment or be unexported (revive)
type ProviderHandlers []ProviderHandler
     ^
terraform/cache/handlers/provider.go:43:11: error returned from interface method should be wrapped: sig: func (github.com/gruntwork-io/terragrunt/terraform/cache/handlers.ProviderHandler).DiscoveryURL(ctx context.Context, registryName string) (*github.com/gruntwork-io/terragrunt/terraform/cache/handlers.RegistryURLs, error) (wrapcheck)
                        return handler.DiscoveryURL(ctx, registryName)
                               ^
terraform/cache/server.go:66:9: error returned from external package is unwrapped: sig: func (github.com/gruntwork-io/terragrunt/terraform/cache/handlers.ProviderHandlers).DiscoveryURL(ctx context.Context, registryName string) (*github.com/gruntwork-io/terragrunt/terraform/cache/handlers.RegistryURLs, error) (wrapcheck)
        return server.providerHandlers.DiscoveryURL(ctx, registryName)
               ^
cli/provider_cache.go:259:11: error returned from external package is unwrapped: sig: func (*github.com/gruntwork-io/terragrunt/terraform/cache.Server).DiscoveryURL(ctx context.Context, registryName string) (*github.com/gruntwork-io/terragrunt/terraform/cache/handlers.RegistryURLs, error) (wrapcheck)
                        return err
```

If possible, we should revisit the contents of this PR with another PR to address the findings either by:
1. Fixing the issue.
2. Adding an explicit ignore.

**Review by yhakbar — APPROVED** [review]

**Comment by levkohimins** [comment]
Resolved in v0.67.12 release.
