### PR TITLE
Remote config parsing improvements

### LINKED ISSUE #5475: `use_lockfile=true` breaks S3 remote state init
## Describe the bug

After upgrading to terragrunt `0.99.0` or later, terragrunt can no longer init an S3 remote state backend when using `use_lockfile=true`

```
* 1 error(s) decoding:
  
  * 'use_lockfile' expected type 'bool', got unconvertible type 'string', value: 'true'
```

Downgrading to `0.98.0` makes it work again.

## Reproducing bugs

In `root.hcl`:

```hcl
remote_state {
  backend = "s3"

  config = {
    use_lockfile = true
  }
}
```

## Expected behavior

Should work.

## Must haves

- [X] Steps for reproduction provided.

## Versions

```
OpenTofu v1.11.4
on linux_amd64
+ provider registry.opentofu.org/hashicorp/aws v6.30.0
```

### PR DESCRIPTION
**Pull request by denis256**
## Description

* improved parsing of S3 configurations

Fixes #5475.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved config parsing to permissively accept string representations of boolean values across remote state, backend, and generate configs, reducing parsing errors and improving compatibility with HCL-like inputs.

* **Tests**
  * Added comprehensive tests verifying string-to-boolean coercion and error handling for S3, GCS, remote state, and generate-related config fields.

* **Chores**
  * Minor internal allocation/improvement to reduce unnecessary allocations.

### CODE REVIEW

File: internal/gcphelper/config.go [hunk 1]
```diff
@@ -137,7 +137,7 @@ func createGCPCredentialsFromGoogleCredentialsEnv(ctx context.Context, opts *opt
 	}
 
 	if err := json.Unmarshal([]byte(contents), &account); err != nil {
-		return nil, errors.Errorf("Error parsing GCP credentials.")
+		return nil, errors.Errorf("Error parsing GCP credentials: %w", err)
```
Comment (yhakbar) [inline internal/gcphelper/config.go]: Does this risk leaking any information about the user's GCP authentication information?

File: internal/remotestate/backend/s3/client.go [hunk 2]
```diff
@@ -735,16 +735,16 @@ func isBucketAlreadyOwnedByYouError(err error) bool {
 func isBucketErrorRetriable(l log.Logger, err error) bool {
 	var apiErr smithy.APIError
 	if errors.As(err, &apiErr) {
-		unrecoverable := apiErr.ErrorCode() == "InternalError" || apiErr.ErrorCode() == "OperationAborted" || apiErr.ErrorCode() == "InvalidParameter"
+		retriable := apiErr.ErrorCode() == "InternalError" || apiErr.ErrorCode() == "OperationAborted" || apiErr.ErrorCode() == "InvalidParameter"
```
Comment (yhakbar) [inline internal/remotestate/backend/s3/client.go]: This logic was super confusing before, and I did some refactoring, so I probably chose poor names, but this changes logic. This makes it so that we retry when `InvalidParameter` is returned as an error. We probably don't want that.

File: pkg/config/config.go [hunk 3]
```diff
@@ -1681,7 +1680,8 @@ func convertToTerragruntConfig(ctx context.Context, pctx *ParsingContext, config
 		}
 
 		var config *remotestate.Config
-		if err := mapstructure.Decode(remoteStateMap, &config); err != nil {
+		// WeakDecode: HCL ternary type unification sends string "true" for bool fields. See #5475.
```
Comment (yhakbar) [inline pkg/config/config.go]: Do we really need this comment everywhere?
