### PR TITLE
3274 - fix: Include nothing when value for `terragrunt-include-dir` doesn't exist on the filesystem

### LINKED ISSUE #3274: CLI argument`--terragrunt-include-dir` includes all folders if the pattern does not match since version `0.50.1`
## Describe the bug

A run of `terragrunt run-all apply --terragrunt-include-dir "does-not-exist-*"` leads to apply of all folders in the current directory. Especially dangerous when running in the CI and you upgraded from 0.50.0 to any later version!

The weird behaviour of this was introduced with this PR: https://github.com/gruntwork-io/terragrunt/pull/2664

IMO this is a breaking change but was added as a patch increment.

## Steps To Reproduce

- Create a folder with multiple subfolders that contain `terragrunt.hcl` files.
- Head to the folder and execute the above mentioned command, make sure the include pattern you specify does not match.
- You should see that it selects all folders for the execution plan.

I confirmed in my local tests that it is not related to glob matching, so any non existing folder in the include should work to reproduce the problem.

## Expected behavior

- After executing the above command and no folder is matching the specified include pattern, I expect an empty execution and nothing to happen.
- The argument `--terragrunt-include-dir` should work like a whitelist (which it did before version 0.50.1)

## Nice to haves

A screenshot of a CLI session to reproduce:
Screenshot 2024-07-18 at 13 00 21

## Versions
- Terragrunt version: 0.50.0

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #3274.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Updated `--terragrunt-include-dir` to properly exclude by default when set, even if the value is not found.

### CODE REVIEW

File: options/options.go [hunk 1]
```diff
@@ -203,6 +203,10 @@ type TerragruntOptions struct {
 	// Unix-style glob of directories to include when running *-all commands
 	IncludeDirs []string
 
+	// If set to true, exclude all directories by default when running *-all commands
+	// Is set automatically if IncludeDirs is set
+	ExcludeByDefault bool
```
Comment (denis256) [inline options/options.go:208]: Usually, when a field is added to `TerragruntOptions`, it should be also updated `Clone()` function to copy the field

**Review by denis256 — APPROVED** [review]
