### PR TITLE
Fixing generation of `provider_installation` block used for provider caching

### LINKED ISSUE #3244: Issues when attempting to use air-gap/offline provider cache and private module (i.e. `provider_installation` possibly being ignored).
## Describe the bug

I am attempting to `terragrunt run-all plan` in an air-gapped/offline-only/private-intranet use case. I basically need to use a private/proprietary module, along with the public `github` provider to communicate with a private GitHub Enterprise Server (GHES) stack. This work is somewhat similar to what is described in <https://github.com/gruntwork-io/terragrunt/issues/3117>.

I'm able to get the [provider cache](https://terragrunt.gruntwork.io/docs/features/provider-cache/) to work with various modules I can pull from `registry.terraform.io`, but not with private modules. For example, I have a private module, `cheeseburger/pickle/3.0.0`, hosted on a private (slow) server, `terraform.food.lan`. Since the private server is slow and unreliable, I'm attempting to manually install the provider into the cache. However, all attempts to get the private module to be sourced via my Terragrunt provider cache fail with the following error:

```
ERRO[0078] remote https://terraform.food.lan/v1/providers/cheeseburger/pickle/versions unreachable, could not forward: context canceled
...
...
...
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
terraform.food.lan/cheeseburger/pickle: could not query provider registry for
terraform.food.lan/cheeseburger/pickle: the request failed after 2 attempts,
please try again later: Get
"http://127.0.0.1:5758/v1/providers//terraform.food.lan/cheeseburger/pickle/versions":
context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

## Steps To Reproduce

First, I setup the Terragrunt provider cache in my shell:

```sh
export TERRAGRUNT_PROVIDER_CACHE="1"
export TERRAGRUNT_PROVIDER_CACHE_REGISTRY_NAMES="registry.terraform.io,terraform.food.lan"
export TERRAGRUNT_PROVIDER_CACHE_HOST=127.0.0.1
export TERRAGRUNT_PROVIDER_CACHE_PORT=5758
```

I create a `~/.terraformrc` file like so:

```hcl
plugin_cache_dir = "$HOME/.cache/terragrunt/providers"
disable_checkpoint = true
provider_installation {
  filesystem_mirror {
    path    = "/home/owner/.cache/terragrunt/providers"
    include = [
      "terraform.food.lan/*/*",
    ]
  }
  direct {
    exclude = [
      "terraform.food.lan/*/*",
    ]
  }
}
```

For additional context, my respective provider cache folders are located at the following paths (and that, with the exception of this use case where I'm trying to manually install a private provider into the Terragrunt provider cache, both Terragrunt and vanilla Terraform provider caches appear to be working as expected):

- Terragrunt: `~/.cache/terragrunt/providers`
- Terraform: `~/.terraform.d/plugins`

## Expected behavior

I expected `terragrunt run-all plan` to conclude normally (i.e. to successful completion), but without requiring any access to the private server, `terraform.food.lan`.

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: `terragrunt version v0.59.6`
- OpenTofu/Terraform version: `Terraform v1.9.1 on linux_arm64`
- Environment details (Ubuntu 20.04, Windows 10, etc.): 
```sh
$> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble

$> uname -a
Linux darkstar 6.8.0-36-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 13:20:23 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

## Additional context

N/A. Happy to provide additional info as we go.

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Fixes #3244.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### CODE REVIEW

File: cli/commands/terraform/creds/providers/externalcmd/provider.go [hunk 1]
```diff
@@ -43,7 +43,6 @@ func (provider *Provider) GetCredentials(ctx context.Context) (*providers.Creden
 		args = parts[1:]
 	}
 
-	provider.terragruntOptions.Logger.Infof("Executing %s to obtain Terragrunt credentials", provider.Name())
```
Comment (yhakbar) [inline cli/commands/terraform/creds/providers/externalcmd/provider.go:46]: Why did we lose this, @levkohimins ?

File: terraform/cliconfig/provider_installation.go [hunk 2]
```diff
@@ -1,16 +1,91 @@
...
+
+func (methods ProviderInstallationMethods) Merge(withMethods ...ProviderInstallationMethod) ProviderInstallationMethods {
+	for _, method := range methods {
+		remainedWithMethods := withMethods
+		withMethods = ProviderInstallationMethods{}
+
+		for _, withMethod := range remainedWithMethods {
+			var isMerged bool
+
+			if method, ok := method.(*ProviderInstallationFilesystemMirror); ok {
```
Comment (denis256) [inline terraform/cliconfig/provider_installation.go:26]: The declaration of 'method' shadows the previous 'method' declaration. Is it by intention?

It was hard to detect which `method` variable is changes, one from if or one from for

File: cli/commands/terraform/creds/providers/externalcmd/provider.go (hunk 1 above)
Comment (levkohimins) [reply cli/commands/terraform/creds/providers/externalcmd/provider.go:46]: Because it duplicates log:

```
time=2024-07-19T15:11:23+03:00 level=debug msg=Running command: echo -n {"awsCredentials": {"ACCESS_KEY_ID ....  
time=2024-07-19T15:11:23+03:00 level=debug msg=Command output will be suppressed. 
time=2024-07-19T15:11:23+03:00 level=debug msg=Obtaining AWS credentials from the external echo -n {"awsCredentials": {"ACCESS_KEY_ID ...
```

File: terraform/cliconfig/provider_installation.go (hunk 2 above)
Comment (levkohimins) [reply terraform/cliconfig/provider_installation.go]: Agree, fixed.
