### PR TITLE
Fix parsing output when AWS CSM is enabled

### LINKED ISSUE #2233: Could not parse output from terragrunt config when AWS_CSM_ENABLED=true
Hi, I've encountered an error when trying to run `terragrunt apply` with `AWS_CSM_ENABLED` environment variable set to `true`. I receive an error message:

```bash
> cd /the/path/to/terragrunt-projects/project-that-depends-on-cicd-setup
> terragrunt apply
ERRO[0002] Could not parse output from terragrunt config /the/path/to/terragrunt-projects/cicd-setup/terragrunt.hcl. Underlying error: invalid character '/' after top-level value 
ERRO[0002] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```  

However I don't encounter the error when I set:

```bash
# /bin/bash
> export AWS_CSM_ENABLED=false
> terragrunt apply  # provides plan with prompt to apply changes as expected
```

>NOTE: I ran `terragrunt apply --terragrunt-log-level debug --terragrunt-debug`, which provided some additional insight, which gave me the idea to try disabling AWS client side monitoring:

```bash
> terragrunt apply --terragrunt-log-level debug --terragrunt-debug
# -- snip --
DEBU[0000] run_cmd, cached output: [REDACTED]            prefix=[/the/path/to/terragrunt-projects/cicd-setup] 
DEBU[0000] Evaluated 1 locals (remaining 2): git_repo_name  prefix=[/the/path/to/terragrunt-projects/cicd-setup] 
DEBU[0000] Evaluated 1 locals (remaining 1): backend_bucket  prefix=[/the/path/to/terragrunt-projects/cicd-setup] 
DEBU[0000] Evaluated 1 locals (remaining 0): dynamodb_table  prefix=[/the/path/to/terragrunt-projects/cicd-setup] 
DEBU[0000] [Partial] Included config /the/path/to/terragrunt-projects/cicd-setup/terragrunt.hcl has strategy shallow merge: merging config in (shallow).  prefix=[/the/path/to/terragrunt-projects/cicd-setup/cicd-setup] 
DEBU[0000] Detected module /the/path/to/terragrunt-projects/cicd-setup/terragrunt.hcl is already init-ed. Retrieving outputs directly from working directory.  prefix=[/the/path/to/terragrunt-projects/cicd-setup] 
DEBU[0000] Running command: terraform output -json       prefix=[/the/path/to/terragrunt-projects/cicd-setup] 
DEBU[0002] Retrieved output from /the/path/to/terragrunt-projects/cicd-setup/terragrunt.hcl as json: 2022/08/11 08:53:48 Enabling CSM
{
  "codebuild_projects": {
    "sensitive": false,
    "type": [
      "object",
      {
        "pr-build": [
          "object",
          {
            "policy_arn": "string",
            "project_arn": "string",
            "project_id": "string",
            "project_name": "string",
            "project_region": "string",
            "role_arn": "string",
            "role_id": "string"
          }
        ],
        "pr-deploy": [
          "object",
          {
            "policy_arn": "string",
            "project_arn": "string",
            "project_id": "string",
            "project_name": "string",
            "project_region": "string",
            "role_arn": "string",
            "role_id": "string"
          }
        ],
# -- snip --
} prefix=[/the/path/to/terragrunt-projects/cicd-setup] 
ERRO[0002] Could not parse output from terragrunt config /the/path/to/terragrunt-projects/cicd-setup/terragrunt.hcl. Underlying error: invalid character '/' after top-level value 
ERRO[0002] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 
```

I was wondering whether anyone had encountered this issue before and what can be done about it - Fundamentally it seems like a bug in terragrunt,  but you can never be sure with all the moving parts these days 😉 

As a user it would be helpful to have a more specific error for this case (or some additional text stating have I tried disabling AWS CSM) otherwise it is hard to understand the underlying root cause of the error.

### PR DESCRIPTION
**Pull request by levkoburburas**
## Description

AWS Go SDK always displays log "Enabling CSM" to stdout when AWS Client Side Monitoring (CSM) is enabled, this prevents the json string from being parsed correctly.

A similar issue is also mentioned in `terraform-provider-aws`: https://github.com/hashicorp/terraform-provider-aws/issues/23620
Fixes #2233.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Fix parsing output when AWS CSM is enabled

### CODE REVIEW

File: config/dependency.go [hunk 1]
```diff
@@ -452,6 +455,14 @@ func getOutputJsonWithCaching(targetConfig string, terragruntOptions *options.Te
 	if err != nil {
 		return nil, err
 	}
+
+	// When AWS Client Side Monitoring (CSM) is enabled the aws-sdk-go always displays log "Enabling CSM" to stdout, before JSON string, even if the `output -json` flag is specified. Since there is no way to disable this log, the only way out is to filter.
+	// Related AWS code: https://github.com/aws/aws-sdk-go/blob/81d1cbbc6a2028023aff7bcab0fe1be320cd39f7/aws/session/session.go#L444
+	// Related issues: https://github.com/gruntwork-io/terragrunt/issues/2233 https://github.com/hashicorp/terraform-provider-aws/issues/23620
+	if index := bytes.IndexByte(newJsonBytes, byte('{')); index > 0 {
```
Comment (zackproser) [inline config/dependency.go:462]: TIL!

**Review by zackproser — DISMISSED** [review]
LGTM

File: test/integration_test.go [hunk 2]
```diff
@@ -873,6 +874,39 @@ func TestTerragruntOutputFromRemoteState(t *testing.T) {
...
 }
+
+func TestTerragruntOutputFromDependency(t *testing.T) {
+	// you cannot use t.Parallel() with t.Setenv
+
+	fixtureAppPath := filepath.Join(TEST_FIXTURE_OUTPUT_FROM_DEPENDENCY, "app")
+	fixtureDepPath := filepath.Join(TEST_FIXTURE_OUTPUT_FROM_DEPENDENCY, "dependency")
+
+	s3BucketName := fmt.Sprintf("terragrunt-test-bucket-%s", strings.ToLower(uniqueId()))
+	//defer deleteS3Bucket(t, TERRAFORM_REMOTE_STATE_S3_REGION, s3BucketName)
```
Comment (denis256) [inline test/integration_test.go:885]: I think this part should be enabled

Comment (levkoburburas) [reply test/integration_test.go]: > I think this part should be enabled

Oh, I commented out when debugging and forgot to put it back. Thanks for catching this up. Fixed.

File: test/integration_test.go [hunk 3]
```diff
@@ -873,6 +874,39 @@ func TestTerragruntOutputFromRemoteState(t *testing.T) {
...
+	// you cannot use t.Parallel() with t.Setenv
+
+	fixtureAppPath := filepath.Join(TEST_FIXTURE_OUTPUT_FROM_DEPENDENCY, "app")
+	fixtureDepPath := filepath.Join(TEST_FIXTURE_OUTPUT_FROM_DEPENDENCY, "dependency")
+
+	s3BucketName := fmt.Sprintf("terragrunt-test-bucket-%s", strings.ToLower(uniqueId()))
+	defer deleteS3Bucket(t, TERRAFORM_REMOTE_STATE_S3_REGION, s3BucketName)
+
+	rootTerragruntConfigPath := util.JoinPath(fixtureDepPath, config.DefaultTerragruntConfigPath)
+	copyTerragruntConfigAndFillPlaceholders(t, rootTerragruntConfigPath, rootTerragruntConfigPath, s3BucketName, "not-used", TERRAFORM_REMOTE_STATE_S3_REGION)
```
Comment (denis256) [inline test/integration_test.go:888]: I think should be used a temporary path for `copyTerragruntConfigAndFillPlaceholders` since it is changing used files, for example, if I run locally this test - git says that was changed file `test/fixture-output-from-dependency/dependency/terragrunt.hcl`

```
--- a/test/fixture-output-from-dependency/dependency/terragrunt.hcl
+++ b/test/fixture-output-from-dependency/dependency/terragrunt.hcl
@@ -9,8 +9,8 @@ remote_state {
 
   config = {
     encrypt = true
-    bucket  = "__FILL_IN_BUCKET_NAME__"
+    bucket  = "terragrunt-test-bucket-rzobct"
     key     = "${path_relative_to_include()}/terraform.tfstate"
-    region  = "__FILL_IN_REGION__"
+    region  = "us-west-2"
   }
 }
diff --git a/test/integration_test.go b/test/integration_test.go

```

Example:
https://github.com/gruntwork-io/terragrunt/blob/master/test/integration_test.go#L847

File: test/integration_test.go [hunk 4]
```diff
@@ -873,6 +874,39 @@ func TestTerragruntOutputFromRemoteState(t *testing.T) {
...
+	t.Setenv("AWS_CSM_ENABLED", "true")
+
+	err := runTerragruntCommand(t, fmt.Sprintf("terragrunt init --terragrunt-non-interactive --terragrunt-working-dir %s --terragrunt-log-level debug", fixtureDepPath), &stdout, &stderr)
+	assert.NoError(t, err)
+
+	err = runTerragruntCommand(t, fmt.Sprintf("terragrunt apply -auto-approve --terragrunt-non-interactive --terragrunt-working-dir %s --terragrunt-log-level debug", fixtureDepPath), &stdout, &stderr)
+	assert.NoError(t, err)
+
+	err = runTerragruntCommand(t, fmt.Sprintf("terragrunt apply -auto-approve --terragrunt-non-interactive --terragrunt-working-dir %s --terragrunt-log-level debug", fixtureAppPath), &stdout, &stderr)
+	assert.NoError(t, err)
```
Comment (denis256) [inline test/integration_test.go:904]: Terragrunt support auto init and automatic apply of dependencies, I think these invocations can be replaced with:
```
"cd test/fixture-output-from-dependency"
terragrunt run-all apply 
```
It will automatically init and apply first dependency and then app with passing outputs

Examples:
https://github.com/gruntwork-io/terragrunt/blob/master/test/integration_test.go#L3619

Comment (levkoburburas) [reply test/integration_test.go:904]: Yes, I read the documentation and in the first implementation I did exactly as you suggested, but the dependency was not being applied. I just tried to investigate, and look what I figured out:

When I don't use the `--terragrunt-non-interactive` flag, the behavior is as expected: 

```
terragrunt run-all apply --terragrunt-log-level debug                                                                                                                          1 ↵
DEBU[0000] Did not find any locals block: skipping evaluation.  prefix=[/private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app]
DEBU[0000] Setting download directory for module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app to /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app/.terragrunt-cache
DEBU[0000] Did not find any locals block: skipping evaluation.  prefix=[/private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency]
DEBU[0000] Setting download directory for module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency to /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency/.terragrunt-cache
Module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app depends on module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency, which is an external dependency outside of the current working directory. Should Terragrunt run this external dependency? Warning, if you say 'yes', Terragrunt will make changes in /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency as well! (y/n) y
DEBU[0005] Stack at /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app:
  => Module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app (excluded: false, assume applied: false, dependencies: [/private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency])
  => Module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency (excluded: false, assume applied: false, dependencies: [])
INFO[0005] The stack at /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app will be processed in the following order for command apply:
Group 1
- Module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency

Group 2
- Module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app

Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n)
```

and with `--terragrunt-non-interactive`

```
terragrunt run-all apply --terragrunt-non-interactive --terragrunt-log-level debug                                                                                           130 ↵
DEBU[0000] Did not find any locals block: skipping evaluation.  prefix=[/private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app]
DEBU[0000] Setting download directory for module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app to /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app/.terragrunt-cache
DEBU[0000] Did not find any locals block: skipping evaluation.  prefix=[/private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency]
DEBU[0000] Setting download directory for module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency to /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency/.terragrunt-cache
DEBU[0000] The --non-interactive flag is set. To avoid accidentally affecting external dependencies with a run-all command, will not run this command against module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency, which is a dependency of module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app.
DEBU[0000] Stack at /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app:
  => Module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app (excluded: false, assume applied: false, dependencies: [/private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency])
  => Module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency (excluded: false, assume applied: true, dependencies: [])
INFO[0000] The stack at /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app will be processed in the following order for command apply:
Group 1
- Module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app

DEBU[0000] Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n)
DEBU[0000] The non-interactive flag is set to true, so assuming 'yes' for all prompts
DEBU[0000] Module /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app must wait for 1 dependencies to finish  prefix=[/private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app]

... omitted

ERRO[0002] 1 error occurred:
        * /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/dependency/terragrunt.hcl is a dependency of /private/work/contract/gruntwork/repos/terragrunt/test/fixture-output-from-dependency/app/terragrunt.hcl but detected no outputs. Either the target module has not been applied yet, or the module has no outputs. If this is expected, set the skip_outputs flag to true on the dependency block.

ERRO[0002] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

Looks like a bug, doesn't it?

Comment (denis256) [reply test/integration_test.go:904]: AFAIK, this is expected, since terragrunt is invoked in `fixture-output-from-dependency/app` but dependency is referencing something outside of `app`

To avoid this, invoke terragrunt in `fixture-output-from-dependency` and it will build right dependencies since `app` and `dependency` are child directories

Comment (levkoburburas) [reply test/integration_test.go]: Yeah, this helped, thanks! 
Either way, this is a bit of a weird behavior. I think it should behave the same whether or not the `--terragrunt-non-interactive` flag is specified.

**Review by denis256 — APPROVED** [review]
