### PR TITLE
fix: Adjusting lockfile handling when modules define constraints

### LINKED ISSUE #4512: .terraform.lock.hcl files showing incorrect constraints with provider cache
## Describe the bug

I believe following https://github.com/gruntwork-io/terragrunt/pull/4380 constraints are in a worse state than before. It now fails to update the constraint file if the minimum version is bumped in the module. If you delete the lock file completely and recreate it, it again uses the "pinned" constraint instead the one from the module.

## Steps To Reproduce
With terragrunt `0.83.0`
```
→ terragrunt --version
terragrunt version v0.83.0
```

My cloudflare module has the following `versions.tf`:
```
terraform {
  required_version = ">= 1.5.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
    time = {
      source  = "hashicorp/time"
      version = ">= 0.10.0"
    }
  }
}
```

My lock file looks like this. This lock file was originally created without provider cache
```
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/cloudflare/cloudflare" {
  version     = "4.37.0"
  constraints = "~> 4.0"
  hashes = [
    "h1:0h0qRJYPHL92Dx3NYZO2WJ21cxyZGEoldzw9aYhPnew=",
    "h1:8tVm+BJvzI14pRbEyt00AvH6oIyqiLRZQ9KxcBeSDhE=",
    "h1:joMURZCLUJ2eSlj645xqHWKYbRBYqvajCkhaz7qzi8g=",
    "zh:012a6c3e8bf4aca0ebe0884e15bd42fd018659193f2159d5d2bf9948a9be1bc4",
    "zh:079666c0a079237af46ed19ffc4143655ee0e8920a274868e44fbc3db88f346d",
    "zh:08e7ff86f6848f3109d59ad46f8c0987178eff2f70c8ef03f2d44ae68e42dfb3",
    "zh:1ce8a499fdf8f484f7d18ec91566bc0759b07d0ca710990cd60d32b222e416b1",
    "zh:348e72338095bffccf7c46c7e6b9d0e063a22d9ae761061b0b31dea1aad22cd9",
    "zh:47d39343dea1ef469a2c8e51c8d5993687af427a132da5379796fec27acb5710",
    "zh:4cdf8e9579f9af3c72270088fc6e22208f0f91fd4382bc4a860d16040c86917b",
    "zh:4fbebb21ecebc7e5ac0ea9e341c5dbea3094fc0579e4dc5b40bfe693164e022e",
    "zh:778578dda7dd98576a3fe228132c8b60f646f4cf113638c94f1c40e2b11c027c",
    "zh:890df766e9b839623b1f0437355032a3c006226a6c200cd911e15ee1a9014e9f",
    "zh:894071f0f42571f820918d1a4316704923e29c5b2392704c1cbd063a04a641b8",
    "zh:8d11dd73dd499c74d89f77a7e1b3d4a077ac88b0c9c3412e9a6a1b4efe17d107",
    "zh:991e088be8381a73872cd33bb659e9dd69d7ab1f1f8d89b3cd17ffe59dffc65f",
    "zh:9c0848b9c7e6799c9ffcf3afa70ad94a027f3e15a94679d56790714de0b072c5",
    "zh:ad71ae800065ffc24b94d994250136ae8a9f6da704cf91b0dc9e14989e947369",
  ]
}
```
I've updated my module's versions.tf as follows:
```
<--snip-->
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.40"
    }
<--snip-->
```

When I run `terragrunt init -upgrade`, the version and hashes are updated but not the constraint.
```
provider "registry.terraform.io/cloudflare/cloudflare" {
  version     = "4.52.0"
  constraints = "~> 4.0"
  hashes = [
    "h1:Pi5M+GeoMSN2eJ6QnIeXjBf19O+rby/74CfB2ocpv20=",
    "zh:19be1a91c982b902c42aba47766860dfa5dc151eed1e95fd39ca642229381ef0",
```

If I delete the lock file and recreate it with `terragrunt init`, it reverts to the old way with the pinned constraint and not the one from the module:
```
provider "registry.terraform.io/cloudflare/cloudflare" {
  version     = "4.52.0"
  constraints = "4.52.0"
  hashes = [
    "h1:Pi5M+GeoMSN2eJ6QnIeXjBf19O+rby/74CfB2ocpv20=",
    "zh:19be1a91c982b902c42aba47766860dfa5dc151eed1e95fd39ca642229381ef0",
```

## Expected behavior

When running `terragrunt init -upgrade` the constraints in the module should be honoured.

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: `v0.83.0`
- OpenTofu/Terraform version: `Terraform v1.12.1`
- Environment details (Ubuntu 20.04, Windows 10, etc.): `darwin_arm64`

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #4512

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [ ] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [ ] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Updated Provider Cache Server logic to handle existing lock files better, even when modules have version constraints.

## Summary by CodeRabbit

* **New Features**
  * Improved handling of Terraform provider version constraints to ensure module-specified constraints are accurately preserved and updated in lock files, especially during upgrades.
  * Enhanced logging throughout provider caching operations for better traceability and debugging.
  * Added support for parsing provider constraints from both `.tf` and `.tofu` files, including custom registry host overrides.

* **Bug Fixes**
  * Resolved issues where provider version constraints could be incorrectly pinned or not updated in certain upgrade scenarios.

* **Tests**
  * Introduced comprehensive integration and unit tests to verify correct provider constraint handling and lock file updates across various scenarios.

### CODE REVIEW

File: test/integration_provider_cache_constraint_test.go [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+
+const (
+	testFixtureProviderCacheConstraintIssue = "fixtures/provider-cache/constraint-issue"
+)
+
+// TestTerragruntProviderCacheConstraintIssue tests that provider cache preserves
+// module constraints instead of pinning exact versions in .terraform.lock.hcl files.
+// Reproduces and validates the fix for GitHub issue #4512.
+//
+//nolint:paralleltest,tparallel
```
Comment (denis256) [inline test/integration_provider_cache_constraint_test.go:26]: I think nolint:paralleltest,tparallel is not required

**Review by denis256 — APPROVED** [review]

File: test/integration_provider_cache_constraint_test.go (hunk 1 above)
Comment (yhakbar) [reply test/integration_provider_cache_constraint_test.go:26]: It is because the `t.Run` calls happen sequentially.

**Comment by igor-raits** [comment]
@yhakbar looks like with this fix, we get now this error:

```
21:38:40.840 INFO   Caching terraform providers for ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/8t3IW7o05XtBI_3YBS5USuDVLtE
21:38:40.876 STDERR terraform: ╷
21:38:40.876 STDERR terraform: │ Error: failed to read dependency lock file: Invalid provider version constraints: The recorded version constraints for provider registry.terraform.io/ns1-terraform/ns1 must be written in normalized form: ">= 2.2.0".
21:38:40.876 STDERR terraform: │ 
21:38:40.876 STDERR terraform: │ 
21:38:40.876 STDERR terraform: ╵
```

**Comment by yhakbar** [comment]
> @yhakbar looks like with this fix, we get now this error:
> 
> ```
> 21:38:40.840 INFO   Caching terraform providers for ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/8t3IW7o05XtBI_3YBS5USuDVLtE
> 21:38:40.876 STDERR terraform: ╷
> 21:38:40.876 STDERR terraform: │ Error: failed to read dependency lock file: Invalid provider version constraints: The recorded version constraints for provider registry.terraform.io/ns1-terraform/ns1 must be written in normalized form: ">= 2.2.0".
> 21:38:40.876 STDERR terraform: │ 
> 21:38:40.876 STDERR terraform: │ 
> 21:38:40.876 STDERR terraform: ╵
> ```

Could you please share steps to reproduce, @ignatenkobrain ?

**Comment by igor-raits** [comment]
> > @yhakbar looks like with this fix, we get now this error:
> > ```
> > 21:38:40.840 INFO   Caching terraform providers for ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/8t3IW7o05XtBI_3YBS5USuDVLtE
> > 21:38:40.876 STDERR terraform: ╷
> > 21:38:40.876 STDERR terraform: │ Error: failed to read dependency lock file: Invalid provider version constraints: The recorded version constraints for provider registry.terraform.io/ns1-terraform/ns1 must be written in normalized form: ">= 2.2.0".
> > 21:38:40.876 STDERR terraform: │ 
> > 21:38:40.876 STDERR terraform: │ 
> > 21:38:40.876 STDERR terraform: ╵
> > ```
> 
> Could you please share steps to reproduce, @ignatenkobrain ?

Still trying to figure out…

I have existing project where I have `main.tf` that has

```hcl
terraform {
  required_providers {
    ns1 = {
      source  = "ns1-terraform/ns1"
      version = ">= 2.2"
    }
  }
}
```

in the same folder as `terragrunt.hcl` (that is pretty much empty / simple enough to not paste it here).

and there is a `.terraform.lock.hcl` that was created by `0.81.0` version of `terragrunt run init -- -upgrade`

```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/ns1-terraform/ns1" {
  version     = "2.6.5"
  constraints = "2.6.5"
…
```

---

`terragrunt run init -- -upgrade` does following change and fails with aforementioned error.

```diff
-  constraints = "2.6.5"
+  constraints = ">= 2.2"
```

Provider cache is always enabled.

---

If I change required_providers to the `2.2.0` and run init then it changes constraints to `+  constraints = ">= 2.2.0"`

**Comment by igor-raits** [comment]
Interestingly, if I move `main.tf` slightly away from `terragrunt.hcl` (into the `module` subfolder) then the `terraform.lock.hcl` stays the same (with "broken" constraings, aka static version) and the error is not there.

**Comment by igor-raits** [comment]
And when the `source = "git::https://github.com/…"` then the constraints are all as they should be. It feels to me there is some slightly different handling for "local filesystem" modules vs "remote" ones.

**Comment by igor-raits** [comment]
```
22:08:41.145 INFO   Downloading Terraform configurations from git::https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v6.0.1 into ./.terragrunt-cache/Rwe5ZSWmjYpDVsGvL0rOXY7KLE0/rLDNduzmcT3lplh503Th9HcsUyk
22:08:44.069 DEBUG  Copying files from . into ./.terragrunt-cache/Rwe5ZSWmjYpDVsGvL0rOXY7KLE0/rLDNduzmcT3lplh503Th9HcsUyk/modules/vpc-endpoints
22:08:44.069 DEBUG  Setting working directory to ./.terragrunt-cache/Rwe5ZSWmjYpDVsGvL0rOXY7KLE0/rLDNduzmcT3lplh503Th9HcsUyk/modules/vpc-endpoints
22:08:44.070 DEBUG  Generated file ./.terragrunt-cache/Rwe5ZSWmjYpDVsGvL0rOXY7KLE0/rLDNduzmcT3lplh503Th9HcsUyk/modules/vpc-endpoints/_provider.tf.
22:08:44.070 DEBUG  Generated file ./.terragrunt-cache/Rwe5ZSWmjYpDVsGvL0rOXY7KLE0/rLDNduzmcT3lplh503Th9HcsUyk/modules/vpc-endpoints/_backend.tf.
22:08:44.195 DEBUG  Discovered "registry.terraform.io" registry URLs: {"modules.v1":"/v1/modules/","providers.v1":"/v1/providers/"}
22:08:44.256 DEBUG  Discovered "registry.opentofu.org" registry URLs: {"modules.v1":"/v1/modules/","providers.v1":"/v1/providers/"}
22:08:44.256 INFO   Caching terraform providers for ./.terragrunt-cache/Rwe5ZSWmjYpDVsGvL0rOXY7KLE0/rLDNduzmcT3lplh503Th9HcsUyk/modules/vpc-endpoints
22:08:44.256 DEBUG  Running command: terraform init -upgrade
22:08:44.257 DEBUG  Engine is not enabled, running command directly in ./.terragrunt-cache/Rwe5ZSWmjYpDVsGvL0rOXY7KLE0/rLDNduzmcT3lplh503Th9HcsUyk/modules/vpc-endpoints
22:08:47.106 DEBUG  CacheProvider called for registry.terraform.io/hashicorp/aws v6.3.0 with requestID: cd665476-344e-425c-8185-8cd8625f1ca1
22:08:47.107 DEBUG  Sending provider registry.terraform.io/hashicorp/aws v6.3.0 to warm up channel
22:08:47.107 DEBUG  Successfully sent provider registry.terraform.io/hashicorp/aws v6.3.0 to warm up channel
22:08:47.107 DEBUG  Received provider cache request for: registry.terraform.io/hashicorp/aws v6.3.0
22:08:47.107 DEBUG  Starting provider caching for: registry.terraform.io/hashicorp/aws v6.3.0
22:08:47.107 DEBUG  Added provider registry.terraform.io/hashicorp/aws v6.3.0 to provider caches list
22:08:47.107 DEBUG  Added requestID cd665476-344e-425c-8185-8cd8625f1ca1 to provider registry.terraform.io/hashicorp/aws v6.3.0
22:08:47.107 DEBUG  Acquiring lock file /tmp/terragrunt/providers/registry.terraform.io-hashicorp-aws-6.3.0-linux_amd64.lock
22:08:47.107 DEBUG  Acquired lock file for registry.terraform.io/hashicorp/aws v6.3.0, starting warm up
22:08:47.107 DEBUG  Successfully cached provider: registry.terraform.io/hashicorp/aws v6.3.0
22:08:47.108 DEBUG  Successfully started provider caching for registry.terraform.io/hashicorp/aws v6.3.0
22:08:47.115 DEBUG  Waiting for cache ready with requestID: cd665476-344e-425c-8185-8cd8625f1ca1
22:08:47.115 DEBUG  Found 1 caches for requestID: cd665476-344e-425c-8185-8cd8625f1ca1
22:08:47.115 DEBUG  Total provider caches: 1
22:08:47.115 DEBUG  Cache 0: registry.terraform.io/hashicorp/aws v6.3.0, requestIDs: [cd665476-344e-425c-8185-8cd8625f1ca1], ready: true, err: <nil>
22:08:47.115 DEBUG  Provider registry.terraform.io/hashicorp/aws v6.3.0 is ready
22:08:47.115 DEBUG  Returning 1 ready providers for requestID: cd665476-344e-425c-8185-8cd8625f1ca1
22:08:47.115 DEBUG  No constraint found for provider registry.terraform.io/hashicorp/aws
22:08:47.683 DEBUG  Running command: terraform init -upgrade
22:08:47.683 DEBUG  Engine is not enabled, running command directly in ./.terragrunt-cache/Rwe5ZSWmjYpDVsGvL0rOXY7KLE0/rLDNduzmcT3lplh503Th9HcsUyk/modules/vpc-endpoints
22:08:47.712 STDOUT terraform: Initializing the backend...
22:08:50.228 STDOUT terraform: Initializing provider plugins...
22:08:50.228 STDOUT terraform: - Finding hashicorp/aws versions matching ">= 6.0.0"...
22:08:50.238 STDOUT terraform: - Installing hashicorp/aws v6.3.0...
22:08:51.207 STDOUT terraform: - Installed hashicorp/aws v6.3.0 (unauthenticated)
22:08:51.207 STDOUT terraform: Terraform has been successfully initialized!
22:08:51.207 STDOUT terraform: 
22:08:51.207 STDOUT terraform: You may now begin working with Terraform. Try running "terraform plan" to see
22:08:51.207 STDOUT terraform: any changes that are required for your infrastructure. All Terraform commands
22:08:51.207 STDOUT terraform: should now work.
22:08:51.207 STDOUT terraform: If you ever set or change modules or backend configuration for Terraform,
22:08:51.207 STDOUT terraform: rerun this command to reinitialize your working directory. If you forget, other
22:08:51.207 STDOUT terraform: commands will detect it and remind you to do so if necessary.
22:08:51.213 DEBUG  Copying lock file from ./.terragrunt-cache/Rwe5ZSWmjYpDVsGvL0rOXY7KLE0/rLDNduzmcT3lplh503Th9HcsUyk/modules/vpc-endpoints/.terraform.lock.hcl to .
```

This is the log when using source = git for some random module

```
22:10:19.888 INFO   Downloading Terraform configurations from ./module into ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/ngZAm9Qw1RZnBVemMJvseDnic30
22:10:19.889 DEBUG  Copying files from . into ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/ngZAm9Qw1RZnBVemMJvseDnic30
22:10:19.889 DEBUG  Setting working directory to ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/ngZAm9Qw1RZnBVemMJvseDnic30
22:10:19.889 DEBUG  Generated file ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/ngZAm9Qw1RZnBVemMJvseDnic30/_provider.tf.
22:10:19.890 DEBUG  Generated file ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/ngZAm9Qw1RZnBVemMJvseDnic30/_backend.tf.
22:10:20.002 DEBUG  Discovered "registry.terraform.io" registry URLs: {"modules.v1":"/v1/modules/","providers.v1":"/v1/providers/"}
22:10:20.097 DEBUG  Discovered "registry.opentofu.org" registry URLs: {"modules.v1":"/v1/modules/","providers.v1":"/v1/providers/"}
22:10:20.098 INFO   Caching terraform providers for ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/ngZAm9Qw1RZnBVemMJvseDnic30
22:10:20.098 DEBUG  Running command: terraform init -upgrade
22:10:20.098 DEBUG  Engine is not enabled, running command directly in ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/ngZAm9Qw1RZnBVemMJvseDnic30
22:10:23.044 DEBUG  CacheProvider called for registry.terraform.io/ns1-terraform/ns1 v2.6.5 with requestID: 507d1730-3189-477a-92da-2de52861798f
22:10:23.045 DEBUG  Sending provider registry.terraform.io/ns1-terraform/ns1 v2.6.5 to warm up channel
22:10:23.045 DEBUG  Successfully sent provider registry.terraform.io/ns1-terraform/ns1 v2.6.5 to warm up channel
22:10:23.045 DEBUG  Received provider cache request for: registry.terraform.io/ns1-terraform/ns1 v2.6.5
22:10:23.045 DEBUG  Starting provider caching for: registry.terraform.io/ns1-terraform/ns1 v2.6.5
22:10:23.045 DEBUG  Added provider registry.terraform.io/ns1-terraform/ns1 v2.6.5 to provider caches list
22:10:23.045 DEBUG  Added requestID 507d1730-3189-477a-92da-2de52861798f to provider registry.terraform.io/ns1-terraform/ns1 v2.6.5
22:10:23.045 DEBUG  Acquiring lock file /tmp/terragrunt/providers/registry.terraform.io-ns1-terraform-ns1-2.6.5-linux_amd64.lock
22:10:23.045 DEBUG  Acquired lock file for registry.terraform.io/ns1-terraform/ns1 v2.6.5, starting warm up
22:10:23.045 DEBUG  Successfully cached provider: registry.terraform.io/ns1-terraform/ns1 v2.6.5
22:10:23.045 DEBUG  Successfully started provider caching for registry.terraform.io/ns1-terraform/ns1 v2.6.5
22:10:23.052 DEBUG  Waiting for cache ready with requestID: 507d1730-3189-477a-92da-2de52861798f
22:10:23.052 DEBUG  Found 1 caches for requestID: 507d1730-3189-477a-92da-2de52861798f
22:10:23.052 DEBUG  Total provider caches: 1
22:10:23.052 DEBUG  Cache 0: registry.terraform.io/ns1-terraform/ns1 v2.6.5, requestIDs: [507d1730-3189-477a-92da-2de52861798f], ready: true, err: <nil>
22:10:23.052 DEBUG  Provider registry.terraform.io/ns1-terraform/ns1 v2.6.5 is ready
22:10:23.052 DEBUG  Returning 1 ready providers for requestID: 507d1730-3189-477a-92da-2de52861798f
22:10:23.052 DEBUG  No constraint found for provider registry.terraform.io/ns1-terraform/ns1
22:10:24.126 DEBUG  Running command: terraform init -upgrade
22:10:24.126 DEBUG  Engine is not enabled, running command directly in ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/ngZAm9Qw1RZnBVemMJvseDnic30
22:10:24.154 STDOUT terraform: Initializing the backend...
22:10:27.118 STDOUT terraform: Initializing provider plugins...
22:10:27.118 STDOUT terraform: - Finding ns1-terraform/ns1 versions matching ">= 2.2.0"...
22:10:27.123 STDOUT terraform: - Installing ns1-terraform/ns1 v2.6.5...
22:10:27.147 STDOUT terraform: - Installed ns1-terraform/ns1 v2.6.5 (unauthenticated)
22:10:27.147 STDOUT terraform: Terraform has been successfully initialized!
22:10:27.148 STDOUT terraform: 
22:10:27.148 STDOUT terraform: You may now begin working with Terraform. Try running "terraform plan" to see
22:10:27.148 STDOUT terraform: any changes that are required for your infrastructure. All Terraform commands
22:10:27.148 STDOUT terraform: should now work.
22:10:27.148 STDOUT terraform: If you ever set or change modules or backend configuration for Terraform,
22:10:27.148 STDOUT terraform: rerun this command to reinitialize your working directory. If you forget, other
22:10:27.148 STDOUT terraform: commands will detect it and remind you to do so if necessary.
22:10:27.154 DEBUG  Copying lock file from ./.terragrunt-cache/PnAQPHoLYBhneCJ_0OR3UvZ-py4/ngZAm9Qw1RZnBVemMJvseDnic30/.terraform.lock.hcl to .
```

In the latter case constraints are lost and in the first case constraints are on their place.

```
22:15:16.455 DEBUG  Generated file ./_backend.tf.
22:15:16.455 DEBUG  Generated file ./_provider.tf.
22:15:16.600 DEBUG  Discovered "registry.terraform.io" registry URLs: {"modules.v1":"/v1/modules/","providers.v1":"/v1/providers/"}
22:15:16.673 DEBUG  Discovered "registry.opentofu.org" registry URLs: {"modules.v1":"/v1/modules/","providers.v1":"/v1/providers/"}
22:15:16.674 INFO   Caching terraform providers for .
22:15:16.674 DEBUG  Running command: terraform init -upgrade
22:15:16.674 DEBUG  Engine is not enabled, running command directly in .
22:15:19.912 DEBUG  CacheProvider called for registry.terraform.io/ns1-terraform/ns1 v2.6.5 with requestID: 4f2945d9-5e3d-4118-8abb-aafba44ffc41
22:15:19.912 DEBUG  Sending provider registry.terraform.io/ns1-terraform/ns1 v2.6.5 to warm up channel
22:15:19.912 DEBUG  Successfully sent provider registry.terraform.io/ns1-terraform/ns1 v2.6.5 to warm up channel
22:15:19.912 DEBUG  Received provider cache request for: registry.terraform.io/ns1-terraform/ns1 v2.6.5
22:15:19.912 DEBUG  Starting provider caching for: registry.terraform.io/ns1-terraform/ns1 v2.6.5
22:15:19.912 DEBUG  Acquiring lock file /tmp/terragrunt/providers/registry.terraform.io-ns1-terraform-ns1-2.6.5-linux_amd64.lock
22:15:19.912 DEBUG  Added provider registry.terraform.io/ns1-terraform/ns1 v2.6.5 to provider caches list
22:15:19.912 DEBUG  Added requestID 4f2945d9-5e3d-4118-8abb-aafba44ffc41 to provider registry.terraform.io/ns1-terraform/ns1 v2.6.5
22:15:19.912 DEBUG  Acquired lock file for registry.terraform.io/ns1-terraform/ns1 v2.6.5, starting warm up
22:15:19.913 DEBUG  Successfully cached provider: registry.terraform.io/ns1-terraform/ns1 v2.6.5
22:15:19.913 DEBUG  Successfully started provider caching for registry.terraform.io/ns1-terraform/ns1 v2.6.5
22:15:19.920 DEBUG  Waiting for cache ready with requestID: 4f2945d9-5e3d-4118-8abb-aafba44ffc41
22:15:19.920 DEBUG  Found 1 caches for requestID: 4f2945d9-5e3d-4118-8abb-aafba44ffc41
22:15:19.920 DEBUG  Total provider caches: 1
22:15:19.920 DEBUG  Cache 0: registry.terraform.io/ns1-terraform/ns1 v2.6.5, requestIDs: [4f2945d9-5e3d-4118-8abb-aafba44ffc41], ready: true, err: <nil>
22:15:19.921 DEBUG  Provider registry.terraform.io/ns1-terraform/ns1 v2.6.5 is ready
22:15:19.921 DEBUG  Returning 1 ready providers for requestID: 4f2945d9-5e3d-4118-8abb-aafba44ffc41
22:15:19.921 DEBUG  Applied constraint >= 2.2 to provider registry.terraform.io/ns1-terraform/ns1
22:15:20.784 DEBUG  Running command: terraform init -upgrade
22:15:20.784 DEBUG  Engine is not enabled, running command directly in .
22:15:20.812 STDOUT terraform: Initializing the backend...
22:15:23.213 STDERR terraform: ╷
22:15:23.213 STDERR terraform: │ Error: failed to read dependency lock file: Invalid provider version constraints: The recorded version constraints for provider registry.terraform.io/ns1-terraform/ns1 must be written in normalized form: ">= 2.2.0".
22:15:23.213 STDERR terraform: │ 
22:15:23.213 STDERR terraform: │ 
22:15:23.213 STDERR terraform: ╵
22:15:23.219 ERROR  terraform invocation failed in .
22:15:23.219 DEBUG  Copying lock file from ./.terraform.lock.hcl to .
22:15:23.220 DEBUG  Provider cache service shutting down...
22:15:23.220 DEBUG  Provider cache service shutdown complete
22:15:23.220 INFO   Shutting down Terragrunt Cache server...
22:15:23.220 INFO   Terragrunt Cache server stopped
22:15:23.220 ERROR  error occurred:

* Failed to execute "terraform init -upgrade" in .
  ╷
  │ Error: failed to read dependency lock file: Invalid provider version constraints: The recorded version constraints for provider registry.terraform.io/ns1-terraform/ns1 must be written in normalized form: ">= 2.2.0".
```

Finally when having main.tf next to terragrunt.hcl, the output looks like this

**Comment by igor-raits** [comment]
* In the last case, disabling provider cache helps, but constraints are "fixed version"
* In the second case (source = ./module), disabling provider cache makes constraints to appear

**Comment by yhakbar** [comment]
@ignatenkobrain , do you mind creating an issue with an easily reproducible example that maintainers can look at to try to address the issue you're seeing?

**Comment by igor-raits** [comment]
@yhakbar I have prepared test cases and results in https://github.com/gruntwork-io/terragrunt/issues/4534, thanks!
