### PR TITLE
Log improvements

### LINKED ISSUE #3217: Log improvements
## Describe the bug

We need to improve Terragrunt logs to make it more intuitive for understanding in real time what module a log entry belongs to. We also should learn from Terraform's experience in displaying logs and errors. Namely what is pleasant for the eye may be of little information for the file log. For example log entry time, for running in the foreground, this information is useless and only eats up space, while for the file log this is useful information. So I think we should implement two types of logs (similar to Terraform), both output to stdout but the first one is human-friendly and the second one is for file logs but with WARN or ERROR log level by default.

1  tmuxinator local 2024-06-20 at 7 40 23 PM

1  tmuxinator local 2024-06-20 at 7 52 32 PM

## Versions

- Terragrunt version: v.0.59.4

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Fixes #3217.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### CODE REVIEW

File: shell/run_shell_cmd_output_test.go [hunk 1]
```diff
@@ -52,15 +54,19 @@ func testCommandOutputOrder(t *testing.T, withPtty bool, fullOutput []string, st
 
 func TestCommandOutputPrefix(t *testing.T) {
```
Comment (yhakbar) [inline shell/run_shell_cmd_output_test.go:55]: TODO: Remember to ask if we're testing the opposite now.

File: shell/run_shell_cmd_output_test.go [hunk 2]
```diff
@@ -98,7 +105,10 @@ func assertOutputs(
 ) func(string, *util.CmdOutput) {
 	return func(allOutput string, out *util.CmdOutput) {
 		allOutputs := strings.Split(strings.TrimSpace(allOutput), "\n")
-		assert.Equal(t, expectedAllOutputs, allOutputs)
+		assert.Equal(t, len(expectedAllOutputs), len(allOutputs))
+		for i := 0; i < len(allOutputs); i++ {
```
Comment (yhakbar) [inline shell/run_shell_cmd_output_test.go:109]: NIT: You can write this as `for i := range len(allOutputs)` now, I believe.

File: util/collections.go [hunk 3]
```diff
@@ -223,3 +223,23 @@ func SplitUrls(s, sep string) []string {
 
 	return urls
 }
+
+func FindCommonPrefixForAllElements(strs []string) string {
```
Comment (yhakbar) [inline util/collections.go:227]: NIT: This should have a comment

File: util/file.go [hunk 4]
```diff
@@ -218,6 +217,17 @@ func GetPathRelativeTo(path string, basePath string) (string, error) {
 	return filepath.ToSlash(relPath), nil
 }
 
+func GetPathRelativeToWithSeparator(path string, basePath string) (string, error) {
```
Comment (yhakbar) [inline util/file.go:220]: NIT: This should have a comment.

File: util/file.go [hunk 5]
```diff
@@ -218,6 +217,17 @@ func GetPathRelativeTo(path string, basePath string) (string, error) {
...
+	relPath, err := GetPathRelativeTo(path, basePath)
+	if err == nil {
```
Comment (yhakbar) [inline util/file.go:222]: This is easier for me to read as:
```go
if err != nil {
  return relPath, err
}

if relPath == "." {
  relPath += string(filepath.Separator)
}
```

File: util/file.go [hunk 6]
```diff
@@ -218,6 +217,17 @@ func GetPathRelativeTo(path string, basePath string) (string, error) {
...
+		if relPath == "." {
+			relPath += string(filepath.Separator)
```
Comment (yhakbar) [inline util/file.go:224]: Why do we want the trailing slash? I'm not saying it's wrong, just that `.` is as useful to me as `./`.

File: util/logger.go [hunk 7]
```diff
@@ -27,75 +31,84 @@ var (
...
 func DisableJsonFormat() {
 	jsonLogFormat = false
 	// Needs to re-create the global logger
-	GlobalFallbackLogEntry = CreateLogEntry("", defaultLogLevel)
+	updateGlobalLogger()
 }
 
 // CreateLogger creates a logger. If debug is set, we use ErrorLevel to enable verbose output, otherwise - only errors are shown
-func CreateLogger(lvl logrus.Level) *logrus.Logger {
+func CreateLogger(lvl logrus.Level, prefixStyle *formatter.PrefixStyle, disableColors, disableFormatting bool) *logrus.Logger {
```
Comment (yhakbar) [inline util/logger.go:73]: I think this would work better with variadic options:
https://medium.com/soon-london/variadic-configuration-functions-in-go-8cef1c97ce99

**Review by yhakbar — CHANGES_REQUESTED** [review]
I made quite a lot of NITs. I think the only real important thing is to settle on the name of the flag. LMK if my suggested rename makes sense.

File: cli/commands/flags.go [hunk 8]
```diff
@@ -10,65 +10,147 @@ import (
...
+	TerragruntLogLevelFlagName = "terragrunt-log-level"
+	TerragruntLogLevelEnvName  = "TERRAGRUNT_LOG_LEVEL"
+
+	TerragruntNoColorFlagName = "terragrunt-no-color"
+	TerragruntNoColorEnvName  = "TERRAGRUNT_NO_COLOR"
+
+	TerragruntDisableLogFormattingFlagName = "terragrunt-disable-log-formatting"
+	TerragruntDisableLogFormattingEnvName  = "TERRAGRUNT_DISABLE_LOG_FORMATTING"
+
+	TerragruntRawModuleOutputFlagName = "terragrunt-raw-module-output"
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply cli/commands/flags.go:132]: Sounds great, but I'm not sure that reflects what it actually does. Unlike the previous log where we just added a prefix, this output becomes part of the log. For example, (for clarity, I will use the `--terragrunt-disable-log-formatting` flag)

with `--terragrunt-raw-module-output`:

```
time=2024-08-23T11:50:11+03:00 level=info prefix=app msg=Running command: tofu plan -input=false

OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

OpenTofu will perform the following actions:
```

without `--terragrunt-raw-module-output`:

```
time=2024-08-23T11:47:18+03:00 level=info prefix=app msg=Running command: tofu plan -input=false
time=2024-08-23T11:47:18+03:00 level=stdout prefix=app binary=tofu msg=OpenTofu used the selected providers to generate the following execution
time=2024-08-23T11:47:18+03:00 level=stdout prefix=app binary=tofu msg=plan. Resource actions are indicated with the following symbols:
time=2024-08-23T11:47:18+03:00 level=stdout prefix=app binary=tofu msg=  + create
time=2024-08-23T11:47:18+03:00 level=stdout prefix=app binary=tofu msg=OpenTofu will perform the following actions:
```

If we assume that this `time=2024-08-23T11:47:18+03:00 level=stdout prefix=app binary=tofu msg=` is a prefix, than your suggestion is correct, but we should indicate in the name that this only applies to the module ouput not for all TG logs. 

I don't mind renaming the flag, I just want it to be as clear as possible to the end user what it does.

File: config/dependency.go [hunk 9]
```diff
@@ -343,8 +352,13 @@ func checkForDependencyBlockCyclesUsingDFS(
...
 	for _, dependency := range dependencyPaths {
 		dependencyPath := getCleanedTargetConfigPath(dependency, dependencyPath)
-		dependencyConetxt := ctx.WithTerragruntOptions(cloneTerragruntOptionsForDependency(ctx, dependencyPath))
 
+		dependencyOpts, err := cloneTerragruntOptionsForDependency(ctx, dependencyPath)
+		if err != nil {
+			return err
+		}
+
+		dependencyConetxt := ctx.WithTerragruntOptions(dependencyOpts)
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply config/dependency.go:361]: Thank you

File: dynamodb/dynamo_lock_table_test.go [hunk 10]
```diff
@@ -103,6 +103,9 @@ func TestTableTagging(t *testing.T) {
 	withLockTableTagged(t, tags, func(tableName string, client *awsDynamodb.DynamoDB) {
 		assertCanWriteToTable(t, tableName, client)
 
+		// TODO: switch to AWS retry method
+		time.Sleep(5 * time.Second)
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply dynamodb/dynamo_lock_table_test.go:107]: Roger. Removed this code.

File: internal/log/formatter/color.go [hunk 11]
```diff
@@ -0,0 +1,86 @@
...
+
+type ColorStyle string
+
+func (style ColorStyle) ColorFunc() ColorFunc {
+	return ansi.ColorFunc(string(style))
+}
+
+type ColorScheme map[ColorStyleName]ColorStyle
+
+func (scheme ColorScheme) Complite() compiledColorScheme {
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply internal/log/formatter/color.go:47]: Yes, thank you

File: internal/log/formatter/formatter.go [hunk 12]
```diff
@@ -0,0 +1,290 @@
...
+	if err := formatter.appendKeyValue(buf, "time", entry.Time.Format(timestampFormat), false); err != nil {
+		return err
+	}
+
+	if err := formatter.appendKeyValue(buf, "level", formatter.levelText(entry.Level), true); err != nil {
+		return err
+	}
+
+	if val, ok := entry.Data[PrefixKeyName]; ok && val != nil {
+		if val := val.(string); val != "" {
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply internal/log/formatter/formatter.go:106]: Ah, yes, thanks

File: internal/log/formatter/formatter.go [hunk 13]
```diff
@@ -0,0 +1,290 @@
...
+			if err := formatter.appendKeyValue(buf, "prefix", val, true); err != nil {
+				return err
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply internal/log/formatter/formatter.go:108]: This does not make sense, since this func returns `fmt.Fprintf` error, that is, they will all be the same.

File: internal/log/formatter/formatter.go [hunk 14]
```diff
@@ -0,0 +1,290 @@
...
+	if entry.Message != "" {
+		if err := formatter.appendKeyValue(buf, "msg", entry.Message, true); err != nil {
+			return err
+		}
+	}
+
+	keys := formatter.keys(entry.Data, PrefixKeyName, TFBinaryKeyName)
+	for _, key := range keys {
+		if err := formatter.appendKeyValue(buf, key, entry.Data[key], true); err != nil {
+			return err
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply internal/log/formatter/formatter.go:130]: they will all be the same, it doesn't make sense

[the remark this answers is not in the document]
Comment (levkohimins) [reply internal/log/formatter/formatter.go:130]: By the way, I didn't know about the existence of the `errors.Join` function 👍, instead I used https://github.com/hashicorp/go-multierror

File: internal/log/formatter/formatter.go [hunk 15]
```diff
@@ -0,0 +1,290 @@
...
+
+	if _, err := fmt.Fprintf(buf, "%s%s%s%s%s", timestamp, level, prefix, tfBinary, entry.Message); err != nil {
+		return errors.WithStackTrace(err)
+	}
+
+	keys := formatter.keys(entry.Data, PrefixKeyName, TFBinaryKeyName)
+	for _, key := range keys {
+		value := entry.Data[key]
+		if err := formatter.appendKeyValue(buf, key, value, true); err != nil {
+			return err
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply internal/log/formatter/formatter.go:183]: Responded above

File: util/logger.go [hunk 16]
```diff
@@ -27,75 +31,84 @@ var (
...
-func CreateLogEntry(prefix string, level logrus.Level) *logrus.Entry {
-	logger := CreateLogger(level)
-
-	var fields logrus.Fields
-
-	if prefix != "" {
-		fields = logrus.Fields{"prefix": prefix}
-	} else {
-		fields = logrus.Fields{}
+func CreateLogEntry(prefix string, level logrus.Level, prefixStyle *formatter.PrefixStyle, disableColors, disableFormatting bool) *logrus.Entry {
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply util/logger.go:100]: I can't agree with you. Variadic functions should be used only to pass values ​​that have the same meaning. The easiest way to explain this is to use a custom variable type. Excerpt from the article at your link:

```go
func New(opts ...Option) MyService {
```

File: util/logger.go [hunk 17]
```diff
@@ -27,75 +31,84 @@ var (
...
 // CreateLogEntryWithWriter Create a logger around the given output stream and prefix
-func CreateLogEntryWithWriter(writer io.Writer, prefix string, level logrus.Level, hooks logrus.LevelHooks) *logrus.Entry {
-	if prefix != "" {
-		prefix = fmt.Sprintf("[%s] ", prefix)
-	} else {
-		prefix = "[terragrunt] " + prefix
-	}
-
-	logger := CreateLogEntry(prefix, level)
+func CreateLogEntryWithWriter(writer io.Writer, prefix string, level logrus.Level, hooks logrus.LevelHooks, prefixStyle *formatter.PrefixStyle, disableColors, disableFormatting bool) *logrus.Entry {
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply util/logger.go:110]: Nope, explained above

File: pkg/cli/bool_flag.go [hunk 18]
```diff
@@ -6,6 +6,8 @@ import (
 	"github.com/urfave/cli/v2"
 )
 
+var _ Flag = new(BoolFlag)
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply pkg/cli/bool_flag.go:9]: We usually don't comment on this, since it is always done for one purpose only, namely to ensure that the given type implements all the interface methods. But why now.

https://github.com/search?q=repo%3Ahashicorp%2Fterraform%20var%20_%20&type=code

File: pkg/cli/generic_flag.go [hunk 19]
```diff
@@ -9,6 +9,8 @@ import (
 	"github.com/urfave/cli/v2"
 )
 
+var _ Flag = new(GenericFlag[string])
```
[the remark this answers is not in the document]
Comment (levkohimins) [reply pkg/cli/generic_flag.go:12]: Sure

**Comment by levkohimins** [comment]
> I made quite a lot of NITs. I think the only real important thing is to settle on the name of the flag. LMK if my suggested rename makes sense.

Thanks for your review. I fixed everything. I wonder if you can see my "pending" messages?
Log improvements by levkohimins · Pull Request #3338 · gruntwork-ioterragrunt 2024-08-26 at 8 33 18 PM

File: cli/commands/flags.go [hunk 20]
```diff
@@ -79,264 +161,277 @@ func NewGlobalFlags(opts *options.TerragruntOptions) cli.Flags {
...
 			Destination: &opts.TerragruntConfigPath,
+			Usage:       "The path to the Terragrunt config file. Default is terragrunt.hcl.",
 		},
 		&cli.GenericFlag[string]{
 			Name:        TerragruntTFPathFlagName,
-			EnvVar:      "TERRAGRUNT_TFPATH",
-			Usage:       "Path to the Terraform binary. Default is terraform (on PATH).",
+			EnvVar:      TerragruntTFPathEnvName,
 			Destination: &opts.TerraformPath,
+			Usage:       "Path to the Terraform binary. Default is terraform (on PATH).",
```
[the remark this answers is not in the document]
Comment (yhakbar) [reply cli/commands/flags.go:172]: @levkohimins I think this change should really be pulled in.

File: cli/deprecated_flags.go [hunk 21]
```diff
@@ -0,0 +1,33 @@
...
+// NewDeprecatedFlags creates and returns deprecated flags.
+func NewDeprecatedFlags(opts *options.TerragruntOptions) cli.Flags {
+	flags := cli.Flags{
+		&cli.BoolFlag{
+			Name:   TerragruntIncludeModulePrefixFlagName,
+			EnvVar: TerragruntIncludeModulePrefixEnvName,
+			Usage:  "When this flag is set output from Terraform sub-commands is prefixed with module path.",
+			Hidden: true,
+			Action: func(ctx *cli.Context) error {
+				util.GlobalFallbackLogEntry.Warnf("The %q flag is deprecated. Use the functionality-inverted %q flag instead. By default, Terraform/OpenTofu output is integrated into the Terragrunt log, which appends additional data, such as timestamps and prefixes, to log entries.", TerragruntIncludeModulePrefixFlagName, commands.TerragruntRawModuleOutputFlagName)
```
Comment (yhakbar) [inline cli/deprecated_flags.go:26]:
```suggestion
				util.GlobalFallbackLogEntry.Warnf("The %q flag is deprecated. Use the functionality-inverted %q flag instead. By default, Terraform/OpenTofu output is integrated into the Terragrunt log, which prepends additional data, such as timestamps and prefixes, to log entries.", TerragruntIncludeModulePrefixFlagName, commands.TerragruntRawModuleOutputFlagName)
```

File: docs/_docs/04_reference/cli-options.md [hunk 22]
```diff
@@ -71,7 +71,7 @@ This page documents the CLI commands and options available with Terragrunt:
   - [terragrunt-modules-that-include](#terragrunt-modules-that-include)
   - [terragrunt-fetch-dependency-output-from-state](#terragrunt-fetch-dependency-output-from-state)
   - [terragrunt-use-partial-parse-config-cache](#terragrunt-use-partial-parse-config-cache)
-  - [terragrunt-include-module-prefix](#terragrunt-include-module-prefix)
+  - [terragrunt-include-module-prefix (DEPRECATED: use terragrunt-raw-module-output)](#terragrunt-include-module-prefix)
```
Comment (yhakbar) [inline docs/_docs/04_reference/cli-options.md:74]: NIT: I think this is better like the following:

- [terragrunt-include-module-prefix](#terragrunt-include-module-prefix) (DEPRECATED: use [terragrunt-raw-module-output](#terragrunt-raw-module-output))

With the updated flag name.

Not a huge deal, though.

File: docs/_docs/04_reference/cli-options.md [hunk 23]
```diff
@@ -771,7 +773,7 @@ prefix `--terragrunt-` (e.g., `--terragrunt-config`). The currently available op
...
```
Comment (yhakbar) [inline docs/_docs/04_reference/cli-options.md:776]: Same here.

File: docs/_docs/04_reference/cli-options.md [hunk 24]
```diff
@@ -1433,3 +1430,17 @@ Note that more specific configurations (e.g. `awsCredentials`) take precedence o
 If you would like to set credentials for AWS with this method, you are encouraged to use `awsCredentials` instead of `envs`, as these keys will be validated to conform to the officially supported environment variables expected by the AWS SDK.
 
 Other credential configurations will be supported in the future, but until then, if your provider authenticates via environment variables, you can use the `envs` field to fetch credentials dynamically from a secret store, etc before Terragrunt executes any IAC.
+
+### terragrunt-disable-log-formatting
+
+**CLI Arg**: `--terragrunt-disable-log-formatting`<br/>
+**Environment Variable**: `TERRAGRUNT_DISABLE_LOG_FORMATTING`<br/>
+
+If specified, logs will be displayed in key/value format. By default, logs are formatted in a human readable format.
```
[the remark this answers is not in the document]
Comment (yhakbar) [reply docs/_docs/04_reference/cli-options.md:1454]: Great job @levkohimins !

File: internal/log/formatter/prefix_style.go [hunk 25]
```diff
@@ -0,0 +1,52 @@
...
+import (
+	"github.com/puzpuzpuz/xsync/v3"
+)
+
+var (
+	// defeultPrefixStyles contains ANSI color codes that are assigned sequentially to each unique prefix in a rotating order
+	// https://user-images.githubusercontent.com/995050/47952855-ecb12480-df75-11e8-89d4-ac26c50e80b9.png
+	// https://www.hackitu.de/termcolor256/
+	defeultPrefixStyles = []ColorStyle{
+		"66", "67", "95", "96", "102", "103", "108", "109", "139", "138", "144", "145",
```
Comment (yhakbar) [inline internal/log/formatter/prefix_style.go:12]: NIT: It might be better to have constants that indicate what these ANSI color codes represent.

e.g.

```go
defaultPrefixStyles = []ColorStyle{
  red, blue, green, ...
}
```

Also note that the variable name is mispelled.

File: internal/log/formatter/prefix_style.go [hunk 26]
```diff
@@ -0,0 +1,52 @@
...
+	}
+
+	// prefixStyle implements PrefixStyle
+	_ PrefixStyle = new(prefixStyle)
+)
+
+type prefixStyle struct {
+	// cache stores prefixes with their color schemes.
+	cache *xsync.MapOf[string, ColorFunc]
```
Comment (yhakbar) [inline internal/log/formatter/prefix_style.go:21]: NIT: I think we should link to explanations like this when we deviate from the standard library:
https://github.com/puzpuzpuz/xsync?tab=readme-ov-file#map

My immediate thought was "why are we using this instead of `sync.Map`, so it would be good to have an answer right in front of where people might have that thought.

File: internal/log/tf_writer.go [hunk 27]
```diff
@@ -0,0 +1,121 @@
...
+	if _, err := writer.Writer.Write(msgs); err != nil {
+		return 0, errors.WithStackTrace(err)
+	}
+
+	return len(p), nil
+}
+
+func extractTimeAndLevel(msg string) (string, string, string) {
+	if extractTimeAndLevelReg.MatchString(msg) {
+		match := extractTimeAndLevelReg.FindStringSubmatch(msg)
```
Comment (yhakbar) [inline internal/log/tf_writer.go:116]: So that we don't pwn ourselves like the Crowdstrike folks, we should check the length of `match` before indexing it.

File: shell/run_shell_cmd.go [hunk 28]
```diff
@@ -139,22 +141,43 @@ func RunShellCommandWithOutput(
...
 
 		if !suppressStdout {
-			cmdStdout = io.MultiWriter(withPrefix(outWriter, prefix), &stdoutBuf)
-		} else {
-			cmdStdout = io.MultiWriter(&stdoutBuf)
+			// display TF stdout as is (without wrapping to TG log) if args contains `-json` flag or `output` command is specified
+			var rawStdout bool
+
+			for i, arg := range args {
+				if (i == 0 && strings.EqualFold(arg, terraform.CommandNameOutput)) || strings.EqualFold(arg, terraform.FlagNameJSON) {
```
Comment (yhakbar) [inline shell/run_shell_cmd.go:161]: NIT: This is a confusing line. I think extracting it into a well named function will make it easier to understand what we're doing here.

**Comment by yhakbar** [comment]
> > I made quite a lot of NITs. I think the only real important thing is to settle on the name of the flag. LMK if my suggested rename makes sense.
> 
> Thanks for your review. I fixed everything. I wonder if you can see my "pending" messages? Log improvements by levkohimins · Pull Request #3338 · gruntwork-ioterragrunt 2024-08-26 at 8 33 18 PM

No, I think you have to click the green dropdown in the top right and finish your review for me to see those.

In that case, it would be helpful to comment that this is why we're adding the trailing slash (LMK if I just missed it).

**Comment by levkohimins** [comment]
> No, I think you have to click the green dropdown in the top right and finish your review for me to see those.

I don't have this dropdown when I'm not a reviewer and can't be the reviewer for my own PR, looks like a bug.

File: internal/log/formatter/prefix_style.go (hunk 25 above)
Comment (yhakbar) [reply internal/log/formatter/prefix_style.go:12]: Don't make any changes now, but all I was saying is that it would be good to have a constant assigned the value of `"103"` so that I didn't have to search for it in the ANSI color thingy to know what color that was. If we want to change any of these, we'll have to do some looking up to find them.

File: internal/log/tf_writer.go (hunk 27 above)
Comment (yhakbar) [reply internal/log/tf_writer.go:116]: That's what Crowdstrike thought:
https://www.spiceworks.com/it-security/network-security/news/crowdstrike-reveals-root-cause-analysis-global-outage/

If the regex changes, we'll have a different number of elements, which could result in an array index out of bounds. We should check here to be sure, and throw an error if the length mismatches expectations instead of assuming it'll always stay the same.

File: docs/_docs/04_reference/cli-options.md (hunk 23 above)
Comment (yhakbar) [reply docs/_docs/04_reference/cli-options.md]: Na, I was saying I think this is better as two links. You can see the md [here](https://github.com/gruntwork-io/terragrunt/pull/3338#discussion_r1731690318). It's not worth changing now, though. I'll look to adjust it later.

File: internal/log/tf_writer.go (hunk 27 above)
Comment (levkohimins) [reply internal/log/tf_writer.go:116]: Thanks for the explanation. I will add this check in the next PR.

Comment (levkohimins) [reply internal/log/tf_writer.go]: Done.

File: docs/_docs/04_reference/cli-options.md (hunk 22 above)
Comment (levkohimins) [reply docs/_docs/04_reference/cli-options.md]: Fixed.

File: docs/_docs/04_reference/cli-options.md (hunk 23 above)
Comment (levkohimins) [reply docs/_docs/04_reference/cli-options.md]: Ah, roger. Fixed.

**Review by yhakbar — APPROVED** [review]

**Review by yhakbar — DISMISSED** [review]

**Review by denis256 — APPROVED** [review]

**Review by yhakbar — DISMISSED** [review]

**Review by denis256 — APPROVED** [review]

**Comment by levkohimins** [comment]
Resolved in [v0.67.0](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.67.0) release.
