### PR TITLE
fix: Emit output from `run_cmd` when included

### LINKED ISSUE #5400: No output form run_cmd from root.hlc included in stack
## Describe the bug

Starting from version v0.89,0 the ouput from run_cmd is not shown in the following case
- run_cmd is used in root.hcl
- root.hcl is included in unit that is used in a stack

The output "-------------------- echo in root.hcl" should be displayed

```
terragrunt_linux_amd64.v0.98.0 init  --all  

10:17:58.529 INFO   Generating unit unit from ./app/terragrunt.stack.hcl
10:17:58.536 INFO   Unit queue will be processed for init in this order:
- Unit app/.terragrunt-stack/unit

++++++++++++++++ echo in terragrunt.hcl
10:17:58.593 STDOUT [app/.terragrunt-stack/unit] terraform: Initializing the backend...
10:17:58.593 STDOUT [app/.terragrunt-stack/unit] terraform: Initializing provider plugins...
10:17:58.593 STDOUT [app/.terragrunt-stack/unit] terraform: Terraform has been successfully initialized!
10:17:58.593 STDOUT [app/.terragrunt-stack/unit] terraform: 
10:17:58.593 STDOUT [app/.terragrunt-stack/unit] terraform: You may now begin working with Terraform. Try running "terraform plan" to see
10:17:58.593 STDOUT [app/.terragrunt-stack/unit] terraform: any changes that are required for your infrastructure. All Terraform commands
10:17:58.594 STDOUT [app/.terragrunt-stack/unit] terraform: should now work.
10:17:58.594 STDOUT [app/.terragrunt-stack/unit] terraform: If you ever set or change modules or backend configuration for Terraform,
10:17:58.594 STDOUT [app/.terragrunt-stack/unit] terraform: rerun this command to reinitialize your working directory. If you forget, other
10:17:58.594 STDOUT [app/.terragrunt-stack/unit] terraform: commands will detect it and remind you to do so if necessary.

❯❯ Run Summary  1 units  59ms
   ────────────────────────────
   Succeeded    1

```

## Steps To Reproduce

Create the following setup and do
cd /live
terragrunt init  --all  

### File: ./live/app/terragrunt.stack.hcl
```plaintext
unit "unit" {
  source = "${get_repo_root()}/modules/unit"
  path   = "unit"
}
```

### File: ./live/root.hcl
```plaintext
locals {
  foo = run_cmd("bash", "-c", "echo -------------------- echo in root.hcl;")
}
```

### File: ./modules/unit/terragrunt.hcl
```plaintext


include "root" {
  path= find_in_parent_folders("root.hcl")
  expose = true
}

inputs = {
  test =   run_cmd("bash", "-c", "echo ++++++++++++++++ echo in terragrunt.hcl;")
  foo = include.root.locals.foo
}

```

### File: ./modules/unit/main.tf
```plaintext
```

## Expected behavior

Output should include "-------------------- echo in root.hcl" as in version v0.88.1 and prior

```
terragrunt_linux_amd64.v0.88.1 init  --all  

10:24:48.945 INFO   Generating unit unit from ./app/terragrunt.stack.hcl
-------------------- echo in root.hcl
10:24:48.965 INFO   The runner at . will be processed in the following order for command init:
Group 1
- Unit ./app/.terragrunt-stack/unit


++++++++++++++++ echo in terragrunt.hcl
10:24:49.030 STDOUT [app/.terragrunt-stack/unit] terraform: Initializing the backend...
10:24:49.030 STDOUT [app/.terragrunt-stack/unit] terraform: Initializing provider plugins...
10:24:49.031 STDOUT [app/.terragrunt-stack/unit] terraform: Terraform has been successfully initialized!
10:24:49.031 STDOUT [app/.terragrunt-stack/unit] terraform: 
10:24:49.031 STDOUT [app/.terragrunt-stack/unit] terraform: You may now begin working with Terraform. Try running "terraform plan" to see
10:24:49.031 STDOUT [app/.terragrunt-stack/unit] terraform: any changes that are required for your infrastructure. All Terraform commands
10:24:49.031 STDOUT [app/.terragrunt-stack/unit] terraform: should now work.
10:24:49.031 STDOUT [app/.terragrunt-stack/unit] terraform: If you ever set or change modules or backend configuration for Terraform,
10:24:49.031 STDOUT [app/.terragrunt-stack/unit] terraform: rerun this command to reinitialize your working directory. If you forget, other
10:24:49.031 STDOUT [app/.terragrunt-stack/unit] terraform: commands will detect it and remind you to do so if necessary.
``` 

## Must haves

- [ ] Steps for reproduction provided.

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

Start of behavior terragrunt  v0.89.0
Ubuntu 24.04.2 LTS

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #5400.

Ensures that the cached entry for `run_cmd` has the stdout and stderr captured for replay when the writers are available.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Release Notes

* **Bug Fixes**
  * Fixed an issue where `run_cmd` output from included configuration files was not properly displayed during execution. Output is now replayed correctly across configuration discovery and execution phases.

### CODE REVIEW

File: pkg/config/config_helpers.go [hunk 1]
```diff
@@ -46,6 +48,24 @@ const (
 	matchedPats   = 2
 )
 
+// RunCmdCacheEntry stores run_cmd results including output for replay.
+// This allows the output to be replayed on cache hits, which is necessary
+// when the command was first executed during discovery phase (with io.Discard writers)
+// but needs to show output during the execution phase (with real writers).
+type RunCmdCacheEntry struct {
```
Comment (denis256) [inline pkg/config/config_helpers.go:55]: Not sure if we need this struct to be public, it is used only in this package

File: pkg/config/config_helpers.go [hunk 2]
```diff
@@ -46,6 +48,24 @@ const (
...
+	// Stdout is the raw stdout of the command.
+	Stdout string
+	// Stderr is the raw stderr of the command.
+	Stderr string
+	// replayOnce ensures output is replayed exactly once to a real (non-Discard) writer.
+	replayOnce sync.Once
+}
+
+// Value returns the whitespace-trimmed stdout, which is the return value of run_cmd.
+func (e *RunCmdCacheEntry) Value() string {
```
Comment (denis256) [inline pkg/config/config_helpers.go:65]: Not sure about the order of code - it is now mixed Struct / Function / Consts / Vars / Functions

**Review by denis256 — APPROVED** [review]
