### PR TITLE
fix: Fixing `.tf` vs `.tofu` extension parity

### LINKED ISSUE #4793: `*.tofu` files are ignored, only `*.tf` files are recognized
## Describe the bug

`*.tofu` files are not recognized by terragrunt as we can see in the source code, it's mostly globs on `*.tf`.

```
% git rev-parse HEAD
ffda97a1cf0161264a902c2a24016fc6d01618e8
% rg -g '*.go' '\*\.(tofu|tf)'
tf/getproviders/constraints.go
26:     tfFiles, err := filepath.Glob(filepath.Join(workingDir, "*.tf"))
33:     tofuFiles, err := filepath.Glob(filepath.Join(workingDir, "*.tofu"))

config/config_helpers.go
1100:// readTFVarsFile reads a *.tfvars or *.tfvars.json file and returns the contents as a JSON encoded string

cli/commands/run/run.go
77:const TerraformExtensionGlob = "*.tf"
626:    definesBackend, err := util.Grep(terraformBackendRegexp, opts.WorkingDir+"/**/*.tf")
640:    definesJSONBackend, err := util.Grep(terraformJSONBackendRegexp, opts.WorkingDir+"/**/*.tf.json")

cli/commands/aws-provider-patch/aws-provider-patch.go
82:// NOTE: this method only supports *.tf files right now. Terraform code defined in *.json files is not currently
120:                    matches, err := zglob.Glob(moduleAbsPath + "/**/*.tf")

cli/commands/run/download_source_test.go
534:                                    ExcludeFromCopy: &[]string{"*.tfstate", "excluded_dir/"},
537:                    expectedExcludeFiles: []string{"*.tfstate", "excluded_dir/"},

cli/commands/run/errors.go
42:     return "Did not find any Terraform files (*.tf) or OpenTofu files (*.tofu) in " + string(path)

cli/commands/run/download_source.go
196:    tfFiles, err := filepath.Glob(terraformSource.WorkingDir + "/*.tf")

internal/runner/common/unit_resolver.go
381:    matches, err := filepath.Glob(filepath.Join(filepath.Dir(terragruntConfigPath), "*.tf"))

internal/remotestate/remote_state.go
160:    file, err := os.CreateTemp("", "*.tfstate")
% 
```

## Steps To Reproduce

Create a Tofu module with `*.tofu` files and no `*.tf` files. Drop-in a `terragrunt.hcl`, try to do some `terragrunt run --log-level=debug …` and you will see:

```
14:53:55.109 DEBUG  Unit . does not have an associated terraform configuration and will be skipped.
```

## Expected behavior

`.tofu` files are first class citizens the way `.tf` files are.

## Versions

```
% terragrunt --version
terragrunt version v0.86.0
% tofu --version
OpenTofu v1.10.5
on linux_amd64
% nixos-version 
25.11.20250821.323333f (Xantusia)
% 
```

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes `.tf` vs `.tofu` extension parity

Fixes #4793

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added support for `.tofu` wherever `.tf` was supported.

## Summary by CodeRabbit

- New Features
  - Added OpenTofu support: CLI recognizes .tofu alongside .tf for detection, backend/module checks, and validation.

- Refactor
  - Centralized Terraform/OpenTofu file discovery and regex searching via shared utilities; JSON-based Terraform files are excluded from detection.

- Chores
  - Removed an external glob dependency in favor of internal file-detection utilities.

- Tests / CI
  - Extensive .tofu/.tf tests added; CI jobs updated to include tofu tags; one integration test now requires both aws and tofu tags; some test assertions adjusted.

### CODE REVIEW

**Comment by denis256** [comment]
I think, we should add tests for .tofu file handling so that any future changes breaking detection are caught automatically.

File: cli/commands/aws-provider-patch/aws-provider-patch.go [hunk 1]
```diff
@@ -114,15 +113,17 @@ func findAllTerraformFilesInModules(opts *options.TerragruntOptions) ([]string,
...
 				return nil, errors.New(err)
 			}
 
-			terraformFiles = append(terraformFiles, matches...)
+			// Filter out JSON files (.tf.json, .tofu.json, or any .json) as hclwrite cannot parse JSON
+			for _, file := range moduleFiles {
+				if !strings.HasSuffix(file, ".json") {
+					terraformFiles = append(terraformFiles, file)
+				}
+			}
```
Comment (mieseprem) [inline cli/commands/aws-provider-patch/aws-provider-patch.go:126]: Wouldn't this change now also read files that have nothing to do with Terraform/Tofu (e.g., *.md, *.png, *.tpl, ...)?

Comment (yhakbar) [reply cli/commands/aws-provider-patch/aws-provider-patch.go:126]: No, `moduleFiles` should only return files that _do_ have to do with OpenTofu/Terraform, by virtue of returning from `FindTFFiles`. Please feel free to double-check and correct me if I missed something.

**Review by denis256 — APPROVED** [review]
