### PR TITLE
Fixes destroy order for `apply -destroy` alias

### LINKED ISSUE #3007: Wrong order of stack execution when running apply with `-destroy`
**Describe the bug**
- I have three modules, namely `A`, `B` and `C`. 
- Order of execution is `A` -> `B` -> `C` when running `terragrunt run-all apply`
- Order of destroy is `C` -> `B` -> `A` when running `terragrunt run-all destroy`
- Order of `terragrunt run-all apply -destroy` is coming as `A` -> `B` -> `C` which is incorrect.

**To Reproduce**
Create more than one dependent modules, execute them  and then try to destroy using `terragrunt run-all apply -destroy` command.

**Expected behavior**
`terragrunt apply -destroy` should take the behaviour of `destroy` sub command and not the `apply`

**Versions**
- Terragrunt version: 0.53.0
- Terraform version: 1.6.2
- Environment details (Ubuntu 20.04, Windows 10, etc.): darwin_arm64

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

This PR fixes the destroy order for `terraform apply -destroy` command which is an alias for the `terraform destroy` command. 

Fixes #3007.

### CODE REVIEW

File: test/integration_test.go [hunk 1]
```diff
@@ -280,6 +281,40 @@ func TestTerragruntProviderCache(t *testing.T) {
...
+	cleanupTerraformFolder(t, TEST_FIXTURE_DESTROY_ORDER)
+	tmpEnvPath := copyEnvironment(t, TEST_FIXTURE_DESTROY_ORDER)
+	rootPath := util.JoinPath(tmpEnvPath, TEST_FIXTURE_DESTROY_ORDER, "app")
+
+	runTerragrunt(t, fmt.Sprintf("terragrunt run-all apply --terragrunt-non-interactive --terragrunt-working-dir %s", rootPath))
+
+	showStdout := bytes.Buffer{}
+	showStderr := bytes.Buffer{}
+
+	err := runTerragruntCommand(t, fmt.Sprintf("terragrunt run-all destroy --terragrunt-non-interactive --terragrunt-working-dir %s", rootPath), &showStdout, &showStderr)
```
Comment (denis256) [inline test/integration_test.go:296]: I think it is better to use `runTerragruntCommandWithOutput()` it will return the output results and will also log outputs to terminal which will help to debug the issue

Comment (levkohimins) [reply test/integration_test.go:296]: Redone. Thanks.

**Review by denis256 — APPROVED** [review]

**Review by denis256 — APPROVED** [review]

**Comment by levkohimins** [comment]
Resolved in [v0.56.5](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.56.5) release.
