### PR TITLE
fix: Fixing exit codes for `run --all`

### LINKED ISSUE #5379: Exit code incorrect
## Describe the bug

The exit code of `terragrunt run --all` is `0` even when errors occur. It doesn't seem to matter what kind of error, below is just an example of some arbitrary error, but the same happens when e.g. OpenTofu plan fails in some unit.
Possibly related to the recent changes regarding `-detailed-exitcode` because as far as I can tell it still worked fine in [alpha-2026011301](https://github.com/gruntwork-io/terragrunt/releases/tag/alpha-2026011301) and started happening as of [v0.98.0-rc2026011501](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.98.0-rc2026011501) or some of the other v0.98 RCs.
Also, since the v0.98 RCs `-detailed-exitcode` doesn't seem to work anymore because it exits with `0` despite having changes.

```
$ terragrunt run --all --filter "terragrunt/test" -- plan xxxx
14:58:23.409 INFO   Unit queue will be processed for plan in this order:
- Unit terragrunt/test

14:58:23.423 INFO   [terragrunt/test] Downloading Terraform configurations from ./terragrunt/test into ./terragrunt/test/.terragrunt-cache/86zAkMlaRj2eIR8ASp5wRNvGgjM/XJ2IEDBSMaGQu0rOYSs_drp-o6Y
14:58:23.424 ERROR  Run failed: error occurred:

* Did not find any Terraform files (*.tf) or OpenTofu files (*.tofu) in ./terragrunt/test/.terragrunt-cache/86zAkMlaRj2eIR8ASp5wRNvGgjM/XJ2IEDBSMaGQu0rOYSs_drp-o6Y


❯❯ Run Summary  1 units  14ms
   ────────────────────────────
   Failed       1

$ echo $?
0
```

```
# terragrunt/test/terragrunt.hcl
terraform {
  source = "."
}
```

## Steps To Reproduce

Run above example.

## Expected behavior

The exit code should not be 0 when errors occur.

## Must haves

- [x] Steps for reproduction provided.

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: terragrunt version v0.98.0
- OpenTofu/Terraform version: OpenTofu v1.11.3
- Environment details (Ubuntu 20.04, Windows 10, etc.): Debian GNU/Linux 13 (trixie)

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes exit code for `run --all` failures.

Fixes #5379

Fixing this resulted in a ton of testing updates, as our assertions assumed nil errors returned when no parsing errors occurred or the like.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Release Notes

* **New Features**
  * Added backend bootstrap support for improved infrastructure initialization.
  * Introduced remote state output fetching for dependency resolution.
  * Enhanced fail-fast early exit handling with clearer error messages.

* **Bug Fixes**
  * Improved error reporting and detection for unit failures and early exits.
  * Fixed checksum verification behavior.

* **Tests**
  * Added JSON report schema validation and enhanced fail-fast test coverage.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: internal/runner/runnerpool/errors.go [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+// NewUnitFailedError creates a new UnitFailedError.
+func NewUnitFailedError(unitPath string) error {
+	return errors.New(UnitFailedError{UnitPath: unitPath})
+}
+
+// findFailedDependency finds the first failed dependency for a given entry.
+func findFailedDependency(entry *queue.Entry, q *queue.Queue) string {
+	for _, dep := range entry.Component.Dependencies() {
+		for _, e := range q.Entries {
+			if e.Component.Path() == dep.Path() {
```
Comment (denis256) [inline internal/runner/runnerpool/errors.go:51]: I was thinking that map lookup may help here - will be O(1) instead of iteration of O(n^2)

File: internal/runner/runnerpool/errors.go [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+
+import (
+	"fmt"
+
+	"github.com/gruntwork-io/terragrunt/internal/errors"
+	"github.com/gruntwork-io/terragrunt/internal/queue"
+)
+
+// UnitEarlyExitError is an error type for units that didn't run due to dependency failure.
+type UnitEarlyExitError struct {
```
Comment (denis256) [inline internal/runner/runnerpool/errors.go:11]: No unit tests cover UnitEarlyExitError. If someone changes the error lookup logic later, we’ll likely only catch it in integration tests

File: internal/runner/runnerpool/errors.go (hunk 1 above)
Comment (yhakbar) [reply internal/runner/runnerpool/errors.go:51]: People very infrequently have a massive number of dependencies, though. For this size, aren't we more likely to be better off just iterating through contiguous memory?

File: internal/runner/runnerpool/errors.go (hunk 2 above)
Comment (yhakbar) [reply internal/runner/runnerpool/errors.go:11]: I'll add something for that.
