### PR TITLE
bug: improved dependency config path validation

### LINKED ISSUE #5206: Panic on unresolvable dependency config_path
### The Error Message

Please paste the exact error message you received:

```bash
panic: not a string

goroutine 90 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x31e5b58?, 0x4c19940?}}, {0x25cbb60?, 0x4bda950?}})
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.17.0/cty/value_ops.go:1432 +0x11e
github.com/gruntwork-io/terragrunt/config.getTerragruntOutput(0xc000fe2900, {0x3214b70, 0xc001990d08}, {{{{0x31e5b58, 0x4c19940}}, {0x25cbb60, 0x4bda950}}, 0x0, 0x0, 0x0, ...})
	/home/runner/work/terragrunt/terragrunt/config/dependency.go:571 +0x57
github.com/gruntwork-io/terragrunt/config.getTerragruntOutputIfAppliedElseConfiguredDefault(0xc000fe2900, {0x3214b70, 0xc001990d08}, {{{{0x31e5b58, 0x4c19940}}, {0x25cbb60, 0x4bda950}}, 0x0, 0x0, 0x0, ...})
	/home/runner/work/terragrunt/terragrunt/config/dependency.go:498 +0x1db
github.com/gruntwork-io/terragrunt/config.(*Dependency).setRenderedOutputs(0xc0002d51f0, 0xc000711a90?, {0x3214b70?, 0xc001990d08?})
	/home/runner/work/terragrunt/terragrunt/config/dependency.go:172 +0x1c5
github.com/gruntwork-io/terragrunt/config.dependencyBlocksToCtyValue.func1()
	/home/runner/work/terragrunt/terragrunt/config/dependency.go:436 +0xac
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.18.0/errgroup/errgroup.go:93 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 140
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.18.0/errgroup/errgroup.go:78 +0x95
make: *** [Makefile:22: plan] Error 2

```

### Current Problems

Panic is not a error message

### What the Error Message Should Say

Please suggest how the error message could be improved:

```bash
Dependency xy not found
```

## Error Reproduction Steps

i am actually unsure, i just had a depdency block as part of one of my units that pointed to a not existing folder. 
```
dependency "organisation" {
  config_path =  find_in_parent_folders("wrong-dir-name")
}
```

## Environment Information

- **Terragrunt version**: 0.94.0
- **OpenTofu/Terraform version**:
- **Operating system**: linux

## Additional Context

Any other information that might help improve the error message.

### PR DESCRIPTION
**Pull request by denis256**
## Description

* simplified null passing in options
* improved function to validate config path string
* added integration tests to track dependency errors

Fixes #5206.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Strengthened dependency config_path validation to reject null/unknown/non-string/empty values and now report clearer "invalid config_path" errors.
  * Improved handling of missing or incorrectly referenced dependency paths; disabled dependencies are skipped from config_path validation.

* **Tests**
  * Added/updated tests covering invalid, missing, and disabled dependency paths and updated error-message expectations.

* **Documentation**
  * Terminology updates for filter-related docs to use "expressions" for consistency.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: config/dependency.go [hunk 1]
```diff
@@ -250,41 +250,65 @@ func decodeDependencies(ctx *ParsingContext, l log.Logger, decodedDependency Ter
...
-					l.Warnf("Error reading partial config for dependency %s: %v", dep.Name, err)
-				}
-			} else {
-				dep.Enabled = cachedDependency.Enabled
-				dep.Inputs = &cachedDependency.Inputs
-			}
+
+		// Missing config file - warn and skip
+		if !util.FileExists(depPath) {
+			l.Warnf("Dependency %q config file not found at %s, skipping", dep.Name, depPath)
```
Comment (yhakbar) [inline config/dependency.go]: Should we really skip this? This shouldn't ever happen if users disable their dependency, right?

**Review by yhakbar — APPROVED** [review]
