### PR TITLE
bug: false positive parsing errors

### LINKED ISSUE #5169: 'There is no variable named "dependency" ' error despite successful CLI commands
## Describe the bug

When running terragrunt commands like `init`, `plan` or `apply`, the error message below is displayed before the `terraform` log messages. Despite it indicating some issue with the `dependency` defined in the `.hcl` file, the commands always run successfully.

```bash
12:16:48.589 ERROR  Error: Unknown variable
12:16:48.589 ERROR    on ../layer.hcl line 6:
12:16:48.589 ERROR     6:   name = dependency.domain.outputs.name
12:16:48.589 ERROR  There is no variable named "dependency".
```

I am not sure if this error log is due to some `terragrunt` limitation on the way IaC files are structured in my case. You can see a minimal example below.

## Steps To Reproduce

I have created an minimal example of the original source code [here](https://github.com/pedroalopes/terraform_dependency_bug). The folder structure splits the infrastructure into two groups ("stacks"), one for domain and another for compute, where the second depends on the first one. Inside each folder, there is a folder for each environment (example only has `dev`). 

You would need to replace the `aws_account_id` in the `stage.hcl` files with a real account id.

The `compute/main.tf` is empty as it is not necessary to actually `apply` anything to get the error.

To get the error log, I ran these commands:
- Inside `deployment/domain/dev` run `terragrunt init` followed by `terragrunt apply -auto-approve`
- Inside `deployment/compute/dev`, run `terragrunt init` (or `plan` or `apply).

Image

## Expected behavior

No error log is expected in this case.
This structure/setup was working fine before upgrading from `terraform=1.7.4` and `terragrunt=0.55.14`.

## Must haves

- [x] Steps for reproduction provided.

## Nice to haves

- [x] Terminal output
- [x] Screenshots

## Versions

- Terragrunt version: 0.93.11
- OpenTofu/Terraform version: 1.13.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): MacOS (darwin_arm64), but can I also see the error in CI/CD running on Linux

### PR DESCRIPTION
**Pull request by denis256**
## Description

* fixed false positive errors during discovery
* added integration test to track parsing errors

Before:

image

After:

image

Fixes #5169.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Suppressed spurious "Unknown variable" diagnostics when including configs that reference unresolved dependency outputs, preventing misleading errors during partial parsing and include handling.

* **Tests**
  * Added regression fixtures and an integration test to verify include directives with dependency blocks no longer produce false positive errors.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: config/dependency.go [hunk 1]
```diff
@@ -285,7 +285,9 @@ func decodeDependencies(ctx *ParsingContext, l log.Logger, decodedDependency Ter
 			return nil, err
 		}
 
-		depCtx := ctx.WithDecodeList(TerragruntFlags).WithTerragruntOptions(depOpts)
+		// Suppress diagnostics during partial parsing to avoid false positive errors for unresolved dependency variables
+		suppressOpts := append(slices.Clone(ctx.ParserOptions), hclparse.WithDiagnosticsWriter(io.Discard, true))
+		depCtx := ctx.WithDecodedDependencies(nil).WithDecodeList(TerragruntFlags).WithTerragruntOptions(depOpts).WithParseOption(suppressOpts)
```
Comment (yhakbar) [inline config/dependency.go]: This is weird. Why do we pass a nil here?

File: test/integration_regressions_test.go [hunk 2]
```diff
@@ -673,3 +675,63 @@ func TestNotExistingDependency(t *testing.T) {
...
+	t.Parallel()
+
+	helpers.CleanupTerraformFolder(t, testFixtureDependencyWarnings)
+	tmpEnvPath := helpers.CopyEnvironment(t, testFixtureDependencyWarnings)
+	depPath := filepath.Join(tmpEnvPath, testFixtureDependencyWarnings, "dep")
+	mainPath := filepath.Join(tmpEnvPath, testFixtureDependencyWarnings, "main")
+
+	helpers.RunTerragrunt(
+		t,
+		"terragrunt apply --auto-approve --non-interactive --working-dir "+depPath,
```
Comment (yhakbar) [inline test/integration_regressions_test.go]: Let's get rid of these `--auto-approve`

File: test/integration_regressions_test.go [hunk 3]
```diff
@@ -673,3 +675,63 @@ func TestNotExistingDependency(t *testing.T) {
...
+	)
+
+	_, _, err := helpers.RunTerragruntCommandWithOutput(
+		t,
+		"terragrunt apply -auto-approve --non-interactive --working-dir "+mainPath,
```
Comment (yhakbar) [inline test/integration_regressions_test.go]: Let's get rid of these `--auto-approve`

File: test/integration_regressions_test.go [hunk 4]
```diff
@@ -673,3 +675,63 @@ func TestNotExistingDependency(t *testing.T) {
...
+
+	helpers.CleanupTerraformFolder(t, testFixtureDependencyIncludeError)
+	tmpEnvPath := helpers.CopyEnvironment(t, testFixtureDependencyIncludeError)
+	depPath := filepath.Join(tmpEnvPath, testFixtureDependencyIncludeError, "dep")
+	unitPath := filepath.Join(tmpEnvPath, testFixtureDependencyIncludeError, "unit")
+
+	// First apply the dependency so it has outputs
+	helpers.RunTerragrunt(
+		t,
+		"terragrunt apply --auto-approve --non-interactive --working-dir "+depPath,
```
Comment (yhakbar) [inline test/integration_regressions_test.go]: Let's get rid of these `--auto-approve`

File: test/integration_regressions_test.go [hunk 5]
```diff
@@ -673,3 +675,63 @@ func TestNotExistingDependency(t *testing.T) {
...
+	)
+
+	// Now apply the unit that includes layer.hcl with dependency block
+	// This should NOT produce any ERROR-level diagnostics about "Unknown variable"
+	stdout, stderr, err := helpers.RunTerragruntCommandWithOutput(
+		t,
+		"terragrunt apply --auto-approve --non-interactive --working-dir "+unitPath,
```
Comment (yhakbar) [inline test/integration_regressions_test.go]: Let's get rid of these `--auto-approve`

File: config/config_helpers.go [hunk 6]
```diff
@@ -732,12 +733,11 @@ func ParseTerragruntConfig(ctx *ParsingContext, l log.Logger, configPath string,
 	// Preserve the ParserOptions from the parent context when creating the new context
 	// This ensures that error suppression handlers and other parser options are propagated
 	// to nested read_terragrunt_config calls
-	parserOptions := ctx.ParserOptions
+	// Additionally, suppress diagnostics during parsing to avoid false positive errors for unresolved
+	// dependency variables in the target config (the target config's dependencies haven't been resolved yet)
+	parserOptions := append(slices.Clone(ctx.ParserOptions), hclparse.WithDiagnosticsWriter(io.Discard, true))
```
Comment (thisguycodes) [inline config/config_helpers.go]: Why do we need to clone here?
