### PR TITLE
Fix panic when S3 Bucket Versioning is not enabled.

### LINKED ISSUE #64: Terragrunt Tests Fail in My LocalDev
Not sure when this started happening and why it's apparently not happening in CI, but Terragrunt tests consistently fail when I run them locally. It's late here, so I'm just recording this but haven't dug into why yet. Here's the test output:

```
[terragrunt] 2016/12/05 01:26:46 Reading Terragrunt config file at /var/folders/g0/0gkdx4sj4qv5gzxfcznscdpw0000gn/T/.terragrunt053106030
[terragrunt] 2016/12/05 01:26:46 Initializing remote state for the s3 backend
Remote state S3 bucket terragrunt-test-bucket-oapzqi does not exist or you don't have permissions to access it. Would you Terragrunt to create it? (y/n)
[terragrunt] 2016/12/05 01:26:46 The non-interactive flag is set to true, so assuming 'yes' for all prompts
[terragrunt] 2016/12/05 01:26:46 Creating S3 bucket terragrunt-test-bucket-oapzqi
[terragrunt] 2016/12/05 01:26:47 S3 bucket terragrunt-test-bucket-oapzqi created.
[terragrunt] 2016/12/05 01:26:47 Enabling versioning on S3 bucket terragrunt-test-bucket-oapzqi
[terragrunt] 2016/12/05 01:26:48 Configuring remote state for the s3 backend
[terragrunt] 2016/12/05 01:26:48 Running command: terraform remote config -backend s3 -backend-config=encrypt=true -backend-config=bucket=terragrunt-test-bucket-oapzqi -backend-config=key=terraform.tfstate -backend-config=region=us-west-2
Initialized blank state with remote state enabled!
Remote state configured and pulled.
[terragrunt] 2016/12/05 01:26:49 Attempting to acquire lock for state file terragrunt-test-fixture in DynamoDB
[terragrunt] 2016/12/05 01:26:49 Lock table terragrunt_locks does not exist in DynamoDB. Will need to create it just this first time.
[terragrunt] 2016/12/05 01:26:49 Creating table terragrunt_locks in DynamoDB
[terragrunt] 2016/12/05 01:26:50 Table terragrunt_locks is not yet in active state. Will check again after 10s.
[terragrunt] 2016/12/05 01:27:00 Success! Table terragrunt_locks is now in active state.
[terragrunt] 2016/12/05 01:27:00 Attempting to create lock item for state file terragrunt-test-fixture in DynamoDB table terragrunt_locks
[terragrunt] 2016/12/05 01:27:00 Lock acquired!
[terragrunt] 2016/12/05 01:27:00 Running command: terraform apply fixture/
data.template_file.test: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

rendered_template =
[terragrunt] 2016/12/05 01:27:01 Attempting to release lock for state file terragrunt-test-fixture in DynamoDB
[terragrunt] 2016/12/05 01:27:01 Lock released!
[terragrunt] 2016/12/05 01:27:03 Reading Terragrunt config file at fixture-lock/.terragrunt
Are you sure you want to acquire a long-term lock? (y/n)
[terragrunt] 2016/12/05 01:27:03 The non-interactive flag is set to true, so assuming 'yes' for all prompts
[terragrunt] 2016/12/05 01:27:03 Acquiring long-term lock. To release the lock, use the release-lock command.
[terragrunt] 2016/12/05 01:27:03 Attempting to acquire lock for state file terragrunt-test-fixture-lock in DynamoDB
[terragrunt] 2016/12/05 01:27:03 Attempting to create lock item for state file terragrunt-test-fixture-lock in DynamoDB table terragrunt_locks
[terragrunt] 2016/12/05 01:27:03 Lock acquired!
[terragrunt] 2016/12/05 01:27:03 Reading Terragrunt config file at fixture-lock/.terragrunt
[terragrunt] 2016/12/05 01:27:03 Attempting to acquire lock for state file terragrunt-test-fixture-lock in DynamoDB
[terragrunt] 2016/12/05 01:27:03 Attempting to create lock item for state file terragrunt-test-fixture-lock in DynamoDB table terragrunt_locks
[terragrunt] 2016/12/05 01:27:03 Someone already has a lock on state file terragrunt-test-fixture-lock! arn:aws:iam::087285199408:user/josh@phoenixdevops.com@10.0.1.9 acquired the lock on 2016-12-05 08:27:03.216425023 +0000 UTC.
Unable to acquire lock for item terragrunt-test-fixture-lock after 1 retries.
exit status 1
FAIL	github.com/gruntwork-io/terragrunt/test	17.631s
```

### LINKED ISSUE #65: Terragrunt Panics when Checking an S3 Bucket for Which Versioning is Not Enabled
When you run `terragrunt` where a `.terragrunt` file specifies an S3 Bucket that exists but for which versioning has not been enabled, it panics when instead it should issue a warning. Here are the steps to reproduce.

1. Create an S3 Bucket but do NOT enable versioning.
2. Specify that S3 Bucket Name in a `.terragrunt` file.
3. Run `terragrunt plan` or `terragrunt apply`.
4. Terragrunt will panic.

I received this output:

```
> terragrunt plan
[terragrunt] 2016/12/05 01:30:59 Reading Terragrunt config file at .terragrunt
[terragrunt] 2016/12/05 01:30:59 Initializing remote state for the s3 backend
[terragrunt] 2016/12/05 01:31:00 runtime.errorString runtime error: invalid memory address or nil pointer dereference
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/errors/errors.go:70 (0x69e31)
/usr/local/go/src/runtime/asm_amd64.s:472 (0x59d8e)
	call32: MOVQ	DX, 0(SP);			\
/usr/local/go/src/runtime/panic.go:443 (0x2ba89)
	gopanic: freedefer(d)
/usr/local/go/src/runtime/panic.go:62 (0x2a145)
	panicmem: panic(memoryError)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x40a39)
	sigpanic: panicmem()
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/remote/remote_state_s3.go:113 (0xca055)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/remote/remote_state_s3.go:49 (0xc96b1)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/remote/remote_state.go:45 (0xc83c8)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/remote/remote_state.go:60 (0xc85a7)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:199 (0x68601)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:102 (0x67475)
/usr/local/go/src/runtime/asm_amd64.s:472 (0x59d8e)
	call32: MOVQ	DX, 0(SP);			\
/usr/local/go/src/reflect/value.go:435 (0x12bc5d)
	Value.call:
/usr/local/go/src/reflect/value.go:303 (0x12a921)
	Value.Call: }
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:480 (0xd13be)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:241 (0xceac5)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/main.go:19 (0x20ce)
/usr/local/go/src/runtime/proc.go:188 (0x2d5a0)
	main: // Make racy client program work: if panicking on
/usr/local/go/src/runtime/asm_amd64.s:1998 (0x5c441)
	goexit: endofpage:
```

The fix is straightforward. I'll submit a PR for it now, but would prefer to fix #64 so that we can write a failing test for it.

### PR DESCRIPTION
**Pull request by josh-padnick**
Fixes #65. My guess is that this is a bug with the AWS SDK for Golang since the interface seems to allow checking a `Status` field, but in practice this field is `nil` unless S3 Bucket Versioning is enabled.

Do NOT merge this until we resolve #64 so that we can write a failing unit test for this to validate that the change.

### CODE REVIEW

File: remote/remote_state_s3.go [hunk 1]
```diff
@@ -109,7 +109,9 @@ func checkIfVersioningEnabled(s3Client *s3.S3, config *RemoteStateConfigS3, terr
 		return errors.WithStackTrace(err)
 	}
 
-	if *out.Status != s3.BucketVersioningStatusEnabled {
+	// NOTE: There must be a bug in the AWS SDK since out == nil when versioning is not enabled. In the future,
+	// check the AWS SDK for updates to see if we can remove "out == nil ||".
+	if out == nil || *out.Status != s3.BucketVersioningStatusEnabled {
```
Comment (brikis98) [inline remote/remote_state_s3.go]: Should this check `out.Status != nil` before dereferencing it as well?
