### PR TITLE
fix: Fixing signal propagation

### LINKED ISSUE #4839: Interrupt leaves state locked
## Describe the bug

When terragrunt is interrupted, like ctrl-c at the 'Do you want to perform these actions?' prompt, the underlying terraform is sent a graceful signal, but the state is left locked. This is notably different behavior than running without terragrunt, where the same action unlocks the state.

It appears that the way terragrunt is interrupt terraform causes terraform to exit more forcefully than when terraform handles the same interrupt

## Steps To Reproduce

This is easier to compare behavior between how terragrunt is wrapping terraform and directly running terraform in a unit that has an empty terragrunt.hcl file (that is, loose terraform files that are valid to be run with terraform alone)

1. terragrunt apply (in a unit where there is a change)
2. at the prompt, press ctrl-c to interrupt
3. terragrunt plan 
4. fails to acquire state lock

for comparison:

1. terraform plan (in a unit where there is a change)
2. at the prompt, press ctrl-c to interrupt
3. terraform plan 
4. plan is successful

Here is a slightly redacted terminal output:

```
$ terragrunt apply
11:45:17.500 STDOUT terraform: data.aws_caller_identity.current: Reading...
11:45:17.501 STDOUT terraform: data.aws_region.current: Reading...
<redacted>
11:45:18.047 STDOUT terraform: Terraform used the selected providers to generate the following execution
11:45:18.047 STDOUT terraform: plan. Resource actions are indicated with the following symbols:
11:45:18.047 STDOUT terraform:   ~ update in-place
11:45:18.047 STDOUT terraform: Terraform will perform the following actions:
<redacted>
11:45:18.047 STDOUT terraform: Plan: 0 to add, 1 to change, 0 to destroy.
11:45:18.048 STDOUT terraform:
11:45:18.048 STDOUT terraform: Do you want to perform these actions?
11:45:18.048 STDOUT terraform:   Terraform will perform the actions described above.
11:45:18.048 STDOUT terraform:   Only 'yes' will be accepted to approve.
11:45:18.048 STDOUT terraform:   Enter a value:
<ctrl-c pressed here>
11:45:19.845 STDOUT terraform: Interrupt received.
11:45:19.845 INFO   Interrupt signal received. Gracefully shutting down...
11:45:19.846 STDOUT terraform: Please wait for Terraform to exit or data loss may occur.
11:45:19.846 STDOUT terraform: Gracefully shutting down...
11:45:19.846 STDERR terraform: ╷
11:45:19.846 STDERR terraform: │ Error: error asking for approval: context canceled
11:45:19.846 STDERR terraform: │
11:45:19.846 STDERR terraform: │
11:45:19.846 STDERR terraform: ╵
11:45:19.867 ERROR  terraform invocation failed in .
11:45:19.867 ERROR  error occurred:

* Failed to execute "terraform apply" in .
  ╷
  │ Error: error asking for approval: context canceled
  │
  │
  ╵

  signal: killed

$ terragrunt plan
11:45:24.037 STDERR terraform: ╷
11:45:24.038 STDERR terraform: │ Error: Error acquiring the state lock
11:45:24.038 STDERR terraform: │
11:45:24.038 STDERR terraform: │ Error message: operation error DynamoDB: PutItem, https response error
11:45:24.038 STDERR terraform: │ StatusCode: 400, RequestID:
```

Here is with `TF_LOG=debug terragrunt apply` around the interrupt:
```
12:06:41.502 STDOUT terraform: Do you want to perform these actions?
12:06:41.502 STDOUT terraform:   Terraform will perform the actions described above.
12:06:41.502 STDOUT terraform:   Only 'yes' will be accepted to approve.
12:06:41.502 STDOUT terraform:   Enter a value:
12:06:43.165 STDOUT terraform: Interrupt received.
12:06:43.165 STDOUT terraform: Please wait for Terraform to exit or data loss may occur.
12:06:43.165 INFO   Interrupt signal received. Gracefully shutting down...
12:06:43.166 STDERR terraform: ╷
12:06:43.166 STDOUT terraform: Gracefully shutting down...
12:06:43.166 STDERR terraform: │ Error: error asking for approval: interrupted
12:06:43.166 STDERR terraform: │
12:06:43.166 STDERR terraform: │
12:06:43.166 STDERR terraform: ╵
12:06:43.166 INFO   terraform: TF_LOG: backend-s3: Attempting to unlock remote state (DynamoDB only)...: <redacted>
12:06:43.241 ERROR  terraform invocation failed in .
12:06:43.244 ERROR  error occurred:

<the entire debug log is repeated>

  2025-09-15T12:06:41.501-0400 [DEBUG] command: asking for input: "\nDo you want to perform these actions?"
  ╷
  │ Error: error asking for approval: interrupted
  │
  │
  ╵
  2025-09-15T12:06:43.166-0400 [INFO]  backend-s3: Attempting to unlock remote state (DynamoDB only)...: <redacted>

  signal: killed
```

Here is with `TF_LOG=debug terraform apply` around the interrupt:
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: ^C
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...


╷
│ Error: error asking for approval: context canceled
│
│
╵
2025-09-15T12:05:34.934-0400 [INFO]  backend-s3: Attempting to unlock remote state (DynamoDB only)...: <redacted>
2025-09-15T12:05:34.935-0400 [DEBUG] backend-s3: HTTP Request Sent: <redacted GetItem>
2025-09-15T12:05:34.957-0400 [DEBUG] backend-s3: HTTP Response Received: <redacted GetItem>
2025-09-15T12:05:34.958-0400 [DEBUG] backend-s3: HTTP Request Sent: <redacted DeleteItem>
2025-09-15T12:05:34.982-0400 [DEBUG] backend-s3: HTTP Response Received: <redacted DeleteItem>
2025-09-15T12:05:34.982-0400 [INFO]  backend-s3: Unlocked remote state (DynamoDB only): <redacted>
```

## Expected behavior

When terragrunt triggers an interrupt to terraform it should have the same behavior if terraform itself was interrupted. 

## Versions

- Terragrunt version: 0.87.2
- OpenTofu/Terraform version: 1.13.2 / hashicorp/aws v6.13.0, also tested opentofu 1.10.6
- Environment details (Ubuntu 20.04, Windows 10, etc.):  Debian 13 via WSL, also tested on Windows 11, macOS

### LINKED ISSUE #5068: Terragrunt can't close a session gracefully since version 0.86.0
## Describe the bug

Starting with terragrunt version 0.86.0 - and in the current version (v0.93.3) - Terragrunt doesn't have a way to gracefully close a session.

## Reproducing bugs

If you run "terragrunt apply" and then press CTRL+C, the session in the S3 bucket won't automatically delete the lock file. This seems to be fine with versions 0.85.1 and below, but not after.

Below listed the example of my backend S3 settings:
```
terraform {
  backend "s3" {
    bucket        = "terraform"
    encrypt       = true
    key           = "s3/terraform.tfstate"
    region        = "me-central-1"
    use_lockfile  = true
  }
}
```

In contrary, below is example of correct behavior: the older version correctly closes the session if you press CTRL+C instead of YES.

Debian-12, terragrunt-0.85.1 and terraform-1.11.4
```
....
17:02:00.648 STDOUT terraform: Do you want to perform these actions?
17:02:00.648 STDOUT terraform:   Terraform will perform the actions described above.
17:02:00.648 STDOUT terraform:   Only 'yes' will be accepted to approve.
17:02:00.648 STDOUT terraform:   Enter a value:
17:02:03.968 STDERR terraform: ╷
17:02:03.968 STDERR terraform: │ Error: error asking for approval: interrupted
17:02:03.968 STDERR terraform: │
17:02:03.968 STDERR terraform: │
17:02:03.968 STDERR terraform: ╵
17:02:03.969 STDOUT terraform: Interrupt received.
17:02:03.969 STDOUT terraform: Please wait for Terraform to exit or data loss may occur.
17:02:03.969 STDOUT terraform: Gracefully shutting down...
17:02:03.969 INFO   Interrupt signal received. Gracefully shutting down...
17:02:04.370 STDOUT terraform: Releasing state lock. This may take a few moments..

```

Starting with version 0.86.0, terragrunt handles Ctrl+C differently, resulting in the creation of a lock file in S3.

Debian-12, terragrunt-0.86.0, terraform-1.11.4 or terraform-1.13.5

```
....
17:05:42.312 STDOUT terraform: Do you want to perform these actions?
17:05:42.312 STDOUT terraform:   Terraform will perform the actions described above.
17:05:42.312 STDOUT terraform:   Only 'yes' will be accepted to approve.
17:05:42.312 STDOUT terraform:   Enter a value:
17:05:45.822 STDOUT terraform: Interrupt received.
17:05:45.822 STDOUT terraform: Please wait for Terraform to exit or data loss may occur.
17:05:45.822 STDOUT terraform: Gracefully shutting down...
17:05:45.822 STDERR terraform: ╷
17:05:45.822 STDERR terraform: │ Error: error asking for approval: interrupted
17:05:45.823 STDERR terraform: │
17:05:45.823 STDERR terraform: │
17:05:45.823 STDERR terraform: ╵
17:05:45.822 INFO   Interrupt signal received. Gracefully shutting down...
17:05:45.845 ERROR  terraform invocation failed in ./.terragrunt-cache/oVpSlAJz9rHZy1oveSUqbItPfl4/PxHdKso5LrPUTiqcixISDiuYUTs
17:05:45.846 ERROR  error occurred:

* Failed to execute "terraform apply" in ./.terragrunt-cache/oVpSlAJz9rHZy1oveSUqbItPfl4/PxHdKso5LrPUTiqcixISDiuYUTs
  ╷
  │ Error: error asking for approval: interrupted
  │
  │
  ╵
 
  signal: killed


17:06:27.413 STDERR terraform: │ Error: Error acquiring the state lock
17:06:27.413 STDERR terraform: │
17:06:27.413 STDERR terraform: │ Error message: operation error S3: PutObject, https response error
17:06:27.413 STDERR terraform: │ StatusCode: 412, RequestID: WJ78PA7A6WZ6RK6H, HostID:
17:06:27.413 STDERR terraform: │ aFsSNCK31+ttzy7ZI/bFWw0IwiYxlrd7IBpcMaHjJePFweJD3wa8qVb6qbYjNooiU/2wc1lePDYAh1IbAAjPyOc0m6Fa8XJn,
17:06:27.413 STDERR terraform: │ api error PreconditionFailed: At least one of the pre-conditions you
17:06:27.413 STDERR terraform: │ specified did not hold
17:06:27.413 STDERR terraform: │ Lock Info:
17:06:27.413 STDERR terraform: │   ID:        cdd08d4c-d00b-69e6-9bf6-a21447dd7f6d
17:06:27.414 STDERR terraform: │   Path:      ......................../terraform.tfstate
17:06:27.414 STDERR terraform: │   Operation: OperationTypeApply
17:06:27.414 STDERR terraform: │   Who:       user@box
17:06:27.414 STDERR terraform: │   Version:   1.11.4
17:06:27.414 STDERR terraform: │   Created:   2025-11-06 16:05:11.858349346 +0000 UTC
17:06:27.414 STDERR terraform: │   Info:      
17:06:27.414 STDERR terraform: │
17:06:27.414 STDERR terraform: │
17:06:27.414 STDERR terraform: │ Terraform acquires a state lock to protect the state from being written
17:06:27.414 STDERR terraform: │ by multiple users at the same time. Please resolve the issue above and try
17:06:27.414 STDERR terraform: │ again. For most commands, you can disable locking with the "-lock=false"
17:06:27.414 STDERR terraform: │ flag, but this is not recommended.
17:06:27.414 STDERR terraform: ╵

```

Please have a look and fix that bug by returning the expected behavior of CTRL+C command output so I could further use newer and latest Teggarant versions.

### LINKED ISSUE #5167: Ctrl-C on Terraform's apply prompt fails to release S3 lock
## Describe the bug

Starting with Terragrunt v0.86.0, S3 state locks are not properly released when pressing Ctrl-C at the terraform apply confirmation prompt. The Terraform process is killed by signal before it can complete the lock cleanup operation, leaving orphaned .tflock files in S3.

### Bisection Results
Through systematic testing, we identified that this regression was introduced in v0.86.0:

v0.72.2: ✅ Working
v0.82.0: ✅ Working
v0.85.0: ✅ Working
v0.85.1: ✅ Working
v0.86.0: ❌ BROKEN (lock not released)
v0.87.0: ❌ Broken
v0.92.1: ❌ Broken

### Evidence from Trace Logs

**Terragrunt v0.85.1 (Working):**
```
2025-12-02T21:45:09.485-0500 [INFO]  backend-s3: Attempting to unlock remote state (S3 Native only)...  
2025-12-02T21:45:09.597-0500 [DEBUG] backend-s3: HTTP Request Sent: ... rpc.method=DeleteObject ...  
2025-12-02T21:45:09.645-0500 [DEBUG] backend-s3: HTTP Response Received: ... http.status_code=204 ...  
2025-12-02T21:45:09.645-0500 [DEBUG] backend-s3: Deleted lock file: ...  
2025-12-02T21:45:09.645-0500 [INFO]  backend-s3: Unlocked remote state (S3 Native only): ...  
exit status 1  
```

**Terragrunt v0.86.0 (Broken):**
```
2025-12-02T21:41:07.733-0500 [INFO]  backend-s3: Attempting to unlock remote state (S3 Native only)...  
signal: killed  
```

The logs clearly show that in v0.86.0, Terraform begins the unlock process but receives signal: killed before it can send the DeleteObject request to S3.

## Reproducing bugs

Reproduced on versions v0.86.0 to v0.92.1, but wasn't able to test newer versions due to a breaking change in the configs.

### Configuration Details
Backend Configuration (generated by Terragrunt):

```
terraform {  
  backend "s3" {  
    bucket               = "xxxxxxxxxxxxxxxxxxx"  
    encrypt              = true  
    key                  = "xxxxxxxxxxxxxxxxxxx.tfstate"  
    profile              = "xxxxxxxxxxxxxxxxxxx"  
    region               = "us-east-1"  
    use_lockfile         = true  
    workspace_key_prefix = null  
  }  
}  
```

## Steps To Reproduce

1. Configure S3 backend with use_lockfile = true
2. Use Terragrunt v0.86.0 or higher
3. Run terragrunt apply
4. Let the plan complete fully
5. Press Ctrl-C at the confirmation prompt
6. Observe that the .tflock file remains in S3
7. Run terragrunt apply again - it will fail with a lock error

## Expected behavior

The S3 lock file should be automatically removed when:

- Interrupting the operation with Ctrl+C
- Any other graceful termination of the Terraform process

## Actual Behavior

The .tflock file remains in S3 and must be manually removed using:

`aws s3 rm s3://bucket-name/path/to/terraform.tfstate.tflock `

or:

`terraform force-unlock <LOCK_ID> `

### Root Cause
The issue was introduced by changes in internal/os/exec/cmd.go where the Command() function signature was changed from:

```
// v0.85.1  
func Command(name string, args ...string) *Cmd  
```
to:
```
// v0.86.0  
func Command(ctx context.Context, name string, args ...string) *Cmd  
```
This change switched from using exec.Command() to exec.CommandContext(). When the user interrupts the operation with Ctrl+C, the context is cancelled, which immediately sends **SIGKILL** to the Terraform subprocess before it can complete its cleanup routine.

### Additional Evidence from Code Diff
The test files were also updated to accept "signal: killed" as a valid outcome, indicating the Terragrunt team was aware this change would cause processes to be killed by signal:

**From shell/run_cmd_unix_test.go:**
```
// v0.85.1  
expectedErr := fmt.Sprintf("Failed to execute \"%s 5\" in .\n\nexit status %d", cmdPath, expectedWait)  
assert.EqualError(t, actualErr, expectedErr)
  
// v0.86.0  
expectedExitStatusErr := fmt.Sprintf("Failed to execute \"%s 5\" in .\n\nexit status %d", cmdPath, expectedWait)  
expectedKilledErr := fmt.Sprintf("Failed to execute \"%s 5\" in .\n\nsignal: killed", cmdPath)  
// Now accepts EITHER error  
```
### Impact
This is a critical regression that affects all users of Terragrunt v0.86.0+ who:

- Use S3 backend with use_lockfile = true
- Ever need to interrupt a Terraform apply operation with Ctrl+C
- Work in team environments where orphaned locks can block other users

Every interrupted operation requires manual intervention to clean up the orphaned lock file.

### Proposed Fix
Terragrunt should handle subprocess termination gracefully by:

1. Using a separate context for subprocess execution that isn't immediately cancelled on interrupt
2. Forwarding SIGINT/SIGTERM to the Terraform process and waiting for it to exit cleanly
3. Only sending SIGKILL if Terraform doesn't exit after a reasonable timeout period
4. Ensuring the cleanup phase completes before terminating the subprocess

The current implementation ties the subprocess lifecycle directly to the parent context cancellation, which prevents Terraform from performing necessary cleanup operations.

### References

- Root cause: internal/os/exec/cmd.go line 31
- Usage: shell/run_cmd.go line 115
- Test changes: shell/run_cmd_unix_test.go and shell/run_cmd_windows_test.go

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Hopefully fully resolves the issues with signal propagation we've been seeing.

I think the issue is ultimately that we don't have the signal in context for some reason when we're getting these cancellations.

Made it so that we always send the interrupt signal to the process, and use a WaitDelay to ensure that we eventually send the SIGKILL.

Closes #5423
Closes #4839
Closes #5167
Closes #5068
Closes #4839

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **New Features**
  * Commands now support graceful shutdown with a default delay before forceful termination; the delay is configurable via a new option.
  * Cancellation will send an interrupt first (then escalate to kill) and can become a no-op when a graceful-shutdown handler is registered.

* **Tests**
  * Added a test and helper script validating graceful-shutdown behavior on cancel.

---

> [!NOTE]
> **Medium Risk**
> Touches process lifecycle and signal handling; incorrect behavior could leave orphaned child processes or delay termination if the new grace period/interrupt logic misfires.
> 
> **Overview**
> Subprocess cancellation now defaults to a *graceful shutdown* flow: `exec.Command` sets a `WaitDelay` (30s) and, when a context is cancelled without a signal cause, sends the configured interrupt signal instead of immediately `SIGKILL`ing the process.
> 
> Adds `WithGracefulShutdownDelay` to customize the grace period and guards against double-wiring cancellation via an atomic `gracefulShutdownRegistered` flag. Introduces a Unix-only test (and shell fixture) that verifies context cancellation triggers `SIGINT` handling rather than bypassing cleanup via `SIGKILL`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit f3e149a73dd9edf9eae07e8f8ca3af0d5411b638. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: internal/os/exec/cmd.go [hunk 1]
```diff
@@ -48,6 +55,10 @@ func Command(ctx context.Context, name string, args ...string) *Cmd {
 			return cmd.Process.Signal(sig)
 		}
 
+		if cmd.interruptSignal != nil {
+			return cmd.Process.Signal(cmd.interruptSignal)
```
Comment (denis256) [inline internal/os/exec/cmd.go:65]: I think there will be a race condition with the invocation of RegisterGracefullyShutdown()

Comment (yhakbar) [reply internal/os/exec/cmd.go:65]: Added check to mitigate the risk of a race condition.

File: internal/os/exec/cmd.go [hunk 2]
```diff
@@ -16,14 +16,19 @@ import (
...
 	logger          log.Logger
 	interruptSignal os.Signal
 	*exec.Cmd
-	filename           string
-	forwardSignalDelay time.Duration
-	usePTY             bool
+	filename                   string
+	forwardSignalDelay         time.Duration
+	usePTY                     bool
+	gracefulShutdownRegistered bool
```
[the remark this answers is not in the document]
Comment (yhakbar) [reply internal/os/exec/cmd.go]: This isn't necessary here because the writes and reads to `graceShutdownRegistered` happen serially. There's no concurrent access that can cause a race condition which we need to protect against.

Comment (denis256) [inline internal/os/exec/cmd.go]: I was wondering if can happen bellow scenario?
```
Goroutine A (main)                    Goroutine B (exec.Cmd runtime)
     ---------------------------------     ---------------------------------
     cmd.Start()
                                           [context cancelled here]
                                           Cancel() invoked by Go runtime
                                           READS gracefulShutdownRegistered  <-- RACE
                                           (sees false, sends signal)
     cmd.RegisterGracefullyShutdown(ctx)
     WRITES gracefulShutdownRegistered=true  <-- RACE

```

Why not to use `atomic.Bool`  Store()/Load()

**Review by denis256 — DISMISSED** [review]
I think we can improve in subsequent PRs

File: internal/os/exec/cmd.go (hunk 2 above)
Comment (yhakbar) [reply internal/os/exec/cmd.go]: I updated it. I thought that we'd definitely call `RegisterGracefullyShutdown` before calling `Start`, so I didn't think it was necessary. Sorry about that.

**Review by denis256 — APPROVED** [review]

**Comment by mschfh** [comment]
Thanks for fixing this, will the patch be backported to 0.99?

**Comment by yhakbar** [comment]
> Thanks for fixing this, will the patch be backported to 0.99?

Ya. We'll get on that soon. We have a couple fixes that are getting backported.
