### PR TITLE
fix: Fixing #4556

### LINKED ISSUE #4556: The Provider Cache Server doesn't filter out invalid provider versions
## Describe the bug

The Provider Cache Server doesn't filter out invalid provider versions.

We use a local mirror of the terraform provider registry. Sometimes it caches providers with invalid versions, like this one - https://github.com/hashicorp/terraform-provider-local/issues/408 . When terraform interacts with mirror directly, it ignores and just throws warnings about invalid versions. But if we enable the terragrunt Provider Cache Server, it acts like a registry, not a mirror. When it caches invalid versions from the mirror, terraform exits with the corresponding error: Failed to query available provider packages.

## Steps To Reproduce

This can be reproduced using a simple example. Empty `terragrunt.hcl` file and `main.tf` file containing only the version of terraform and the provider cached in the mirror with an invalid version:

```hcl
// main.tf
terraform {
  required_version = ">=1.6"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "= 2.5.2"
    }
  }
}
```

When I run `terragrunt plan --provider-cache --provider-cache-registry-names registry.terraform.io --provider-cache-dir .tg_provider_cache --log-level=trace --tf-path terraform`, I get the following output:

```log
02:09:14.023 DEBUG  Terragrunt Version: 0.83.2
02:09:14.024 DEBUG  Provider service initialized with cache dir: ./.tg_provider_cache, user cache dir: ../../../.terraform.d/plugins
02:09:14.027 INFO   Terragrunt Cache server is listening on 127.0.0.1:54834
02:09:14.027 INFO   Start Terragrunt Cache server
02:09:14.027 DEBUG  Skipping stack generation in .
02:09:14.027 DEBUG  Starting provider cache service with cache dir: "./.tg_provider_cache"
02:09:14.028 DEBUG  Provider cache service temp dir: /var/folders/46/x40wk2vd5qx0q1t0fd_brvyr0000gp/T/terragrunt/providers
02:09:14.028 DEBUG  Provider cache service is ready to process requests
02:09:14.029 DEBUG  Did not find any locals block: skipping evaluation.
02:09:14.029 DEBUG  using cache key for version files: r01AJjVD7VSXCQk1ORuh_no_NRY
02:09:14.029 DEBUG  Running command: terraform -version
02:09:14.029 DEBUG  Engine is not enabled, running command directly in .
02:09:14.894 DEBUG  terraform version: 1.12.2
02:09:14.894 DEBUG  Reading Terragrunt config file at ./terragrunt.hcl
02:09:14.894 DEBUG  Did not find any locals block: skipping evaluation.
02:09:14.894 DEBUG  Did not find any locals block: skipping evaluation.
02:09:15.116 DEBUG  Unable to discover "registry.terraform.io" registry URLs, reason: ".well-known/terraform.json not found", use default URLs: {"modules.v1":"/v1/modules","providers.v1":"/v1/providers"}
02:09:15.118 INFO   Caching terraform providers for .
02:09:15.118 DEBUG  Running command: terraform init
02:09:15.118 DEBUG  Engine is not enabled, running command directly in .
02:09:15.508 TRACE  Cache server received request url=/v1/providers/d489e239-37e6-4892-a397-1231b68356d3/registry.terraform.io/hashicorp/local/versions status=200
02:09:15.170 INFO   terraform: Initializing the backend...
02:09:15.170 INFO   terraform: Initializing provider plugins...
02:09:15.170 INFO   terraform: - Finding hashicorp/local versions matching "2.5.2"...
02:09:15.509 ERROR  terraform: ╷
02:09:15.509 ERROR  terraform: │ Error: Failed to query available provider packages
02:09:15.509 ERROR  terraform: │ 
02:09:15.509 ERROR  terraform: │ Could not retrieve the list of available versions for provider
02:09:15.510 ERROR  terraform: │ hashicorp/local: could not query provider registry for
02:09:15.510 ERROR  terraform: │ registry.terraform.io/hashicorp/local: registry response includes invalid
02:09:15.510 ERROR  terraform: │ version string "v2.5.3-alpha1": a "v" prefix should not be used
02:09:15.510 ERROR  terraform: │ 
02:09:15.510 ERROR  terraform: │ To see which modules are currently depending on hashicorp/local and what
02:09:15.510 ERROR  terraform: │ versions are specified, run the following command:
02:09:15.510 ERROR  terraform: │     terraform providers
02:09:15.510 ERROR  terraform: ╵
02:09:15.515 ERROR  terraform invocation failed in .
02:09:15.516 DEBUG  Provider cache service shutting down...
02:09:15.516 DEBUG  Provider cache service shutdown complete
02:09:15.516 INFO   Shutting down Terragrunt Cache server...
02:09:15.516 INFO   Terragrunt Cache server stopped
02:09:15.516 ERROR  error occurred:

* Failed to execute "terraform init" in .
  ╷
  │ Error: Failed to query available provider packages
  │ 
  │ Could not retrieve the list of available versions for provider
  │ hashicorp/local: could not query provider registry for
  │ registry.terraform.io/hashicorp/local: registry response includes invalid
  │ version string "v2.5.3-alpha1": a "v" prefix should not be used
  │ 
  │ To see which modules are currently depending on hashicorp/local and what
  │ versions are specified, run the following command:
  │     terraform providers
  ╵
  
  exit status 1

02:09:15.810 TRACE  util.ProcessExecutionError Failed to execute "terraform init" in .
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/local: could not query provider registry for
│ registry.terraform.io/hashicorp/local: registry response includes invalid
│ version string "v2.5.3-alpha1": a "v" prefix should not be used
│ 
│ To see which modules are currently depending on hashicorp/local and what
│ versions are specified, run the following command:
│     terraform providers
╵

exit status 1
```

While waiting for the local mirror team to clean it up, the only solution is to disable the Provider Cache Server. 😢 

## Expected behavior

The Provider Cache Server, acting like a registry, must follow provider's version convention and filter out invalid versions.

## Versions

- Terragrunt version: v0.83.2
- Terraform version: v1.12.2
- Environment details (Ubuntu 20.04, MacOS):

### PR DESCRIPTION
**Pull request by yhakbar**
## Description

Fixes #4556.

Filters out invalid versions requested from the provider cache server.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Invalid version entries are now filtered from API responses, ensuring only properly formatted versions are returned to users.

* **Tests**
  * Added comprehensive test coverage for version validation logic.

### CODE REVIEW

File: internal/tf/cache/models/provider.go [hunk 1]
```diff
@@ -64,6 +66,27 @@ func (version Version) String() string {
 	return fmt.Sprintf("%s/%s/%s", version.Version, version.Protocols, version.Platforms)
 }
 
+// FilterValid returns only versions with valid semver strings that conform to
+// the Terraform registry protocol (no "v" prefix, no empty strings).
+// The second return value contains the invalid version strings that were filtered out.
+func (versions Versions) FilterValid() (valid Versions, invalid []string) {
+	for _, v := range versions {
```
Comment (denis256) [inline internal/tf/cache/models/provider.go:76]: Not sure how nil values will be handled, AFAIK, nil slice serializes as JSON null instead of []

**Review by denis256 — APPROVED** [review]

**Review by denis256 — APPROVED** [review]
