### PR TITLE
Fixed reading of outputs during destroy

### LINKED ISSUE #2479: Terragrunt destroy command fails with "Could not parse output from terragrunt config"
I have following directory structure
📦iac
 ┣ 📂environment
 ┃ ┗ 📂dev
 ┃ ┃ ┣ 📂0-vpc
 ┃ ┃ ┃ ┗ 📜terragrunt.hcl
 ┃ ┃ ┣ 📂1-igw
 ┃ ┃ ┃ ┗ 📜terragrunt.hcl
 ┃ ┃ ┣ 📂2-subnets
 ┃ ┃ ┃ ┗ 📜terragrunt.hcl
 ┃ ┃ ┣ 📂3-natgw
 ┃ ┃ ┃ ┗ 📜terragrunt.hcl
 ┃ ┃ ┗ 📂4-rtbs
 ┃ ┃ ┃ ┗ 📜terragrunt.hcl
 ┗ 📂modules
 ┃ ┣ 📂igw
 ┃ ┃ ┣ 📜igw.tf
 ┃ ┃ ┣ 📜output.tf
 ┃ ┃ ┗ 📜variables.tf
 ┃ ┣ 📂natgw
 ┃ ┃ ┣ 📜natgw.tf
 ┃ ┃ ┣ 📜output.tf
 ┃ ┃ ┗ 📜variables.tf
 ┃ ┣ 📂rtb
 ┃ ┃ ┣ 📜rtb.tf
 ┃ ┃ ┗ 📜variables.tf
 ┃ ┣ 📂subnet
 ┃ ┃ ┣ 📜output.tf
 ┃ ┃ ┣ 📜subnet.tf
 ┃ ┃ ┗ 📜variables.tf
 ┃ ┗ 📂vpc
 ┃ ┃ ┣ 📜output.tf
 ┃ ┃ ┣ 📜variables.tf
 ┃ ┃ ┗ 📜vpc.tf

I am doing terragrunt apply from each sub folder in the dev folder and all works fine and infrastructure is creating fine. But when I try to do terragrunt destroy it doesn't work and give following error. I am using dependency blocks to get outputs form 0-vpc,1-igw,2-subnets folders to 4-rtbs folder
image

### PR DESCRIPTION
**Pull request by denis256**
## Description

Included changes:
  * fixed outputs reading from dependencies during destroy
  * added error handling for reding modules outputs

Fixes #2479.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Fixed dependencies output reading during destroy.

### CODE REVIEW

File: test/integration_test.go [hunk 1]
```diff
@@ -147,6 +146,7 @@ const (
 	TEST_FIXTURE_INIT_ERROR                                 = "fixture-init-error"
 	TEST_FIXTURE_MODULE_PATH_ERROR                          = "fixture-module-path-in-error"
 	TEST_FIXTURE_HCLFMT_DIFF                                = "fixture-hclfmt-diff"
+	TEST_FIXTURE_DESTROY_DEPENENT_MODULE                    = "fixture-destroy-dependent-module"
```
Comment (zackproser) [inline test/integration_test.go:149]: Looks like there's a typo here:  `DEPENENT` => `DEPENDENT` ?

Comment (denis256) [reply test/integration_test.go]: :+1:
