### PR TITLE
Fix bug where dependency output call runs hooks 

### LINKED ISSUE #1273: before/after hooks run for dependencies
When using the dependency block to declare a dependency for outputs, the before and after hooks are called despite the fact that only `terraform output` is being called within the dependent module. In my case, I have a hook to save the plan in JSON format when a plan is executed. I'm trying to execute a plan in module B, which depends on module A. Terragrunt is calling `terraform output` on module A successfully but seems to trigger module A's `after_hook` for `plan` even though plan is not being executed on that module.
```
zach@C02CH4U3MD6R per-repository % terragrunt plan
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/per-repository] 2020/07/30 15:27:08 Running command: terraform --version
[terragrunt] 2020/07/30 15:27:08 Terraform version: 0.12.28
[terragrunt] 2020/07/30 15:27:08 Reading Terragrunt config file at /Users/zach/Repositories/terraform/aws/cicd/automation/per-repository/terragrunt.hcl
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:08 Running command: terraform --version
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:08 Terraform version: 0.12.28
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:08 Reading Terragrunt config file at /Users/zach/Repositories/terraform/aws/cicd/automation/framework/terragrunt.hcl
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:08 Detected 2 Hooks
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:08 Downloading Terraform configurations from file:///Users/zach/Repositories/terraform/aws/cicd/automation/framework into /Users/zach/Repositories/terraform/aws/cicd/automation/framework/.terragrunt-cache/3KaExAd9shMrH-SpREjbKVxT0TU/6CVv0W2szsSrB4UmjMUemJ_AonI
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:08 Detected 2 Hooks
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:08 Copying files from /Users/zach/Repositories/terraform/aws/cicd/automation/framework into /Users/zach/Repositories/terraform/aws/cicd/automation/framework/.terragrunt-cache/3KaExAd9shMrH-SpREjbKVxT0TU/6CVv0W2szsSrB4UmjMUemJ_AonI
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:08 Setting working directory to /Users/zach/Repositories/terraform/aws/cicd/automation/framework/.terragrunt-cache/3KaExAd9shMrH-SpREjbKVxT0TU/6CVv0W2szsSrB4UmjMUemJ_AonI
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:09 Running command: terraform output -json
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:13 Detected 2 Hooks
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:13 Executing hook: plan
[terragrunt] [/Users/zach/Repositories/terraform/aws/cicd/automation/framework] 2020/07/30 15:27:13 Running command: sh -c terraform show -json framework.terraform.tfplan > framework.terraform.tfplan.json

Error: Saved plan is stale

The given plan file can no longer be applied because the state was changed by
another operation after the plan was created.shell
```

```hcl
after_hook plan {
    commands     = ["plan"]
    execute      = ["sh", "-c", "terraform show -json ${local.file_prefix}.terraform.tfplan > ${local.file_prefix}.terraform.tfplan.json"]
}
```

### PR DESCRIPTION
**Pull request by yorinasub17**
Fixes #1273 and #1274

The cause of the bug is that we weren't setting `TerraformCommand` on the cloned options when retrieving the outputs, so the `terraform output` call was running in the context of the current command.

### CODE REVIEW

File: config/dependency.go [hunk 1]
```diff
@@ -337,6 +337,7 @@ func getOutputJsonWithCaching(targetConfig string, terragruntOptions *options.Te
 // Clone terragrunt options and update context for dependency block so that the outputs can be read correctly
 func cloneTerragruntOptionsForDependencyOutput(terragruntOptions *options.TerragruntOptions, targetConfig string) (*options.TerragruntOptions, error) {
 	targetOptions := terragruntOptions.Clone(targetConfig)
+	targetOptions.TerraformCommand = "output"
 	targetOptions.TerraformCliArgs = []string{"output", "-json"}
```
Comment (brikis98) [inline config/dependency.go:341]: Should the command be `output` _and_ the args contain `output` too? Or is that redundant?

Comment (brikis98) [reply config/dependency.go:341]: Or should we add a `--terragrunt-skip-hooks` flag and pass that to the dependency module to ensure hooks are disabled?

Comment (yorinasub17) [reply config/dependency.go:341]: You need both because `TerraformCommand` is used for the hook determination, while `TerraformCliArgs` is what is actually passed to `terraform`. This redundancy is actually what got me confused and caused me to omit one of them...

**Comment by yorinasub17** [comment]
> So by setting Command to output, hooks won't execute unless they have output in their commands = [...] list?

Yup, because `TerraformCommand` is actually what is used for hook determination, not `TerraformCliArgs`.

File: config/dependency.go (hunk 1 above)
Comment (yorinasub17) [reply config/dependency.go:341]: > Or should we add a --terragrunt-skip-hooks flag and pass that to the dependency module to ensure hooks are disabled?

I think it is more intuitive for `output` hooks to run when getting dependencies, given that the mental model is that fetching dependencies is a call to `terragrunt output` in the target module.

Comment (brikis98) [reply config/dependency.go:341]: I could see it either way: i.e., `dependency` = `output`, so run the `output` hooks... Or that hooks should only run when the module is being executed directly, so never run hooks for `dependency`. 

I don't have a strong opinion here, so let's go with what you have.

**Comment by yorinasub17** [comment]
Thanks for review! Merging and releasing now.
