### PR TITLE
fix #3845 set the correct exit code when a retry is successful.

### LINKED ISSUE #3845: `-detailed-exitcode` causes a wrong exit code to be emitted when there was a retry
## Describe the bug

When using `-detailed-exitcode` this causes a wrong exit code to be emitted when there was a retry according to the terragrunt config. It should show the exit code 0 if the retry was successful.

## Steps To Reproduce

Configure some testing suitable retry values:

```hcl
# File: terragrunt.hcl
retry_max_attempts       = 2
retry_sleep_interval_sec = 1
retryable_errors         = ["(?s).*marker.*"]
```

Put a dummy resource which executes the script and prints the script name on failure (i.e. triggering a retry):

```hcl
# File: main.tf
data "external" "script" {
  program = ["/bin/bash", "-c", "./marker.sh"]
}
```

The script will fail on the first run but succeed on the second:

```bash
# File: marker.sh
#!/usr/bin/env bash
set -euo pipefail

if [[ -f .file ]]; then
  echo "{}"
  rm .file
  exit 0
else
  touch .file
  exit 1
fi
```

## Expected behavior

Works as it should and gives us exit code 0.

```bash
$ terragrunt plan
13:59:05.069 STDOUT terraform: data.external.script: Reading...
13:59:05.099 STDOUT terraform: Planning failed. Terraform encountered an error while generating this plan.
13:59:05.099 STDOUT terraform: 
13:59:05.099 STDERR terraform: ╷
13:59:05.099 STDERR terraform: │ Error: External Program Execution Failed
13:59:05.099 STDERR terraform: │ 
13:59:05.099 STDERR terraform: │   with data.external.script,
13:59:05.099 STDERR terraform: │   on main.tf line 2, in data "external" "script":
13:59:05.099 STDERR terraform: │    2:   program = ["/bin/bash", "-c", "./marker.sh"]
13:59:05.099 STDERR terraform: │ 
13:59:05.099 STDERR terraform: │ The data source received an unexpected error while attempting to execute
13:59:05.099 STDERR terraform: │ the program.
13:59:05.099 STDERR terraform: │ 
13:59:05.099 STDERR terraform: │ The program was executed, however it returned no additional error
13:59:05.099 STDERR terraform: │ messaging.
13:59:05.099 STDERR terraform: │ 
13:59:05.099 STDERR terraform: │ Program: /bin/bash
13:59:05.099 STDERR terraform: │ State: exit status 1
13:59:05.099 STDERR terraform: ╵
13:59:05.101 INFO   Encountered an error eligible for retrying. Sleeping 1s before retrying.

13:59:06.221 STDOUT terraform: data.external.script: Reading...
13:59:06.242 STDOUT terraform: data.external.script: Read complete after 0s [id=-]
13:59:06.243 STDOUT terraform: No changes. Your infrastructure matches the configuration.
13:59:06.243 STDOUT terraform: Terraform has compared your real infrastructure against your configuration
13:59:06.243 STDOUT terraform: and found no differences, so no changes are needed.
$ echo $?
0
```

Will show exit code 1, although the retry was successful. It should be exit code 0. Also visible in the terminal output:

```bash
$ terragrunt plan -detailed-exitcode
13:59:33.243 STDOUT terraform: data.external.script: Reading...
13:59:33.258 STDOUT terraform: Planning failed. Terraform encountered an error while generating this plan.
13:59:33.258 STDOUT terraform: 
13:59:33.258 STDERR terraform: ╷
13:59:33.258 STDERR terraform: │ Error: External Program Execution Failed
13:59:33.258 STDERR terraform: │ 
13:59:33.258 STDERR terraform: │   with data.external.script,
13:59:33.258 STDERR terraform: │   on main.tf line 2, in data "external" "script":
13:59:33.258 STDERR terraform: │    2:   program = ["/bin/bash", "-c", "./marker.sh"]
13:59:33.258 STDERR terraform: │ 
13:59:33.258 STDERR terraform: │ The data source received an unexpected error while attempting to execute
13:59:33.258 STDERR terraform: │ the program.
13:59:33.258 STDERR terraform: │ 
13:59:33.258 STDERR terraform: │ The program was executed, however it returned no additional error
13:59:33.258 STDERR terraform: │ messaging.
13:59:33.258 STDERR terraform: │ 
13:59:33.258 STDERR terraform: │ Program: /bin/bash
13:59:33.258 STDERR terraform: │ State: exit status 1
13:59:33.258 STDERR terraform: ╵
13:59:33.261 INFO   Encountered an error eligible for retrying. Sleeping 1s before retrying.

13:59:34.388 STDOUT terraform: data.external.script: Reading...
13:59:34.404 STDOUT terraform: data.external.script: Read complete after 0s [id=-]
13:59:34.405 STDOUT terraform: No changes. Your infrastructure matches the configuration.
13:59:34.405 STDOUT terraform: Terraform has compared your real infrastructure against your configuration
13:59:34.405 STDOUT terraform: and found no differences, so no changes are needed.
$ echo $?
1
```

## Versions

- Terragrunt version: 0.72.6
- OpenTofu/Terraform version: 1.10.5
- Environment details: MacOS Sonoma 14.7

## PS

Thank you for your great work! 😄

### PR DESCRIPTION
**Pull request by wakeful**
## Description

Fixes #3845 set the correct exit code when a retry is successful.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Fixes #3845 set the correct exit code when a retry is successful.

### Migration Guide

n/a

## Summary by CodeRabbit

- **New Features**
	- Introduced a data source that checks for file existence and manages output accordingly.
	- Added configurable retry options with set maximum attempts and pause intervals for improved error-handling during operations.
	- Added dependency declarations to enforce test execution order and prevent flaky tests.
- **Bug Fixes**
	- Enhanced exit code management to ensure successful executions are accurately reflected.
- **Refactor**
	- Simplified the logic for setting detailed exit codes to allow unrestricted assignment.

### CODE REVIEW

**Comment by wakeful** [comment]
hey @yhakbar,

Could I ask for the list of tests that failed in the CI? I don't have access to the CircleCI output.

**Comment by wakeful** [comment]
@yhakbar Can you re-run the tests?

File: test/integration_test.go [hunk 1]
```diff
@@ -209,10 +209,12 @@ func TestDetailedExitCodeError(t *testing.T) {
 	ctx := context.Background()
 	ctx = tf.ContextWithDetailedExitCode(ctx, &exitCode)
 
+	_, _, err := helpers.RunTerragruntCommandWithOutputWithContext(t, ctx, "terragrunt run-all init --terragrunt-log-level trace --terragrunt-non-interactive --terragrunt-working-dir "+rootPath)
+	require.NoError(t, err)
 	_, stderr, err := helpers.RunTerragruntCommandWithOutputWithContext(t, ctx, "terragrunt run-all plan --terragrunt-log-level trace --terragrunt-non-interactive -detailed-exitcode --terragrunt-working-dir "+rootPath)
 	require.Error(t, err)
 	assert.Contains(t, stderr, "not-existing-file.txt: no such file or directory")
-	assert.Equal(t, 1, exitCode.Get())
+	assert.Equal(t, 2, exitCode.Get())
```
Comment (wakeful) [inline test/integration_test.go:217]: I tested several different versions of Terraform directly in the "fixture" folder and consequently received `exit code = 2`.

**Comment by wakeful** [comment]
hey, @yhakbar 

Can we try again? I tested a few cases manually, and the tests should be passing now.

**Comment by yhakbar** [comment]
Hey @wakeful , sorry it's been so frustrating to get this working.

I am able to reproduce the test failure (sometimes) locally. I think there might be a side-effect making the test unreliable somehow.


```bash
go test -run 'TestDetailedExitCodeError'
--- FAIL: TestDetailedExitCodeError (1.11s)
    integration_test.go:205: Copying fixtures/detailed-exitcode/error to /var/folders/x3/j561187d7bn7j25xf6hs73wr0000gn/T/TestDetailedExitCodeError3643194524/001
    integration_test.go:212: [terragrunt run-all init --terragrunt-log-level trace --terragrunt-non-interactive --terragrunt-working-dir /var/folders/x3/j561187d7bn7j25xf6hs73wr0000gn/T/TestDetailedExitCodeError3643194524/001/fixtures/detailed-exitcode/error --log-format=key-value]
    integration_test.go:212: [TestDetailedExitCodeError] Full contents of stdout:
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=stdout prefix=app2 tf-path=tofu msg=Initializing the backend...
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=stdout prefix=app2 tf-path=tofu msg=Initializing provider plugins...
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=stdout prefix=app2 tf-path=tofu msg=- Finding latest version of hashicorp/local...
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=stdout prefix=app1 tf-path=tofu msg=Initializing the backend...
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=stdout prefix=app1 tf-path=tofu msg=Initializing provider plugins...
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=stdout prefix=app1 tf-path=tofu msg=- Finding latest version of hashicorp/local...
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=stdout prefix=app1 tf-path=tofu msg=- Installing hashicorp/local v2.5.2...
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=- Installing hashicorp/local v2.5.2...
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=- Installed hashicorp/local v2.5.2 (signed, key ID 0C0AF313E5FD9F80)
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=Providers are signed by their developers.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=If you'd like to know more about provider signing, you can read about it here:
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=https://opentofu.org/docs/cli/plugins/signing/
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=OpenTofu has created a lock file .terraform.lock.hcl to record the provider
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=selections it made above. Include this file in your version control repository
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=so that OpenTofu can guarantee to make the same selections by default when
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=you run "tofu init" in the future.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=OpenTofu has been successfully initialized!
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=You may now begin working with OpenTofu. Try running "tofu plan" to see
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=any changes that are required for your infrastructure. All OpenTofu commands
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=should now work.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=If you ever set or change modules or backend configuration for OpenTofu,
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=rerun this command to reinitialize your working directory. If you forget, other
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=commands will detect it and remind you to do so if necessary.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=- Installed hashicorp/local v2.5.2 (signed, key ID 0C0AF313E5FD9F80)
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=Providers are signed by their developers.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=If you'd like to know more about provider signing, you can read about it here:
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=https://opentofu.org/docs/cli/plugins/signing/
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=OpenTofu has created a lock file .terraform.lock.hcl to record the provider
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=selections it made above. Include this file in your version control repository
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=so that OpenTofu can guarantee to make the same selections by default when
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=you run "tofu init" in the future.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=OpenTofu has been successfully initialized!
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=You may now begin working with OpenTofu. Try running "tofu plan" to see
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=any changes that are required for your infrastructure. All OpenTofu commands
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=should now work.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=If you ever set or change modules or backend configuration for OpenTofu,
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=rerun this command to reinitialize your working directory. If you forget, other
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=commands will detect it and remind you to do so if necessary.
    integration_test.go:212: [TestDetailedExitCodeError]
    integration_test.go:212: [TestDetailedExitCodeError] Full contents of stderr:
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=warn msg=The `--terragrunt-log-level` flag is deprecated and will be removed in a future version of Terragrunt. Use `--log-level=trace` instead.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=warn msg=The `--terragrunt-non-interactive` flag is deprecated and will be removed in a future version of Terragrunt. Use `--non-interactive` instead.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=warn msg=The `--terragrunt-working-dir` flag is deprecated and will be removed in a future version of Terragrunt. Use `--working-dir=/var/folders/x3/j561187d7bn7j25xf6hs73wr0000gn/T/TestDetailedExitCodeError3643194524/001/fixtures/detailed-exitcode/error` instead.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug msg=Terragrunt Version: 0.0.0
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Setting download directory for module ./app1 to ./app1/.terragrunt-cache
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Setting download directory for module ./app2 to ./app2/.terragrunt-cache
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug msg=Stack at ../error:
    integration_test.go:212: [TestDetailedExitCodeError]   => Module ./app1 (excluded: false, assume applied: false, dependencies: [])
    integration_test.go:212: [TestDetailedExitCodeError]   => Module ./app2 (excluded: false, assume applied: false, dependencies: [])
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=info msg=The stack at . will be processed in the following order for command init:
    integration_test.go:212: [TestDetailedExitCodeError] Group 1
    integration_test.go:212: [TestDetailedExitCodeError] - Module ./app1
    integration_test.go:212: [TestDetailedExitCodeError] - Module ./app2
    integration_test.go:212: [TestDetailedExitCodeError]
    integration_test.go:212: [TestDetailedExitCodeError]
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Module ./app2 must wait for 0 dependencies to finish
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Running ./app2
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Module ./app1 must wait for 0 dependencies to finish
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Running ./app1
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Running command: tofu -version
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Engine is not enabled, running command directly in ./app2
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Running command: tofu -version
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Engine is not enabled, running command directly in ./app1
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=tofu version: 1.9.0
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=tofu version: 1.9.0
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Reading Terragrunt config file at ./app2/terragrunt.hcl
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Reading Terragrunt config file at ./app1/terragrunt.hcl
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Running command: tofu init -input=false
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app1 msg=Engine is not enabled, running command directly in ./app1
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Running command: tofu init -input=false
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:58-04:00 level=debug prefix=app2 msg=Engine is not enabled, running command directly in ./app2
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Copying lock file from ./app1/.terraform.lock.hcl to ./app1
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Module ./app1 has finished successfully!
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Copying lock file from ./app2/.terraform.lock.hcl to ./app2
    integration_test.go:212: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Module ./app2 has finished successfully!
    integration_test.go:212: [TestDetailedExitCodeError]
    integration_test.go:214: [terragrunt run-all plan --terragrunt-log-level trace --terragrunt-non-interactive -detailed-exitcode --terragrunt-working-dir /var/folders/x3/j561187d7bn7j25xf6hs73wr0000gn/T/TestDetailedExitCodeError3643194524/001/fixtures/detailed-exitcode/error --log-format=key-value]
    integration_test.go:214: [TestDetailedExitCodeError] Full contents of stdout:
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=OpenTofu used the selected providers to generate the following execution
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=plan. Resource actions are indicated with the following symbols:
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=  + create
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=OpenTofu will perform the following actions:
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=  # local_file.example will be created
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=  + resource "local_file" "example" {
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + content              = "Test"
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + content_base64sha256 = (known after apply)
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + content_base64sha512 = (known after apply)
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + content_md5          = (known after apply)
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + content_sha1         = (known after apply)
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + content_sha256       = (known after apply)
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + content_sha512       = (known after apply)
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + directory_permission = "0777"
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + file_permission      = "0777"
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + filename             = "./example.txt"
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=      + id                   = (known after apply)
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=    }
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=Plan: 1 to add, 0 to change, 0 to destroy.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=─────────────────────────────────────────────────────────────────────────────
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=Note: You didn't use the -out option to save this plan, so OpenTofu can't
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app2 tf-path=tofu msg=guarantee to take exactly these actions if you run "tofu apply" now.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=data.local_file.read_not_existing_file: Reading...
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=Planning failed. OpenTofu encountered an error while generating this plan.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stdout prefix=app1 tf-path=tofu msg=
    integration_test.go:214: [TestDetailedExitCodeError]
    integration_test.go:214: [TestDetailedExitCodeError] Full contents of stderr:
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=warn msg=The `--terragrunt-log-level` flag is deprecated and will be removed in a future version of Terragrunt. Use `--log-level=trace` instead.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=warn msg=The `--terragrunt-non-interactive` flag is deprecated and will be removed in a future version of Terragrunt. Use `--non-interactive` instead.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=warn msg=The `--terragrunt-working-dir` flag is deprecated and will be removed in a future version of Terragrunt. Use `--working-dir=/var/folders/x3/j561187d7bn7j25xf6hs73wr0000gn/T/TestDetailedExitCodeError3643194524/001/fixtures/detailed-exitcode/error` instead.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug msg=Terragrunt Version: 0.0.0
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Setting download directory for module ./app1 to ./app1/.terragrunt-cache
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Setting download directory for module ./app2 to ./app2/.terragrunt-cache
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug msg=Stack at ../error:
    integration_test.go:214: [TestDetailedExitCodeError]   => Module ./app1 (excluded: false, assume applied: false, dependencies: [])
    integration_test.go:214: [TestDetailedExitCodeError]   => Module ./app2 (excluded: false, assume applied: false, dependencies: [])
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=info msg=The stack at . will be processed in the following order for command plan:
    integration_test.go:214: [TestDetailedExitCodeError] Group 1
    integration_test.go:214: [TestDetailedExitCodeError] - Module ./app1
    integration_test.go:214: [TestDetailedExitCodeError] - Module ./app2
    integration_test.go:214: [TestDetailedExitCodeError]
    integration_test.go:214: [TestDetailedExitCodeError]
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Module ./app2 must wait for 0 dependencies to finish
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Running ./app2
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Module ./app1 must wait for 0 dependencies to finish
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Running ./app1
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Running command: tofu -version
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Engine is not enabled, running command directly in ./app2
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Running command: tofu -version
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Engine is not enabled, running command directly in ./app1
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=tofu version: 1.9.0
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Reading Terragrunt config file at ./app1/terragrunt.hcl
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=tofu version: 1.9.0
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Reading Terragrunt config file at ./app2/terragrunt.hcl
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Did not find any locals block: skipping evaluation.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Running command: tofu plan -input=false -detailed-exitcode
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Running command: tofu plan -input=false -detailed-exitcode
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app1 msg=Engine is not enabled, running command directly in ./app1
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Engine is not enabled, running command directly in ./app2
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=debug prefix=app2 msg=Module ./app2 has finished successfully!
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=╷
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=│ Error: Read local file data source error
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=│
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=│   with data.local_file.read_not_existing_file,
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=│   on main.tf line 1, in data "local_file" "read_not_existing_file":
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=│    1: data "local_file" "read_not_existing_file" {
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=│
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=│ The file at given path cannot be read.
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=│
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=│ +Original Error: open ./not-existing-file.txt: no such file or directory
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=stderr prefix=app1 tf-path=tofu msg=╵
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=error prefix=app1 msg=tofu invocation failed in ./app1
    integration_test.go:214: [TestDetailedExitCodeError] time=2025-04-10EDT10:06:59-04:00 level=error prefix=app1 msg=Module ./app1 has finished with an error
    integration_test.go:214: [TestDetailedExitCodeError]
    integration_test.go:217:
        	Error Trace:	/Users/yousif/tmp/tmp-terragrunt/test/integration_test.go:217
        	Error:      	Not equal:
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestDetailedExitCodeError
FAIL
exit status 1
FAIL	github.com/gruntwork-io/terragrunt/test	1.797s
```

**Comment by wakeful** [comment]
hey @yhakbar

I finally had some time to look into the **weird** behaviour in the `TestDetailedExitCodeError` test. It was related to the ordering of `unit(s)`.

The test should be stable now - I ran it with `-count=50` to confirm.

File: test/integration_test.go [hunk 2]
```diff
@@ -233,6 +233,23 @@ func TestDetailedExitCodeChangesPresentAll(t *testing.T) {
...
+	testFixturePath := filepath.Join(testFixtureDetailedExitCode, "fail-on-first-run")
+
+	helpers.CleanupTerraformFolder(t, testFixturePath)
+	tmpEnvPath := helpers.CopyEnvironment(t, testFixturePath)
+
+	var exitCode tf.DetailedExitCode
+	ctx := context.Background()
+	ctx = tf.ContextWithDetailedExitCode(ctx, &exitCode)
+
+	_, _, err := helpers.RunTerragruntCommandWithOutputWithContext(t, ctx, "terragrunt run-all plan --terragrunt-log-level trace --terragrunt-non-interactive -detailed-exitcode --terragrunt-working-dir "+util.JoinPath(tmpEnvPath, testFixturePath))
```
Comment (yhakbar) [inline test/integration_test.go:248]: Don't fix this now, but we should remember to replace this with a `run --all` version for future compatibility.

- [ ] TODO: Replace `run-all` with `run --all` in `TestDetailedExitCodeFailOnFirstRun`

**Review by yhakbar — APPROVED** [review]
Thank you, @wakeful .

Always a pleasure!
