### PR TITLE
bug: fixed bootstrap and use_lockfile

### LINKED ISSUE #5646: `use_lockfile=true` breaks `--backend-bootstrap`
## Describe the bug

Similar to https://github.com/gruntwork-io/terragrunt/issues/5475

## Reproducing bugs

Error when `remote_state.config` refers to a local resolved with a ternary operator AND when it includes `use_lockfile=true`

```
# command

terragrunt run --all --fail-fast --no-auto-init --non-interactive --backend-bootstrap --filter="{./**}..." --queue-exclude-dir "**/.terragrunt-cache/**"  -- init -upgrade -reconfigure

# output

* 1 error(s) decoding:
  
  * 'use_lockfile' expected type 'bool', got unconvertible type 'string', value: 'true'
```

### PR DESCRIPTION
**Pull request by denis256**
## Description

* normalize string bools in remote state backend config
* type unification converts bool values to strings (true -> "true"), causing generated backend blocks to emit use_lockfile = "true" (quoted) instead of use_lockfile = true, which Terraform/OpenTofu rejects

Fixes #5646.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **Bug Fixes**
  * Remote state configuration now properly normalizes boolean values when initializing Terraform backends, ensuring string booleans are correctly converted to native boolean literals.

* **Tests**
  * Added comprehensive test coverage for boolean value handling in remote state configuration across S3 and GCS backends.
  * Added validation tests for Terraform code generation with remote state settings.

### CODE REVIEW

File: internal/remotestate/backend/gcs/backend_test.go [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+
+	"github.com/stretchr/testify/assert"
+)
+
+func TestBackend_GetTFInitArgs(t *testing.T) {
+	t.Parallel()
+
+	remoteBackend := gcsbackend.NewBackend()
+
+	testCases := []struct { //nolint: govet
```
Comment (yhakbar) [inline internal/remotestate/backend/gcs/backend_test.go:17]: What are we suppressing here? Why?

File: internal/remotestate/backend/normalize.go [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+
+	for t.Kind() == reflect.Ptr {
+		t = t.Elem()
+	}
+
+	if t.Kind() != reflect.Struct {
+		return nil
+	}
+
+	keys := make(map[string]bool)
```
Comment (yhakbar) [inline internal/remotestate/backend/normalize.go:57]: NIT: Isn't it more idiomatic to use `map[string]struct{}` here?

**Review by yhakbar — APPROVED** [review]
