### PR TITLE
Relative path handling

### LINKED ISSUE #3253: `--terragrunt-out-dir` does not work when running `run-all plan` in a leaf directory
## Describe the bug

When running a `run-all plan` with `--terragrunt-out-dir` in a leaf directory, a strange filesystem permissions error pops up that is difficult to debug.

Terragrunt should either throw a clear error explaining why this is happening, or gracefully handle the behavior.

Note that this is a strange edge case, as most users should just use `terragrunt plan` instead of `terragrunt run-all plan` in a scenario such as this, but most users expect `run-all plan` to work just like `plan` within a leaf directory.

There's likely some logic that doesn't work right for reproducing the relative paths to `terragrunt.hcl` files in the `--terragrunt-out-dir` directory when run at a leaf directory.

## Steps To Reproduce

Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```bash
terragrunt run-all plan --terragrunt-out-dir test
```

## Nice to haves

- [x] Terminal output
- [x] Screenshots

```
│ Error: Failed to write plan file
│
│ The plan file could not be written: open
│ github-actions-openid-connect-provider/tfplan.tfplan: no such file or
│ directory.
```

image

## Versions

- Terragrunt version: v0.60.0
- OpenTofu version: v1.6.2
- Environment details (Ubuntu 20.04, Windows 10, etc.): GHA Ubuntu Latest and MacOS

### PR DESCRIPTION
**Pull request by denis256**
## Description

Included changes:
* Added handling of relative path for output and json output
* Added tests to track relative path usage
* Updated timeout for `golangci-lint` execution to avoid false positive failures

Before this change:
```
* Failed to execute "tofu plan -input=false -out=test/modules/module2/tfplan.tfplan" in ./modules/module2
  ╷
  │ Error: Failed to write plan file
  │ 
  │ The plan file could not be written: open
  │ test/modules/module2/tfplan.tfplan: no such file or directory.
  ╵
  
  exit status 1

```
After this change:
```
20:55:54.279 STDOUT [modules/module2] tofu: local_file.module2: Refreshing state... [id=0cf7edc2ec41ede392583a0ef1377a17feab24ae]
20:55:54.297 STDOUT [modules/module1] tofu: local_file.module1: Refreshing state... [id=999b7ab94303be85f2531d4fba0859374c6ce16f]
20:55:54.308 STDOUT [modules/module2] tofu: No changes. Your infrastructure matches the configuration.
20:55:54.308 STDOUT [modules/module2] tofu: OpenTofu has compared your real infrastructure against your configuration and
20:55:54.308 STDOUT [modules/module2] tofu: found no differences, so no changes are needed.
20:55:54.317 STDOUT [modules/module1] tofu: No changes. Your infrastructure matches the configuration.
20:55:54.318 STDOUT [modules/module1] tofu: OpenTofu has compared your real infrastructure against your configuration and
20:55:54.318 STDOUT [modules/module1] tofu: found no differences, so no changes are needed.
20:55:54.890 STDOUT [app] tofu: local_file.app: Refreshing state... [id=7d1043473d55bfa90e8530d35801d4e381bc69f0]
20:55:54.919 STDOUT [app] tofu: No changes. Your infrastructure matches the configuration.
20:55:54.919 STDOUT [app] tofu: OpenTofu has compared your real infrastructure against your configuration and
20:55:54.919 STDOUT [app] tofu: found no differences, so no changes are needed.

```

Fixes #3253.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

Updated `--terragrunt-out-dir` / `--terragrunt-json-out-dir` to handle relative paths.

### CODE REVIEW

File: configstack/module.go [hunk 1]
```diff
@@ -116,25 +116,51 @@ func (module *TerraformModule) planFile(terragruntOptions *options.TerragruntOpt
...
 	}
 
+	path, _ := filepath.Rel(opts.WorkingDir, module.Path)
+	dir := filepath.Join(opts.OutputFolder, path)
+
+	if !filepath.IsAbs(dir) {
+		dir = filepath.Join(opts.WorkingDir, dir)
+	}
+
+	if absDir, err := filepath.Abs(dir); err == nil {
```
Comment (levkohimins) [inline configstack/module.go:130]: Not sure if this expression is needed since it will be absolute after the line 127.

File: configstack/module.go [hunk 2]
```diff
@@ -116,25 +116,51 @@ func (module *TerraformModule) planFile(terragruntOptions *options.TerragruntOpt
...
 	}
 
+	path, _ := filepath.Rel(opts.WorkingDir, module.Path)
+	dir := filepath.Join(opts.JSONOutputFolder, path)
+
+	if !filepath.IsAbs(dir) {
+		dir = filepath.Join(opts.WorkingDir, dir)
+	}
+
+	if absDir, err := filepath.Abs(dir); err == nil {
```
Comment (levkohimins) [inline configstack/module.go:156]: The same, we are already have abs path in the 153.

**Review by levkohimins — CHANGES_REQUESTED** [review]
