### PR TITLE
bug: unit output flushing

### LINKED ISSUE #5187: Opentofu output gets lost during terragrunt run --all apply
## Describe the bug

Terragrunt v0.94.0
Opentofu v1.10.8
When running terragrunt run --all apply, periodically the output from the plan gets lost. 
For example:
```
13:29:07.470 STDOUT [module1] tofu: OpenTofu has compared your real infrastructure against your configuration and
13:29:07.470 STDOUT [module1] tofu: found no differences, so no changes are needed.
13:29:07.666 STDOUT [module1] tofu:
13:29:07.667 STDOUT [module1] tofu: Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
13:29:07.667 STDOUT [module1] tofu:
13:35:39.080 INFO   Interrupt signal received. Gracefully shutting down...
13:35:39.080 STDERR [module2] tofu: ╷
13:35:39.080 STDERR [module2] tofu: │ Error: error asking for approval: interrupted
13:35:39.081 STDERR [module2] tofu: │
13:35:39.081 STDERR [module2] tofu: │
13:35:39.081 STDERR [module2] tofu: ╵
13:29:12.524 STDOUT [module2] tofu: data.aws_availability_zones.available: Reading...
....
13:29:16.177 STDOUT [module2] tofu: Plan: 0 to add, 1 to change, 0 to destroy.
13:29:16.177 STDOUT [module2] tofu:
13:29:16.177 STDOUT [module2] tofu: Do you want to perform these actions?
13:29:16.177 STDOUT [module2] tofu:   OpenTofu will perform the actions described above.
13:29:16.177 STDOUT [module2] tofu:   Only 'yes' will be accepted to approve.
13:29:16.177 STDOUT [module2] tofu:   Enter a value:
13:35:39.080 STDOUT [module2] tofu: Interrupt received.
13:35:39.080 STDOUT [module2] tofu: Please wait for OpenTofu to exit or data loss may occur.
13:35:39.080 STDOUT [module2] tofu: Gracefully shutting down...
```

Once I kill the tofu instance on module 2, all of the output gets dumped out and the rest of the run bails out. 
Reverting to 0.93.13 fixes the issue.

Sadly not entirely sure what is causing this so not sure how to reproduce this issue.

### PR DESCRIPTION
**Pull request by denis256**
## Description

* updated unit output writer to flush output
* added tests to track output flushing

Fixes #5187.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] I authored this code entirely myself
- [x] I am submitting code based on open source software (e.g. MIT, MPL-2.0, Apache)]
- [x] I am adding or upgrading a dependency or adapted code and confirm it has a compatible open source license
- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

## Summary by CodeRabbit

* **New Features**
  * Implemented incremental output flushing to display complete lines in real-time during unit execution, rather than waiting for completion.

* **Bug Fixes**
  * Enhanced output handling to ensure buffered data is properly flushed when operations are interrupted or cancelled, preventing loss of output.

* **Tests**
  * Added tests to validate output flushing behavior and error handling during interruptions.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: internal/runner/runnerpool/writer.go [hunk 1]
```diff
@@ -2,37 +2,110 @@ package runnerpool
...
 
-// UnitWriter buffers output for a single unit and flushes atomically on completion.
-// This prevents interleaved output when multiple units run in parallel.
+// UnitWriter buffers output for a single unit and flushes incrementally during execution.
+// This prevents interleaved output when multiple units run in parallel while ensuring
+// output appears in real-time during execution, not just at completion.
+// It also flushes when the context is cancelled to prevent output loss on interrupt.
 type UnitWriter struct {
 	out    io.Writer
+	ctx    context.Context
```
Comment (yhakbar) [inline internal/runner/runnerpool/writer.go]: We shouldn't embed context on the struct:
https://go.dev/blog/context-and-structs
