### PR TITLE
Fixed handling of module prefixes

### LINKED ISSUE #3102: Broken tfplan.json if --terragrunt-include-module-prefix is used
## Describe the bug

Combination of `--terragrunt-include-module-prefix` and `--terragrunt-json-out-dir …` results in JSON file being invalid because module prefix is being included inside of JSON.

```json
[/home/brain/Projects/gooddata/iac/ns1/zones/getgooddata.info/zone] {"format_version":"1.2","terraform_version":"1.8.1",…
```

## Expected behavior

JSON file should be valid and not having any module prefix.

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: 0.57.8
- OpenTofu/Terraform version: 1.8.1
- Environment details (Ubuntu 20.04, Windows 10, etc.): Fedora 39

### PR DESCRIPTION
**Pull request by denis256**
## Description

Included changes:
* Changed JSON logger to pass wrapped messages to existing writters
* Fixed generation of plan JSON files when json log format is enabled
* Extracted common test code
* Added tests to track that issue will continue to work
* Updated logic for no-color to avoid adding double `no-color` flags

Fixes #3102.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

Fixed generation of plan JSON files when json log format is enabled.

### CODE REVIEW

File: cli/provider_cache.go [hunk 1]
```diff
@@ -234,7 +234,7 @@ func runTerraformCommand(ctx context.Context, opts *options.TerragruntOptions, a
 	errWriter := util.NewTrapWriter(opts.ErrWriter, HTTPStatusCacheProviderReg)
 
 	// add -no-color flag if the user specified it in the CLI
-	if util.ListContainsElement(opts.TerraformCliArgs, terraform.FlagNameNoColor) {
+	if !util.ListContainsElement(opts.TerraformCliArgs, terraform.FlagNameNoColor) {
```
Comment (levkohimins) [inline cli/provider_cache.go:237]: I think the comment above should be changed, otherwise it is confusing.

**Review by levkohimins — CHANGES_REQUESTED** [review]

File: cli/provider_cache.go (hunk 1 above)
Comment (denis256) [reply cli/provider_cache.go:237]: Yes, updated

**Review by levkohimins — APPROVED** [review]
LGTM!

File: cli/provider_cache.go (hunk 1 above)
Comment (levkohimins) [reply cli/provider_cache.go:237]: Ah, I forgot, during normal operation, when the cache server returns a 423 code, we hide this error, but in all other cases we will display it as is. So it may happen that we will display this error without color, while in the rest of the logs the color will be.

**Review by levkohimins — CHANGES_REQUESTED** [review]

File: cli/provider_cache.go (hunk 1 above)
Comment (levkohimins) [reply cli/provider_cache.go:237]: For example, if the provider's address contains an incorrect URL.

**Review by levkohimins — APPROVED** [review]
LGTM!
