### PR TITLE
Resolves #1369

### LINKED ISSUE #1369: Remote State Backend S3 Bucket missing attributes in GovCloud
When creating the Terraform Remote State S3 Bucket with the standard Terragrunt `remote_state` and `config` blocks under the Gov Cloud region (us-gov-west-1), the `encrypt` and `s3_bucket_tags` attributes are not applied to the resultant backend S3 bucket when Terragrunt creates it.  In addition, S3 bucket versioning is not enabled even though the `skip_bucket_versioning` attribute is not set (default is `false`).

## Example config:
```hcl
remote_state {
  backend = "s3"

  config = {
    region         = "us-gov-west-1"
    encrypt        = true
    bucket         = "org.foo.terraform-state"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    dynamodb_table = "org.foo.terraform-state"

    s3_bucket_tags = {
      env     = "dev"
      product = "foo"
    }

    dynamodb_table_tags = {
      env     = "dev"
      product = "foo"
    }
  }
}
```

## Expected Behavior:
By supplying the standard encryption and tag attributes in the `remote_state` `config` block, the resultant resources created by Terragrunt would have those tags and encryption settings applied.
```sh
❯ aws s3api get-bucket-tagging --bucket gov.snafu.foo.dev.terraform
{
    "TagSet": [
        {
            "Key": "env",
            "Value": "dev"
        },
        {
            "Key": "product",
            "Value": "foo"
        }
    ]
}

❯ aws s3api get-bucket-encryption --bucket gov.snafu.foo.dev.terraform
{
    "ServerSideEncryptionConfiguration": {
        "Rules": [
            {
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "AES256"
                }
            }
        ]
    }
}

❯ aws s3api get-bucket-versioning --bucket gov.snafu.foo.dev.terraform
{
    "Status": "Enabled"
}
```

## Actual Behavior:
While the DynamoDB table _is_ getting its tags created; the S3 bucket is neither getting its tags or its encryption set...
```
❯ terragrunt plan
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/23 23:59:44 Running command: terraform --version
[terragrunt] 2020/09/23 23:59:45 Terraform version: 0.13.3
[terragrunt] 2020/09/23 23:59:45 Reading Terragrunt config file at /homedir/code/terragrunt_proj/live/dev/iam/terragrunt.hcl
[terragrunt] 2020/09/23 23:59:52 Copying files from /homedir/code/terragrunt_proj/live/dev/iam into /homedir/code/terragrunt_proj/live/dev/iam/.terragrunt-cache/NmUb0NQowR_kidRL6AqXOQfqPAw/jEuKqkF7Y7XrbxJ9C_9A3LTh-5I
[terragrunt] 2020/09/23 23:59:52 Setting working directory to /homedir/code/terragrunt_proj/live/dev/iam/.terragrunt-cache/NmUb0NQowR_kidRL6AqXOQfqPAw/jEuKqkF7Y7XrbxJ9C_9A3LTh-5I
[terragrunt] 2020/09/23 23:59:52 Generated file /homedir/code/terragrunt_proj/live/dev/iam/.terragrunt-cache/NmUb0NQowR_kidRL6AqXOQfqPAw/jEuKqkF7Y7XrbxJ9C_9A3LTh-5I/providers.tf.
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/23 23:59:52 Initializing remote state for the s3 backend
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/23 23:59:52 [terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam]  Remote state S3 bucket gov.snafu.foo.dev.terraform does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)
y
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/23 23:59:54 Create S3 bucket gov.snafu.foo.dev.terraform
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/23 23:59:54 Creating S3 bucket gov.snafu.foo.dev.terraform
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/23 23:59:55 Waiting for bucket gov.snafu.foo.dev.terraform to be created
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/23 23:59:55 S3 bucket gov.snafu.foo.dev.terraform created.
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/23 23:59:55 Enabling root access to S3 bucket gov.snafu.foo.dev.terraform
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/23 23:59:55 Create S3 bucket gov.snafu.foo.dev.terraform returned an error: InvalidClientTokenId: The security token included in the request is invalid
	status code: 403, request id: a86716b9-42ac-49ae-a70e-ac7b598befdf. Sleeping for 10s and will try again.
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:05 Create S3 bucket gov.snafu.foo.dev.terraform
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:05 Creating S3 bucket gov.snafu.foo.dev.terraform
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:05 Looks like someone is creating bucket gov.snafu.foo.dev.terraform at the same time. Will not attempt to create it again.
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:05 Waiting for bucket gov.snafu.foo.dev.terraform to be created
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:05 S3 bucket gov.snafu.foo.dev.terraform created.
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:05 WARNING: Versioning is not enabled for the remote state S3 bucket gov.snafu.foo.dev.terraform. We recommend enabling versioning so that you can roll back to previous versions of your Terraform state in case of error.
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:05 Lock table gov.snafu.foo.dev.terraform-lock-table does not exist in DynamoDB. Will need to create it just this first time.
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:05 Creating table gov.snafu.foo.dev.terraform-lock-table in DynamoDB
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:06 Table gov.snafu.foo.dev.terraform-lock-table is not yet in active state. Will check again after 10s.
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:16 Success! Table gov.snafu.foo.dev.terraform-lock-table is now in active state.
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:16 Adding tags to lock table: map[env:dev product:foo]
[terragrunt] [/homedir/code/terragrunt_proj/live/dev/iam] 2020/09/24 00:00:16 Running command: terraform init -backend-config=bucket=gov.snafu.foo.dev.terraform -backend-config=dynamodb_table=gov.snafu.foo.dev.terraform-lock-table -backend-config=encrypt=true -backend-config=key=iam/terraform.tfstate -backend-config=region=us-gov-west-1 -lock-timeout=20m
Initializing modules...

❯ aws s3api get-bucket-tagging --bucket gov.snafu.foo.dev.terraform
An error occurred (NoSuchTagSet) when calling the GetBucketTagging operation: The TagSet does not exist

❯ aws s3api get-bucket-encryption --bucket gov.snafu.foo.dev.terraform
An error occurred (ServerSideEncryptionConfigurationNotFoundError) when calling the GetBucketEncryption operation: The server side encryption configuration was not found

❯ aws s3api get-bucket-versioning --bucket gov.snafu.foo.dev.terraform

```

### PR DESCRIPTION
**Pull request by ryno75**
making the AWS ARN partition value a dynamic lookup and removing hard-coding of ":aws:" to support GovCloud and other paritions. Resolves #1369

### CODE REVIEW

File: aws_helper/config.go [hunk 1]
```diff
@@ -167,6 +168,17 @@ func GetAWSCallerIdentity(config *AwsSessionConfig, terragruntOptions *options.T
...
 
+// Get the AWS Partition of the current session configuration
+func GetAWSPartition(config *AwsSessionConfig, terragruntOptions *options.TerragruntOptions) (string, error) {
+	identity, err := GetAWSCallerIdentity(config, terragruntOptions)
+	if err != nil {
+		return "", errors.WithStackTrace(err)
+	}
+
+	arn_slice := strings.Split(*identity.Arn, ":")
+	return arn_slice[1], nil
```
Comment (brikis98) [inline aws_helper/config.go:179]: NIT: there is an [`arn` package](https://docs.aws.amazon.com/sdk-for-go/api/aws/arn/) in the SDK that can do this with somewhat better error handling.

File: remote/remote_state_s3.go [hunk 2]
```diff
@@ -595,6 +600,7 @@ func EnableRootAccesstoS3Bucket(s3Client *s3.S3, config *ExtendedRemoteStateConf
 	}
 
 	_, err = s3Client.PutBucketPolicy(&s3.PutBucketPolicyInput{
+
```
Comment (brikis98) [inline remote/remote_state_s3.go:603]: NIT: unintentional extra newline?

**Review by brikis98 — COMMENTED** [review]
Thanks for the PR! The code changes LGTM for the most part; I just left a couple NITs. Once resolved, I can kick off tests.

File: aws_helper/config.go (hunk 1 above)
Comment (ryno75) [reply aws_helper/config.go:179]: I was thinking I should use `arnSlice` for the var name anyway so... happy to modify that!

**Comment by ryno75** [comment]
@brikis98 you NIT is my command. 😄   
Thanks!

**Review by brikis98 — APPROVED** [review]
LGTM, thank you! I'll kick off tests now.

**Comment by brikis98** [comment]
Tests passed. Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.30.6

**Comment by ryno75** [comment]
awesome! thank you!
